### ISSUE TITLE
Server crash java.lang.OutOfMemoryError: Java heap space 	at org.spongepowered.common.event.tracking.PhaseContext.addBlockCaptures

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1006]
https://gist.github.com/ProsperCraft/0684d5e4442884e99ab39bd9ef829b18

java.lang.OutOfMemoryError: Java heap space
    at org.spongepowered.common.event.tracking.PhaseContext.addBlockCaptures(PhaseContext.java:131)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:195)
    at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjj000(WorldServer.java:1297)
    at net.minecraft.world.World.func_72939_s(World.java:1270)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:712)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by gabizou** [comment]
That's an OutOfMemoryError. Not something sponge will throw or cause directly. Is this happening consistently?

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/b7f8d1e071e162f05885b14dc146f473
https://gist.github.com/ProsperCraft/aeabbb49701a83a587452cef1e54982b

Was not happening until the update to Hermitpack 1.2.1

**Comment by ProsperCraft** [comment]
We have 12 gigs set for the pack.

It might be be related to the memory leaks in the pack.

The ram does a lot of spiking then back down.

**Comment by gabizou** [comment]
@ProsperCraft It feels like it's not so much a sponge issue still, but could you post a screenshot of the memory timeline? I wouldn't be surprised that there are some mods that updated in the pack that are either having bad object churn or a legitimate memory leak.

**Comment by ProsperCraft** [comment]
memory timeline from the timings?

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/c570affba55dc8dfd64e60c72ff2885b

This is from the Allthemods server as opposed to the hermitpack server before, the memory issue wasn't happening before, but I updated both packs so its possible it could be from one of the mods that updated in both of the packs.

**Comment by bloodmc** [comment]
Update to latest SF.
