### ISSUE TITLE
Server Crash - Block facing problem Random things

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1008]
https://gist.github.com/ProsperCraft/058d72e8d3db633d340f2834b42405f2

Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at lumien.randomthings.tileentity.TileEntityAdvancedItemCollector.func_73660_a(TileEntityAdvancedItemCollector.java:108)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:211)
    at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjj000(WorldServer.java:1297)
    at net.minecraft.world.World.func_72939_s(World.java:1270)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:712)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.
