### ISSUE TITLE
Some value was null from a block snapshot

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#1022]
As reported initially on Prism plugin here: https://github.com/prism/Prism/issues/49#issuecomment-257933152

**Comment by bloodmc** [comment]
@gabizou Can you take a look at this?

**Comment by LemADEC** [comment]
Issue is still live on 1.10.2 with spongeforge-1.10.2-2221-5.2.0-BETA-2219.jar.
It happens relatively frequently in our small modpack
```
[17:33:39] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=prism, name=Prism, version=3.0.0, source=/home/magmayhem/./plugins/Prism-3.0.0-beta2-28-g5087827-all#58.jar}
java.lang.NullPointerException: value
>       at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.10.2.jar:?]
>       at org.spongepowered.api.data.MemoryDataView.set(MemoryDataView.java:226) ~[MemoryDataView.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.api.data.MemoryDataContainer.set(MemoryDataContainer.java:73) ~[MemoryDataContainer.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.block.state.BlockStateContainer$StateImplementation.toContainer(BlockStateContainer.java:867) ~[art$a.class:?]
>       at org.spongepowered.api.data.MemoryDataView.set(MemoryDataView.java:259) ~[MemoryDataView.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.api.data.MemoryDataContainer.set(MemoryDataContainer.java:73) ~[MemoryDataContainer.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.block.SpongeBlockSnapshot.toContainer(SpongeBlockSnapshot.java:257) ~[SpongeBlockSnapshot.class:1.10.2-2221-5.2.0-BETA-2219]
>       at com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.formatBlockDataContainer(PrismRecord.java:339) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2-28-g5087827+unknown-b0.git-unknown]
>       at com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.writeBlockTransaction(PrismRecord.java:262) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2-28-g5087827+unknown-b0.git-unknown]
>       at com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.placedBlock(PrismRecord.java:228) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2-28-g5087827+unknown-b0.git-unknown]
>       at com.helion3.prism.events.listeners.ChangeBlockListener.onChangeBlock(ChangeBlockListener.java:76) ~[ChangeBlockListener.class:3.0.0-beta2-28-g5087827+unknown-b0.git-unknown]
>       at org.spongepowered.common.event.listener.ChangeBlockEventListener_ChangeBlockListener_onChangeBlock182.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:640) ~[TrackingUtil.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:547) ~[TrackingUtil.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$processPostTick$1(BlockTickPhaseState.java:86) ~[BlockTickPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.processPostTick(BlockTickPhaseState.java:86) [BlockTickPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:251) [CauseTracker.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:311) [TrackingUtil.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2093) [ls.class:?]
>       at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220) [ls.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Zidane** [comment]
@gabizou 

Status? We need to get these old issues resolved before worrying about new stuff.

**Comment by bloodmc** [comment]
Reopen if this is still an issue with latest builds.
