### ISSUE TITLE
BlockPosTable NBT Server Crash/Map Corruption

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeForge#1029]
On my server, there is a chunk that presumably has a really large BlockPosTable which is causing the server to crash.

Loading the area around 6013.00, y=71.00, z=2416 immediately crashes the server with this error message.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar)
  TweaksLoadingPlugin (CCTweaks-1.8.9-1.2.2.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 11/6/16 9:33 AM
Description: Loading NBT data

java.io.UTFDataFormatException: malformed input around byte 25
	at java.io.DataInputStream.readUTF(DataInputStream.java:656)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:404)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:45)
	at net.minecraft.nbt.NBTTagList.func_152446_a(SourceFile:66)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:132)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:82)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:151)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:96)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.io.DataInputStream.readUTF(DataInputStream.java:656)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:404)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:45)
	at net.minecraft.nbt.NBTTagList.func_152446_a(SourceFile:66)

-- NBT Tag --
Details:
	Tag name: BlockPosTable
	Tag type: 9
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:132)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:82)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:151)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:96)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 2.6.32-46-pve
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 768071288 bytes (732 MB) / 2203676672 bytes (2101 MB) up to 8563785728 bytes (8167 MB)
	JVM Flags: 4 total; -Xmx8192M -Xincgc -XX:ParallelGCThreads=3 -XX:MaxPermSize=128m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.8-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	sponge{1.8.9-1890-4.2.0-BETA-1762} [SpongeForge] (spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar) 
	UCHIJAAAA	<CCTweaks ASM>{1.2.2} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJAAAA	ComputerCraft{1.79} [ComputerCraft] (ComputerCraft1.79.jar) 
	UCHIJAAAA	CCTweaks{1.2.2} [CCTweaks] (CCTweaks-1.8.9-1.2.2.jar) 
	UCHIJAAAA	chunkloaderz{1.0.3} [ChunkLoaderZ] (ChunkLoaderZ-1.8.9-1.0.3.jar) 
	UCHIJAAAA	Dynmap{2.3-15} [Dynmap] (Dynmap-2.3-forge-1.8.9.jar) 
	UCHIJAAAA	io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.8.9-8.1.14-universal.jar) 
	UCHIJAAAA	griefprevention{2.0.0} [GriefPrevention] (griefprevention-1.8.9-2.0.0.87.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
	UCHIJAAAA	io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
	UCHIJAAAA	kristmarket{1.0} [KristMarket] (kristmarket.jar) 
	UCHIJAAAA	kristpay{1.0.0} [KristPay] (kristpay.jar) 
	UCHIJAAAA	voterestart{1.0} [Vote Restart] (liggy_voterestart.jar) 
	UCHIJAAAA	logdupepatch{1.0} [LogDupePatch] (logdupepatch-2.0-snapshot.jar) 
	UCHIJAAAA	minimalperipherals{0.0} [MinimalPeripherals] (MinimalPeripherals-lite-1.8.9-1.1.jar) 
	UCHIJAAAA	MoreFurnaces{1.5.2} [More Furnaces] (MoreFurnaces-1.8.9-1.5.2.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.8-rc.1} [OpenComputers] (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar) 
	UCHIJAAAA	ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	prism{3.0.0} [Prism] (Prism-3.0.0-beta2-14-g154e2b2.jar) 
	UCHIJAAAA	com.gmail.trentech.pjb{0.1.0} [Project Borders] (projectborders-4.2.0-0.1.0.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1-dist.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TweaksLoadingPlugin (CCTweaks-1.8.9-1.2.2.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 8 / 50; [EntityPlayerMP['BTC'/629, l='world', x=6013.00, y=71.00, z=2416.00], EntityPlayerMP['demhydraz'/630, l='world', x=7710.38, y=74.00, z=2349.23], EntityPlayerMP['086'/631, l='world', x=5889.08, y=69.50, z=2833.75], EntityPlayerMP['Gonow32'/632, l='world', x=5834.66, y=68.00, z=1747.77], EntityPlayerMP['GabbeV'/633, l='world', x=5822.11, y=86.06, z=2565.72], EntityPlayerMP['Ale32bit'/634, l='world', x=5979.27, y=67.00, z=2791.27], EntityPlayerMP['nothjarnan'/635, l='world', x=5876.93, y=93.00, z=2572.35], EntityPlayerMP['umwn'/637, l='world', x=5904.61, y=59.00, z=2665.74]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```
Using spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar

**Comment by inklit** [comment]
I am still fiddling around with NBTExplorer in the chunk in question to see if I can uncorrupt it but have had no luck so far.

http://switchcraft.pw/r.11.4.mca is the file so you can see what might be wrong.

EDIT: I ended up rolling back the region file from my last backup - however this issue still persists.

**Comment by phit** [comment]
just got one of those myself, http://vpaste.net/bLJn2

currently trying to track down what chunk is even causing it, rolling back from the last 3 backups didnt help

**Comment by phit** [comment]
Closing this, probably not related to Sponge at all and no reproduction.
