### ISSUE TITLE
Command on sign causing exception in Minetweaker

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#1035]
When triggering a /say command on a sign, Minetweaker is reporting an exception.
Issue isn't reproduced in SSP without sponge.
Issue is reproduced in SSP with sponge with a NoClassDefFoundError:
```
[00:49:55] [Server thread/INFO]: [@: Block data updated to: {ForgeData:{SpongeData:{CustomManipulators:[]}},x:437,Text4:"{\"text\":\"blo\"}",y:69,Text3:"{\"text\":\"bli\"}",z:-111,Text2:"{\"text\":\"bla\"}",id:"Sign",Text1:"{\"text\":\"Minecraft Tools\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"say @p  hello\"}}"}]
[00:49:55] [Client thread/INFO]: [CHAT] [@: Block data updated to: {ForgeData:{SpongeData:{CustomManipulators:[]}},x:437,Text4:"{\"text\":\"blo\"}",y:69,Text3:"{\"text\":\"bli\"}",z:-111,Text2:"{\"text\":\"bla\"}",id:"Sign",Text1:"{\"text\":\"Minecraft Tools\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"say @p  hello\"}}"}]
[00:50:00] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/server/dedicated/DedicatedServer
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/dedicated/DedicatedServer
	at minetweaker.mc1102.server.MCServer.getPlayer(MCServer.java:48) ~[MCServer.class:?]
	at minetweaker.mc1102.server.MCServer.access$000(MCServer.java:38) ~[MCServer.class:?]
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184882_a(MCServer.java:130) ~[MCServer$MCCommand.class:?]
	at org.spongepowered.common.command.WrapperCommandSource.<init>(WrapperCommandSource.java:67) ~[WrapperCommandSource.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.common.command.WrapperCommandSource.<init>(WrapperCommandSource.java:51) ~[WrapperCommandSource.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.common.command.WrapperCommandSource$Located.<init>(WrapperCommandSource.java:130) ~[WrapperCommandSource$Located.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.common.command.WrapperCommandSource.of(WrapperCommandSource.java:122) ~[WrapperCommandSource.class:1.10.2-2123-6.0.0-BETA-1876]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:81) ~[bd.class:?]
	at net.minecraft.tileentity.TileEntitySign.func_174882_b(TileEntitySign.java:222) ~[arc.class:?]
	at net.minecraft.block.BlockSign.func_180639_a(SourceFile:84) ~[aox.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:192) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zgp000(NetHandlerPlayServer.java:522) ~[me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:125) ~[PacketUtil.class:1.10.2-2123-6.0.0-BETA-1876]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) ~[fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[00:50:01] [Client thread/INFO] [FML]: InvTweaks: successfully transformed setFocused/func_146195_b
```

Issue is reproduced in SMP with a NullPointerException:
```
[18:31:27] [Server thread/INFO] [STDOUT]: [minetweaker.mc1102.server.MCServer:getPlayer:55]: Unsupported command sender: net.minecraft.tileentity.TileEntitySign$2@2a8b3e77
[18:31:27] [Server thread/INFO] [STDOUT]: [minetweaker.mc1102.server.MCServer:getPlayer:56]: player name: LemADEC
[18:31:27] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
>       at minetweaker.mc1102.server.MCServer.isOp(MCServer.java:77) ~[MCServer.class:?]
>       at minetweaker.MineTweakerImplementationAPI$20.canExecute(MineTweakerImplementationAPI.java:674) ~[MineTweakerImplementationAPI$20.class:?]
>       at minetweaker.mc1102.server.MCServer$MCCommand.func_184882_a(MCServer.java:130) ~[MCServer$MCCommand.class:?]
>       at org.spongepowered.common.command.WrapperCommandSource.<init>(WrapperCommandSource.java:67) ~[WrapperCommandSource.class:1.10.2-2123-6.0.0-BETA-1876]
>       at org.spongepowered.common.command.WrapperCommandSource.<init>(WrapperCommandSource.java:51) ~[WrapperCommandSource.class:1.10.2-2123-6.0.0-BETA-1876]
>       at org.spongepowered.common.command.WrapperCommandSource$Located.<init>(WrapperCommandSource.java:130) ~[WrapperCommandSource$Located.class:1.10.2-2123-6.0.0-BETA-1876]
>       at org.spongepowered.common.command.WrapperCommandSource.of(WrapperCommandSource.java:122) ~[WrapperCommandSource.class:1.10.2-2123-6.0.0-BETA-1876]
>       at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:81) ~[bd.class:?]
>       at net.minecraft.tileentity.TileEntitySign.func_174882_b(TileEntitySign.java:222) ~[arc.class:?]
>       at net.minecraft.block.BlockSign.func_180639_a(SourceFile:84) ~[aox.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:192) ~[lv.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zgp000(NetHandlerPlayServer.java:522) ~[me.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:125) ~[PacketUtil.class:1.10.2-2123-6.0.0-BETA-1876]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) ~[fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>       ... 5 more
```

Steps to reproduce the issue:
FTB InfinityLite
forge-1.10.2-12.18.2.2119 (SSP) or forge-1.10.2-12.18.2.2123 (SMP)
spongeforge-1.10.2-2123-6.0.0-BETA-1876.jar
Create a new world in creative
Place a command block with this command:
```
/blockdata ~ ~1 ~ {Text1:"{\"text\":\"Minecraft Tools\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"say @p  hello\"}}",Text2:"{\"text\":\"bla\"}",Text3:"{\"text\":\"bli\"}",Text4:"{\"text\":\"blo\"}"}
```
Place a sign on top
Place a button on the command block and trigger it => sign should be updated
Right click the sign => server should say "hello" to you

**Comment by ryantheleach** [comment]
You mention 1.10 but call it MineTweaker, Are you sure you don't mean CraftTweaker?

**Comment by LemADEC** [comment]
The internal name is still MineTweaker, but yes it's CraftTweaker.

**Comment by simon816** [comment]
Both of these issues look to be a problem with CraftTweaker
They should not be hard [referencing `DedicatedServer`](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-MC1102-Main/src/main/java/minetweaker/mc1102/server/MCServer.java#L49) on the client and they also haven't handled the situation where [their `getPlayer` returns null](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-MC1102-Main/src/main/java/minetweaker/mc1102/server/MCServer.java#L58)

**Comment by LemADEC** [comment]
Sponge isn't supposed to change forge behavior in events received from mods either.

**Comment by kashike** [comment]
@LemADEC What event is Sponge changing the behaviour of?

**Comment by LemADEC** [comment]
My understanding is that something in WrapperCommandSource doesn't reproduce original behavior when calling getPlayer().

**Comment by kashike** [comment]
No, CraftTweaker just doesn't handle all vanilla command source types - such as sign block entities.

**Comment by LemADEC** [comment]
It works fine without Sponge. It fails on a null player with Sponge. How could that be a bug in the mod itself?

**Comment by kashike** [comment]
@LemADEC If you look at [the source](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/command/WrapperCommandSource.java#L115-L126) you'll see that all `WrapperCommandSource` does is wrap an `ICommandSender`.
If you look [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/command/WrapperCommandSource.java#L68) you'll see that Sponge calls the `checkPermission` (`func_184882_a`) method, which ends up calling [this](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-API/src/main/java/minetweaker/MineTweakerImplementationAPI.java#L614-L619) method, which ends up calling [this](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-MC1102-Main/src/main/java/minetweaker/mc1102/server/MCServer.java#L68-L81) method, which is where the problem is, due to CraftTweaker [not having support for `TileEntitySign` command sources](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-MC1102-Main/src/main/java/minetweaker/mc1102/server/MCServer.java#L46-L60), and returning null, resulting in `player.getName()` throwing an NPE.

Additionally, the first exception is caused [here](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-MC1102-Main/src/main/java/minetweaker/mc1102/server/MCServer.java#L46-L60), due to `DedicatedServer` being referenced on the client.

**Comment by LemADEC** [comment]
Fixed in CraftTweaker
