### ISSUE TITLE
Server crash 1.10.2

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeForge#1039]
Running SpongeForge 2123 1.10.2.

Unknown server crash - no obvious reason why.
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  TweaksLoadingPlugin (CCTweaks-1.10.2-1.2.3-pr0.jar)
  UnborkedPlugin (unborked-1.10.2-1.80pr0-1.0.1-patched0.jar)
  SpongeCoremod (spongeforge-1.10.2-2123-6.0.0-BETA-1876.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 11/11/16 4:12 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.server.MinecraftServer.redirect$onUpdateTimeLightAndEntitiesGetWorld$zhj000(MinecraftServer.java:556)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:684)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 2.6.32-46-pve
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1184367664 bytes (1129 MB) / 3319484416 bytes (3165 MB) up to 8563785728 bytes (8167 MB)
	JVM Flags: 4 total; -Xmx8192M -Xincgc -XX:ParallelGCThreads=3 -XX:MaxPermSize=128m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2123 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2123-universal.jar) 
	UCHIJAAAA	Forge{12.18.2.2123} [Minecraft Forge] (forge-1.10.2-12.18.2.2123-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	spongeapi{6.0.0-SNAPSHOT-bd88c91} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2123-6.0.0-BETA-1876} [SpongeForge] (spongeforge-1.10.2-2123-6.0.0-BETA-1876.jar) 
	UCHIJAAAA	unborked_core{1.0.1} [Unborked Core] (minecraft.jar) 
	UCHIJAAAA	<CCTweaks ASM>{1.2.3-pr0} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJAAAA	noxray{0.3.2-beta} [NoXray] (NoXray.jar) 
	UCHIJAAAA	ComputerCraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0.jar) 
	UCHIJAAAA	cctweaks{1.2.3-pr0} [CCTweaks] (CCTweaks-1.10.2-1.2.3-pr0.jar) 
	UCHIJAAAA	chunkloaderz{1.2} [ChunkLoaderZ] (ChunkLoaderZ-1.9.4-1.2.jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	Dynmap{2.3-3} [Dynmap] (Dynmap-2.3-forge-1.9.4.jar) 
	UCHIJAAAA	io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.10.2-8.1.14-universal.jar) 
	UCHIJAAAA	griefprevention{2.1.0} [GriefPrevention] (griefprevention-1.10.2-2.1.0.129.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	JEI{3.13.2.360} [Just Enough Items] (jei_1.10.2-3.13.2.360.jar) 
	UCHIJAAAA	io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
	UCHIJAAAA	kristmarket{1.0} [KristMarket] (kristmarket.jar) 
	UCHIJAAAA	kristpay{1.0.0} [KristPay] (kristpay.jar) 
	UCHIJAAAA	logdupepatch{1.0} [LogDupePatch] (logdupepatch-2.0-snapshot.jar) 
	UCHIJAAAA	minimalperipherals{0.0} [MinimalPeripherals] (MinimalPeripherals-lite-1.10.2-1.3-pre.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCHIJAAAA	permissionsex{2.0-SNAPSHOT-b145} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	prism{3.0.0} [Prism] (Prism-3.0.0-beta2-21-gdae772d.jar) 
	UCHIJAAAA	unborked{1.0.1} [Unborked] (unborked-1.10.2-1.80pr0-1.0.1-patched0.jar) 
	UCHIJAAAA	worldedit{6.1.5-SNAPSHOT} [WorldEdit] (worldedit-sponge-mc1.10.2-6.1.5-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
TweaksLoadingPlugin (CCTweaks-1.10.2-1.2.3-pr0.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
UnborkedPlugin (unborked-1.10.2-1.80pr0-1.0.1-patched0.jar)
  org.squiddev.unborked.core.UnborkedTransformer
SpongeCoremod (spongeforge-1.10.2-2123-6.0.0-BETA-1876.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 3 / 50; [EntityPlayerMP['jakejakey1208'/544, l='world', x=5872.34, y=66.00, z=2614.44], EntityPlayerMP['awsumben13'/546, l='world', x=5566.11, y=64.00, z=2203.74], EntityPlayerMP['umwn'/549, l='world', x=11395.24, y=71.00, z=5056.59]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by bloodmc** [comment]
This NPE should never happen but in your case happened due to max-tick-time being set to a really high number or disabled entirely. Set max-tick-time back to a reasonable number and you wont have this crash but instead get a proper Watchdog thread dump.
