### ISSUE TITLE
Server crashed from a block of sand? NPE SpongeBlockSnapshot

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1044]
https://gist.github.com/ProsperCraft/af08979eace10474cecfa3f06c954b8e

Description: Exception while ticking a block

java.lang.NullPointerException: Exception while ticking a block
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:116)
	at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:108)
	at net.minecraft.world.WorldServer.createSpongeBlockSnapshot(WorldServer.java:1453)
	at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:220)
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$zjl000(WorldServer.java:734)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:743)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bloodmc** [comment]
This should never happen and seems like a result of your server timing out. Make sure your max-tick-time in server.properties is set to around 6000 and not too high.
