### ISSUE TITLE
Using a redstone contraptions(piston doors) in a nation you don't own causes a crash/lockup

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1054]
https://gist.github.com/ProsperCraft/4830fb5e5e84afb8811e7b20d5b2a053

We have the nations plugin.

Description: Watching Server

java.lang.Error
	at java.util.ArrayList.remove(ArrayList.java:528)
	at net.minecraft.world.World.func_175713_t(World.java:2484)
	at net.minecraft.tileentity.TileEntityPiston.func_145866_f(TileEntityPiston.java:200)
	at net.minecraft.block.BlockPistonMoving.func_180663_b(BlockPistonMoving.java:55)
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:566)
	at org.spongepowered.common.event.tracking.CauseTracker.setBlockStateWithFlag(CauseTracker.java:445)
	at net.minecraft.world.WorldServer.setBlockState(WorldServer.java:1183)
	at org.spongepowered.common.block.SpongeBlockSnapshot.restore(SpongeBlockSnapshot.java:202)
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:555)
	at org.spongepowered.common.event.tracking.phase.block.PistonMovingPhaseState.unwind(PistonMovingPhaseState.java:58)
	at org.spongepowered.common.event.tracking.phase.block.BlockPhase.unwind(BlockPhase.java:73)
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:190)
	at net.minecraft.block.BlockPistonBase.handler$onDoMoveReturn$zbh000(BlockPistonBase.java:106)
	at net.minecraft.block.BlockPistonBase.func_176319_a(BlockPistonBase.java:418)
	at net.minecraft.block.BlockPistonBase.func_189539_a(BlockPistonBase.java:196)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:458)
	at org.spongepowered.common.event.tracking.TrackingUtil.fireMinecraftBlockEvent(TrackingUtil.java:314)
	at net.minecraft.world.WorldServer.redirect$onFireBlockEvent$zjl000(WorldServer.java:768)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1217)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:233)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bloodmc** [comment]
Your server timed out. Have nations fix the issue as this works perfectly fine in my plugin GriefPrevention.
