### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeForge#1058]
Running spongeforge-1.10.2-2123-5.1.0-BETA-1891

```
[18:14:25] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=moisture, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=minecraft:stone, properties=[variant]}
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
        at net.minecraft.block.Block.isFertile(Block.java:1680) ~[akf.class:?]
        at net.minecraft.block.BlockCrops.func_180672_a(BlockCrops.java:125) ~[ala.class:?]
        at net.minecraft.block.BlockStem.func_180650_b(BlockStem.java:71) ~[apk.class:?]
        at net.minecraft.block.Block.func_180645_a(Block.java:480) ~[akf.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:266) ~[TrackingUtil.class:1.10.2-2123-5.1.0-BETA-1891]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:653) ~[ls.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) ~[MinecraftServer.class:?]
        ... 4 more
```
Just a random crash, not sure how to reproduce it but it has only happened about 4 times over the span of a few weeks.

**Comment by hugeblank** [comment]
It looks like, just based off of some of the things I see in the log, that it's crashing because of an issue with random ticking crops. I'm pretty sure it has something to do with moisturizing land in the same tick that a crop is growing. Sponge is probably not handling it correctly and causing the crash

I don't know if that helped, but I figured I'd share

**Comment by inklit** [comment]
@hugeblank It looks more to me like it was trying to moisturize stone.

**Comment by hugeblank** [comment]
Oh yep I see it now. Stupid screen resolution not showing it all. XP

Well here's a few thoughts that may or may not be of use:

Maybe someone used (right clicked) a hoe on stone, and sponge assumed it to be tilled? 

Or is world edit available? If that were the case, a crop block could have been replaced by stone, and sponge just didn't recognize it, mixed the block data up, and then caused the issue.

From what I know, water hydrates up to 4 blocks away, and then no more. Maybe spong is allowing it to hydrate more than that, and minecraft sees it as an error?

I'm not sure to what extent sponge manipulates the game, from what I thought it just detects and inserts events in game. All of these seem to be over what I thought sponge did.

**Comment by bloodmc** [comment]
Create a new ticket if it occurs with latest SF builds.
