### ISSUE TITLE
chisel mod NPE in server console

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1082]
```
[14:06:31] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@9702855:
java.lang.NullPointerException
        at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:40) ~[bbz.class:?]
        at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:27) ~[bbz.class:?]
        at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:46) ~[ChiselController.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:141) [EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:918) [SpongeForgeEventFactory.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:573) [SpongeForgeEventFactory.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385) [SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) [SpongeImpl.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventPrimary(SpongeCommonEventFactory.java:390) [SpongeCommonEventFactory.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:208) [PacketUtil.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:88) [PacketUtil.class:1.10.2-2171-5.1.0-BETA-1930]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[14:06:31] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[14:06:31] [Server thread/ERROR] [FML/]: 0: NORMAL
[14:06:31] [Server thread/ERROR] [FML/]: 1: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[14:06:31] [Server thread/ERROR] [FML/]: 2: ASM: mod.chiselsandbits.events.EventPlayerInteract@1bd72a92 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[14:06:31] [Server thread/ERROR] [FML/]: 3: ASM: minetweaker.mc1102.ForgeEventHandler@bc97c75 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[14:06:31] [Server thread/ERROR] [FML/]: 4: ASM: hunterzcz.ic2laserfix.IC2MiningLaser@3fe50e41 onIC2LaserUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[14:06:31] [Server thread/ERROR] [FML/]: 5: ASM: hunterzcz.ic2laserfix.IC2MiningLaser@3fe50e41 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[14:06:31] [Server thread/ERROR] [FML/]: 6: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@1776268e onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V

```

**Comment by Codazed** [comment]
I have also gotten NPE from this same issue. This happens whenever trying to use TeamChisel's Chisel mod to chisel blocks by left-clicking on them. (FTB Presents Direwolf20 1.10.2 Version 1.6.2)
```
[08:08:59] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-2221-5.2.0-BETA-2223]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:40) ~[bbz.class:?]
        at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:27) ~[bbz.class:?]
        at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:47) ~[ChiselController.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_232_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) ~[EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:806) ~[SpongeForgeEventFactory.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:462) ~[SpongeForgeEventFactory.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventPrimary(SpongeCommonEventFactory.java:446) ~[SpongeCommonEventFactory.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:225) ~[PacketUtil.class:1.10.2-2221-5.2.0-BETA-2223]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:90) ~[PacketUtil.class:1.10.2-2221-5.2.0-BETA-2223]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) ~[fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 7 more
```

**Comment by proverbiallemon** [comment]
I'm getting this same error, it works fine with out sponge.  I like sponge though and want to be able to use my chisel :< 

```
[05:51:20] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2254-5.2.0-BETA-2272]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:40) ~[bbz.class:?]
	at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:27) ~[bbz.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:47) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_153_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) ~[EventBus.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:806) ~[SpongeForgeEventFactory.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:462) ~[SpongeForgeEventFactory.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventPrimary(SpongeCommonEventFactory.java:444) ~[SpongeCommonEventFactory.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:224) ~[PacketUtil.class:1.10.2-2254-5.2.0-BETA-2272]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:90) ~[PacketUtil.class:1.10.2-2254-5.2.0-BETA-2272]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539) ~[fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 7 more
```

**Comment by bloodmc** [comment]
Unable to reproduce with latest SF and chisel builds.
