### ISSUE TITLE
build 2000 crashes - tile entity activation

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1122]
<pre>
[13:39:59] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalAccessError
        at sun.misc.Unsafe.throwIllegalAccessError(Unsafe.java:1142) ~[?:1.8.0_102]
        at org.spongepowered.common.mixin.plugin.tileentityactivation.TileEntityActivation.checkIfActive(TileEntityActivation.java:202) ~[TileEntityActivation.class:1.10.2-2171-5.1.0-BETA-2000]
        at net.minecraft.world.WorldServer.handler$onUpdateTileEntityHead$zmp000(WorldServer.java:44) ~[ls.class:?]
        at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java) ~[ls.class:?]
        at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1291) ~[ls.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1282) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]

</pre>

crashlog:

http://pastebin.com/S4KUCSE2

I think is due new feature announced as tileentity activation.

In my server config is this new feature disabled.

**Comment by Aaron1011** [comment]
@hunter688: Can you retest on the latest SpongeForge?

**Comment by ghost** [comment]
Ok, deployed build 2003, i will report how it works. Idk howto reproduce crash.

**Comment by Aaron1011** [comment]
@hunter688: Enable tile entity activation in your config, and place down/walk near a `ic2:chargepad_mfsu` block. (There was a bug in the older build where tile entity activation would be on, even if disabled in the config).

**Comment by ghost** [comment]
Looks like bug fixed, thanks a lot.
