### ISSUE TITLE
spongeforge-1.10.2-2202-5.1.0-BETA-2022 and below Error occurred while executing command /i

### ISSUE THREAD

**Issue by craigbrian** [SpongePowered/SpongeForge#1167]
It seems any mod that you try to use /i gives this error.

```
07.01 01:58:05 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'i pixelmon:poke_ball' for source EntityPlayerMP['craigbrian'/108, l='Kanto', x=40.94, y=65.00, z=-640.88]: org.spongepowered.api.world.World.createEntity(Lorg/spongepowered/api/entity/EntityType;Lcom/flowpowered/math/vector/Vector3d;)Ljava/util/Optional; 07.01 01:58:05
[Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.world.World.createEntity(Lorg/spongepowered/api/entity/EntityType;Lcom/flowpowered/math/vector/Vector3d;)Ljava/util/Optional; 07.01 01:58:05 
[Server] INFO at main.java.me.cuebyte.nexus.utils.ItemUtils.drop(ItemUtils.java:32) ~[ItemUtils.class:?] 07.01 01:58:05 [Server] INFO at main.java.me.cuebyte.nexus.commands.CommandItem.process(CommandItem.java:73) ~[CommandItem.class:?] 07.01 01:58:05 
[Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2202-5.1.0-BETA-2022] 07.01 01:58:05 
[Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:295) [SpongeCommandManager.class:1.10.2-2202-5.1.0-BETA-2022] 07.01 01:58:05 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?] 07.01 01:58:05 
[Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?] 07.01 01:58:05 
[Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?] 07.01 01:58:05 
[Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?] 07.01 01:58:05 
[Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?] 07.01 01:58:05 
[Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:147) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2022] 07.01 01:58:05 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) [fl$1.class:?] 07.01 01:58:05
 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?] 07.01 01:58:05 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111] 07.01 01:58:05
 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111] 07.01 01:58:05 
[Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?] 07.01 01:58:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?] 07.01 01:58:05
 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?] 07.01 01:58:05 
[Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?] 07.01 01:58:05 
[Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] 07.01 01:58:05 
[Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111
```

and if you use id's it says
/i 4134
Item not found!
this worked in 1.7.10 in Cauldron Forge perfectly fine why is SpongeForge limited?

**Comment by simon816** [comment]
You are using an old version of Nexus. Looks like you have sponge `5.1.0` but the nexus plugin is targeting version `4.x.x`
>and if you use id's it says
/i 4134
Item not found!

Item IDs are no longer numerical, you should use the string ID instead (e.g. "minecraft:stone")

**Comment by craigbrian** [comment]
I assume this is why /i command or /i minecraft:command_block doesn't work either.

I have to wait for Nexus to release a 1.10.2? Thank you for the help! 
I notcied /give @p minecraft:grass says Player not found is that a bug or part of nexus also?

**Comment by Aaron1011** [comment]
Make sure that NExus supports the version of Sponge that you're running.
