### ISSUE TITLE
Server crash- Watchdog- spongepowered.common.service.user.UserDiscoverer.findByProfile

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1187]
https://gist.github.com/ProsperCraft/cb02b1caac3cfc6395a2b2d830bf61e9

Description: Watching Server

java.lang.Error
	at com.google.common.base.Equivalence$Equals.doHash(Equivalence.java:330)
	at com.google.common.base.Equivalence.hash(Equivalence.java:104)
	at com.google.common.cache.LocalCache.hash(LocalCache.java:1837)
	at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:3922)
	at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:4730)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:83)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:66)
	at net.minecraft.world.chunk.Chunk.getUserFromId(Chunk.java:257)
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(Chunk.java:246)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:201)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:1321)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1308)
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:717)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Deamon5550** [comment]
All this means is that your server timed out, the stacktrace is irrelevant. Use a profiler or increase the max-tick-time.
