### ISSUE TITLE
Custom Villagers throw Exceptions when trying to trade

### ISSUE THREAD

**Issue by kremi151** [SpongePowered/SpongeForge#1189]
My server is running a self developed Forge mod which adds 3 new villager types. Altough these villagers are working perfectly in a non-Sponge environment (single player or plain forge server), they are no longer working in combination with Sponge. This is the exception being thrown when I try to trade with a custom villager:

Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bound must be positive
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: bound must be positive
at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_101]
at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:194) ~[zn.class:?]
at net.minecraft.entity.passive.EntityVillager.func_145748_c_(EntityVillager.java:675) ~[zn.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:815) ~[lu.class:?]
at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:238) ~[zn.class:?]
at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1229) ~[sg.class:?]
at net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1161) ~[zs.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:618) ~[me.class:?]
at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]
at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) ~[PacketUtil.class:1.10.2-2202-5.1.0-BETA-2026]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) ~[fl$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more

Also during the starting phase of the server the following output is given in the console:
VillagerProfession has not been registered: net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession@760d4505
VillagerProfession has not been registered: net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession@280332d1
VillagerProfession has not been registered: net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession@254a8769
Sponge has no registration for this career: minamod.baker!
Sponge has no registration for this career: minamod.baker!
Sponge has no registration for this career: minamod.baker!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.jewelier!
Sponge has no registration for this career: minamod.jewelier!
Sponge has no registration for this career: minamod.jewelier!

I'm using SpongeForge 2026 Beta for Minecraft 1.10.2

**Comment by gabizou** [comment]
It sounds like the mod Minamod is failing to register their villager professions correctly, since it's in-house developed, I can't imagine that a public source or public jar file would be available to inspect and verify that the registrations are correct.

**Comment by kremi151** [comment]
You cannot find it as it is not made public yet, sorry for that :/

Here is my class where I define my villagers: (I truncated it a bit)
http://pastebin.com/Qixt2dS8

The `registerVillagers` method is called from the main class during pre init phase, so I don't see how I should register them otherwise as they are working perfectly when I don't use sponge

**Comment by gabizou** [comment]
@kremi151 the reason why it's not working is because you're using GameRegistry.register. I can fix it, but it's rather annoying to fix as it will require multiple checks. For the mean time, it's very well possible to simply use `VillagerRegistry.register(VillagerProfession)` since the id is auto-assigned.

**Comment by kremi151** [comment]
My class is now looking like this: http://pastebin.com/Z2xVeNw6

The output is the following when starting up the server:

> [Server thread/INFO] [STDOUT]: [lu.kremi151.minamod.util.VillagerHelper:<init>:42]: creating villagers...
> VillagerProfession has not been registered: net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession@d77e3b3
VillagerProfession has not been registered: net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession@2cf8388e
VillagerProfession has not been registered: net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession@4fc19bca
[17:17:53] [Server thread/INFO] [STDOUT]: [lu.kremi151.minamod.util.VillagerHelper:<init>:55]: created villagers
> Sponge has no registration for this career: minamod.baker!
Sponge has no registration for this career: minamod.baker!
Sponge has no registration for this career: minamod.baker!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.carpenter!
Sponge has no registration for this career: minamod.jewelier!
Sponge has no registration for this career: minamod.jewelier!
Sponge has no registration for this career: minamod.jewelier!
[17:17:53] [Server thread/INFO] [STDOUT]: [lu.kremi151.minamod.util.VillagerHelper:registerVillagers:138]: registering villagers...
[17:17:53] [Server thread/INFO] [STDOUT]: [lu.kremi151.minamod.util.VillagerHelper:registerVillagers:142]: registered villagers

It looks like sponge doesn't even give me a chance to register my villagers. It begins complaining that the professions are not registered at the creation time of a profession. Also the same error message is thrown ingame when I try to trade with my villagers...

**Comment by kremi151** [comment]
Alright I solved it myself. Here is my new class: http://pastebin.com/WT90w2QV
I solved it by registering the villager professions before registering careers to them. No more outputs in the console that sponge doesn't recognize them and they are finally working now in game,
