### ISSUE TITLE
Any help ? Entity tracking keeps killing tps

### ISSUE THREAD

**Issue by Bennyboy1695** [SpongePowered/SpongeForge#1196]
Not sure what causes it, our players believe its graves but i think its just a random occurrence, but either way whatever causes it keeps killing the server to the point that the majority of the online players get kicked until the lags fixes itself.
Here's a copy of the section of the log that causes the issues, if you need more i can grab it no problem as this is a continual issue.
`[22:03:54] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:246) ~[lp.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:139) ~[lp.class:?]
	at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:33) ~[lt.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1142) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1118) ~[ls.class:?]
	at net.minecraft.world.WorldServer.onSpongeEntityAdded(WorldServer.java:1398) ~[ls.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:1444) ~[ls.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:1427) ~[ls.class:?]
	at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.lambda$processPostTick$7(EntityTickPhaseState.java:244) ~[EntityTickPhaseState.class:1.10.2-2202-5.1.0-BETA-2032]
	at org.spongepowered.common.event.tracking.CapturedMultiMapSupplier.ifPresentAndNotEmpty(CapturedMultiMapSupplier.java:60) [CapturedMultiMapSupplier.class:1.10.2-2202-5.1.0-BETA-2032]
	at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.processPostTick(EntityTickPhaseState.java:225) [EntityTickPhaseState.class:1.10.2-2202-5.1.0-BETA-2032]
	at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.10.2-2202-5.1.0-BETA-2032]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2032]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:154) [TrackingUtil.class:1.10.2-2202-5.1.0-BETA-2032]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjl000(WorldServer.java:1333) [ls.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:85) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:649) [ls.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1217) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:717) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Entity EntityItem['item.item.itemMaterial.silkworm'/2130281, l='world', x=770.56, y=76.13, z=5883.46] is already tracked for world: world
	at net.minecraft.entity.EntityTracker.redirect$reportEntityAlreadyTrackedWithWorld$zda000(EntityTracker.java:65) ~[lp.class:?]
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:214) ~[lp.class:?]
	... 25 more`

**Comment by Bennyboy1695** [comment]
Do you know if there's any config option i can turn off to fix this temporarily ? As the server is almost unplayable because of these random lags

**Comment by ktole1999** [comment]
need full log

**Comment by Bennyboy1695** [comment]
https://gist.github.com/Bennyboy1695/231ef1d9999a2772a358a789f14fdd94 The code chicken issues we know whats causing them and its not related to the issue with the entity tracking.

**Comment by Aaron1011** [comment]
@Bennyboy1695: Can you set `verbose-errors` to `true` in your `global.conf`, and re-run your server until you get an exception? The message will be much longer this time.

**Comment by Bennyboy1695** [comment]
https://gist.github.com/Bennyboy1695/a919bb87f4f1cc7cd2d49980cc627006 Ok thats after maybe 30 mins of the server being up with that setting on. If you need anymore then im leaving it on until the next restart/crash. The first line of extended info is 30145, probably could have trimmed the log down a bit until it started but oh well 😛

**Comment by Aaron1011** [comment]
Sorry for the delay in getting to this - I think I have a fix for it now.

**Comment by Aaron1011** [comment]
@Bennyboy1695 If the exception re-occurs, please re-open this issue.
