### ISSUE TITLE
Crash 1.10.2-2202-5.1.0-BETA-2042

### ISSUE THREAD

**Issue by masterrip** [SpongePowered/SpongeForge#1204]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2202-5.1.0-BETA-2042.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 1/18/17 2:14 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at com.mrcrayfish.furniture.proxy.CommonProxy.isDedicatedServer(CommonProxy.java:50)
	at com.mrcrayfish.furniture.handler.SyncEvent.onPlayerLogin(SyncEvent.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_SyncEvent_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callPlayerLoggedInEvent(SpongeForgeEventFactory.java:1148)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:467)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:441)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5c8eee0f from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 24 more
Caused by: java.lang.RuntimeException: Attempted to load class bcx for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.10.0-327.28.2.el7.x86_64
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1511516208 bytes (1441 MB) / 1935147008 bytes (1845 MB) up to 1935147008 bytes (1845 MB)
	JVM Flags: 2 total; -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (server8.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (server8.jar) 
	UCHIJAAAA	spongeapi{5.1.0-SNAPSHOT-b7a6e54} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2202-5.1.0-BETA-2042} [SpongeForge] (spongeforge-1.10.2-2202-5.1.0-BETA-2042.jar) 
	UCHIJAAAA	movillages{1.5.2} [Mo' Villages] (1.9.4mo-villages-1.5.2.jar) 
	UCHIJAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAA	AIC{1.5} [Anti Id Conflict] (AntiIdConflict-1.5-1.10.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.5.0} [InfinityLib] (infinitylib-0.5.0.jar) 
	UCHIJAAAA	boatlantern{1.10.2-0.4.0} [Lantern] (boatlantern-0.4.0.jar) 
	UCHIJAAAA	cfm{4.1} [MrCrayfish's Furniture Mod] (cfm-4.1.1-mc1.10.2.jar) 
	UCHIJAAAA	ctrades{1.3.3} [Custom Trades Mod] (ctrades-1.3.3.jar) 
	UCHIJAAAA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJAAAA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHIJAAAA	dungeontactics{DT-0.11.1} [DungeonTactics] (DungeonTactics-1.10.2-0.11.1.jar) 
	UCHIJAAAA	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs_1.10.2.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	lootchests{1.0.0.1} [LootChests] (LootChests-1.10.2-1.0.0.3.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.2} [Minecraft Comes Alive] (MCA-1.10.2-5.2.2-universal.jar) 
	UCHIJAAAA	MoreFish{0.6} [More Fish] (More Fish-1.10.2-0.6.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.17} [Natura] (natura-1.10.2-4.1.0.17.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	sccraftingrunes{1.1} [SeriousCreeper's Crafting Runes] (sccraftingrunes-1.1.jar) 
	UCHIJAAAA	totemic{1.9.4-0.7.9.1} [Totemic] (Totemic-1.9.4-0.7.9.1.jar) 
	UCHIJAAAA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJAAAA	villagebox{0.5.0} [Village Box] (villagebox_1.10.2_0.5.0.jar) 
	UCHIJAAAA	waystones{2.0.10} [Waystones] (Waystones_1.10.2_2.0.10.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2202-5.1.0-BETA-2042.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Meiva'/1350, l='world', x=-90.50, y=68.00, z=477.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by masterrip** [comment]
1.10.2-2202-5.1.0-BETA-2039 Version did not have this problem

**Comment by simon816** [comment]
(reposted from the comment on the commit)

@masterrip That has nothing do do with these changes. It's an issue with the furniture mod.
It appears to have been fixed as of last week https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/5465b1bdfbb3f1bbdc74b244536490919bff848f
see this issue 
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/120
I'd expect an update of the furniture mod soon

**Comment by masterrip** [comment]
You're right . Furniture causes crash. Thank you.
