### ISSUE TITLE
SimpleChannelHandlerWrapper exception java.lang.RuntimeException: PLAYER target expects a Player arg [Sponge 1.10.2-2221-5.1.0-BETA-2109] 

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1242]
Dont know if its actually causing any issues but we get it very often seems thats its linked to waila when the player disconnects.

Error:

```
[Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.RuntimeException: PLAYER target expects a Player arg
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.validateArgs(FMLOutboundHandler.java:125) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:282) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:254) [SimpleNetworkWrapper.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:112) [MessageRequestTile$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by simon816** [comment]
Definitely an issue with Waila. I can't seem to find the source code for waila 1.10.2, where did you get it from and what version is it?

**Comment by alicheek** [comment]
looking in my mod directory now and cant actually find it , the only other mod like it i think is : Wawla-1.10.2-2.3.1.214

Its the SkyFactory3 3.0.6 modpack that is being used.

**Comment by simon816** [comment]
OK so I found out it's actually HWYLA (https://github.com/TehNut/HWYLA), they seem to have kept the `mcp.mobius.waila` name so I didn't realise it wasn't WAILA.

The issue appears to be client sends HWYLA message to server and the server replies but the player has since been disconnected.

Report this on the HWYLA issue tracker. Closing this since it's not an issue with spongeforge.

**Comment by alicheek** [comment]
ok thanks for the info will do :)
