### ISSUE TITLE
[1.11.2-2227] SpongeForge crashes on client side

### ISSUE THREAD

**Issue by liach** [SpongePowered/SpongeForge#1284]
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2227-6.0.0-BETA-2170
- Forge version: forge-1.11.2-13.20.0.2227
- Java version: 1.8.0_112 x64
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: None beside Forge and SpongeForge

**What is the expected result?**
The client finishes loading and show up main screen
**What is the current result?**
The game crashes during pre-initialization

A full log can be found [here](http://pastebin.com/2Q4MwQA9). Unfortunately, there is no `fml-client-latest.log` present.
Crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.11.2-2227-6.0.0-BETA-2170.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 2/20/17 1:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SpongeForge (sponge)
Caused by: java.lang.ClassCastException: net.minecraftforge.fml.common.LoadController cannot be cast to org.spongepowered.mod.interfaces.IMixinLoadController
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:293)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:268)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 108105488 bytes (103 MB) / 451670016 bytes (430 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2227 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2227.jar) 
	UCH	forge{13.20.0.2227} [Minecraft Forge] (forge-1.11.2-13.20.0.2227.jar) 
	UCH	spongeapi{6.0.0-SNAPSHOT-4dd6a22} [SpongeAPI] (spongeforge-1.11.2-2227-6.0.0-BETA-2170.jar) 
	UCE	sponge{1.11.2-2227-6.0.0-BETA-2170} [SpongeForge] (spongeforge-1.11.2-2227-6.0.0-BETA-2170.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.11.2-2227-6.0.0-BETA-2170.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4600'
```

Moreover, SpongeForge does not crash on a server environment with the same mods.

**Comment by piperswe** [comment]
Same thing's happening to me, except I have a bunch of other mods installed. Good to see that it's at least an issue with SpongeForge alone.

**Comment by ktole1999** [comment]
why are you loading sponge on a client? If you are testing then you need to test with server environment

**Comment by liach** [comment]
SpongeForge can be a client mod. It contains mixins for the client.

**Comment by bsun0000** [comment]
Sadly, but this issue is still not resolved. spongeforge-1.11.2-2227-6.0.0-BETA-2266 crashing with same problem..

> java.lang.ClassCastException: net.minecraftforge.fml.common.LoadController cannot be cast to org.spongepowered.mod.interfaces.IMixinLoadController

**Comment by Zidane** [comment]
There is more to this issue than you're putting here. This means a Mixin failed to apply so you've got a workspace issue. SpongeForge works fine in client-mode for me locally in IDE.

**Comment by liach** [comment]
Will test and report.

**Comment by liach** [comment]
Will test and report.
