### ISSUE TITLE
Exception caught when switching into nether world

### ISSUE THREAD

**Issue by gd71** [SpongePowered/SpongeForge#1296]
Forge Mod Loader version 12.18.3.2221 for Minecraft 1.10.2
Sponge 1.10.2-2221-5.2.0-BETA-2198 
This was not occurring before installing sponge mod
Other effects may or may not be linked
 - server disconnection when switching back to overworld (need to retry once)
 - some vanilla blocks cannot be mined (soulsand, quartz...) but netherhack ok

```
 [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityTravelToDimensionEvent@4ccf1fba:
java.lang.NullPointerException
        at com.bartz24.skyresources.events.EventHandler.onTravelToDimensionEvent(EventHandler.java:517) ~[EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_696_EventHandler_onTravelToDimensionEvent_EntityTravelToDimensionEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onTravelToDimension(ForgeHooks.java:970) [ForgeHooks.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callEntityTravelToDimensionEvent(SpongeForgeEventFactory.java:1177) [SpongeForgeEventFactory.class:1.10.2-2221-5.2.0-BETA-2198]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:474) [SpongeForgeEventFactory.class:1.10.2-2221-5.2.0-BETA-2198]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2198]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2198]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2198]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2198]
        at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityPortalEvent(EntityUtil.java:428) [EntityUtil.class:1.10.2-2221-5.2.0-BETA-2198]
        at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:1822) [mp.class:?]
        at org.spongepowered.common.entity.EntityUtil.teleportPlayerToDimension(EntityUtil.java:250) [EntityUtil.class:1.10.2-2221-5.2.0-BETA-2198]
        at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:4153) [lu.class:?]
        at net.minecraft.entity.Entity.func_70030_z(Entity.java:412) [rw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216) [sf.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) [rw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932) [sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) [zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zhc000(NetHandlerPlayServer.java:1968) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) [me.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[11:53:44] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[11:53:44] [Server thread/ERROR] [FML]: 0: NORMAL
[11:53:44] [Server thread/ERROR] [FML]: 1: ASM: com.bartz24.skyresources.events.EventHandler@244e38c3 onTravelToDimensionEvent(Lnet/minecraftforge/event/entity/EntityTravelToDimensionEvent;)V
[11:53:44] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:49100
```

**Comment by gd71** [comment]
wrong place?
Could be an issue from skyresources mod not detectable on a pure forge server?

**Comment by gd71** [comment]
in addition:
```
[11:46:51] [Server thread/ERROR] [Sponge]: /******************************************************************************************************************************************************/
> /******************************************************************************************************************************************************/
/*                                                     Changing a different World than expected!!                                                     */
/******************************************************************************************************************************************************/
/* Sponge is going to process the block changes as normal, however, a mod seems to be changing                                                        */
/* a world during a general server tick event! If you do not wish to see this                                                                         */
/* message, you may disable this check in the <gamedir>/config/sponge/global.conf under                                                               */
/* cause-tracker.report-different-world-changes = false                                                                                               */
/******************************************************************************************************************************************************/
/* Providing information of the event:                                                                                                                */
/* Changed world : WorldServer{LevelName=DIM-1, DimensionId=-1,                                                                                       */
/* DimensionType=minecraft:nether}                                                                                                                    */
/* Listener : ASM: portablejim.veinminer.core.MinerInstance@3efaa276                                                                                  */
/* mineScheduled(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent                                                                   */
/* )V                                                                                                                                                 */
/* Stacktrace:                                                                                                                                        */
/* java.lang.Exception: null                                                                                                                          */
/*     org.spongepowered.common.event.tracking.phase.plugin.ListenerPhaseState.logWarningOfDifferentWorldchanges(ListenerPhaseState.java:106)         */
/*     org.spongepowered.common.event.tracking.phase.plugin.PostServerTickListenerState.lambda$processPostTick$1(PostServerTickListenerState.java:60) */
/*     org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57)                                        */
/*     org.spongepowered.common.event.tracking.phase.plugin.PostServerTickListenerState.processPostTick(PostServerTickListenerState.java:58)          */
/*     org.spongepowered.common.event.tracking.phase.plugin.PluginPhase.unwind(PluginPhase.java:79)                                                   */
/*     org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:251)                                                      */
/*     org.spongepowered.mod.event.SpongeForgeEventHooks.postEventPhaseCheck(SpongeForgeEventHooks.java:172)                                          */
/*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:636)                                                                    */
/*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)                                                                    */
/*     net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)                                                     */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)                                                                    */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                                                             */
/*     java.lang.Thread.run(Thread.java:745)                                                                                                          */
/******************************************************************************************************************************************************/
```

**Comment by Aaron1011** [comment]
The root of this issue seems to be that `EntityPlayerMP.isDead` is somehow being set to `true`. I'm investigating further.

**Comment by gd71** [comment]
so maybe this can help. few seconds before in the same log
[11:48:59] [Server thread/WARN]: Force-added player with duplicate UUID 951d01e4-bc2c-41a1-b1bb-77b836a3efed
I've noticed a level.dat in the DIM-1 folder which was not present before
I've performed the migration twice before reporting that
Migration was done from a vanilla+forge well running server (I stil have it if you want me to test things) to spongeforge
Overworld doesn't seem to be affected but the nether has been regenerated each time

**Comment by bloodmc** [comment]
This is an issue with the mod

https://github.com/Bartz24/SkyResources/blob/1.10/src/main/java/com/bartz24/skyresources/events/EventHandler.java#L516

The dev's method can return null yet he never checks for it.

**Comment by gd71** [comment]
Thanks for your reply and time spent for investigation
Greatly appreciated
