### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by ArukaAlter** [SpongePowered/SpongeForge#1321]
Every once in a while the server console gets filled with this warning
https://hastebin.com/fecahoqili.vbs
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-982a6b0
SpongeForge: 1.10.2-2221-5.2.0-BETA-2211
Minecraft Forge: 12.18.3.2239

**Comment by Aaron1011** [comment]
That appears to be cut off. Can you include some lines above and below that exception (along with the full log, if you have it).

**Comment by ArukaAlter** [comment]
The server was stopped shortly after, and I can't seem to find the exact lines in the file anymore.
Here's the full log 
https://gist.github.com/ArukaAlter/f1e1778bf3115229894f8e18a4af0f59

**Comment by Aaron1011** [comment]
The only stacktrace from that log that I was able to find was this:

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_111-internal]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_111-internal]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_111-internal]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-2221-5.2.0-BETA-2211]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2221-5.2.0-BETA-2211]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
Caused by: java.lang.NullPointerException
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:842) ~[ServerPreparedStatement.class:?]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1885) ~[PreparedStatement.class:?]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[ProxyPreparedStatement.class:1.10.2-2221-5.2.0-BETA-2211]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:1.10.2-2221-5.2.0-BETA-2211]
	at me.lucko.luckperms.common.storage.backing.SQLBacking.loadGroup(SQLBacking.java:542) ~[SQLBacking.class:?]
	at me.lucko.luckperms.common.storage.backing.SQLBacking.loadAllGroups(SQLBacking.java:616) ~[SQLBacking.class:?]
	at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$6(AbstractStorage.java:150) ~[AbstractStorage.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_111-internal]
	... 7 more
```

Which is an issue with LuckPerms. If this issue re-occurs, please re-open it.
