### ISSUE TITLE
Stuck at logging in menu for clients

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1330]
Error Log: http://pastebin.com/CHG48Nmr

Sponge: spongeforge-1.10.2-2221-5.2.0-BETA-2219.jar

Hey there so we seem to have an issue where the player is stuck in a logging in screen basically untill they are kicked for being inactive, so it seems the server itself thinks the client is connected but the client cant see that its connected to the server. From what we have tested is that it only seems to be on custom made worlds but not the overworld or say the nether, this is happening on all servers we are running spongeforge with.

**Comment by Aaron1011** [comment]
The root of the problem seems to be this:

```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Could not get provider type for dimension 2, does not exist
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Could not get provider type for dimension 2, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:132) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:282) ~[DimensionManager.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at Reflector.call(Reflector.java:471) ~[Reflector.class:?]
	at net.minecraft.client.multiplayer.WorldClient.makeWorldProvider(WorldClient.java:107) ~[bln.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:80) ~[bln.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:274) ~[bll.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) ~[gw.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) ~[gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 9 more
```

Can you provide more details about the custom world that you're using?

**Comment by alicheek** [comment]
yes sorry for the delay, we are using the nucleus plugin to generate the other world but apart from that there isnt anything different with it.

**Comment by Aaron1011** [comment]
What generator type are you using?

**Comment by alicheek** [comment]
@Aaron1011 for that world its Biomes of plenty but we also have the same issues with the mining worlds we made which were just normal generation.

**Comment by ktole1999** [comment]
did someone create a world using rftools and then not remove it properly?

**Comment by bloodmc** [comment]
Unable to reproduce this with latest builds. If it reoccurs, provide proper steps on how to reproduce.
