### ISSUE TITLE
SimpleNetworkWrapper not working

### ISSUE THREAD

**Issue by FirEmerald** [SpongePowered/SpongeForge#1340]
I'm trying to make a 1.10.2 server for my mod, Metroid Cubed 3, which is HEAVILY dependent on it's packet system using SimpleNetworkWrapper. However, installing it on a spongeforge server causes the network to not send or receive ANY packets.

**Comment by FirEmerald** [comment]
Cannot debug this because dev builds of spongeforge do not work in the forge dev environment, they cause this error:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/AbstractClientPlayer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.AbstractClientPlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:604) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.common.core.json:entity.player.MixinEntityPlayer] from phase [DEFAULT] in config [mixins.common.core.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:883) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:836) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:596) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field playerLocation was not located in the target class
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:431) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:202) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:184) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1100) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:244) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:280) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:817) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:787) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:592) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) ~[spongeforge-1.10.2-2221-5.2.0-BETA-2219-dev-shaded.jar:1.10.2-2221-5.2.0-BETA-2219]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
```
Forge version is correct, already checked that.

**Comment by stephan-gh** [comment]
If you want to use the SpongeForge `dev-shaded` build you need to use the same MCP mappings version as Sponge. For 1.10.2 this is `snapshot_20160822`.

**Comment by FirEmerald** [comment]
How do I change the MCP mappings when I'm using forge? I'm currently at snapshot_20161009, which is clearly newer than the version you're at.
Also, that's still not the primary issue here. The primary issue is that SimpleNetworkWrapper isn't working with SpongeForge installed.

**Comment by stephan-gh** [comment]
You would need to change the MCP mappings of your project in the Gradle build script temporarily while testing with SpongeForge.

**Comment by FirEmerald** [comment]
Any reason sponge completely disables the server GUI? Becaue I kinda can't debug properly without being able to op myself on the dev server, which I need the GUI for since Eclipse doesn't seem to have an input panel.

**Comment by FirEmerald** [comment]
Ok, it seems the eclipse console can be used as an input. Still, the GUI is nice to have and I can't think of any reason to disable it completely

**Comment by FirEmerald** [comment]
Also, SimpleNetworkWrapper IS working in my dev - so it's either the obfuscated release or something on my server that's breaking it.

**Comment by FirEmerald** [comment]
The problem is in the obfuscated version.

**Comment by FirEmerald** [comment]
Nevermind, decided to test it on my computer and that's not the issue. Weird.

**Comment by FirEmerald** [comment]
Closed as I think it might actually be an issue with the network thread locking/crashing on the server
