### ISSUE TITLE
Apparent incompatibility with IC2's achievements

### ISSUE THREAD

**Issue by gdude2002** [SpongePowered/SpongeForge#1363]
Sponge: `1.10.2-2254-5.2.0-BETA-2234` (Server only, no Sponge on client)
Forge: 2254 (1.10.2)
IC2: 2.6.173 (Experimental for 1.10.2)

Upon mining some IC2 copper and collecting a block of it, the client is disconnected from the server and the following error occurs. Achievements from other mods seem to be fine.

<details> 
  <summary>Error log</summary>

```
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: net.minecraft.stats.Achievement cannot be cast to org.spongepowered.api.statistic.achievement.Achievement
at net.minecraft.util.text.event.HoverEvent.getHandle(SourceFile:572) ~[fa.class:?]
at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:710) ~[ew.class:?]
at net.minecraft.util.text.TextComponentTranslation.wrapFormatArgs(SourceFile:570) ~[ff.class:?]
at net.minecraft.util.text.TextComponentTranslation.createBuilder(SourceFile:552) ~[ff.class:?]
at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:697) ~[ew.class:?]
at org.spongepowered.common.text.SpongeTexts.toText(SpongeTexts.java:79) ~[SpongeTexts.class:1.10.2-2254-5.2.0-BETA-2234]
at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:48) ~[ChatUtil.class:1.10.2-2254-5.2.0-BETA-2234]
at net.minecraft.server.management.PlayerList.func_148544_a(PlayerList.java:2074) ~[mp.class:?]
at net.minecraft.server.management.PlayerList.func_148539_a(PlayerList.java:1070) ~[mp.class:?]
at net.minecraft.stats.StatisticsManagerServer.func_150873_a(SourceFile:69) ~[nr.class:?]
at net.minecraft.stats.StatisticsManager.func_150871_b(SourceFile:38) ~[nx.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71064_a(EntityPlayerMP.java:945) ~[lu.class:?]
at net.minecraft.entity.player.EntityPlayer.func_71029_a(EntityPlayer.java:1763) ~[zs.class:?]
at ic2.core.IC2Achievements.issueAchievement(IC2Achievements.java:211) ~[IC2Achievements.class:?]
at ic2.core.IC2Achievements.onItemPickup(IC2Achievements.java:378) ~[IC2Achievements.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_280_IC2Achievements_onItemPickup_EntityItemPickupEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) ~[EventBus.class:?]
at org.spongepowered.mod.event.SpongeForgeEventFactory.callEntityItemPickupEvent(SpongeForgeEventFactory.java:846) ~[SpongeForgeEventFactory.class:1.10.2-2254-5.2.0-BETA-2234]
at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:454) ~[SpongeForgeEventFactory.class:1.10.2-2254-5.2.0-BETA-2234]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2234]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2234]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2234]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2254-5.2.0-BETA-2234]
at org.spongepowered.common.event.SpongeCommonEventFactory.callPlayerChangeInventoryPickupEvent(SpongeCommonEventFactory.java:183) ~[SpongeCommonEventFactory.class:1.10.2-2254-5.2.0-BETA-2234]
at net.minecraft.entity.item.EntityItem.handler$onPlayerItemPickup$zeh000(EntityItem.java:800) ~[yk.class:?]
at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:367) ~[yk.class:?]
at net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$zfe000(EntityPlayer.java:3583) ~[zs.class:?]
at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578) ~[zs.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570) ~[zs.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
... 10 more
```
</details>

**Comment by johnfriedrich** [comment]
Does happen with vanilla + every other achievement aswell.
In some rare cases, it can even crash your server + client.
In addition to that, it breaks ALL messages sent from the server.

**Comment by gdude2002** [comment]
I've only noticed this with IC2's achievements, we've been getting others fine

**Comment by gdude2002** [comment]
In addition to this, I've just noticed that this also prevents achievements from being broadcast entirely. Once the error occurs, that stops working.

**Comment by bloodmc** [comment]
@simon816 Please fix this as it broke with your last commit.

**Comment by simon816** [comment]
Fixed. I implemented a stub class for Achievement since achievements aren't implemented on the 5.x branch
