### ISSUE TITLE
1.10.2 Crashes on forge 2254 [user error]

### ISSUE THREAD

**Issue by To-mos** [SpongePowered/SpongeForge#1433]
I have a fresh vanilla minecraft install with no mods(except spongeforge) or plugins running version 1.10.2, forge version 1.10.2-12.18.3.2254 and spongeforge-1.10.2-2254-5.2.0-BETA-2272 based on the site (1.10.2-2254-5.2.0-BETA-2272 "Stable" "Forge 2254") it is supposed to run on that version of forge but it crashes with this. The only mod running is spongeforge with no coremods, or other mods. Noticing ```[16:23:36] [main/INFO]: [org.spongepowered.launch.JavaVersionCheckUtils:ensureJava8:51]: You may be running an outdated version of Java. Any crashes from Sponge may require an update to Java.``` I also tried downloading the latest java 8 x64 and running it instead of the launcher version but it still crashes. It will launch when I remove spongeforge from the mods folder.

```
[16:23:36] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:23:36] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:23:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:23:36] [main/INFO]: Forge Mod Loader version 12.18.3.2254 for Minecraft 1.10.2 loading
[16:23:36] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at D:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[16:23:36] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar
[16:23:36] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:23:36] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:23:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.6.8 Source=file:/C:/Users/To-mos/AppData/Roaming/.minecraft/mods/spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar Env=CLIENT
[16:23:36] [main/INFO]: [org.spongepowered.launch.JavaVersionCheckUtils:ensureJava8:51]: You may be running an outdated version of Java. Any crashes from Sponge may require an update to Java.
[16:23:36] [main/INFO]: Compatibility level set to JAVA_8
[16:23:36] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[16:23:36] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[16:23:36] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[16:23:36] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:23:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:23:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:23:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:23:37] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:23:37] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:23:37] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:23:37] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[16:23:37] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@5215cd9a
[16:23:37] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:23:38] [main/WARN]: Error loading class: net/minecraft/client/Minecraft
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: java.lang.NullPointerException
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:552)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:207)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at java.lang.Class.getMethod0(Class.java:3010)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at java.lang.Class.getMethod(Class.java:1776)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:54)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[16:23:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:601]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/MinecraftDummyContainer
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.getMethod0(Class.java:3010)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.getMethod(Class.java:1776)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:54)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.MinecraftDummyContainer
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:23:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 8 more
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:603)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 10 more
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.NullPointerException
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:552)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:207)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591)
[16:23:38] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 13 more

```

**Comment by To-mos** [comment]
I have been away from minecraft a while and forgot plugins are server side...so yeah user error...

**Comment by gabizou** [comment]
This isn't so much plugins are server side, this is your version of Java 8 is too old. Sponge requires Java 8 Update 40+ due to a bug fix from oracle for some collections.

**Comment by To-mos** [comment]
As I had mentioned in the original post "I also tried downloading the latest java 8 x64 and running it instead of the launcher version"...
And It was the plugin because I was trying to use a server one in the client...as to why I closed this...It's now working.
