### ISSUE TITLE
Slot cannot be null! moving item to/from Ender Chest

### ISSUE THREAD

**Issue by diluvium** [SpongePowered/SpongeForge#1454]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.11.2-2282-6.0.0-BETA-2283.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 21/04/17 20:59
Description: Ticking player

java.lang.NullPointerException: Slot cannot be null!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at org.spongepowered.api.item.inventory.transaction.SlotTransaction.<init>(SlotTransaction.java:49)
	at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1478)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:1453)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2826)
	at net.minecraft.world.World.func_72866_a(World.java:4049)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:6396)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2163)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at org.spongepowered.api.item.inventory.transaction.SlotTransaction.<init>(SlotTransaction.java:49)
	at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1478)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:1453)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2826)
	at net.minecraft.world.World.func_72866_a(World.java:4049)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1717
	Entity Name: Auzathoth
	Entity's Exact location: 187.57, 87.00, 384.19
	Entity's Block location: World: (187,87,384), Chunk: (at 11,5,0 in 11,24; contains blocks 176,0,384 to 191,255,399), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:6396)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2163)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Auzathoth'/1717, l='world', x=187.57, y=87.00, z=384.19]]
	Chunk stats: ServerChunkCache: 447 Drop: 0
	Level seed: -4634911029666314389
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (236,64,236), Chunk: (at 12,4,12 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1835 game time, 1835 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 167717 (now: false), thunder time: 15517 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.9.6-gentoo-r1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 591749616 bytes (564 MB) / 1353187328 bytes (1290 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xms1G -Xmx2G
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282-universal.jar) 
	UCHIJAAAA	spongeapi{6.0.0-SNAPSHOT-cc938b9} [SpongeAPI] (spongeforge-1.11.2-2282-6.0.0-BETA-2283.jar) 
	UCHIJAAAA	sponge{1.11.2-2282-6.0.0-BETA-2283} [SpongeForge] (spongeforge-1.11.2-2282-6.0.0-BETA-2283.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.11.2-2282-6.0.0-BETA-2283.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 30; [EntityPlayerMP['Auzathoth'/1717, l='world', x=187.57, y=87.00, z=384.19]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by Nazta** [comment]
It's still in 2287, I had to revert to an older version(2260) to keep it working(but that keeps spamming errors with shulker boxes). Tried running no other mods, besides forge and spongeforge, same result.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.11.2-2282-6.0.0-BETA-2287.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 28/04/17 08:38
Description: Ticking player

java.lang.NullPointerException: Slot cannot be null!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at org.spongepowered.api.item.inventory.transaction.SlotTransaction.<init>(SlotTransaction.java:49)
	at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1478)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:1453)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2837)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:5894)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2174)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at org.spongepowered.api.item.inventory.transaction.SlotTransaction.<init>(SlotTransaction.java:49)
	at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1478)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:1453)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2837)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 209
	Entity Name: Nazta
	Entity's Exact location: 356.64, 64.00, 234.24
	Entity's Block location: World: (356,64,234), Chunk: (at 4,4,10 in 22,14; contains blocks 352,0,224 to 367,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:5894)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2174)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Nazta'/209, l='world', x=356.64, y=64.00, z=234.24]]
	Chunk stats: ServerChunkCache: 940 Drop: 0
	Level seed: -2482597248312941685
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":920.0,"heightScale":768.0,"lowerLimitScale":360.0,"upperLimitScale":360.0,"depthNoiseScaleX":24.0,"depthNoiseScaleZ":24.0,"depthNoiseScaleExponent":0.01,"mainNoiseScaleX":256.0,"mainNoiseScaleY":1024.0,"mainNoiseScaleZ":256.0,"baseSize":5.2,"stretchY":16.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":1.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":7,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useMansions":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":4,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":10,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":2,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16}
	Level spawn location: World: (626,63,199), Chunk: (at 2,3,7 in 39,12; contains blocks 624,0,192 to 639,255,207), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 96351833 game time, 98797015 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 87768 (now: false), thunder time: 12979 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4038883584 bytes (3851 MB) / 5244977152 bytes (5002 MB) up to 5244977152 bytes (5002 MB)
	JVM Flags: 2 total; -Xmx5G -Xms5G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228-universal.jar) 
	UCHIJAAAA	spongeapi{6.0.0-SNAPSHOT-fceb092} [SpongeAPI] (spongeforge-1.11.2-2282-6.0.0-BETA-2287.jar) 
	UCHIJAAAA	sponge{1.11.2-2282-6.0.0-BETA-2287} [SpongeForge] (spongeforge-1.11.2-2282-6.0.0-BETA-2287.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.11.2-2282-6.0.0-BETA-2287.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Nazta'/209, l='world', x=356.64, y=64.00, z=234.24]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/ba06972bdd9d87052f08de922132d151f9ec666b
