### ISSUE TITLE
Error force loading a chunk

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1463]
This stacktrace randomly appears in the console when using the BetterChunkLoader plugin:
```
>  [18:01:32] [Server thread/ERROR] [Sponge]: Could not pass UnloadWorldEvent$Impl to Plugin{id=betterchunkloader, name=BetterChunkLoader, version=3.4.6-SNAPS
HOT, description=Continuation of KaiKikuchi's BetterChunkLoader plugin for Sponge., authors=[ShadowKitten], source=/home/container/mods/BetterChunkLoader-Spon
ge-3.4.6-SNAPSHOT.jar}
java.lang.NullPointerException
    at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:119) ~[minecraft_server.1.10.2.jar:?]
    at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:853) ~[ForgeChunkManager.class:?]
    at org.spongepowered.mod.service.world.SpongeChunkTicketManager$SpongeLoadingTicket.unforceChunk(SpongeChunkTicketManager.java:224) ~[SpongeChunkTicketMan
ager$SpongeLoadingTicket.class:1.10.2-2254-5.2.0-BETA-2264]
    at ca.shadownode.betterchunkloader.sponge.ChunkManager.unloadChunk(ChunkManager.java:136) ~[ChunkManager.class:?]
    at ca.shadownode.betterchunkloader.sponge.ChunkManager.lambda$unloadChunkLoader$3(ChunkManager.java:87) ~[ChunkManager.class:?]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_111-internal]
    at ca.shadownode.betterchunkloader.sponge.ChunkManager.unloadChunkLoader(ChunkManager.java:86) ~[ChunkManager.class:?]
    at ca.shadownode.betterchunkloader.sponge.events.WorldListener.lambda$onWorldUnLoad$3(WorldListener.java:40) ~[WorldListener.class:?]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111-internal]
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_111-internal]
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_111-internal]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111-internal]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111-internal]
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_111-internal]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_111-internal]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111-internal]
    at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423) ~[?:1.8.0_111-internal]
    at ca.shadownode.betterchunkloader.sponge.events.WorldListener.onWorldUnLoad(WorldListener.java:39) ~[WorldListener.class:?]
    at org.spongepowered.common.event.listener.UnloadWorldEventListener_WorldListener_onWorldUnLoad281.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2254-5.2.0-BETA-2264]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2264]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2264]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2264]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2264]
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2254-5.2.0-BETA-2264]
    at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:484) [WorldManager.class:1.10.2-2254-5.2.0-BETA-2264]
    at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:654) [DimensionManager.class:?]
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```

The author linked here: https://bitbucket.org/shadownode/betterchunkloader/issues/8/error-on-stop

**Comment by phit** [comment]
still an issue in 1.12.2, pretty sure shadow said its a forge issue at some point

**Comment by LemADEC** [comment]
BCL says its SpongeForge issue. SpongeForge is closed. Where's the fix?

**Comment by phit** [comment]
I talked to the author of BCL, this is a nonissue. Quote:
> It's because I didn't understand how the chunkloading callbacks worked and I believed that you had to unforce the chunks to get them to not load after startup.
>
> Infact forge never ever stores the chunks force loaded on the ticket it's up to the mod or plugin to handle the callback and readd them on world-load. 
> Someone should outline a wiki entry for that as it was extremely unclear that's what the callbacks and things were for until I went digging.
