### ISSUE TITLE
Crash when using Extra Utilities Quantum Quarry

### ISSUE THREAD

**Issue by kaal-1** [SpongePowered/SpongeForge#1466]
Does not happen when not using sponge.

Description: Ticking block entity
 
java.util.concurrent.RejectedExecutionException: Task net.minecraft.world.WorldServer$$Lambda$1849/1667412907@17fbc659 rejected from java.util.concurrent.ThreadPoolExecutor@745a78d6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3048]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
    at net.minecraft.world.WorldServer.updateLightAsync(WorldServer.java:3890)
    at net.minecraft.world.WorldServer.func_180500_c(WorldServer.java:3715)
    at net.minecraft.world.World.func_175664_x(World.java:2779)
    at org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:478)
    at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2670)
    at net.minecraft.world.gen.structure.template.Template.func_189960_a(SourceFile:222)
    at net.minecraft.world.gen.structure.template.Template.func_189962_a(SourceFile:180)
    at net.minecraft.world.gen.feature.WorldGenFossils.func_180709_b(SourceFile:92)
    at net.minecraft.world.biome.BiomeDesert.func_180624_a(BiomeDesert.java:43)
    at net.minecraft.world.gen.ChunkProviderFlat.func_185931_b(ChunkProviderFlat.java:215)
    at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
    at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.generate(WorldProviderSpecialDim.java:390)
    at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.prepareNewChunk(WorldProviderSpecialDim.java:260)
    at com.rwtema.extrautils2.quarry.TileQuarry.getNextChunk(TileQuarry.java:428)
    at com.rwtema.extrautils2.quarry.TileQuarry.getNewChunk(TileQuarry.java:420)
    at com.rwtema.extrautils2.quarry.TileQuarry.advance(TileQuarry.java:409)
    at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:301)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:226)
    at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2803)
    at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2790)
    at net.minecraft.world.World.func_72939_s(World.java:6003)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by bloodmc** [comment]
Provide the complete fml-server-latest log so I can see what it showed before this error.

**Comment by DrZoddiak** [comment]
I'm having a similar issue. Below I've put my crash report (top) and the fml-server-latest (bottom)
This was run on a server with only XU2 and sponge

https://pastebin.com/37RQgLiw

https://pastebin.com/HFpr25LE

**Comment by bloodmc** [comment]
@DrZoddiak Stop using pastebin as it strips files that are too long. Use gist.github.com

**Comment by DrZoddiak** [comment]
My bad I had no idea!
same separation as before crash report (top) fml (bottom) sorry for that!
https://gist.github.com/DrZoddiak/f88bf2b3c89f6c9dbb5b14e0b1426749
https://gist.github.com/DrZoddiak/927cc72280a1730573bf8155e7be6f5d

**Comment by bloodmc** [comment]
@DrZoddiak 

spongeforge-1.10.2-2254-5.2.0-BETA-2264.jar
You will not be supported unless you are running latest SpongeForge builds. Update then post a new log.

**Comment by DrZoddiak** [comment]
Oh dear my bad again! The only reason I ran the test was because it wasn't working on the new version, I forgot to load it into the test!
Here's the files (again) with the latest version sorry!

https://gist.github.com/DrZoddiak/c734671287378aab226ceb15cb4bc030
https://gist.github.com/DrZoddiak/922725c150d3a5f128f68e9e865bbd70
