### ISSUE TITLE
Error - Mixin apply failed - after adding foamfix and BetterFPS

### ISSUE THREAD

**Issue by Heartfyre** [SpongePowered/SpongeForge#1485]
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2300
- Forge version: 2281
- Java version: jre1.8.0_131 (64Bit)
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
Forge mods only
BiomesOPlenty-1.11.2-6.1.0.2206-universal
foamfix-0.6.2-anarchy
BetterFps-1.4.3

**What is the current result?**
Hey guys,

I just started a fresh and new sponge/forge server, which I am running local.

I am running Sponge version: 1.10.2-2281-5.2.0-BETA-2300 together with Forge: 2281

Right now there's only Biomes O' Plenty, foamfix (0.6.2) and BetterFps (1.4.3). After I added foamfix and BetterFPS to the mods, I am getting some error on the log. As I am not an expert at all, I am not sure what it means, but it is coming from those two mods. I am not sure, if this is even Sponge related or a problem with those mods.

Error log: [fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/974334/fml-server-latest.txt)

Here's the part of the log, with the error:

```[20:16:11] [main/INFO] [BetterFps]: Patching net.minecraft.block.Block... (alu)
[20:16:11] [main/INFO] [mixin]: A re-entrant transformer 'guichaguri.betterfps.transformers.PatcherTransformer' was detected and will no longer process meta class data
[20:16:13] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixReplaceClassSimpleName$FFMethodVisitor:visitMethodInsn:47]: Replaced INVOKEVIRTUAL getSimpleName
[20:16:15] [main/INFO] [BetterFps]: Patching math utils with "RIVENS_HALF" algorithm
[20:16:15] [main/INFO] [mixin]: A re-entrant transformer 'guichaguri.betterfps.transformers.MathTransformer' was detected and will no longer process meta class data
[20:16:16] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixReplaceClassSimpleName$FFMethodVisitor:visitMethodInsn:47]: Replaced INVOKEVIRTUAL getSimpleName
[20:16:17] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[20:16:17] [main/INFO] [BetterFps]: Patching net.minecraft.block.Block... (alu)
[20:16:17] [main/INFO]: [STDOUT]: Spliced in METHOD: net.minecraft.block.state.BlockStateContainer.createState
[20:16:18] [main/INFO] [BetterFps]: Patching net.minecraft.block.BlockHopper... (aoh)
[20:16:18] [main/INFO] [BetterFps]: Patching math utils with "RIVENS_HALF" algorithm
[20:16:18] [main/INFO]: [STDOUT]: Spliced in METHOD: net.minecraft.block.state.BlockStateContainer.createState
[20:16:18] [main/INFO] [mixin]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[20:16:18] [main/WARN] [mixin]: Mixin apply failed mixins.common.core.optional.json:util.math.MixinMutableBlockPos -> net.minecraft.util.math.BlockPos$MutableBlockPos: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field field_177997_b was not located in the target class
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field field_177997_b was not located in the target class
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:448) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:204) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.<init>(BlockPropertyIdProvider.java:146) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider$Holder.<clinit>(BlockPropertyIdProvider.java:281) [BlockPropertyIdProvider$Holder.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getInstance(BlockPropertyIdProvider.java:49) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getIdAndTryRegistration(BlockPropertyIdProvider.java:67) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerBlockTrait(BlockTypeRegistryModule.java:128) [BlockTypeRegistryModule.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerFromGameData(BlockTypeRegistryModule.java:116) [BlockTypeRegistryModule.class:1.11.2-2282-7.0.0-BETA-2301]
        at net.minecraft.block.Block.handler$onRegisterBlock$zzl000(Block.java:2660) [alu.class:?]
        at net.minecraft.block.Block.func_176215_a(Block.java:2448) [alu.class:?]
        at net.minecraft.block.Block.func_176219_a(Block.java:2452) [alu.class:?]
        at net.minecraft.block.Block.func_149671_p(Block.java:2150) [alu.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:491) [kt.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1419) [MinecraftServer.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [yucom.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [yucom.jar:?]
[20:16:19] [main/INFO] [BetterFps]: Patching net.minecraft.tileentity.TileEntityHopper... (asp)
[20:16:20] [main/INFO] [BetterFps]: Patching net.minecraft.tileentity.TileEntityBeacon... (asb)
[20:16:23] [main/INFO] [BetterFps]: Patching net.minecraft.server.dedicated.DedicatedServer... (lh)
[20:16:24] [Server thread/INFO]: Starting minecraft server version 1.11.2```

**Comment by phit** [comment]
remove BetterFPS there's no point in having it installed with Sponge anyway, see this  https://github.com/SpongePowered/SpongeForge/issues/762#issuecomment-233420532

**Comment by Heartfyre** [comment]
Hey mate,

thanks for the hint! I did remove it. That being said, the error still appears with foamfix only.

```[20:44:04] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixReplaceClassSimpleName$FFMethodVisitor:visitMethodInsn:47]: Replaced INVOKEVIRTUAL getSimpleName
[20:44:07] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixReplaceClassSimpleName$FFMethodVisitor:visitMethodInsn:47]: Replaced INVOKEVIRTUAL getSimpleName
[20:44:08] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[20:44:08] [main/INFO]: [STDOUT]: Spliced in METHOD: net.minecraft.block.state.BlockStateContainer.createState
[20:44:09] [main/INFO]: [STDOUT]: Spliced in METHOD: net.minecraft.block.state.BlockStateContainer.createState
[20:44:09] [main/INFO] [mixin]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[20:44:09] [main/WARN] [mixin]: Mixin apply failed mixins.common.core.optional.json:util.math.MixinMutableBlockPos -> net.minecraft.util.math.BlockPos$MutableBlockPos: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field field_177997_b was not located in the target class
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field field_177997_b was not located in the target class
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:448) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:204) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.<init>(BlockPropertyIdProvider.java:146) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider$Holder.<clinit>(BlockPropertyIdProvider.java:281) [BlockPropertyIdProvider$Holder.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getInstance(BlockPropertyIdProvider.java:49) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getIdAndTryRegistration(BlockPropertyIdProvider.java:67) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerBlockTrait(BlockTypeRegistryModule.java:128) [BlockTypeRegistryModule.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerFromGameData(BlockTypeRegistryModule.java:116) [BlockTypeRegistryModule.class:1.11.2-2282-7.0.0-BETA-2301]
        at net.minecraft.block.Block.handler$onRegisterBlock$zzl000(Block.java:2660) [alu.class:?]
        at net.minecraft.block.Block.func_176215_a(Block.java:2448) [alu.class:?]
        at net.minecraft.block.Block.func_176219_a(Block.java:2452) [alu.class:?]
        at net.minecraft.block.Block.func_149671_p(Block.java:2150) [alu.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:491) [kt.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1419) [MinecraftServer.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [yucom.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [yucom.jar:?]
[20:44:15] [Server thread/INFO]: Starting minecraft server version 1.11.2```

**Comment by phit** [comment]
Try the "lawful" FoamFix version, since it's less invasive. If that works I would consider opening an issue on the FoamFix side [here](https://github.com/asiekierka/FoamFix/issues) and see if asie can fix it, since he fixed compatibility with [Sponge before](https://github.com/asiekierka/FoamFix/issues/15).

**Comment by Heartfyre** [comment]
Hey @phit 

Thank you for your reply. As it seems it is indeed a problem with the Anarchy-version, as the lawful isn't producing any errors so far. I will let asie know about it. Thanks for pointing it out and helping me that quick!

Best regards!

**Comment by Deamon5550** [comment]
@Heartfyre make sure you're using the latest version, there was an issue with older versions of anarchy with sponge but they were fixed
