### ISSUE TITLE
Crash on Server Launch with OTG

### ISSUE THREAD

**Issue by chezpaul** [SpongePowered/SpongeForge#1489]
- SpongeForge version: 2281 2300 1.10.2
- Forge version: Forge 2281 1.10.2
- Java version: Java 8 121
- Operating System:
- [√ ] macOS 10.12.4
My server crashes when I add the [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) mod in mods folder.
Without Sponge (but with OTG), server starts fine, without Open Terrain Generator (but with Sponge), server also starts fine.

With both in mods folder, I get this:
[09:06:46] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 95 mods [09:06:46] [Server thread/INFO] [pjw]: Running World Migration tool.. 
[09:06:46] [Server thread/INFO] [pjw]: No worlds to migrate 
[09:06:47] [Server thread/INFO]: Preparing level "Biome Bundle" 
[09:06:47] [Server thread/INFO] [Sponge]: Checking for worlds that need to be migrated... 
[09:06:47] [Server thread/INFO] [Sponge]: No worlds were found in need of migration. 
[09:06:47] [Server thread/INFO] [OTG]: Creating world "Biome Bundle" 
[09:06:47] [Server thread/ERROR]: Encountered an unexpected exception java.lang.NullPointerException at com.khorn.terraincontrol.forge.TCDimensionManager.RemoveTCDims(TCDimensionManager.java:449) ~[TCDimensionManager.class:?] at com.khorn.terraincontrol.forge.ForgeWorld.<init>(ForgeWorld.java:149) ~[ForgeWorld.class:?] at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:243) ~[WorldLoader.class:?] at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:221) ~[WorldLoader.class:?] at com.khorn.terraincontrol.forge.TCWorldType.getBiomeProvider(TCWorldType.java:67) ~[TCWorldType.class:?] at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:56) ~[atl.class:?] at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39) ~[atl.class:?] at net.minecraft.world.WorldServer.redirect$onRegisterWorld$zka000(WorldServer.java:1668) ~[ls.class:?] at net.minecraft.world.WorldServer.<init>(WorldServer.java:113) ~[ls.class:?] at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:796) ~[WorldManager.class:1.10.2-2281-5.2.0-BETA-2300] at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:767) ~[WorldManager.class:1.10.2-2281-5.2.0-BETA-2300] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3485) ~[MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) ~[ld.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

Thanks

**Comment by cfulton** [comment]
Hey guys, getting this issue as well.

Here are the details from the crash report

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2312.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta4-anarchy.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 9/05/17 8:07 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.khorn.terraincontrol.forge.TCDimensionManager.RemoveTCDims(TCDimensionManager.java:449)
	at com.khorn.terraincontrol.forge.ForgeWorld.<init>(ForgeWorld.java:149)
	at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:243)
	at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:221)
	at com.khorn.terraincontrol.forge.TCWorldType.getBiomeProvider(TCWorldType.java:67)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:56)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39)
	at net.minecraft.world.WorldServer.redirect$onRegisterWorld$zka000(WorldServer.java:1668)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:113)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:796)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:767)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3485)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.0-77-generic
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 283108152 bytes (269 MB) / 606601216 bytes (578 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAA	ivtoolkit{1.3.2.1-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJAA	spongeapi{5.2.0-SNAPSHOT-a26c654} [SpongeAPI] (minecraft.jar) 
	UCHIJAA	sponge{1.10.2-2281-5.2.0-BETA-2312} [SpongeForge] (spongeforge-1.10.2-2281-5.2.0-BETA-2312.jar) 
	UCHIJAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAA	openterraingenerator{v14} [Open Terrain Generator] (OpenTerrainGenerator-1.10.2-v17.jar) 
	UCHIJAA	biomebundle{1.0} [Biome Bundle] (Biome_Bundle-v5.jar) 
	UCHIJAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta4-anarchy.jar) 
	UCHIJAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAA	reccomplex{1.2.10-1.10} [Recurrent Complex] (RecurrentComplex-1.2.10-1.10.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  
SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2312.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta4-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)`

**Comment by Grauldon** [comment]
This [post][a] in the forum may help.

https://forums.spongepowered.org/t/sponge-server-crash/18780

[a]: <https://forums.spongepowered.org/t/sponge-server-crash/18780>

**Comment by phit** [comment]
I believe this was fixed by the mod author https://github.com/PG85/OpenTerrainGenerator/issues/25#issuecomment-307558973
