### ISSUE TITLE
Exception in thread "Server Watchdog"

### ISSUE THREAD

**Issue by EmanYm** [SpongePowered/SpongeForge#1522]
**I am currently running...**

- SpongeForge version:  [MC1.10.2]SpongeForge[v5.2.0β2328][Forge2281][S].jar
- Forge version: [MC1.10.2]Forge[v12.18.3.2297][U].jar
- Java version: jre1.8.0_131
- Operating System:
 - [x] Windows

- Plugins/Mods: 
I started to get this issue with just the above version of SpongeForge and [MC1.10.2]LuckPermsSponge[v3.1.51][S].jar installed

(I can get an fml-latest, console log and configs if it's needed.)

The only other thing that happens is a roughly two minute hang when LuckPerms is registering its api
>[10:43:26] [Server thread/INFO]: [LP] Registering API...
[10:45:09] [Server thread/INFO]: [LP] Successfully loaded.

After everything else finishes I get this
>[10:55:03] [Server thread/INFO]: Done (3.161s)! For help, type "help" or "?"
Exception in thread "Server Watchdog" [10:55:03] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalArgumentException: timeout value is negative
[10:55:03] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.sleep(Native Method)
[10:55:03] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[10:55:03] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.run(Thread.java:745)

Other possibly relevant information
As Blood said at the bottom of [this](https://github.com/SpongePowered/SpongeForge/issues/1348) issue, my `max-tick-time=600`

**Comment by EmanYm** [comment]
I removed ChatUI, and not this error is telling me it's caused by FoxGuard.  I will close this, and open a ticket there, then reference this issue.
