### ISSUE TITLE
[1.11.2] Task rejected crash

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1534]
SF randomly crashed with no apparent reason. I got this crash when my players started walking to find their homes (just opened the server)...

    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-806a22a
    SpongeForge: 1.11.2-2282-6.1.0-BETA-2343
    Minecraft Forge: 13.20.0.2298
    Operating System: Linux (Alpine)

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, OpenComputers (Core), Spong
eAPI, SpongeForge, ccl-entityhook, NoXray, Psi, Quark, AutoRegLib, Baubles, BetterChunkLoader, Biomes O' Plenty, Botania, BuildCraft Lib, BuildCraft, BC Fac
tory, BC Transport, BC Builders, BC Energy, BC Robotics, BC Silicon, Chameleon, CodeChicken Lib, CraftTweaker JEI Support, Just Enough Items, Crafttweaker, 
Embers, EnderStorage, Ender Zoo,  FastAsyncWorldEdit, WorldEdit, IndustrialCraft 2, Forestry, GriefPrevention, Holograms, Inventory Tweaks, JourneyMap, Kai'
s Commons, LuckPerms, MagiChat, Magistics, Nucleus, OpenComputers, Pam's HarvestCraft, Player Glow, Reborn Core, reborncore-MCMultiPart, Recurrent Complex, 
Roots 2, SignEditor, SimpleAntiAFK, Steve's Carts 2, Storage Drawers, TabManager, The One Probe

Quick stacktrace:
```
java.util.concurrent.RejectedExecutionException: Task net.minecraft.world.WorldServer$$Lambda$1462/414191456@7ccc08f rejected from java.util.concurrent.ThreadPoolExecutor@7d3d6347[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 11874860]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
	at net.minecraft.world.WorldServer.updateLightAsync(WorldServer.java:3943)
	at net.minecraft.world.WorldServer.func_180500_c(WorldServer.java:3768)
	at net.minecraft.world.World.func_175664_x(World.java:2737)
	at org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:481)
	at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2687)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:174)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:132)
	at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:268)
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$zkd000(WorldServer.java:2195)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:745)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:748)
```

Full crash-report: https://hastebin.com/isologagut.pl

**Comment by gigafunk** [comment]
I'm just nobody lurking waiting to see about an issue I am having, so this is unofficial. But, have you tried to match the forge version to the sponge version? I dunno how much it matters. But I always do. I keep everything else up to date, but I leave forge the same as sponge. That sponge was built against 2282 and your running 2298.

**Comment by Eufranio** [comment]
Well, BuildCraft needs a newer version of Forge, so I can't :/
I've seen other people running BC in the issue tracker and they dont seem to have this problem (or didnt report) so I doubt it could be the issue.

**Comment by gigafunk** [comment]
I almost retracted my statement cause you have an avatar and I figured you probably had a good reason.lol

Sorry bout the noise. You just never know.

**Comment by Eufranio** [comment]
It's fine :+1:

**Comment by Eufranio** [comment]
New crash, now mentioning Biomes O' Plenty:
```
java.util.concurrent.RejectedExecutionException: Task net.minecraft.world.WorldServer$$Lambda$1549/1201331068@3be8933e rejected from java.util.concurrent.ThreadPoolExecutor@e5a38d0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 27063349]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
	at net.minecraft.world.WorldServer.updateLightAsync(WorldServer.java:3943)
	at net.minecraft.world.WorldServer.func_180500_c(WorldServer.java:3768)
	at net.minecraft.world.World.func_72975_g(World.java:449)
	at net.minecraft.world.chunk.Chunk.func_76615_h(Chunk.java:361)
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2198)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:2090)
	at org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:470)
	at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2687)
	at net.minecraft.world.gen.feature.WorldGenerator.func_175903_a(SourceFile:31)
	at net.minecraft.world.gen.feature.WorldGenTrees.func_180709_b(WorldGenTrees.java:118)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:138)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:229)
	at net.minecraft.world.biome.BiomeForest.func_180624_a(BiomeForest.java:99)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:560)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:247)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:973)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zpi000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:748)
```
Full crash-report: https://gist.github.com/Eufranio/5ef9e30d87bf9e324d5a5659797849dd
and with RecurrentComplex: https://gist.github.com/Eufranio/466bf839937e137cdf29dc0e5b161da6

**Comment by simon816** [comment]
This is an issue with the "async lighting" optimisation. For now, set `async-lighting=false` in the global.conf file.
I've previously seen this issue on the forums:
https://forums.spongepowered.org/t/error-spongecoremod-i-need-help/18153/4

**Comment by Eufranio** [comment]
I have it already disabled.

**Comment by Eufranio** [comment]
Please don't forget this 😢

**Comment by Zidane** [comment]
@JBYoshi 

Can you look into this?

**Comment by JBYoshi** [comment]
Sorry I missed this. I put it on a TODO list I created and will try to get to it later today.

**Comment by JBYoshi** [comment]
@Eufranio Could you add this plugin to your server and post the full console output next time the issue occurs?

(Note: I had to change the file extension for GitHub to accept it; just place it in your `mods` folder like any other plugin.)
(Note 2: Source code is included in the JAR/ZIP in case you want it.)

[common1534-1.0-1.10.2.zip](https://github.com/SpongePowered/SpongeForge/files/1131009/common1534-1.0-1.10.2.zip)
[common1534-1.0-1.11.2.zip](https://github.com/SpongePowered/SpongeForge/files/1131032/common1534-1.0-1.11.2.zip)

**Comment by Eufranio** [comment]
Sorry, but I cannot test this on my end, I removed Biomes O' Plenty and won't be adding it anytime soon :(

**Comment by JBYoshi** [comment]
@Eufranio It isn't related to Biomes O' Plenty. It's something else, though I can't tell what it is without more debugging information (which is what the plugin does).

**Comment by Eufranio** [comment]
The crash didn't happen anymore since I removed Biomes O' Plenty. I can use your plugin but not sure if it will give you the info you need (since there are no crashes to debug...)

**Comment by JoeSGT** [comment]
Hello i am also having this very same issue with 1.10.2,
here is my crash report https://pastebin.com/YvZRVpDP
here is the list of the plugins i have https://gyazo.com/2822d33067b7df8d07077704cc72e546
i don't know if this help or not maybe @Eufranio can compare plugins so like that @JBYoshi  can find the issue faster i just release my server and this happen dang :/
Sponge verison: https://gyazo.com/e5dd5c474f3395c128c6496719981528

**Comment by JoeSGT** [comment]
what @JBYoshi  requested here: https://pastebin.com/yvmaEknk

**Comment by JoeSGT** [comment]
Here is the Latest.logs also
https://pastebin.com/tx5cDJjD  - FIXED LINK
all i modified was the player and mine IP address

**Comment by JBYoshi** [comment]
@JoeSGT

Sorry I didn't get to this earlier; I was on vacation. Next time you get this crash, could you post the console output (not the crash report)?
