### ISSUE TITLE
CME generating a world 

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1565]
I started walking and suddenly the server crashed. It will crash again if I generate more chunks.

**I am currently running...**
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-a15cc3e
    SpongeForge: 1.11.2-2282-6.1.0-BETA-2358
    Minecraft Forge: 13.20.0.2298
- Operating System: Linux (Alpine)

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, OpenComputers (Core), SpongeA
PI, SpongeForge, FoamFixCore, ccl-entityhook, Animania, Psi, Quark, AutoRegLib, Baubles, BetterChunkLoader, Biomes O' Plenty, Botania, BuildCraft Lib, BuildCr
aft, BC Factory, BC Transport, BC Builders, BC Energy, BC Robotics, BC Silicon, Chameleon, CodeChicken Lib, CraftTweaker JEI Support, Just Enough Items, Craft
tweaker, Embers, EnderPay, EnderStorage, Ender Zoo,  FastAsyncWorldEdit, WorldEdit, FoamFix, IndustrialCraft 2, Forestry, Gravestone, GriefPrevention, Invento
ry Tweaks, JourneyMap, Kai's Commons, LuckPerms, MagiChat, Magistics, Nucleus, OpenComputers, Pam's HarvestCraft, Player Glow, Reborn Core, reborncore-MCMulti
Part, Recurrent Complex, Refined Storage, Roots 2, SignEditor, SimpleAntiAFK, Steve's Carts 2, Storage Drawers, TabManager, The One Probe, Vending

Stacktrace:
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.complementStructuresInChunk(WorldGenStructures.java:129)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.decorate(WorldGenStructures.java:193)
	at ivorius.reccomplex.events.handlers.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_260_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:186)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:973)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zpd000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:748)
```
Full crash-report: https://hastebin.com/kozijeloko.sql

**Comment by Zidane** [comment]
@Deamon5550 thoughts?

**Comment by Deamon5550** [comment]
Can you reproduce this without sponge? This is happening entirely within their code with their own data structures so I think it looks like an issue with their mod.

**Comment by Eufranio** [comment]
The RecComplex dev fixed this issue (yea it was in his end)
