### ISSUE TITLE
"Exception reading ./world/level.dat" On every startup

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeForge#1583]
**I am currently running...**
- SpongeForge version: 1.12-2321-7.0.0-BETA-2386 (Didn't occur in 1.12-2321-7.0.0-BETA-2383)
- Forge version: 1.12-14.21.0.2324
- Java version: 1.8_131
- Operating System: Linux Debian 
- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, OpenEye, SpongeAPI, SpongeForge, Broadcast, BungeeTabListPlus-SpongeBridge, EconomyLite,  FastAsyncWorldEdit, WorldEdit, FoxCore, FoxGuard, Inventory Sync, Latch, LuckPerms, MMCTickets, ModBanner, Nucleus, NuVotifier, PayDay, Prism, VotifierListener, SkinsRestorer, SleepVote, Just Enough Items

**What is the expected result?**

The server should start normally without any issues.

**What is the current result?**

The server gives this error:

```
[01:11:42] [Server thread/ERROR]: Exception reading ./world/level.dat


java.lang.NullPointerException: null
        at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:282) ~[PersistentRegistryManager.class:?]
        at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:332) ~[FMLContainer.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:419) ~[FMLCommonHandler.class:?]
        at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bfa.class:?]
        at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$zpj000(SaveHandler.java:1064) [bez.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bez.class:?]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:686) [WorldManager.class:1.12-2321-7.0.0-BETA-2386]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3550) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267) [nx.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[01:11:42] [Server thread/WARN] [FML]: Forge Mod Loader detected that the backup level.dat is being used.

This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

Full logs: https://gist.github.com/BrainStone/4fb6ce66836afe7d64d6191f3472d069

**Comment by BrainStone** [comment]
Accidentally created an issue over on MinecraftForge/MinecraftForge#3989

**Comment by BrainStone** [comment]
Damnit xD Might be still a Forge issue. I honestly don't know...

**Comment by gabizou** [comment]
It's a forge thing to be honest, Sponge doesn't have many things that interfere with Forge's registry management system aside from callback additions on additional mod items being registered (things like items, blocks, tile entities, entities, villager professions, careers, etc.)
