### ISSUE TITLE
Unable to connect when SpongeForge is installed client side

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeForge#1592]
**I am currently running...**
```
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-a15cc3e
    SpongeForge: 1.11.2-2315-6.1.0-BETA-2395
    Minecraft Forge: 13.20.0.2315
```

**Exception:**
```
[23:28:29] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:2024) ~[bno.class:?]
        at net.minecraft.network.play.server.SPacketEntityProperties.func_148833_a(SourceFile:70) ~[ik.class:?]
        at net.minecraft.network.play.server.SPacketEntityProperties.func_148833_a(SourceFile:15) ~[ik.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:164) ~[PacketUtil.class:1.11.2-2315-6.1.0-BETA-2395]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjk000(SourceFile:539) ~[fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 9 more
```
```
[10:48:11] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:917) ~[bno.class:?]
        at net.minecraft.network.play.server.SPacketSpawnMob.func_148833_a(SPacketSpawnMob.java:125) ~[ft.class:?]
        at net.minecraft.network.play.server.SPacketSpawnMob.func_148833_a(SPacketSpawnMob.java:16) ~[ft.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:164) ~[PacketUtil.class:1.11.2-2315-6.1.0-BETA-2395]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjk000(SourceFile:539) ~[fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8Exception in thread "Thread-8" java.lang.NullPointerException
        at javax.swing.text.DefaultStyledDocument.getParagraphElement(DefaultStyledDocument.java:597)
        at javax.swing.text.StyledEditorKit$AttributeTracker.updateInputAttributes(StyledEditorKit.java:240)
        at javax.swing.text.StyledEditorKit$AttributeTracker.caretUpdate(StyledEditorKit.java:275)
        at javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:397)
        at javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4394)
        at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4416)
        at javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:802)
        at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1274)
        at javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1173)
        at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1154)
        at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1051)
        at javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1631)
        at com.skcraft.launcher.swing.MessageLog.log(MessageLog.java:125)
        at com.skcraft.launcher.swing.MessageLog$ConsoleOutputStream.flush(MessageLog.java:308)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at java.io.PrintWriter.flush(PrintWriter.java:320)
        at com.skcraft.launcher.swing.MessageLog$2.run(MessageLog.java:213)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by EmanYm** [comment]
I suggest removing SpongeForge from your client.
Probably don't need SpongeAPI client side either

**Comment by parlough** [comment]
@EmanYm SpongeForge is designed to be able to work on servers and clients just fine, it even provides some very slight extra features. Eventually the client version will provide a lot more functionality as well.

It can be a good way to test your plugins quickly, and it is another use case plugin developers should test and plan for. There are some people who even use SpongeForge on singleplayer to add certain functionality I would assume. 

Removing it is not the solution.

**Comment by EmanYm** [comment]
Have you tried without Spongeforge installed?
Did you use the forge installer?
Do you have any other mods installed?

**Comment by DarkArc** [comment]
@EmanYm It's not any other mods, it's SpongeForge. I've tried with every other mods removed. 

I need SpongeForge client side, as my mod is one jar, for client and server, and both a mix of Sponge, and Forge, for Item/Block registration. That's non-trivial to change, and I need Sponge present, if for no other reason, than to allow classes to load properly.

**Comment by EmanYm** [comment]
Just trying to help by running down a troubleshooting list.  I will leave this for a dev to look into now.

**Comment by DarkArc** [comment]
Started to investigate, this is the original exception, which seems to be the source of the problem:
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Server has not been initialized yet!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.runTask(Util.java:30) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:407) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.IllegalStateException: Server has not been initialized yet!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[guava-17.0.jar:?]
	at org.spongepowered.mod.SpongeModGame.getServer(SpongeModGame.java:57) ~[SpongeModGame.class:?]
	at org.spongepowered.api.Sponge.getServer(Sponge.java:240) ~[Sponge.class:?]
	at net.minecraft.world.chunk.Chunk.handler$onConstructedTracker$zmk000(Chunk.java:5023) ~[Chunk.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:114) ~[Chunk.class:?]
	at net.minecraft.world.chunk.EmptyChunk.<init>(EmptyChunk.java:23) ~[EmptyChunk.class:?]
	at net.minecraft.client.multiplayer.ChunkProviderClient.<init>(ChunkProviderClient.java:43) ~[ChunkProviderClient.class:?]
	at net.minecraft.client.multiplayer.WorldClient.createChunkProvider(WorldClient.java:131) ~[WorldClient.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:77) ~[WorldClient.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleJoinGame(NetHandlerPlayClient.java:309) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:89) ~[SPacketJoinGame.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:13) ~[SPacketJoinGame.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:164) ~[PacketUtil.class:?]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjk000(PacketThreadUtil.java:539) ~[PacketThreadUtil$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.runTask(Util.java:29) ~[Util.class:?]
	... 15 more
```

**Comment by DarkArc** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/pull/1384
