### ISSUE TITLE
spongeforge-1.10.2-2281-5.2.0-BETA-2416 crash

### ISSUE THREAD

**Issue by IceSoulHanxi** [SpongePowered/SpongeForge#1605]
**I am currently running...**

- SpongeForge version: 2416
- Forge version: 2281
- Java version: 8u131
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
sponge
**What is the expected result?**

**What is the current result?**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2416.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 17-6-26 下午11:44
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.entity.passive.EntityRabbit cannot be cast to org.spongepowered.common.interfaces.entity.player.IMixinEntityPlayerMP
	at net.minecraft.entity.EntityTrackerEntry.modify$spongeRelocateDataManager$zdd000(EntityTrackerEntry.java:855)
	at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:308)
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:264)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.EntityTrackerEntry.modify$spongeRelocateDataManager$zdd000(EntityTrackerEntry.java:855)
	at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:308)
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:264)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:282)

-- Sponge CauseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zho000(MinecraftServer.java:3937)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:503)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 541382624 bytes (516 MB) / 946864128 bytes (903 MB) up to 1890582528 bytes (1803 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	spongeapi{5.2.0-SNAPSHOT-c675e80} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2281-5.2.0-BETA-2416} [SpongeForge] (spongeforge-1.10.2-2281-5.2.0-BETA-2416.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2416.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by relative2** [comment]
Getting this with chickens on 1.10.2-2281-5.2.0-BETA-2417 on a completely new world
forge 2281,
ubuntu 16.04.2 amd64
java 8u131 openjdk-8-jdk

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2417.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 6/26/17 5:23 PM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.entity.passive.EntityChicken cannot be cast to org.spongepowered.common.interfaces.entity.player.IMixinEntityPlayerMP
        at net.minecraft.entity.EntityTrackerEntry.modify$spongeRelocateDataManager$zdd000(EntityTrackerEntry.java:855)
        at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:308)
        at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:264)
        at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:282)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.entity.EntityTrackerEntry.modify$spongeRelocateDataManager$zdd000(EntityTrackerEntry.java:855)
        at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:308)
        at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:264)
        at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:282)

-- Sponge CauseTracker --
Details:
        Cause Stack: [Empty stack]
Stacktrace:
        at net.minecraft.server.MinecraftServer.handler$onCrashReport$zho000(MinecraftServer.java:3937)
        at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
        at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:503)
        at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
        Minecraft Version: 1.10.2
        Operating System: Linux (amd64) version 4.10.0-21-generic
        Java Version: 1.8.0_131, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1157555584 bytes (1103 MB) / 1613234176 bytes (1538 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 2 total; -Xmx2048M -Xms1024M
        IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
        FML: MCP 9.32 Powered by Forge 12.18.3.2281 6 mods loaded, 6 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
        UCHIJAAAA       FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
        UCHIJAAAA       Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
        UCHIJAAAA       spongeapi{5.2.0-SNAPSHOT-c675e80} [SpongeAPI] (minecraft.jar) 
        UCHIJAAAA       sponge{1.10.2-2281-5.2.0-BETA-2417} [SpongeForge] (spongeforge-1.10.2-2281-5.2.0-BETA-2417.jar) 
        UCHIJAAAA       mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
        Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2417.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
        Profiler Position: N/A (disabled)
        Player Count: 0 / 20; []
        Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
        Type: Dedicated Server (map_server.txt)```

**Comment by Arkiio** [comment]
Also getting this, reset world, and now errors on a different mob, (ender zoo mob)
running spongeforge 1.10.2-2281-5.2.0-BETA-2417 Forge 2281 

// I'm sorry, Dave.

Time: 6/26/17 6:50 PM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.entity.passive.EntitySheep cannot be cast to org.spongepowered.common.interfaces.entity.player.IMixinEntityPlayerMP
	at net.minecraft.entity.EntityTrackerEntry.modify$spongeRelocateDataManager$zdd000(EntityTrackerEntry.java:855)
	at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:308)
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:264)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.EntityTrackerEntry.modify$spongeRelocateDataManager$zdd000(EntityTrackerEntry.java:855)
	at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:308)
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:264)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:282)

**Comment by gabizou** [comment]
Fixed in the the build with that commit.
