### ISSUE TITLE
Server Crash after Auto Restart

### ISSUE THREAD

**Issue by JSingDreams** [SpongePowered/SpongeForge#1612]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2394.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/29/17 1:00 AM
Description: Watching Server

java.lang.Error
	at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.<init>(AbstractChannel.java:380)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.<init>(AbstractNioChannel.java:172)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:48)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:48)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:45)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:34)
	at com.vexsoftware.votifier.netty.channel.AbstractChannel.<init>(AbstractChannel.java:82)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:82)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:40)
	at com.vexsoftware.votifier.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:84)
	at com.vexsoftware.votifier.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:453)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:306)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:271)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:267)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:249)
	at com.vexsoftware.votifier.sponge.VotifierPlugin.onServerStart(VotifierPlugin.java:227)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_VotifierPlugin_onServerStart9.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:561)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:858)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.<init>(AbstractChannel.java:380)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.<init>(AbstractNioChannel.java:172)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:48)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:48)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:45)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:34)
	at com.vexsoftware.votifier.netty.channel.AbstractChannel.<init>(AbstractChannel.java:82)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:82)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:40)
	at com.vexsoftware.votifier.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:84)
	at com.vexsoftware.votifier.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:453)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:306)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:271)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:267)
	at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:249)
	at com.vexsoftware.votifier.sponge.VotifierPlugin.onServerStart(VotifierPlugin.java:227)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_VotifierPlugin_onServerStart9.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:561)

-- Sponge CauseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhn000(MinecraftServer.java:3937)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:62)
	at java.lang.Thread.run(Unknown Source)

-- Thread Dump --
Details:
	Threads: "pool-2-thread-4" Id=79 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"Server Watchdog" Id=76 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:46)
	at java.lang.Thread.run(Unknown Source)

"Query Listener #1" Id=75 RUNNABLE
	at java.net.PlainDatagramSocketImpl.peekData(Native Method)
	-  locked java.net.PlainDatagramSocketImpl@3b2a6e48
	at java.net.DatagramSocket.receive(Unknown Source)
	-  locked java.net.DatagramPacket@3f15edf5
	-  locked java.net.DatagramSocket@6f69f5dc
	at net.minecraft.network.rcon.RConThreadQuery.run(SourceFile:268)
	at java.lang.Thread.run(Unknown Source)

"Timer-2" Id=74 TIMED_WAITING on java.util.TaskQueue@7a176473
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@7a176473
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"Netty Epoll Server IO #5" Id=35 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

"ForkJoinPool.commonPool-worker-2" Id=73 TIMED_WAITING on java.util.concurrent.ForkJoinPool@23171c1a
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@23171c1a
	at java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Netty Epoll Server IO #4" Id=34 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

"Timer-1" Id=68 TIMED_WAITING on java.util.TaskQueue@4b277e1e
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@4b277e1e
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"Netty Epoll Server IO #3" Id=33 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

"Netty Epoll Server IO #2" Id=32 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

"Netty Epoll Server IO #1" Id=31 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

"pool-2-thread-3" Id=66 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"pool-2-thread-2" Id=65 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"MVStore background writer nio:/home/minecraft/multicraft/servers/server42081/config/gts/storage/GTS.mv.db" Id=60 TIMED_WAITING on java.lang.Object@5bcd58ca
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@5bcd58ca
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2689)

"GTS housekeeper" Id=57 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1a389b3c
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1a389b3c
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"Netty Epoll Server IO #0" Id=30 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

"H2 Log Writer PIXELMON2" Id=28 TIMED_WAITING on org.h2.store.WriterThread@1d4b3ad
	at java.lang.Object.wait(Native Method)
	-  waiting on org.h2.store.WriterThread@1d4b3ad
	at org.h2.store.WriterThread.run(WriterThread.java:102)
	at java.lang.Thread.run(Unknown Source)

"pool-2-thread-1" Id=27 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@35ed8685
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"Sponge Async Scheduler Thread" Id=25 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@71f3fa07
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@71f3fa07
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at org.spongepowered.common.scheduler.AsyncScheduler.preTick(AsyncScheduler.java:112)
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:105)
	at org.spongepowered.common.scheduler.AsyncScheduler.mainLoop(AsyncScheduler.java:66)
	at org.spongepowered.common.scheduler.AsyncScheduler$$Lambda$329/1493608358.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Timer-0" Id=22 TIMED_WAITING on java.util.TaskQueue@40c9f7fb
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@40c9f7fb
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"process reaper" Id=20 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1e7665a5
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1e7665a5
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"Server console handler" Id=17 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	-  locked java.io.BufferedInputStream@3a1bf41d
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	-  locked java.io.InputStreamReader@54d6129b
	at java.io.InputStreamReader.read(Unknown Source)
	...

"DestroyJavaVM" Id=18 RUNNABLE

"Server thread" Id=15 RUNNABLE
	at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.<init>(AbstractChannel.java:380)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.<init>(AbstractNioChannel.java:172)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:48)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:48)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:45)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:34)
	at com.vexsoftware.votifier.netty.channel.AbstractChannel.<init>(AbstractChannel.java:82)
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:82)
	...

"Server Infinisleeper" Id=14 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:78)

"Snooper Timer" Id=13 WAITING on java.util.TaskQueue@1307f582
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@1307f582
	at java.lang.Object.wait(Unknown Source)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@77216fb3
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@77216fb3
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@56a1a97b
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@56a1a97b
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.10.0-327.22.2.el7.x86_64
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2015392064 bytes (1922 MB) / 3817865216 bytes (3641 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 98
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (pixelmon1102.jar) 
	UCHIJAAAA	Forge{12.18.3.2202} [Minecraft Forge] (pixelmon1102.jar) 
	UCHIJAAAA	spongeapi{5.2.0-SNAPSHOT-ab52c0c} [SpongeAPI] (minecraft.jar) 
	UCHIJAAA	sponge{1.10.2-2281-5.2.0-BETA-2394} [SpongeForge] (spongeforge-1.10.2-2281-5.2.0-BETA-2394.jar) 
	UCHIJAAA	pixelmon{5.1.1} [Pixelmon] (Pixelmon-1.10.2-5.1.1-universal.jar) 
	UCHIJAAA	agp{0.4.3} [AGP] (AnotherGymPlugin-1.10.2-0.5.0-beta.jar) 
	UCHIJAAA	betterkits{0.9.6} [BetterKits] (BetterKits-0.9.6.jar) 
	UCHIJAAA	catclearlag{0.7.1} [CatClearLag] (CatClearLag-0.7.1.jar) 
	UCHIJAAA	commandbooks{1.3.0} [CommandBooks] (CommandBooks-v1.3.0.jar) 
	UCHIJAAA	nuvotifier{2.3.4} [NuVotifier] (nuvotifier-universal-2.3.4.jar) 
	UCHIJAAA	enjin-minecraft-plugin{3.2.0-sponge} [Enjin Minecraft Plugin] (EMPSponge.jar) 
	UCHIJAAA	gts{1.10.2-2.1.3} [Global Trading Station] (GTS-1.10.2-2.1.3.jar) 
	UCHIJAAA	huskycrates{1.5.0} [HuskyCrates] (HuskyCrates-v1.5.0.jar) 
	UCHIJAAA	inspector{0.6.4} [Inspector] (Inspector-0.6.4.jar) 
	UCHIJAAA	nucleus{0.29.5-S5.1} [Nucleus] (Nucleus-0.29.5-1.10.2-S5.1-plugin.jar) 
	UCHIJAAA	permissionsex{2.0-SNAPSHOT-b147} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAA	pixelannouncer{1.0.3} [Pixel Announcer] (PixelAnnouncer-1.10.2-1.0.3.jar) 
	UCHIJAAA	pixelextras{2.2.9} [Pixel Extras] (PixelExtras-1.10.2-2.2.9-universal.jar) 
	UCHIJAAA	pixelmoneconomybridge{1.2.2} [PixelmonEconomyBridge] (PixelmonEconomyBridge-1.10.2-1.3.0.jar) 
	UCHIJAAA	polis{2.7.0} [Polis] (Polis-1.10.2-2.7.0.jar) 
	UCHIJAAA	seriousvote{3.0} [SeriousVote] (seriousvote-3.2-Bleeding-F.jar) 
	UCHIJAAA	spongychest{0.4.8} [SpongyChest] (SpongyChest-1.10.2-0.4.8-universal.jar) 
	UCHIJAAA	totaleconomy{1.6.0} [Total Economy] (TotalEconomy-1.6.0.jar) 
	UCHIJAAA	universeguard{1.0} [Universe Guard] (UniverseGuard.jar) 
	UCHIJAAA	wondertrade{4.4.5} [Wondertrade] (WonderTrade-1.10.2-4.4.5-universal.jar) 
	UCHIJAAA	worldedit{6.1.5-SNAPSHOT} [WorldEdit] (worldedit-sponge-mc1.10.2-6.1.5-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2394.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 100; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by JSingDreams** [comment]
Server Info is provided in the logs at the bottom.

**Comment by phit** [comment]
@JSingDreams does this happen after every restart? what fixes it?
the crash mentions nuvotifier, consider reporting it to them

**Comment by Deamon5550** [comment]
Networking on the main thread.... definitely report it to that plugin, this is not a sponge issue.
