### ISSUE TITLE
Random crash relating to spongeforge

### ISSUE THREAD

**Issue by Hellcommander** [SpongePowered/SpongeForge#1652]
**I am currently running...**

- SpongeForge version: 1.12-2397-7.0.0-BETA-2469
- Forge version: 14.21.1 (up to date so that mods work)
- Java version: latest version 8
- Operating System:Windows 10 Pro

- Plugins/Mods: 

**What is the expected result?**Not randomly crashing

**What is the current result?**Random crash crash result is here for easy viewing:
[crash-2017-07-15_18.49.35-server.txt](https://github.com/SpongePowered/SpongeForge/files/1150792/crash-2017-07-15_18.49.35-server.txt) (edit uploaded wrong one for this one so deleted and reuploaded it)

```
Time: 7/15/17 6:49 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:646)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:646)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:560)
	at org.spongepowered.common.event.SpongeCommonEventFactory.handler$onCallDestructEntityEventDeath$zoa000(SpongeCommonEventFactory.java:965)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:3804)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3531)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1036)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at thut.api.boom.ExplosionCustom$1.hitEntity(ExplosionCustom.java:84)
	at thut.api.boom.ExplosionCustom.applyEntityEffects(ExplosionCustom.java:358)
	at thut.api.boom.ExplosionCustom.doRemoveBlocks(ExplosionCustom.java:328)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_753_ExplosionCustom_doRemoveBlocks_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:634)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:646)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.returnToPokecube(EntityTameablePokemob.java:686)
	at pokecube.core.events.handlers.EventsHandler.recallAllPokemobsExcluding(EventsHandler.java:270)
	at pokecube.core.events.handlers.PCEventsHandler.sendPokemobToPCPlayerDeath(PCEventsHandler.java:242)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_403_PCEventsHandler_sendPokemobToPCPlayerDeath_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:634)
	... 21 more
Caused by: java.lang.NullPointerException
	at jds.bibliocraft.events.EventItemToss.DroppedItemEvent(EventItemToss.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_123_EventItemToss_DroppedItemEvent_ItemTossEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:634)
	... 28 more
```

**Comment by Hellcommander** [comment]
Here is another random crash involving a npc and a enderman
`// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/15/17 10:20 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:646)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at net.minecraft.server.MinecraftServer.func_193030_aL(MinecraftServer.java:1414)
	at net.minecraft.advancements.AdvancementRewards.func_192113_a(SourceFile:79)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(SourceFile:175)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:31)
	at net.minecraft.advancements.critereon.KilledTrigger$Listeners.func_192503_a(SourceFile:120)
	at net.minecraft.advancements.critereon.KilledTrigger.func_192211_a(SourceFile:66)
	at net.minecraft.entity.player.EntityPlayerMP.func_191956_a(EntityPlayerMP.java:571)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:3302)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3531)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:67)
	at net.minecraft.entity.monster.EntityEnderman.func_70097_a(EntityEnderman.java:348)
	at thut.api.boom.ExplosionCustom$1.hitEntity(ExplosionCustom.java:84)
	at thut.api.boom.ExplosionCustom.applyEntityEffects(ExplosionCustom.java:358)
	at thut.api.boom.ExplosionCustom.doRemoveBlocks(ExplosionCustom.java:328)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_816_ExplosionCustom_doRemoveBlocks_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:634)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:646)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)

-- Sponge CauseTracker --
Details:
	Cause Stack: /*******************************************************************************************************/
/*   - Phase: org.spongepowered.common.event.tracking.phase.entity.DeathPhase@1e9eadff                 */
/*     Context:                                                                                        */
/*     - Name: Source                                                                                  */
/*       Object: EntityEnderman['Enderman'/7485, l='New World----------', x=-245.31, y=18.00, z=449.50] */
/*     - Name: DamageSource                                                                            */
/*       Object: EntityDamageSource{Name=explosion.player, Type=explosive,                             */
/*       Source=FakePlayer['[Pokecube]DispenserPlayer'/0, l='New World----------', x=-209.50, y=61.00, */
/*       z=509.50]}                                                                                    */
/*     - Name: CapturedBlocks                                                                          */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                    */
/*     - Name: CapturedEntities                                                                        */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                  */
/*   - Phase: org.spongepowered.common.event.tracking.phase.plugin.PostWorldTickListenerState@467bae5e */
/*     Context:                                                                                        */
/*     - Name: Source                                                                                  */
/*       Object: ASM: thut.api.boom.ExplosionCustom@35d55df4                                           */
/*       doRemoveBlocks(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V           */
/*     - Name: CapturedWorldTickEvent                                                                  */
/*       Object: net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@25de0435             */
/*     - Name: CapturedBlocks                                                                          */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                    */
/*     - Name: CapturedEntities                                                                        */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                  */
/*     - Name: CapturedPlayer                                                                          */
/*       Object: CapturePlayer{player=null}                                                            */
/*******************************************************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zia000(MinecraftServer.java:3998)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:883)
	at net.minecraft.server.integrated.IntegratedServer.func_71230_b(IntegratedServer.java:359)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:555)
	at java.lang.Thread.run(Unknown Source)
[crash-2017-07-15_22.20.05-server.txt](https://github.com/SpongePowered/SpongeForge/files/1150789/crash-2017-07-15_22.20.05-server.txt)
`

**Comment by Zidane** [comment]
This has nothing to do with Sponge:

	at jds.bibliocraft.events.EventItemToss.DroppedItemEvent(EventItemToss.java:22)
