### ISSUE TITLE
[1.10.2] fail to save chunks on galacticraft dims

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeForge#1656]
running latest forge 1.10.2 - 12.18.3.2316
with sponge 1.10.2-2281-5.2.0-beta-2464
Server says failed to save chunks on saving galaciticraft dimensions
（using galaciticraft with plants and more planets)
Works fine under pure forge env.

**Comment by phit** [comment]
please add your fml-server-latest.log

**Comment by loveyanbei** [comment]
ok, seems like a FuturePack issue on every dim, not galacitycraft

[13:03:19] [Server thread/INFO]: Stopping server
[13:03:19] [Server thread/INFO]: Saving players
[13:03:19] [Server thread/INFO]: Saving worlds
[13:03:19] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-2544'/Nibiru
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-2543'/Chalos
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-2542'/Diona
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-31'/Venus
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-30'/Asteroids
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-28'/Moon
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM_Menelaus'/Menelaus
[13:03:19] [Server thread/INFO]: Saving chunks for level 'DIM_Tyros'/Tyros
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [world] (DIM0)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM-1/DIM-1
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (DIM-1)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM1/DIM1
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM1] (DIM1)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM-2544/DIM-2544
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM-2544] (DIM-2544)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM-2543/DIM-2543
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM-2543] (DIM-2543)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM-2542/DIM-2542
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM-2542] (DIM-2542)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM-31/DIM-31
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM-31] (DIM-31)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM-30/DIM-30
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM-30] (DIM-30)
[13:03:20] [Server thread/INFO] [Futurepack]: Saving Chunks(FP) for ./world/DIM-28/DIM-28
[13:03:20] [Server thread/ERROR] [Futurepack]: Saving Chunks Failed!
[13:03:20] [Server thread/INFO] [Sponge]: Unloading world [DIM-28] (DIM-28)
[13:03:20] [Server thread/ERROR]: Exception stopping the server
java.lang.RuntimeException: Attempt made to unload a world with dimension id [-1].
	at net.minecraftforge.common.DimensionManager.lambda$setWorld$0(DimensionManager.java:654) ~[DimensionManager.class:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_131]
	at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:654) ~[DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[13:03:20] [Server thread/INFO] [gregtech]: GT_Mod: Re-Unificating Recipes.
[13:03:20] [Server thread/INFO] [FML]: Applying holder lookups
[13:03:20] [Server thread/INFO] [FML]: Holder lookups applied
[13:03:20] [Server thread/ERROR] [galacticraftplanets]: Skipping event FMLServerStoppedEvent and marking errored mod galacticraftplanets since required dependency galacticraftcore has errored
[13:03:20] [Server thread/ERROR] [moreplanets]: Skipping event FMLServerStoppedEvent and marking errored mod moreplanets since required dependency galacticraftcore has errored
[13:03:20] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[13:03:20] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[13:03:20] [Server Shutdown Thread/INFO]: Stopping server
[13:03:20] [Server Shutdown Thread/INFO]: Saving players
[13:03:20] [Server Shutdown Thread/INFO]: Saving worlds
[13:03:20] [Server Shutdown Thread/INFO]: Saving chunks for level 'DIM-29'/Mars
> Exception in thread "Server Watchdog" %

**Comment by ryantheleach** [comment]
FuturePack seems to be closed source for anyone investigating.

**Comment by Bysokar** [comment]
This also happens for users running Advanced Rocketry mod (aka me).
