### ISSUE TITLE
[1.12-2397-7.0.0-BETA-2477] Crash before generating/loading world

### ISSUE THREAD

**Issue by TekuSP** [SpongePowered/SpongeForge#1672]
https://pastebin.com/g8MzGhNf = Pipe Source from Console ( .\start.bat > result.txt )
https://gist.github.com/78b46498e5868f889a41e96693310bc6 = fml-junk-earlystartup.log
https://pastebin.com/CfTNFS1d = fml-server-latest.log
https://pastebin.com/LRfr4AR6 = latest.log
https://pastebin.com/UCj7YTdW = crash-2017-07-23_18.46.27-server.txt

Problem started when I installed latest forge because of Immersive Engineering requirment of it. 

forge-1.12-14.21.1.2420
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
Windows 10 x64 Build 16241.1001

**Comment by Zidane** [comment]
@Deamon5550 

First long seems to imply that a null biome type is being registered?

```
[18:46:13] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[18:46:13] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
[18:46:13] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
[18:46:13] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at org.spongepowered.common.registry.type.world.gen.BiomeTypeRegistryModule.registerAdditional(BiomeTypeRegistryModule.java:75)
```

Thoughts?

**Comment by Deamon5550** [comment]
`getId` for some biome must be null, if the biome itself was null then the NPE would be in our code. Which means whatever biome it is is not being passed through `Biome#registerBiome`. Perhaps we could make this a little more resilient by forming the id out of the registry name if its not there, if a biome isn't in the registry then thats an error on the mods part, but I can see perhaps a biome being registered into the registry without going through that particular method in Biome (does forge's registration for biomes go through that method normally?)

**Comment by TekuSP** [comment]
If you need more debugging information, you can quickly write mod which will write into console everything you need to know from Biomes and why is some null, or if part of it is null. I will happily help by running it.

**Comment by Deamon5550** [comment]
I'll add some more robustness to our registration and some debug for what biome it is if it still fails.

**Comment by Deamon5550** [comment]
@TekuSP There try the next SpongeForge build once it's available (it'll be build 2479 or so).

**Comment by FiveEYZ** [comment]
is this related? https://github.com/SpongePowered/SpongeCommon/issues/1361

**Comment by TekuSP** [comment]
Updated to 2479.
Same issue.
@Deamon5550 
```
[22:30:50] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at org.spongepowered.mod.SpongeMod.lambda$new$1(SpongeMod.java:154) ~[SpongeMod.class:1.12-2397-7.0.0-BETA-2479]
        at org.spongepowered.mod.registry.SpongeGameData.lambda$addRegistryCallback$0(SpongeGameData.java:55) ~[SpongeGameData.class:1.12-2397-7.0.0-BETA-2479]
        at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:330) ~[ForgeRegistry.class:?]
        at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:508) ~[ForgeRegistry.class:?]
        at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:471) ~[GameData.class:?]
        at net.minecraftforge.registries.GameData.freezeData(GameData.java:217) ~[GameData.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:790) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:216) ~[nx.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[22:30:50] [Server thread/ERROR]: This crash report has been saved to: C:\Users\TekuSP\Desktop\Server\.\crash-reports\crash-2017-07-26_22.30.50-server.txt
```

**Comment by Deamon5550** [comment]
Oh thats a different issue, I was talking about the error @Zidane was pointing out. I'm going to need @gabizou to look at that one because it looks like an item thats being passed to the callback (which happens right after its added) doesn't actually have a key.

**Comment by FiveEYZ** [comment]
decided to try 1.12, now i keep getting this crash (looks same as the crash @TekuSP are getting):
https://gist.github.com/FiveEYZ/818b050ec2c23aea4d6d41a5a863412a

**Comment by FiveEYZ** [comment]
Looking at this issue: https://github.com/SpongePowered/SpongeForge/issues/1678
disabling MalisisDoors + Core fixes above crash.

**Comment by TekuSP** [comment]
Okay, Looks like MalisisDoor is for unknown reasons registering vanilla minecraft doors as doors without name, texture and that small texture. I recommend catching this issue in Sponge, but looks like bug of MalisisDoors.
