### ISSUE TITLE
Error happened when using season sensor in the mod, Tough As Nails

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#1691]
```
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: org.h2.jdbc.JdbcSQLException: Value too long for column "DATACONTAINER VARCHAR(10000) SELECTIVITY 93": "'{""User"":{""ContentVersion"":1,""EntityClass"":""net.minecraft.entity.player.EntityPlayerMP"",""WorldUuid"":""4bdbb744-7c86-44d5-82a6-a5f... (155570)"; SQL statement:
INSERT INTO `blockmonitor` (`locationX`,`locationY`,`locationZ`,`worldName`,`eventtype`,`datacontainer`, `timestamp`) VALUES (?, ?, ?, ?, ?, ?, ?); [22001-193]
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.message.DbException.get(DbException.java:179)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:335)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.command.dml.Insert.insertRows(Insert.java:151)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.command.dml.Insert.update(Insert.java:114)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.command.Command.executeUpdate(Command.java:258)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:201)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at com.amict.blockmonitor.api.Record.submitToDatabase(Record.java:203)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at com.amict.blockmonitor.api.RecordBuilder.run(RecordBuilder.java:122)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[02:08:56] [pool-10-thread-4/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: org.h2.jdbc.JdbcSQLException: Value too long for column "DATACONTAINER VARCHAR(10000) SELECTIVITY 93": "'{""User"":{""ContentVersion"":1,""EntityClass"":""net.minecraft.entity.player.EntityPlayerMP"",""WorldUuid"":""4bdbb744-7c86-44d5-82a6-a5f... (155574)"; SQL statement:
INSERT INTO `blockmonitor` (`locationX`,`locationY`,`locationZ`,`worldName`,`eventtype`,`datacontainer`, `timestamp`) VALUES (?, ?, ?, ?, ?, ?, ?); [22001-193]
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.message.DbException.get(DbException.java:179)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:335)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.command.dml.Insert.insertRows(Insert.java:151)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.command.dml.Insert.update(Insert.java:114)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.command.Command.executeUpdate(Command.java:258)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:201)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at com.amict.blockmonitor.api.Record.submitToDatabase(Record.java:203)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at com.amict.blockmonitor.api.RecordBuilder.run(RecordBuilder.java:122)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[02:09:10] [pool-10-thread-1/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
```

windows server 2012
ToughAsNails-1.11.2-2.1.0.36-universal
spongeforge-1.11.2-2393-6.1.0-BETA-2471
forge-1.11.2-13.20.1.2393-universal

**Comment by dualspiral** [comment]
Not a Sponge error, report this to the developers of the BlockMonitor plugin, their `DATACONTAINER` column is too short.
