### ISSUE TITLE
Server crashes on placement of a robot without inventory upgrade

### ISSUE THREAD

**Issue by Polyana-Fontes** [SpongePowered/SpongeForge#1697]
If we assembly an OpenComputer's Robot without an Inventory Upgrade, it will crash the server on placement with:

```java
java.lang.IllegalArgumentException: Invalid size: 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
	at org.spongepowered.common.item.inventory.lens.impl.AbstractLens.<init>(AbstractLens.java:89)
	at org.spongepowered.common.item.inventory.lens.impl.AbstractLens.<init>(AbstractLens.java:80)
	at org.spongepowered.common.item.inventory.lens.impl.MinecraftLens.<init>(MinecraftLens.java:44)
	at org.spongepowered.common.item.inventory.lens.impl.minecraft.PlayerInventoryLens.<init>(PlayerInventoryLens.java:60)
	at net.minecraft.entity.player.InventoryPlayer.handler$onConstructed$zfh000(InventoryPlayer.java:1469)
	at net.minecraft.entity.player.InventoryPlayer.<init>(InventoryPlayer.java:43)
	at li.cil.oc.server.agent.Inventory.<init>(Inventory.scala:18)
	at li.cil.oc.server.agent.Player.<init>(Player.scala:107)
	at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$Robot$$player_$lzycompute(Robot.scala:190)
	at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$Robot$$player_(Robot.scala:190)
	at li.cil.oc.common.tileentity.Robot$$anonfun$updateEntity$1.apply$mcVI$sp(Robot.scala:374)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.common.tileentity.Robot.updateEntity(Robot.scala:372)
	at li.cil.oc.common.tileentity.RobotProxy.updateEntity(RobotProxy.scala:135)
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
	at li.cil.oc.common.tileentity.RobotProxy.func_73660_a(RobotProxy.scala:33)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:230)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2854)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zke000(WorldServer.java:2841)
	at net.minecraft.world.World.func_72939_s(World.java:6509)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
```
**I am currently running...**
- SpongeForge version: 1.11.2-2393-6.1.0-BETA-2484 / 1.11.2-2393-6.1.0-BETA-2499
- Forge version: 1.11.2-13.20.1.2429
- Java version: 1.8.0_45-b15 x64
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows 7 64 bits

- Plugins/Mods: 
Only SpongeForge and OpenComputers are needed to reproduce this bug.
Plugins (8): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, OpenComputers (Core), SpongeAPI, SpongeForge, OpenComputers

**What is the expected result?**
Do not crash the server

**What is the current result?**
Crashes the server on placement.
Video demonstration: https://youtu.be/9W9diLUov5w

fml-server-latest.log: [view](https://gist.githubusercontent.com/joserobjr/77d8b5aeb5b85ead263e7ad2531b80fb/raw/c6f059e08045cc8e90538fdf1ea0e343d9bc376f/fml-server-latest.log) - [download](https://github.com/SpongePowered/SpongeForge/files/1201839/fml-server-latest.log.txt)
crash-2017-08-04_19.40.10-server.txt: [view](https://gist.githubusercontent.com/joserobjr/77d8b5aeb5b85ead263e7ad2531b80fb/raw/790c38359b38c76469b72c27bb7c910a1b532810/crash-2017-08-04_19.40.10-server.txt)

**Comment by Eufranio** [comment]
Duplicated: https://github.com/SpongePowered/SpongeForge/issues/1526

**Comment by Polyana-Fontes** [comment]
Tested on the latest 1.11.2 build 1.11.2-2393-6.1.0-BETA-2499 and it still crashes.
Tested on the latest 1.12 build 1.12-2443-7.0.0-BETA-2498 with OpenComputers-MC1.12-1.7.0.3 and it also crashes.

Does not crash on Minecraft 1.10.2 with:
- spongeforge-1.10.2-2281-5.2.0-BETA-2464
- OpenComputers-MC1.10.2-1.6.2.7

**Comment by ghost** [comment]
OC is stable and released for 1.11.2 or 1.12 ?

**Comment by Polyana-Fontes** [comment]
@hunter688 no, it's alpha for 1.11.2 and wip for 1.12, but doesn't mean that the compatibility issue doesn't exists. Maybe it can be fixed from the OpenComputers side, or here in SpongeForge, but if we work together I'm sure that we can fix it.

I've been investigating the issue and the crashes started happening from this [OpenComputers commit][oc-commit], a nightly build from that commit was versioned as [MC1.10.2-1.6.2.87-dev](http://ci.cil.li/job/OpenComputers-dev-MC1.10/87/). That was the 7th commit after the [stable 1.10.2 release](https://minecraft.curseforge.com/projects/opencomputers/files/2385987) from OpenComputers, which was versioned as [MC1.10.2-1.6.2.80-dev](http://ci.cil.li/job/OpenComputers-dev-MC1.10/80/) and [MC1.10.2-1.6.2.7](http://ci.cil.li/job/OpenComputers-1.6-MC1.10/7/).

The main change from that commit was that it added an `EntityPlayer` to the `InventoryPlayer`, before that change the `InventoryPlayer` had a `null` value instead.

The commit fixed the MightyPirates/OpenComputers#2370 issue but cause this incompatibility issue, which happens to be related to #1526 and #824 

The `public InventoryPlayer(EntityPlayer playerIn)` constructor originally doesn't do any constructor call, so I believe that the call is being injected by a SpongeForge mixin.

The mixin seems to check if the `playerIn` parameter is `null` before trying to create a [PlayerInventoryLens](https://github.com/SpongePowered/SpongeCommon/blob/b8cc78acec25a039d2e6bdd9d9922dadf43f99ff/src/main/java/org/spongepowered/common/item/inventory/lens/impl/minecraft/PlayerInventoryLens.java) instance, and the `PlayerInventoryLens` creation calls a super chain up to the [AbstractLens constructor at line 89](https://github.com/SpongePowered/SpongeCommon/blob/b8cc78acec25a039d2e6bdd9d9922dadf43f99ff/src/main/java/org/spongepowered/common/item/inventory/lens/impl/AbstractLens.java#L89), which checks if the inventory size is greater then `0` and throws an exception.

I can see 3 ways to fix it.

1. Making `AbstractLens` accept inventories with size 0. I don't understand why it is being considered wrong as an inventory with that size is valid on the Minecraft environment just like an array of 0 items is valid on any programming language. I think that this would be the best fix because it would accommodate the inventory system better.
2. Making the mixin which creates an `InventoryPlayerLens` object also checks if the player's inventory size is greater the `0`. I think that this would be the easiest fix.
3. Reverting the [OpenComputer's commit][oc-commit] which fixed the MightyPirates/OpenComputers#2370 issue but triggered this incompatibility problem. I think that this would be the worst fix because the inventory would have no reference to the player and that could cause other issues like MightyPirates/OpenComputers#2370

[oc-commit]: https://github.com/MightyPirates/OpenComputers/commit/442d8feec3c69a74389582a92d38acfe9bb8c3aa

**Comment by Polyana-Fontes** [comment]
By the way, I forget to mention that this issue happens a little different on the latest development version of OpenComputers 1.10.2, instead of crashing on placement it will crash when a robot has an item in the tool's slot.

**Comment by Polyana-Fontes** [comment]
Here is the mixin which is involved in this issue: [MixinInventoryPlayer at line 91](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinInventoryPlayer.java#L91)

**Comment by Faithcaio** [comment]
This might be fixed in latest. Please retest.

Also why is OpenComputers extending InventoryPlayer but then overriding its inventory methods?
