### ISSUE TITLE
Netty spam in console

### ISSUE THREAD

**Issue by PixelmonPRO** [SpongePowered/SpongeForge#1755]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2597
- Forge version: forge-1.10.2-12.18.3.2422-universal
- Java version: 1.8.0_121
- Operating System: Debian 8 Jessie 64 bit

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

Periodically, servers start to hang because of Netty errors. I managed to see the beginning of the log of this error.
Netty spam in console, players discards from the server, servers not chash... This errors in 3 my servers. Example Netty spam:

FML:

**Comment by Aaron1011** [comment]
The root cause of this issue seems to be that connected clients are disconnecting unexpectedly. I'm not certain what would cause so many exceptions or disconnections, however.

Other people on the forum seem to be having this issue; https://forums.spongepowered.org/t/console-constant-spam-all-my-logs-are-over-4gb/17316

**Comment by Werwolfi** [comment]
We have the same issue on our server.
 Forge 12.18.3.2477-universal
Sponge 1.10.2-2477-5.2.0-BETA-2637

`[03:35:21] [Netty Epoll Server IO #14/WARN] [io.netty.channel.DefaultChannelPipeline]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Error while writev(...): Connection reset by peer
	at io.netty.channel.epoll.Native.$$YJP$$writevAddresses(Native Method) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.Native.writevAddresses(Native.java) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:184) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.1.10.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.1.10.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by PixelmonPRO** [comment]
In the last Forge (1.10.2 - 12.18.3.2488), it seems to have solved this problem.
<img width="727" alt="screenshot at 03 02-46-48" src="https://user-images.githubusercontent.com/26658563/31104343-22950f86-a7e5-11e7-8eab-e8725384fcda.png">
But I can be wrong :)
