### ISSUE TITLE
[1.10] Agricraft Seed Analyzer - PlaceBLockPacketState

### ISSUE THREAD

**Issue by Magi1053** [SpongePowered/SpongeForge#1761]
I get the following error on my console anytime someone right clicks on a seed analyzer in Agricraft, and the analyzer gui never opens up.
```
/*****************************************************************************************************************/
/*                                          Completing incorrect phase                                           */
/*****************************************************************************************************************/
/* Sponge's tracking system is very dependent on                                                                 */
/* knowing whena change to any world takes place,                                                                */
/* however, we are attemptingto complete a "phase"                                                               */
/* other than the one we most recently entered.This                                                              */
/* is an error usually on Sponge's part, so a                                                                    */
/* reportis required on the issue tracker on GitHub.                                                             */
/*****************************************************************************************************************/
/* Expected to exit phase: org.spongepowered.common.event.tracking.phase.plugin.ScheduledTaskPhaseState@11e15b99 */
/* But instead found phase: org.spongepowered.common.event.tracking.phase.packet.PlaceBlockPacketState@a8cd114   */
/* StackTrace:                                                                                                   */
/* java.lang.Exception: null                                                                                     */
/*     org.spongepowered.common.event.tracking.CauseTracker.printIncorrectPhaseCompletion(CauseTracker.java:275) */
/*     org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:197)                 */
/*     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239)                          */
/*     net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3951)                     */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)                               */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                     */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                               */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                        */
/*     java.lang.Thread.run(Thread.java:748)                                                                     */
/*  Phases Remaining:                                                                                            */
/*   - Phase: org.spongepowered.common.event.tracking.phase.packet.PlaceBlockPacketState@a8cd114                 */
/*     Context:                                                                                                  */
/*     - Name: Source                                                                                            */
/*       Object: EntityPlayerMP['Magi1053'/10533, l='world', x=-1897.99, y=67.80, z=-3703.30]                    */
/*     - Name: PacketPlayer                                                                                      */
/*       Object: EntityPlayerMP['Magi1053'/10533, l='world', x=-1897.99, y=67.80, z=-3703.30]                    */
/*     - Name: Packet                                                                                            */
/*       Object: CPacketPlayerTryUseItemOnBlock{position=BlockPos{x=-1899, y=67, z=-3705},                       */
/*       placedBlockDirection=south, hand=MAIN_HAND, facingX=0.8125, facingY=0.8125, facingZ=1.0}                */
/*     - Name: Cursor                                                                                            */
/*       Object: SpongeItemStackSnapshot{itemType=Item{Name=none}, count=1}                                      */
/*     - Name: IgnoringCreative                                                                                  */
/*       Object: false                                                                                           */
/*     - Name: ItemUsed                                                                                          */
/*       Object: 1xitem.egg@0                                                                                    */
/*     - Name: CapturedBlocks                                                                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                              */
/*     - Name: CapturedEntities                                                                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                            */
/*     - Name: Owner                                                                                             */
/*       Object: EntityPlayerMP['Magi1053'/10533, l='world', x=-1897.99, y=67.80, z=-3703.30]                    */
/*     - Name: Notifier                                                                                          */
/*       Object: EntityPlayerMP['Magi1053'/10533, l='world', x=-1897.99, y=67.80, z=-3703.30]                    */
/*   - Phase: org.spongepowered.common.event.tracking.phase.plugin.ScheduledTaskPhaseState@11e15b99              */
/*     Context:                                                                                                  */
/*     - Name: Source                                                                                            */
/*       Object: com.google.common.util.concurrent.ListenableFutureTask@384189bc                                 */
/*     - Name: CapturedBlocks                                                                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                              */
/*     - Name: CapturedEntities                                                                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                            */
/*                                                                                                               */
/* Minecraft : 1.10.2                                                                                            */
/* SpongeAPI : 5.2.0-SNAPSHOT-c675e80                                                                            */
/* SpongeForge : 1.10.2-2281-5.2.0-BETA-2597                                                                     */
/* Minecraft Forge : 12.18.3.2422                                                                                */
/*****************************************************************************************************************/
```

**Comment by JBYoshi** [comment]
Could you post the full log? Usually errors like this are actually caused by an earlier error.

**Comment by Magi1053** [comment]
```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.infinityraider.infinitylib.container.ContainerBase.<init>(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/entity/player/InventoryPlayer;II)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:238) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2597]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3951) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: com.infinityraider.infinitylib.container.ContainerBase.<init>(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/entity/player/InventoryPlayer;II)V
	at com.infinityraider.agricraft.container.ContainerSeedAnalyzer.<init>(ContainerSeedAnalyzer.java:42) ~[ContainerSeedAnalyzer.class:?]
	at com.infinityraider.agricraft.handler.GuiHandler.getServerGuiElement(GuiHandler.java:47) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
	at com.infinityraider.agricraft.blocks.BlockSeedAnalyzer.func_180639_a(BlockSeedAnalyzer.java:110) ~[BlockSeedAnalyzer.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1252) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zhf000(NetHandlerPlayServer.java:2292) ~[me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163) ~[CauseTracker.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2597]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) ~[fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 7 more
```

**Comment by JBYoshi** [comment]
Make sure you're using matching versions of Agricraft and InfinityLib.

**Comment by Magi1053** [comment]
Neither agricraft or infinitylib have been updated since July, so yes I have the the most up to date and matching version.

**Comment by Magi1053** [comment]
Update to latest source fixes issue
