### ISSUE TITLE
[1.12.2] In-game commands from mod does not works

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1788]
Minecraft: 1.12.2
    SpongeAPI: 7.0.0-SNAPSHOT-fb55a76
    SpongeForge: 1.12.2-2486-7.0.0-BETA-2665
    Minecraft Forge: 14.23.0.2493

console:
<pre>
[16:54:49] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'cms debug' for source DedicatedServer: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:164) ~[MinecraftCommandWrapper.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:145) ~[MinecraftCommandWrapper.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-2486-7.0.0-BETA-2665]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at drzhark.customspawner.command.CommandCMS.func_184881_a(CommandCMS.java:142) ~[CommandCMS.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) ~[bj.class:?]
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:160) ~[MinecraftCommandWrapper.class:1.12.2-2486-7.0.0-BETA-2665]
        ... 9 more

</pre>

player:
<pre>
[17:04:26] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'cms debug' for source EntityPlayerMP['petrenko17'/2957, l='world', x=678.94, y=67.76, z=2007.59]: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:164) ~[MinecraftCommandWrapper.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:145) ~[MinecraftCommandWrapper.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-2486-7.0.0-BETA-2665]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2486-7.0.0-BETA-2665]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkb000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:271) [SpongeImplHooks.class:1.12.2-2486-7.0.0-BETA-2665]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zid000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at drzhark.customspawner.command.CommandCMS.func_184881_a(CommandCMS.java:142) ~[CommandCMS.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) ~[bj.class:?]
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:160) ~[MinecraftCommandWrapper.class:1.12.2-2486-7.0.0-BETA-2665]
        ... 21 more

</pre>

**Comment by Zidane** [comment]
Caused by: java.lang.NullPointerException
        at drzhark.customspawner.command.CommandCMS.func_184881_a(CommandCMS.java:142) ~[CommandCMS.class:?]

Report to CMS
