### ISSUE TITLE
[1.12.2] CustomMobSpawner does not work with SpongeForge

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1789]
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-fb55a76
SpongeForge: 1.12.2-2486-7.0.0-BETA-2665
Minecraft Forge: 14.23.0.2493

No mobs spawned. Singleplayer works fine. Turned on cms debug from config:

<pre>
[17:13:05] [Server thread/DEBUG] [mixin]: Mixing status.MixinServerStatusResponseVersion from mixins.common.core.json into net.minecraft.network.ServerStatusResponse$Version
[17:13:06] [Server thread/INFO] [Astral Sorcery]: Load CachedWorldData 'lightnetwork' for world 0
[17:13:06] [Server thread/INFO] [Astral Sorcery]: Loading of 'lightnetwork' for world 0 finished.
[17:13:06] [Server thread/DEBUG] [mixin]: Mixing status.MixinServerStatusResponsePlayers from mixins.common.core.json into net.minecraft.network.ServerStatusResponse$Players
[17:13:06] [Server thread/TRACE] [mixin]: Added class metadata for org/spongepowered/api/network/status/StatusResponse$Players to metadata cache
[17:13:06] [Server thread/DEBUG] [mixin]: Mixing world.MixinChunkCache from mixins.common.core.json into net.minecraft.world.ChunkCache
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]: java.lang.Exception: Stack trace
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at java.lang.Thread.dumpStack(Thread.java:1333)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at drzhark.customspawner.EventHooks.isValidEntity(EventHooks.java:208)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at drzhark.customspawner.EventHooks.onLivingDespawn(EventHooks.java:97)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_322_EventHooks_onLivingDespawn_AllowDespawn.invoke(.dynamic)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraftforge.event.ForgeEventFactory.canEntityDespawn(ForgeEventFactory.java:209)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.EntityLiving.func_70623_bb(EntityLiving.java:711)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:754)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.passive.EntityWolf.func_70636_d(EntityWolf.java:212)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.entity.passive.EntityWolf.func_70071_h_(EntityWolf.java:230)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:162)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkk000(WorldServer.java:2837)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.world.World.func_72866_a(World.java:1986)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.world.World.func_72870_g(World.java:1948)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.world.World.func_72939_s(World.java:6048)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2209)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[17:13:07] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:    at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by Dockter** [comment]
What version of CMS are you using?

**Comment by ghost** [comment]
3.11.3

**Comment by Zidane** [comment]
This isn't a crash, someone left in a dumpStack in CMS as the log says...

**Comment by ghost** [comment]
server runs, but nothing spawned - dump is when debug cms is enabled

**Comment by ghost** [comment]
It looks some of 6.0 api plugins blocks spawning.
