### ISSUE TITLE
Weird client error that says something about sponge when sponge is not even installed

### ISSUE THREAD

**Issue by xAlicatt** [SpongePowered/SpongeForge#1826]
This may or may not be the appropriate place for this, but I've been trying to figure out why my custom pack profile on Twitch launcher will not load for about an hour now, with no success. This is using the Java launcher.

When I click the play button on the launcher it prints out a blurb of errors and doesn't go anywhere. There are no config files or crash logs, because it doesn't get that far.

This is purely singleplayer/client only and unrelated to a server. I do not have sponge installed. It's not in my mods folder, yet it's printing several errors related to sponge somehow?

```
2:21:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:21:12] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
Exception in thread "main" [02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Error reading configuration file
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.fail(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.parse(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.access$200(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.hasNextService(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.access$600(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator$1.run(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator$1.run(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.hasNext(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$1.hasNext(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.io.FileNotFoundException: D:\Games\Minecraft\Curse\Instances\Build-It (The system cannot find the file specified)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.zip.ZipFile.open(Native Method)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.zip.ZipFile.<init>(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.zip.ZipFile.<init>(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.jar.JarFile.<init>(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.jar.JarFile.<init>(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URL.openStream(Unknown Source)
[02:21:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 22 more
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
```

**Comment by phit** [comment]
looks like some mod is using https://github.com/SpongePowered/Mixin and erroring, either way not related to SpongeForge at all, I can recommend removing mods one by one to figure it out.

**Comment by xAlicatt** [comment]
For anyone finding this in the future, the mod appears to be MalisisCore. Will report back if I find more information. Closing this since it's not SpongeForge related.

**Comment by thecrazycraft** [comment]
Pov: You see this 4 YEARS after it is posted and it helps you.

**Comment by thecrazycraft** [comment]
thanks btw

**Comment by itzacookie** [comment]
> For anyone finding this in the future, the mod appears to be MalisisCore. Will report back if I find more information. Closing this since it's not SpongeForge related.

I LOVE YOU
