### ISSUE TITLE
Spam in console [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#1844]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2698.jar
- Forge version: 12.18.3.2422
- Java version: 1.8.0_151
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
**Modpack Sky Factory 3 (3.0.15)**
Plugins (180): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, Fence Overhaul, Actually Additions, CodeChicken Lib, CodeChicken Core, EnderStorage, Just Enough Items, OpenComputers, ActuallyComputers, Baubles, Extra Utilities 2, AngelRing 2 Bauble, AppleCore, apple_shields, AppleSkin, AutoPackager, Psi, AutoRegLib, Baconators, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, BD Lib, Bed Bugs, Better Builder's Wands, BiomeTweaker, BlockDispenser, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Mantle, Tinkers' Construct, Ceramics, Chameleon, MCMultiPart, ‽, |, /, Chickens, Chisel, Chisels & Bits, ShadowMC, Clipboard, Clumps, Cyclops Core, Colossal Chests, CommonCapabilities, Cooking for Blockheads, Waila, Dark Utilities, PTRModelLib, Decocraft, Dimensional Cake, Draconic Evolution, Dragon Mounts, Storage Drawers, Drawers & Bits, Elevator Mod, EnderCore, Ender IO, Energy Converters, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Ex Nihilo Adscensio, Ex Compressum, Extra Bit Manipulation, Zero CORE, Extreme Reactors, Farming for Blockheads, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, Funnels, Garden of Glass, Advanced Generators, Gravestone Mod, Grue, Get Ya' Tanks Here, Hammer Core, Headcrumbs, Hopper Ducts, HydroGel, Immersive Engineering, Integrated Dynamics, Integrated Tunnels, Iron Chest, It's Raining Food, KleeSlabs, LLibrary, Literal Ascension, Long Fall Boots, Loot Bags, LunatriusCore, MineMenu, MiniCoal, Natura, Missing Pieces, Random Things, Roots, MoarSigns, mob_grinding_utils, MTLib, Mod Tweaker, More Chickens, More Shearables, More Shears, Morpheus, Mystical Agriculture, Nice, Not Enough Wands, OreExcavation, Pam's HarvestCraft, ShetiPhian-Core, Platforms, BetterChunkLoader, Buycraft, CatClearLag, GriefPrevention, LuckPerms, Nucleus, SkyClaims, TabManager, TickProfiler, UltimateCore, StatusProtocol, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Refined Storage, RebornStorage, Redstone Paste, Reliquia, RFTools, RFTools Control, RFTools Dimensions, Wooden Shears, Scanner, Shear Madness, Simple Achievements, Simple Barrels, Simple Corn, Simple Generators, SimpleLabels, Simply Jetpacks 2, Snad, Solar Flux Reborn, Steve's Carts 2, Super Circuit Maker, The Beneath, Tinkers Tool Leveling, Tiny Progressions, TorchMaster, Translocator, Twerk-Sim 2K16, Twitchcrumbs, voidcup, Waddles, WanionLib, I Can See Everything, What Are We Looking At, Wither Crumbs, WorldEdit, Experience Rings, UniDict

**What is the current result?**
I am not sure if it is the right place to report this problem, please correct me if necessary.
My server Sky Factory 3 is sending too much spam to the console and during that time the server ejects all users for the reason "Time Out", it appears as if it had crashed but does not leave any report on it, it just stays stuck.
Reviewing the file "fml-server-latest.log" I found tons of the same error:
`[09:43:58] [Netty Epoll Server IO #4/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: Error while writev(...): Conexión reinicializada por la máquina remota
	at io.netty.channel.epoll.Native.writevAddresses(Native Method) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:184) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.1.10.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.1.10.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[09:43:58] [Netty Epoll Server IO #4/WARN] [io.netty.channel.DefaultChannelPipeline/]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Error while writev(...): Conexión reinicializada por la máquina remota
	at io.netty.channel.epoll.Native.writevAddresses(Native Method) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:184) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.1.10.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.1.10.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

And this causes files to be generated with more than 30mb, sometimes I can not open them because of the large size.
I suppose that such reports also affect the performance during the generation of them.
Here is my full report, the errors start on line 28078 and for obvious reasons I had to cut it out otherwise it would be impossible to upload it to pastebin.

**Edit:** I have decided to compress it so that you can download it completely
fml-server-latest.log: http://heberon.com/descargas/temporales/fml-server-latest.rar

**Comment by phit** [comment]
Please update Forge to newer than 12.18.3.2488 or newer and see if it still happens.

**Comment by phit** [comment]
No reply, closed.
