### ISSUE TITLE
Crash on server load - unexplained by crash logs

### ISSUE THREAD

**Issue by drewc5131** [SpongePowered/SpongeForge#1887]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2757
- Forge version: forge-1.12.2-14.23.1.2559-universal
- Java version: jdk1.8.0_91
- Operating System: Windows 10

MODS

Name                                           | Version                     | Source                                      |
:-------------------------------------------- |:--------------------------- |:------------------------------------------- |
 minecraft                                    | 1.12.2                      | minecraft.jar                               |
 mcp                                          | 9.42                        | minecraft.jar                               |
 FML                                          | 8.0.99.99                   | forge-1.12.2-14.23.1.2559-universal.jar     |
 forge                                        | 14.23.1.2559                | forge-1.12.2-14.23.1.2559-universal.jar     |
 com.elytradev.movingworld.common.asm.coremod |                             | minecraft.jar                               |
 spongeapi                                    | 7.0.0-SNAPSHOT-4456498      | spongeforge-1.12.2-2555-7.0.0-BETA-2756.jar |
 sponge                                       | 1.12.2-2555-7.0.0-BETA-2756 | spongeforge-1.12.2-2555-7.0.0-BETA-2756.jar |
 opencomputers|core                           | 1.7.0.20                    | minecraft.jar                               |
 quark                                        | r1.3-110                    | Quark-r1.3-110.jar                          |
 autoreglib                                   | 1.3-15                      | AutoRegLib-1.3-15.jar                       |
 bibliocraft                                  | 2.4.3                       | BiblioCraft[v2.4.3][MC1.12.0].jar           |
 chisel                                       | MC1.12-0.0.14.18            | Chisel-MC1.12-0.0.14.18.jar                 |
 customnpcs                                   | 1.12                        | CustomNPCs_1.12.0(22jul17)beta.jar          |
 movingworld                                  | 1.12-6.342                  | movingworld-1.12-6.342-full.jar             |
 davincisvessels                              | @DVESSELSVER@               | davincisvessels-1.12-6.340-full.jar         |
 ic2                                          | 2.8.16-ex112                | industrialcraft-2-2.8.16-ex112.jar          |
 ironchest                                    | 1.12.2-7.0.34.820           | ironchest-1.12.2-7.0.34.820.jar             |
 baseloto                                     | 1.0                         | lotobase-1.12.jar                           |
 opencomputers                                | 1.7.0.20                    | OpenComputers-MC1.12.1-1.7.0.20.jar         |
 refinedstorage                               | 1.5.25                      | refinedstorage-1.5.25.jar                   |

**Issue Description**
Starting the server, after loading mods and stuff it crashes

***CRASH REPORT***
https://gist.githubusercontent.com/drewc5131/06a5e696b139b38036f8b5764c8e8b8b/raw/445f3fa83ac4eb3dfe4611f99a7d162ec02f422d/crashxd
Forge Crash Log https://gist.githubusercontent.com/drewc5131/69b035be51d41c2e7b0d63e15f4c8c52/raw/1e2aae91be02fc2efbb29769b4b1a6e8e6d7e463/forgecrash

**Comment by ryantheleach** [comment]
Remapped:

```
[16:26:33] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.scoreboard.ServerScoreboard.getOrCreateScore(SourceFile:764) ~[nv.class:?]
	at net.minecraft.scoreboard.ScoreboardSaveData.readScores(SourceFile:152) ~[bhl.class:?]
	at net.minecraft.scoreboard.ScoreboardSaveData.readFromNBT(SourceFile:46) ~[bhl.class:?]
	at net.minecraft.scoreboard.ScoreboardSaveData.setScoreboard(SourceFile:34) ~[bhl.class:?]
	at net.minecraft.world.WorldServer.redirect$onSetSaveDataScoreboard$zkp000(WorldServer.java:1749) ~[oo.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:153) ~[oo.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:789) ~[WorldManager.class:1.12.2-2555-7.0.0-BETA-2757]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:759) ~[WorldManager.class:1.12.2-2555-7.0.0-BETA-2757]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:3553) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[16:26:33] [Server thread/ERROR]: This crash report has been saved to: E:\LOTO VANILLA S2\spong\.\crash-reports\crash-2017-12-04_16.26.33-server.txt
[16:26:33] [Server thread/INFO]: Stopping server
```

**Comment by drewc5131** [comment]
Update: I deleted the scoreboard.dat file from the world and it fixed the crash.

**Comment by MVillabon** [comment]
[crash-2023-02-19_21.37.17-server.txt](https://github.com/SpongePowered/SpongeForge/files/10778043/crash-2023-02-19_21.37.17-server.txt)

**Comment by MVillabon** [comment]
[latest.log](https://github.com/SpongePowered/SpongeForge/files/10778048/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/10778050/debug.log)
