### ISSUE TITLE
Error executing task - Industrial Foregoing

### ISSUE THREAD

**Issue by FilipK-CZ** [SpongePowered/SpongeForge#1888]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2760
- Forge version: forge-1.12.2-14.23.1.2555-universal
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
- Operating System: Ubuntu 14.04.5 LTS

Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, InstantRespawn, LuckPerms, Nucleus, ProjectCore, ProjectWorlds, SkinsRestorer, Web-API, Web-API API

Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Industrial Foregoing, TESLA, Tesla Core Lib, Tesla Core Lib Registries, Refined Storage

**Issue Description**

By opening any device from mod Industrial Foregoing

```
[01:53:35] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid size: 0
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2760]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zif000(MinecraftServer.java:4008) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Invalid size: 0
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.item.inventory.lens.impl.AbstractLens.<init>(AbstractLens.java:81) ~[AbstractLens.class:1.12.2-2555-7.0.0-BETA-2760]
        at org.spongepowered.common.item.inventory.lens.impl.DelegatingLens.<init>(DelegatingLens.java:46) ~[DelegatingLens.class:1.12.2-2555-7.0.0-BETA-2760]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:257) ~[ContainerUtil.class:1.12.2-2555-7.0.0-BETA-2760]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.getLens(ContainerUtil.java:228) ~[ContainerUtil.class:1.12.2-2555-7.0.0-BETA-2760]
        at net.minecraft.inventory.Container.init(Container.java:972) ~[afr.class:?]
        at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1025) ~[afr.class:?]
        at net.minecraft.inventory.Container.func_75142_b(Container.java:1020) ~[afr.class:?]
        at net.minecraft.inventory.Container.func_75132_a(Container.java:1007) ~[afr.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:100) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
        at net.ndrei.teslacorelib.blocks.RegisteredBlock.func_180639_a(RegisteredBlock.kt:105) ~[RegisteredBlock.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1246) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zhk000(NetHandlerPlayServer.java:2376) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) ~[PacketUtil.class:1.12.2-2555-7.0.0-BETA-2760]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjp000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
```

**Comment by rob5251** [comment]
Also happening when opening an ME Terminal from Applied Energistics.

**Comment by FilipK-CZ** [comment]
Grid from Refined Storage too

**Comment by ryantheleach** [comment]
@Faithcaio I believe this is due to your recent merge of the inventory refactor.

https://github.com/SpongePowered/SpongeCommon/pull/1585

**Comment by Faithcaio** [comment]
should be fixed in latest
