### ISSUE TITLE
ChangeInventoryEvent error

### ISSUE THREAD

**Issue by yyeerai** [SpongePowered/SpongeForge#1943]
**I am currently running**
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-eebceb6
    SpongeForge: 1.12.2-2555-7.1.0-BETA-2825
    Minecraft Forge: 14.23.1.2555

- Plugins/Mods:
Mods (27): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Better Questing, Better Questing Triggerer, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, Ex Compressum, Ex Nihilo Creatio, Forestry, IndustrialCraft 2, Mantle, Redstone Flux, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tree Chopper

Plugins (11): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, GriefPrevention, Holograms, LuckPerms, Nucleus, SkyClaims, Total Economy

**In version SpongeForge: 1.12.2-2555-7.1.0-BETA-2821 there is no such error**

`[19:49:46] [Server thread/ERROR] [Sponge]: Could not pass ChangeInventoryEvent$Pickup$Pre$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=4.3.0, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/home/mc/island/mods/griefprevention-1.12.2-4.3.0.509.jar}
java.lang.NoSuchMethodError: org.spongepowered.common.config.type.ConfigBase.getWorld()Lorg/spongepowered/common/config/category/WorldCategory;
        at me.ryanhamshire.griefprevention.claim.GPClaim.isPvpEnabled(GPClaim.java:916) ~[GPClaim.class:1.12.2-4.3.0.509]
        at me.ryanhamshire.griefprevention.claim.GPClaim.pvpRulesApply(GPClaim.java:925) ~[GPClaim.class:1.12.2-4.3.0.509]
        at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerPickupItem(PlayerEventHandler.java:1571) ~[PlayerEventHandler.class:1.12.2-4.3.0.509]
        at org.spongepowered.common.event.listener.PreListener_PlayerEventHandler_onPlayerPickupItem133.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.1.0-BETA-2825]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2825]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:302) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2825]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:367) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2825]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2555-7.1.0-BETA-2825]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2555-7.1.0-BETA-2825]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callPlayerChangeInventoryPickupPreEvent(SpongeCommonEventFactory.java:168) [SpongeCommonEventFactory.class:1.12.2-2555-7.1.0-BETA-2825]
        at net.minecraft.entity.item.EntityItem.handler$onPlayerItemPickup$zfj000(EntityItem.java:762) [acl.class:?]
        at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:392) [acl.class:?]
        at net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$zgh000(EntityPlayer.java:3726) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571) [aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zif000(NetHandlerPlayServer.java:2029) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]`

**Comment by phit** [comment]
was fixed in griefprevention
