### ISSUE TITLE
refined storage phase tracking console spam

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1944]
**I am currently running**
- SpongeForge version: build 2822
- Forge version: build 2562
- Java version: 1.8
- Operating System:linux

**Issue Description**
Console spam when insert crafting upgrade to exporter from refined storage mod.

https://pastebin.com/62R58nsy

**Comment by phit** [comment]
Refined Storage bug, not caused by Sponge https://github.com/raoulvdberge/refinedstorage/issues/1567

**Comment by ghost** [comment]
It not same bug, server running, not closed or crashed. Just filling console/log with tons of phase tracking text. Reopen please.

**Comment by phit** [comment]
it is the same bug, sponge just stops the server from crashing

from the linked issue
```
java.lang.NullPointerException: Ticking block entity
    at java.util.ArrayList.removeIf(ArrayList.java:1405)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:466)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:181)
    at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:203)
    at net.minecraft.world.World.func_72939_s(World.java:1829)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Thread.java:745)
```

from your log
```
[10:46:26] [Server thread/ERROR] [Sponge]: /* java.lang.NullPointerException: null                                                                      */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:466)  */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:181) */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:204)             */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:242)            */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2843)                               */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zle000(WorldServer.java:2830)           */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72939_s(World.java:6602)                                               */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2219)                                   */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)                           */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)                 */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)                           */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)                                    */
[10:46:26] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Thread.java:745)  
```

exactly the same mod stacktrace

**Comment by ghost** [comment]
Ah ok, thanks for reply.
