### ISSUE TITLE
Bibliocraft AbstractMethodError

### ISSUE THREAD

**Issue by unstablecraft** [SpongePowered/SpongeForge#1948]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.1.0-BETA-2825.jar
- Forge version: 1.12.2-14.23.1.2573.jar
- Java version: 8
- Operating System: centos

- Plugins/Mods: 
![image](https://user-images.githubusercontent.com/33659444/34792770-6f0b84c8-f649-11e7-91ab-edc3fee5e671.png)

**Issue Description** sponge is spitting out this error and another error stack trace that i will post if i can catch it 

https://gist.github.com/unstablecraft/9f2ffcb1e7bb0049562c13d71dddf7c4  FATAL ERROR

**Comment by unstablecraft** [comment]
https://gist.github.com/unstablecraft/1844592316af61a8197ce35bb7f07c60 ERROR stack trace

**Comment by phit** [comment]
the first error looks like a mod bug, not related to Sponge, the second one has the stacktrace cut off

please add your full `fml-junk-earlystartup.log`

**Comment by unstablecraft** [comment]
https://gist.githubusercontent.com/unstablecraft/69fd256082b72b9eb40704a3a0e577a4/raw/667060bcc2c5639f4c65cd34f21085281c6c52e3/phit's%25208000%2520lines%2520to%2520read


around 8000 lines  but this the log you requested

**Comment by ryantheleach** [comment]
![image](https://user-images.githubusercontent.com/141554/34825561-ecb14406-f722-11e7-98b4-161cac8957f9.png)

```
[11:02:07] [Server thread/INFO] [nucleus]: Server ran the command: /list 
[11:02:09] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world
[11:02:09] [Server thread/DEBUG] [fluxnetworks]: ALL 19 Networks were saved successfully
[11:02:10] [Server thread/DEBUG] [torchmaster]: Saved 39 entries for mega_torch to disk
[11:02:10] [Server thread/DEBUG] [torchmaster]: Saved 1 entries for dread_lamp to disk
[11:02:11] [JDA MainWS-ReadThread/TRACE] [net.dv8tion.jda.core.requests.WebSocketClient]: PRESENCE_UPDATE -> {"nick":"Irvin Wimmers","game":{"timestamps":{"start":1515664931282},"name":"drinking like its 1999","type":0},"roles":["357267747064905738","357267810675589120","357567859393822720","377185530216972308"],"guild_id":"357266943507693570","user":{"id":"337539482205290498"},"status":"online"}
[11:02:12] [HikariPool-1 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Pool stats (total=17, active=2, idle=15, waiting=0)
[11:02:13] [HikariPool-2 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Pool stats (total=17, active=0, idle=17, waiting=0)
[11:02:20] [Server thread/ERROR] [EnjinMinecraftPlugin]: Exception Caught: 
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at com.enjin.sponge.command.DirectiveNode.invoke(DirectiveNode.java:59) ~[DirectiveNode.class:?]
	at com.enjin.sponge.command.CommandNode.invoke(CommandNode.java:50) ~[CommandNode.class:?]
	at com.enjin.sponge.command.CommandBank.handle(CommandBank.java:204) ~[CommandBank.class:?]
	at com.enjin.sponge.command.CommandBank.onSendCommand(CommandBank.java:187) ~[CommandBank.class:?]
	at org.spongepowered.common.event.listener.SendCommandEventListener_CommandBank_onSendCommand79.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:371) ~[SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) ~[SpongeEventManager.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:299) ~[SpongeCommandManager.class:1.12.2-2555-7.1.0-BETA-2825]
	at com.enjin.sponge.sync.SpongeInstructionHandler.lambda$execute$0(SpongeInstructionHandler.java:143) ~[SpongeInstructionHandler.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2825]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_151]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2555-7.1.0-BETA-2825]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:269) [SpongeMod.class:1.12.2-2555-7.1.0-BETA-2825]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_321_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_151]
	at com.enjin.sponge.command.commands.CoreCommands.inform(CoreCommands.java:186) ~[CoreCommands.class:?]
	... 32 more
```

Enjin is invoking a method using reflection on a null target? And also calling .get() without checking if it's present.

![image](https://user-images.githubusercontent.com/141554/34825804-e06e15a6-f723-11e7-835b-d5ed4d5b2974.png)

Not Sponges Issue, Contact Enjin plugin support.

**Comment by ryantheleach** [comment]
That was maybe a little rash. Leaving open for now because of the other stack traces.

**Comment by unstablecraft** [comment]
tell me what you need and ill provide it

**Comment by unstablecraft** [comment]
and ill link enjin to this "again" so 
far theire support within 24 hours

**Comment by ryantheleach** [comment]
Yeah I can't even find the phase tracker trace in your log. @phit Any ideas?

**Comment by ryantheleach** [comment]
The modded stack trace might be async lighting related?
Remapped Trace
https://gist.github.com/ryantheleach/62d5eead19d59ec682543de5298faff2/revisions

**Comment by Zidane** [comment]
@Faithcaio 

+10.01 20:57:12 [Server] INFO java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityTypeMachine.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract

**Comment by Faithcaio** [comment]
ItemStack getStackInSlot(int index)
is part of the IInventory interface in vanilla
no idea how this can happen

**Comment by ryantheleach** [comment]
@Zidane @Faithcaio This is a long shot, but is it a remapping error of some kind? I can't fine 'getStackInSlot' defined in their mod on that class, but shouldn't it have an MCP name in the stack trace?

**Comment by Zidane** [comment]
Closing this as neither are Sponge issues.

**Comment by Shybella** [comment]
This is still a present issue but no one contacted Enjin about it?

They are aware now.
