### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#1968]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar
- Forge version: forge-1.12.2-14.23.1.2555-universal.jar
- Java version: java version "1.8.0_151"
- Operating System: Win 7 x64

- Plugins/Mods:
ActionBroadcaster.jar
ActiveTime-s7.1-v1.3.2.jar
AntiXray-1.0.0.jar
CatClearLag-0.8.2.jar
ChangeSkin.jar
chopchop.jar
console-lock-1.1.1.jar
craftbook-sponge-S7.1-4.0-SNAPSHOT-dist.jar
denizen2core-0.4.0.jar
denizen2sponge-0.4.0.jar
Dynmap-2.6-beta-1-forge-1.12.jar
Dynmap-GriefPrevention-master-1.0-SNAPSHOT.jar
EasyScoreboards.jar
EconomyLite-7.0.0-2.13.0.jar
extradrop-0.1.2.jar
flexiblelogin-0.16.7.jar
griefprevention-1.12.2-4.3.0.512.jar
holograms-3.1.jar
InstantRespawn.jar
iplog-0.2.1.jar
itemduct.jar
lambdaattack-core-2.3.1.jar
LangSwitch.jar
LibCube.jar
LuckPerms-Sponge-4.0.98.jar
MineReset-1.0.8.BETA2.jar
Nucleus-1.2.2-S7.0-MC1.12.2-plugin.jar
PlaceholderAPI-4.4.jar
projectcore-7.0.0-0.2.1.jar
projectinventories-7.0.0-0.11.1.jar
projectportals-7.0.0-0.14.1.jar
SkyClaims-0.27.0-S7.0-SNAPSHOT.jar
SkyGrid-1.0.jar
spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar
TabManager-1.0.4.jar
TimTheEnchanter.jar
TitleMOTD.-.1.0.jar
VillagerShops.jar
walletdrop-7.0.0-0.3.0.jar
worldedit-sponge-6.1.9-SNAPSHOT-dist.jar

**Issue Description**

1. Run server.
2. The client attempts to connect to the server.
3. In the console indicates that the client has connected.
4. But the client is not connected. A message appears about the connection...
5. Pressed the disable button. Again, pressed the connect button. Joined!
6. Console continuous spam NetworkDispatcher exception.
7. The player plays.

full logs https://cloud.mail.ru/public/5vmt/e9Yub4mDT

**Comment by phit** [comment]
upload the logs to gist.github.com, nobody wants to download some file to get your logs
apart from this, with the amount of plugins you have this is gonna be impossible to track down for a third party, remove all your plugins and add them back one by one, when it stops working you found the source

**Comment by ryantheleach** [comment]
```
AntiXray-1.0.0.jar
ChangeSkin.jar
Dynmap-2.6-beta-1-forge-1.12.jar
Dynmap-GriefPrevention-master-1.0-SNAPSHOT.jar
flexiblelogin-0.16.7.jar
InstantRespawn.jar
LangSwitch.jar
TabManager-1.0.4.jar
```

If you want a short cut, these would be my personal first suspects just based on what I think the API can do and my guess at whether they hook into internals based on the plugin name.

**Comment by XakepSDK** [comment]
I found this in the logs. Nothing more.
```
[12:38:25] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: (unreadable message here, decoded as: program on your host dropped down the connection)
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_151]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[NioSocketChannel.class:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [AbstractChannel$AbstractUnsafe.class:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [AbstractNioChannel$AbstractNioUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by ziceptor** [comment]
@phit I forgot to post the link
[fml-junk-earlystartup.log ](https://gist.github.com/ziceptor/7e8e3010f0850f13a4849e0255ed9c19)
\+
[fml-server-1.log ](https://gist.github.com/ziceptor/ea8f59f6852c70ac40d130b726e7628c)
[fml-server-2.log ](https://gist.github.com/ziceptor/89d077c315abed49c257569c4e93594c)
[fml-server-3.log](https://gist.github.com/ziceptor/7de60cfa3e19104bdfaebd4b3343c1fd)
[fml-server-latest.log](https://gist.github.com/ziceptor/140902cd0104fba958ef4efa9a959cf4)
[latest.log](https://gist.github.com/ziceptor/b2c80f8e4ed2620fd75dbfc8034ba0e9)

@ryantheleach  I use these plugins for a long time. There were no problems.

> ChangeSkin.jar
> Dynmap-2.6-beta-1-forge-1.12.jar
> Dynmap-GriefPrevention-master-1.0-SNAPSHOT.jar

@games647
> flexiblelogin-0.16.7.jar

> InstantRespawn.jar
> LangSwitch.jar
> TabManager-1.0.4.jar

Recent changes:
- Add plugin AntiXray-1.0.0.jar
- Update Sponge to spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar

I met the problem twice in one day.

**Comment by phit** [comment]
remove antixray and try again?

**Comment by ziceptor** [comment]
Still not removed. Recorded the video. Now removes the plugin and try again.

**Comment by ziceptor** [comment]
This happens without the plugin antixray

**Comment by ziceptor** [comment]
Difficult to reproduce. I've done a lot of successive connections and disconnections. Here's what happened: [video](https://www.youtube.com/watch?v=BdDlwnxduY0)

**Comment by XakepSDK** [comment]
@ziceptor отправь логи из видео.
/en/
send logs from video

**Comment by phit** [comment]
once again
> with the amount of plugins you have this is gonna be impossible to track down for a third party, remove all your plugins and add them back one by one, when it stops working you found the source

more logs or videos aren't gonna change that

**Comment by ziceptor** [comment]
@phit I'll do it later
@XakepSDK 
https://gist.github.com/ziceptor/3eefa1c3166ef2c87ecc940dda4c803f
https://gist.github.com/ziceptor/4bc1aa6a313e446f3c1b59b3ade69179
https://gist.github.com/ziceptor/a6977625485e741a9773f7162400527c
https://gist.github.com/ziceptor/65c55560f8b989b20521dcf0d64792b9
https://gist.github.com/ziceptor/a1c17636b1d13859081d3cd75ea60934

**Comment by XakepSDK** [comment]
```
[04:30:20] [Server thread/INFO]: lipa lost connection: Disconnected
[04:30:20] [Server thread/INFO]: 
[04:30:21] [Server thread/WARN]: Failed to handle packet for /192.168.10.105:51135
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240) ~[DefaultChannelPipeline.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.insertIntoChannel(NetworkDispatcher.java:174) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:160) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:72) ~[FMLNetworkHandler.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135) ~[pc.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63) ~[pc.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[04:30:21] [Server thread/INFO]: lipa lost connection: Disconnected
```

**Comment by XakepSDK** [comment]
@ziceptor можешь моды и плагины раздельно написать?
/en/
can you divide mods and plugins in description?

**Comment by ziceptor** [comment]
mod: Dynmap-2.6-beta-1-forge-1.12.jar
other: plugins

**Comment by XakepSDK** [comment]
После чего эта проблема появилась?

T: Then this problem appeared?

**Comment by ziceptor** [comment]
Я думаю, что после обновления губки. Я сейчас создал сервер без модов.. только spongeforge. И смог воспроизвести проблему. Только немного другое поведение. Спам в консоли есть, но во время спама уже не подключиться к серверу.

T: I think that after updating the sponge. I now created a server without mods .. only spongeforge. I was able to reproduce the problem. Just a little bit different behavior. Spam in the console is there, but during the spam no longer connect to the server.

**Comment by XakepSDK** [comment]
Скинь лог. Мне кажется, где-то в forge race condition ну или губка добавила
его.

T: Throw off the log. It seems to me, somewhere in the forge race condition well, or the sponge added him.

**Comment by ziceptor** [comment]
Снова все?

T: Everything again?

**Comment by XakepSDK** [comment]
Ну в которых ошибки есть (exception)

T: Well, in which there are errors

**Comment by ziceptor** [comment]
only spongeforge (without plugins and mods)
the problem remained

https://gist.github.com/ziceptor/40825cd7bf99f3457786eddb72f245ef
https://gist.github.com/ziceptor/1d48d6f67609dc6a3e435dc1723144b7
https://gist.github.com/ziceptor/88e8988036f81b205ef269f6b04d074e

**Comment by ziceptor** [comment]
video https://youtu.be/7HZVv4CoAbA

**Comment by Zidane** [comment]
Closing as this isn't a Sponge issue and is either a Forge or Minecraft issue.

I would start with Forge.

**Comment by XakepSDK** [comment]
Создай тут issue

T: Create a new issue here
https://github.com/MinecraftForge/MinecraftForge
