### ISSUE TITLE
[1.12.2] SpongeCommon missed introduction of KeyBind TextComponent

### ISSUE THREAD

**Issue by kremi151** [SpongePowered/SpongeForge#1986]
I am using SpongeForge BETA 2865. The server crashes when loading a world when the newest version of my mod (MinaMod) is present, as it worked perfectly before the new version. One thing I changed was the descriptions of 2 advancements to display the key binding on the client side in order to open a custom GUI. Pressing the key should then trigger the advancement(s).
For example: Pressing the 'N' key should open a special GUI and trigger an advancement. This advancement should than dynamically include the keybinding 'G' in the description.
One of the respective JSON files looks like follows: (have a look at the description)

{
    "display": {
        "icon": {
            "item": "minamod:amulet_of_ender"
        },
        "title": {
		    "translate": "achievement.minamod.amulets"
	    },
        "description": {
            "translate": "achievement.minamod.amulets.desc",
            "with":[{"keybind":"key.minamod.amulets"}]
        }
    },
	"parent": "minamod:story/root",
    "criteria": {
        "see_amulets": {
            "trigger": "minamod:open_amulet_inventory"
        }
    }
}

The error message gives a hint that it is caused by the dynamic description, as this has something to do with text components. It worked perfectly when running the mod in a non-Sponge environment.

Here is the complete crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 2/3/18 11:59 AM
Description: Exception in server tick loop

java.lang.UnsupportedOperationException
	at net.minecraft.util.text.TextComponentBase.createBuilder(TextComponentBase.java:562)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:695)
	at net.minecraft.util.text.TextComponentTranslation.wrapFormatArgs(SourceFile:570)
	at net.minecraft.util.text.TextComponentTranslation.createBuilder(SourceFile:552)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:695)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:716)
	at net.minecraft.util.text.event.HoverEvent.getHandle(SourceFile:564)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:708)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:716)
	at org.spongepowered.common.text.SpongeTexts.toText(SpongeTexts.java:79)
	at net.minecraft.advancements.Advancement.handler$onInit$zzi000(SourceFile:629)
	at net.minecraft.advancements.Advancement.<init>(SourceFile:60)
	at net.minecraft.advancements.Advancement$Builder.func_192056_a(SourceFile:163)
	at net.minecraft.advancements.AdvancementList.func_192083_a(SourceFile:65)
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:70)
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:790)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:760)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3552)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.text.TextComponentBase.createBuilder(TextComponentBase.java:562)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:695)
	at net.minecraft.util.text.TextComponentTranslation.wrapFormatArgs(SourceFile:570)
	at net.minecraft.util.text.TextComponentTranslation.createBuilder(SourceFile:552)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:695)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:716)
	at net.minecraft.util.text.event.HoverEvent.getHandle(SourceFile:564)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:708)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:716)
	at org.spongepowered.common.text.SpongeTexts.toText(SpongeTexts.java:79)
	at net.minecraft.advancements.Advancement.handler$onInit$zzi000(SourceFile:629)
	at net.minecraft.advancements.Advancement.<init>(SourceFile:60)
	at net.minecraft.advancements.Advancement$Builder.func_192056_a(SourceFile:163)
	at net.minecraft.advancements.AdvancementList.func_192083_a(SourceFile:65)
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:70)
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:790)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjc000(MinecraftServer.java:4017)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.26-nitradoV3-MC-1000-nH-dP-d-i
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1761180688 bytes (1679 MB) / 2459959296 bytes (2346 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xmx6144M -Xms256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2586 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID              | Version                     | Source                                      | Signature                                |
	|:------- |:--------------- |:--------------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft       | 1.12.2                      | minecraft.jar                               | None                                     |
	| UCHIJAA | mcp             | 9.42                        | minecraft.jar                               | None                                     |
	| UCHIJAA | FML             | 8.0.99.99                   | minecraft_server.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge           | 14.23.1.2586                | minecraft_server.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | spongeapi       | 7.1.0-SNAPSHOT-b163786      | spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar | None                                     |
	| UCHIJAA | sponge          | 1.12.2-2586-7.1.0-BETA-2865 | spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar | None                                     |
	| UCHIJAA | ttt3d           | 0.0.3.1                     | 3DTicTacToe for Sponge.jar                  | None                                     |
	| UCHIJAA | buttonwarp      | 0.0.3.0                     | ButtonWarp.jar                              | None                                     |
	| UCHIJAA | forgedperms     | 1.0.0.2                     | ForgedPerms.jar                             | None                                     |
	| UCHIJAA | linkedbookshelf | 0.2.0.1                     | LinkedBookShelf.jar                         | None                                     |
	| UCHIJAA | luckperms       | 4.0.121                     | LuckPerms-Sponge-4.0.121.jar                | None                                     |
	| UCHIJAA | luxmc           | 0.7.4.0                     | LuxMC Core.jar                              | None                                     |
	| UCHIJAA | guidebook       | 1.7.0                       | mod_guidebook-1.7.0.jar                     | None                                     |
	| UCHIJAA | minamod         | 1.1.0.8                     | mod_minamod-1.12.2-1.1.0.8.jar              | None                                     |
	| UCHIJAA | nucleus         | 1.2.2-S7.0                  | Nucleus-1.2.2-S7.0-MC1.12.2-plugin.jar      | None                                     |
	| UCHIJAA | worldedit       | 6.1.9-SNAPSHOT              | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar    | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 4; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by dualspiral** [comment]
Can you try SF 2881? There were some advancements related issues that were worked around in some of the latest versions.

**Comment by kremi151** [comment]
I tried it with SpongeForge 2881, same error:

java.lang.UnsupportedOperationException
	at net.minecraft.util.text.TextComponentBase.createBuilder(TextComponentBase.java:562)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:695)
	at net.minecraft.util.text.TextComponentTranslation.wrapFormatArgs(SourceFile:570)
	at net.minecraft.util.text.TextComponentTranslation.createBuilder(SourceFile:552)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:695)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:716)
	at net.minecraft.util.text.event.HoverEvent.getHandle(SourceFile:564)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:708)
	at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:716)
	at org.spongepowered.common.text.SpongeTexts.toText(SpongeTexts.java:79)
	at net.minecraft.advancements.Advancement.handler$onInit$zzj000(SourceFile:629)
	at net.minecraft.advancements.Advancement.<init>(SourceFile:60)
	at net.minecraft.advancements.Advancement$Builder.func_192056_a(SourceFile:163)
	at net.minecraft.advancements.AdvancementList.func_192083_a(SourceFile:65)
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:70)
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:790)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:760)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3552)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

**Comment by ryantheleach** [comment]
https://minecraft.gamepedia.com/17w16a (1.12 snapshot version) Added the TextComponents for keybinds, we have totally failed to catch this, and will probably be throwing errors whenever a TextComponent is parsed as a Text.

@limbo-app move to sc

**Comment by dualspiral** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @kremi151! I've moved your issue to [SpongePowered/SpongeCommon#1758](https://github.com/SpongePowered/SpongeCommon/issues/1758).
