### ISSUE TITLE
Minecraft Comes Alive Crash

### ISSUE THREAD

**Issue by Fently** [SpongePowered/SpongeForge#2004]
Hi, I'm having problems with sponge and Minecraft Comes Alive

1) Crashes when trying to trade with MCA villager
2) Every server restart results in a purple and black textured villager named "Steve the Farmer":
* Any MCA villager npc that is currently loaded in the game, will be transformed into "Steve the Farmer" on any crash, restart, etc. No clue why. When discovering an MCA villager npc for the first time, it will work no problem, but as soon as the server turns off and back on again, it will be "Steve the Farmer"
* Both problems are present _only_ when SpongeForge is running

Crash log when trying to trade
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 11/02/18 1:43 AM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.NullPointerException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:663)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1854)
	at net.minecraft.entity.passive.EntityVillager.func_70934_b(EntityVillager.java:651)
	at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:923)
	at mca.packets.PacketInteract.processOnGameThread(PacketInteract.java:161)
	at mca.packets.PacketInteract.processOnGameThread(PacketInteract.java:46)
	at radixcore.modules.net.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:174)
	at radixcore.core.RadixEvents.serverTickEventHandler(RadixEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_RadixEvents_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651)
	... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:663)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 994046144 bytes (947 MB) / 1933049856 bytes (1843 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx3072M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2613 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version                     | Source                                      | Signature                                |
	|:--------- |:----------------- |:--------------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2                      | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp               | 9.42                        | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99                   | forge-1.12.2-14.23.2.2613-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.2.2613                | forge-1.12.2-14.23.2.2613-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | spongeapi         | 7.1.0-SNAPSHOT-dcd7174      | spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar | None                                     |
	| UCHIJAAAA | sponge            | 1.12.2-2586-7.1.0-BETA-2890 | spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar | None                                     |
	| UCHIJAAAA | radixcore         | 1.12.x-2.2.1                | RadixCore-1.12.x-2.2.1-universal.jar        | None                                     |
	| UCHIJAAAA | mca               | 1.12.2-5.3.1                | MCA-1.12.x-5.3.1-universal.jar              | None                                     |
	| UCHIJAAAA | mercurius_updater | 1.0                         | MercuriusUpdater-1.12.2.jar                 | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```
When sponge is installed, this is spouted everywhere under info
```[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: java.lang.reflect.MalformedParameterizedTypeException
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at sun.reflect.generics.repository.FieldRepository.getGenericType(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at java.lang.reflect.Field.getGenericType(Unknown Source)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at mca.entity.VillagerAttributes.readFromNBT(VillagerAttributes.java:982)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at mca.entity.EntityVillagerMCA.func_70037_a(EntityVillagerMCA.java:446)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1863)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:221)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:601)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:528)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:485)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunkForce(ChunkProviderServer.java:1081)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.gen.ChunkProviderServer.redirect$onProvideChunkHead$zmc000(ChunkProviderServer.java:678)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3602)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:815)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:760)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3552)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[11:35:10] [Server thread/INFO] [STDERR]: [mca.entity.VillagerAttributes:readFromNBT:1026]: 	at java.lang.Thread.run(Unknown Source)
```
• Note, this is repeated 431 more times in the log, which you can see here: [Pastebin](https://zerobin.net/?5cffb250788fcf1d#UcdEk1Thja5r7s2NBRW1TN33MIWQHFNTf14j3K6HS04=)
• The "MalformedParameterizedTypeException" message does not crash the server, though it _may_ be 
   releated to the trading problem

-------Versions-------
OS: Windows10 Professional & Linux 4.9.76
Sponge : 1.12.2-2586-7.1.0-BETA-2890
Forge: 1.12.2-14.23.2.2613
MCA: 1.12.x-5.3.1
RadixCore: 1.12.x-2.2.1

**Comment by phit** [comment]
please retest this without sponge, this looks like a mod issue on first glance

**Comment by Fently** [comment]
I thought so too, but the weird part is these issues only occur when SpngeForge is installed. Here is the log without SpongeForge running: [Pastebin](https://zerobin.net/?7b0f548f651b0138#iFeRl1tHzEQel+3uZBSi3VuCA9bVU8YL8Ot9vyG785Y=)

The "MalformedParameterizedTypeException" no longer shows up, server can be rebooted any number of times and mca villagers will still remain the same, and trading will no longer crash the server

**Comment by gabizou** [comment]
If you want to give it a shot with SF 3014, might fix a few things.

**Comment by Zidane** [comment]
Closing until we hear further.
