### ISSUE TITLE
NPE bug

### ISSUE THREAD

**Issue by yyeerai** [SpongePowered/SpongeForge#2006]
**I am currently running**

- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-6aa4e43
- SpongeForge: 1.12.2-2611-7.1.0-BETA-2906
- Minecraft Forge: 14.23.2.2611

plugins And mods
Plugins (14): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, GriefPrevention, Holograms, LangSwitch, LuckPerms, Nucleus, SkyClaims, Total Economy, VillagerShops, WorldEdit

Mods (12): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Better Questing, Better Questing Quest Book, CraftTweaker JEI Support, CraftTweaker2, Standard Expansion, The Twilight Forest

**Edit**: remapped stacktrace: https://gist.github.com/ryantheleach/db145a909179adcea2cee1eaaaa8c3bb ~ryantheleach
```
[11:37:13] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
        at net.minecraft.util.Util.runTask(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:275) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2906]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:2529) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:69) ~[li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:13) ~[li.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) ~[PacketUtil.class:1.12.2-2611-7.1.0-BETA-2906]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
        at net.minecraft.util.Util.runTask(SourceFile:46) ~[h.class:?]
        ... 7 more
```

**Comment by phit** [comment]
literally 0 context or reproduction, please explain when this happens and what is needed to for this to show up

edit: didnt mean to close

**Comment by yyeerai** [comment]
Vshop to create a non-villager entity, add items to the vshop inside, right-wrong entity when the error

**Comment by phit** [comment]
https://github.com/DosMike/VillagerShops/issues/35
