### ISSUE TITLE
UserStorageService NPE

### ISSUE THREAD

**Issue by ShortCircuit908** [SpongePowered/SpongeForge#2021]
**I am currently running**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2793
- Forge version: 12.18.3.2422
- Java version: 1.8
- Operating System: ubuntu 16.04.3 LTS

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, Aroma1997Core, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, Nucleus Mixins, ActionBroadcaster, CoFH Core, Actually Additions, AdamantineShield, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Just Enough Items, AppleSkin, Aquaculture, ArchitectureCraft, Aroma1997Core|Helper, Aroma1997's Dimensional World, Morph-o-Tool, Psi, Quark, AutoRegLib, Bazaar, Bed Bugs, Better Builder's Wands, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, CodeChicken Lib, Brandon's Core, CatClearLag, Mantle, Tinkers' Construct, Ceramics, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Dark Utilities, PTRModelLib, Decocraft, Extra Utilities 2, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, Storage Drawers, Drawers & Bits, EasyScoreboards, Elevator Mod, Embers, NuVotifier, Enjin Minecraft Plugin, EnderCore, Ender IO, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Zero CORE, Extreme Reactors, Fast Leaf Decay, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, Funky Locomotion, Funnels, GenDustry, Golden Sands, Gravestone Mod, Gravitation Suite, Golden Sands Chunkloader, Golden Sands Restrictions, Hammer Core, HelpFixer, Hopper Ducts, The One Probe, Immersive Engineering, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, Kraken, Long Fall Boots, LuckPerms, MalisisCore, MalisisDoors, Mercurius, Modular ForceField System, MmmMmmMmmMmm, mob_grinding_utils, MTLib, Mod Tweaker, Railcraft, RebornCore, TechReborn, More Bees, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Natura, Nether Portal Fix, Nucleus, Open Glider, p455w0rd's Library, Pam's HarvestCraft, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, QuantumStorage, Ranged Pumps, RankUpper, reborncore-MCMultiPart, Thermal Foundation, Thermal Expansion, Redstone Arsenal, Redstone Clock, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, RFTools Dimensions, Roots, SeriousVote, Signals, SimpleVoidWorld, Simple Retrogen, Simply Jetpacks 2, Sleeping Bag, Snad, Solar Flux Reborn, Steve's Carts 2, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, Thermal Dynamics, TickProfiler, TieredKits, Tinkers Tool Leveling, TOP Addons, TorchMaster, Total Economy, Translocator, Useful Nullifiers, WanionLib, Wireless Crafting Grid, Wireless Crafting Terminal 2, Woot, WorldEdit, WirelessRedstone-CBE, XNet, YABBA, UniDict

**Issue Description**

Calling `UserStorageService.get(UUID uniqueId)` with a valid player UUID produces the following exception:
```
java.lang.NullPointerException
	at org.spongepowered.common.service.user.UserDiscoverer.getOnlinePlayer(UserDiscoverer.java:192) ~[UserDiscoverer.class:1.10.2-2477-5.2.0-BETA-2793]
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:92) ~[UserDiscoverer.class:1.10.2-2477-5.2.0-BETA-2793]
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:50) ~[SpongeUserStorageService.class:1.10.2-2477-5.2.0-BETA-2793]
	at com.shortcircuit.bazaar.util.UserUtils.getUser(UserUtils.java:34) ~[UserUtils.class:?]
	at com.shortcircuit.bazaar.market.MarketStall.getOwner(MarketStall.java:60) ~[MarketStall.class:?]
	at com.shortcircuit.bazaar.market.EvictionTask.run(EvictionTask.java:29) ~[EvictionTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-2477-5.2.0-BETA-2793]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2477-5.2.0-BETA-2793]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

Contents of `com.shortcircuit.bazaar.util.UserUtils` is available here: https://gist.github.com/Short-Circuit/7fcb4d10c5c9127c522cf96b9b272446

Server log:
https://gist.github.com/Short-Circuit/5a5928d8a7257eb96cb7524690e3381a

**Comment by simon816** [comment]
The problem is that you're calling the service before the server has loaded.

From the logs we can see that the server is still in the initialization phase:
```
[18:02:18] [Server thread/TRACE] [ae2stuff/ae2stuff]: Sending event FMLInitializationEvent to mod ae2stuff
[18:02:18] [Server thread/INFO] [bdlib/ae2stuff]: Initialized network channel 'bdew.ae2stuff' for mod 'ae2stuff'
[18:02:18] [pool-2-thread-6/ERROR] [Sponge/luckperms]: The Scheduler tried to run the task bazaar-A-31 owned by Plugin{id=bazaar, name=Bazaar, version=1.9-SNAPSHOT, description=Full market solution, authors=[ShortCircuit908], source=/home/desktop/McMyAdmin/Beyond/Minecraft/mods/bazaar.jar}, but an error occured.
java.lang.NullPointerException
	at org.spongepowered.common.service.user.UserDiscoverer.getOnlinePlayer(UserDiscoverer.java:192) ~[UserDiscoverer.class:1.10.2-2477-5.2.0-BETA-2793]
```

`UserDiscoverer` attempts to validate the server is available ([here](https://github.com/SpongePowered/SpongeCommon/blob/57702bf6baf492d72a0d4307d7eaef0434a7bfce/src/main/java/org/spongepowered/common/service/user/UserDiscoverer.java#L186)) but it probably should check that `playerList` is also available
