### ISSUE TITLE
“A fatal error has ocorred, this connection is terminated” Sponge and Dalek Mod!

### ISSUE THREAD

**Issue by CebolaSelvagem** [SpongePowered/SpongeForge#2065]
**I am currently running**

- SpongeForge version: Sponge 1.12.2-2611-7.1.0-BETA-2983
- Forge version: Forge 1.12.2 - 14.23.2.2635
- Java version: Java 8u161
- Operating System: Windows Server 2012

- Plugins/Mods: Sponge and Dalek Mod 1.12.2 (Update 47)

**Issue Description**
Hello guys, guess what? Big problem here

I’m trying to run a server with my friends with the latest dalek mod and some plugins on sponge, everything is working fine, i’m mean, no bugs, no errors… Except, when you try to set a destination in the TARDIS… The mod works creating about 3 or 4 worlds that you can travel to using a interface, but everytime you choose a world and click in “Save” you are disconnect and get this message: “A fatal error has ocorred, this connection is terminated.” I searched everything looking for a fix, I saw something about “netty leak” but i don’t know what that means, neither how to fix it...

[Here's the console log](https://gist.github.com/CebolaSelvagem/539401887e527e09d7f3e1ffc72a1211)

If anyone could help i would be very greatful!

**Comment by phit** [comment]
please report this to the mod authors, not a Sponge issue

```
[02:13:08] [Netty Server IO #0/ERROR] [FML]: There was a critical exception handling a packet on channel thedalekmod
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=Netty Server IO #0, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!        
at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:71) ~[SpongeCauseStackManager.class:1.12.2-2611-7.1.0-BETA-2983]
        at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:85) ~[SpongeCauseStackManager.class:1.12.2-2611-7.1.0-BETA-2983]
        at net.minecraft.world.chunk.Chunk.handler$onLoadReturn$zle000(Chunk.java:1895) ~[axw.class:?]
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:861) ~[axw.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvder.java:105) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.redirect$onProvideChunkHead$zme000(ChunkProviderServer.java:669) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:309) ~[amu.class:?]
        at net.minecraft.world.World.func_175726_f(World.java:304) ~[amu.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:6323) ~[amu.class:?]
        at com.swdteam.network.packets.Packet_UpdateTardisDataField$Handler.handleServerMessage(Packet_UpdateTardisDataField.java:87) ~[Packet_UpdateTardisDataField$Handler.class:?]
        at com.swdteam.network.packets.Packet_UpdateTardisDataField$Handler.handleServerMessage(Packet_UpdateTardisDataField.java:45) ~[Packet_UpdateTardisDataField$Handler.class:?]
        at com.swdteam.network.packets.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:35) ~[AbstractMessageHandler.class:?]
```
