### ISSUE TITLE
server time-out chunks loads off-thread

### ISSUE THREAD

**Issue by Excaliburning** [SpongePowered/SpongeForge#2066]
Hi !

**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2983.jar
- Forge version: forge-1.12.2-14.23.2.2611-universal.jar
- Java version: Java 8
- Operating System: Windows 10 Pro x64

- Plugins/Mods: 
- Plugins (16): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CraftBook, Holograms, ItemChat, KaroglanSignEditor, LuckPerms, MMCReboot, MagiBridge, Nucleus, Pieconomy, SayItem, SleepVote, SmoofyDungeon

Mods (22): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Amazing Stands, Baby Animals Model Swapper, CodeChicken Lib, Doggy Talents, Farseek, JourneyMap, Just Enough Items, Just a Few Fish, Millenaire, Moar Boats, Multi Mine, Not Enough Items, Shadowfacts' Forgelin, Streams, WorldEdit, uppers

All of them are either the lastest stable version or the lastest 1.12.2 version (in this case, they're often a beta, like for Millénaire).

**Issue Description**
Technically no idea what happened. I was roaming a bit, to check if the server was stable after the addition of Amazing Stands, Multi Mine and Shadowfacts' Forgelin.
I tried to make a baby pig to check the Baby Animals mod was working as intended since I had forgotten to check last run.
So far, everything worked, I wanted to see if there was any lag with hostile mobs and spawned a zombie then went into survival. The zombie didn't chase me, I set the night to get naturally spawned hostile mobs, none of them got an aggro on me, even if I dealt them damage. Typical of a server time-out, I waited a bit and effectively got timed-out, the server being unreachable after that. Then I saw the console and the recommendation of sending these logs to you on Github. That, I've done, see the link below.

Sorry for bothering you about it, no idea of what went on. Thanks for looking into it, I wish you a good day !

**Logs:**
https://gist.github.com/Excaliburning/7e59b0cf42ac634f7707f85c9753a71e

Edit: sorry if something's amiss, I don't really use Github, feel free to tell if I've done something wrong, I'll correct it.

**Comment by gabizou** [comment]
I'm seeing a lot of this at first:
```
Exception in thread "Thread-1905" [01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: CauseStackManager called from off main thread (current='UpdateThread{class=class org.millenaire.common.village.VillageMapInfo$UpdateThread, name=Thread-1905, priority=1, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:71)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:85)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.chunk.Chunk.handler$onLoadReturn$zle000(Chunk.java:1895)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:861)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.redirect$onProvideChunkHead$zme000(ChunkProviderServer.java:669)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.World.func_72964_e(World.java:309)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.World.func_175726_f(World.java:304)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3117)
[01:06:19] [Thread-1905/INFO] [STD
ERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.utilities.WorldUtilities.getBlock(WorldUtilities.java:143)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.village.VillageMapInfo.updateChunk(VillageMapInfo.java:695)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.village.VillageMapInfo.access$000(VillageMapInfo.java:30)
[01:06:19] [Thread-1905/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.village.VillageMapInfo$UpdateThread.run(VillageMapInfo.java:39)
Exception in thread "Thread-1906" [01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: CauseStackManager called from off main thread (current='UpdateThread{class=class org.millenaire.common.village.VillageMapInfo$UpdateThread, name=Thread-1906, priority=1, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:71)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:85)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.chunk.Chunk.handler$onLoadReturn$zle000(Chunk.java:1895)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:861)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.redirect$onProvideChunkHead$zme000(ChunkProviderServer.java:669)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.World.func_72964_e(World.java:309)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.World.func_175726_f(World.java:304)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3117)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.utilities.WorldUtilities.getBlock(WorldUtilities.java:143)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.village.VillageMapInfo.updateChunk(VillageMapInfo.java:695)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.village.VillageMapInfo.access$000(VillageMapInfo.java:30)
[01:06:19] [Thread-1906/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.millenaire.common.village.VillageMapInfo$UpdateThread.run(VillageMapInfo.java:39)
```
Which reminds me of https://github.com/SpongePowered/SpongeForge/issues/2065. Part of the problem is that there are several chunk generations that got halted on another thread, and those are now leaking into the main thread.

Sponge itself could "workaround" by terminating the thread properly, but it boils down to chunks generating off thread and sponge exposing it.

**Comment by Excaliburning** [comment]
Edit: my bad, the culprit is clearly Millénaire. Didn't notice the names in the reports. I'm going to report it to them and see what can be done, thanks.

Hmm I see, the culprits could be Millénaire and Streams then.
They're the only ones actually generating anything in the overworld aside of normal.
I saw a river from Stream cross a Millénaire village, but aside of this happening as in vanilla (except this river is not a vanilla river, but this happens in vanilla sometimes too) nothing special seemed to bother the generation. It generated nicely  (even if the result's ugly 'cause of the village floating over the river) and nothing seemed to go wrong.

What could be the cause, if you have any idea ?

There's also SmoofyDungeon that could generate something but that'd only be if I actually wrote the command and created another world with it, which I haven't done.
Could Nucleus cause that kind of thing ?

Thanks for the fast answer earlier !

**Comment by dualspiral** [comment]
With respect to Nucleus: no

**Comment by dualspiral** [comment]
Oh, yes, the non-hostile mobs thing - I bet you gave yourself * permissions. That’s causing Nucleus to vanish you on login.

https://ore.spongepowered.org/Nucleus/Nucleus/pages/The-Permissions-Wildcard-(And-Why-You-Shouldn't-Use-It)

**Comment by Excaliburning** [comment]
@dualspiral Just noticed that as well, I'd read your topic just before you sent it but thanks a lot, greatly appreciated.
I sent this issue to Millénaire since it seems to come from them.

**Comment by Kinniken** [comment]
Hi,

Millénaire creator here. This is indeed due to Millénaire loading chunks off the main thread, which I'll prevent. However the root cause is that the chunks are not loaded in the first place even though Millénaire requests them to be using Forge's ticket system. With regular Minecraft servers nobody has reported this issue.

Does Sponge impose harsher restrictions on keeping chunks loaded? Because if that's the case I can fix this, but villages will not work properly if the chunks they are on cannot be kept loaded reliably.

**Comment by Excaliburning** [comment]
@Kinniken could it come from Stream (forge mod) ? I noticed the streams often crossed Millénaire towns for some reason. But I'm not sure if it tinkers with the things you mentionned.

I do not know if Sponge's restrictions towards chunks is different from Forge's.
Maybe @dualspiral could have an idea since he's well versed in Sponge. I would ask a Sponge dev but I don't know their team sadly.

Thanks for taking the time to take a look over here !
For now we removed Millénaire, it caused other issues (notably the issue 101 on your Gitlab, which happened way too often for me, a friend didn't have this problem on the server but ended up having it too so we nuked it but we're still following Millénaire's progression on this beta).

edit: I changed the title to a more fitting name, since the "hostile not hostile" was another issue created by... none other than myself (Nucleus permissions w/ Luck Perms).

**Comment by Kinniken** [comment]
I doubt it's those streams. They could cause some issues with pathing etc but not chunk-loading.

I'll check #101, a little odd.

**Comment by ProsperCraft** [comment]
Could this be related to - 
https://forums.spongepowered.org/t/psa-spongeforge-rb-2985-spongevanilla-rb-30-for-minecraft-1-12-2/23123

**Comment by Zidane** [comment]
@ProsperCraft 

No lol

**Comment by dualspiral** [comment]
Is `deny-chunk-requests` set to `true` in your `global.conf` file? If so, it could be that Sponge is denying the requests to load, in which case try setting it to `false` and reloading the config/restarting.

**Comment by Excaliburning** [comment]
@dualspiral it seems this is set to false by default.
`deny-chunk-requests=false` in my `global.conf`.

It can't come from that then. However, it's a good idea to double-check it.

As expected by @Kinniken it's not Streams either.

**Comment by phit** [comment]
don't see an outstanding issue here? if you have issues with chunkloading please open an issue for that

**Comment by Excaliburning** [comment]
@phit the issue being the server forced to shut down, I wouldn't consider it "outstanding" but maybe just a crank below "critical".
It is indeed an issue about chunkloading ? I quote the title "chunks loads off-thread".

I haven't followed Millénaire's development these past weeks for some reasons but @Kinniken 's question stood unanswered about chunk generation "Does Sponge impose harsher restrictions on keeping chunks loaded?". I believe we came to the conclusion that Millénaire was part of the cause of this issue but never got to understand why, at least in this issue's topic.
Maybe Kinniken has figured it out by now/got answered somewhere else.

But I don't really understand why would you ask to open another issue about this issue ?
Rather, while I had forgotten this was still open, I'd ask if this issue has been solved on Millénaire's side or if it is tied with some obscure ways in Sponge that Millénaire can't change or go around.

**Comment by phit** [comment]
Nothing in your logs mentioned crashing, the spam was caused by something Millenaire did and was fixed on their end. They were loading chunks off the main thread and you can't load chunks off the main thread in this game or do any world interaction really.

I'm asking for a new issue from Millenaire if they are having issues with loading in general in Sponge because it has nothing to do with your initial report, and multiple topics in one issue just lead to confusion and makes it hard to keep track of what is even relevant.
