### ISSUE TITLE
Crashed on startup

### ISSUE THREAD

**Issue by sheng-ri** [SpongePowered/SpongeForge#2131]
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3065
- Forge version: 1.12.2-14.23.3.2655
- Java version: 8-64
- Operating System: Windows 10(My computer) - Linx(Server) 

- Plugins/Mods: only a Sponge

```
[18:45:20] [Server thread/WARN] [Sponge]: sponge: It is no longer required to include the plugin id when specifying a Key id through Key.Builder#id. This is deprecated and may be removed later. The plugin id will be retrieved from the current PluginContainer in the cause stack. 
[18:54:06] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/spongepowered/common/data/processor/value/entity/ExperienceFromStartOfLevelValueProcessor
	at org.spongepowered.common.data.DataRegistrar.setupSerialization(DataRegistrar.java:755) ~[DataRegistrar.class:1.12.2-2655-7.1.0-BETA-3065]
	at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:198) ~[SpongeGameRegistry.class:1.12.2-2655-7.1.0-BETA-3065]
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:155) ~[SpongeMod.class:1.12.2-2655-7.1.0-BETA-3065]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_162]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_162]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:377) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:541) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.common.data.processor.value.entity.ExperienceFromStartOfLevelValueProcessor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	... 15 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(Unknown Source) ~[?:1.8.0_162]
	at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_162]
	at java.util.HashMap.putMapEntries(Unknown Source) ~[?:1.8.0_162]
	at java.util.HashMap.<init>(Unknown Source) ~[?:1.8.0_162]
	at java.util.jar.Attributes.<init>(Unknown Source) ~[?:1.8.0_162]
	at java.util.jar.Attributes.clone(Unknown Source) ~[?:1.8.0_162]
	at sun.net.www.protocol.jar.URLJarFile.getManifest(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:147) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	... 15 more
[18:54:18] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[18:54:18] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[18:54:18] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[18:54:24] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: org/spongepowered/api/event/SpongeEventFactory
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:226)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.handler$postGameStoppingEvent$zoe000(DedicatedServer.java:830)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71240_o(DedicatedServer.java)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.SpongeEventFactory
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 5 more
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.newNode(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.putVal(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.putMapEntries(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.<init>(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.jar.Attributes.<init>(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.jar.Attributes.clone(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.net.www.protocol.jar.URLJarFile.getManifest(Unknown Source)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:148)
[18:54:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 7 more
```

**Comment by EnderGamingFilms** [comment]
Try deleting the world and running the server again.

**Comment by phit** [comment]
`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`

Please make sure you are allocating enough memory, see our docs for more help https://docs.spongepowered.org/stable/en/server/getting-started/launch-script.html
