### ISSUE TITLE
Loading World, ERROR:  java.lang.NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by MacKey-255** [SpongePowered/SpongeForge#2169]
**I am currently running**

- Minecraft Version: 1.12.2
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3065
- Forge version: 14.23.3.2655
- Java version: 1.8.0_131, Oracle Corporation
- Operating System: Windows 10 (amd64) version 10.0

- Plugins/Mods:
```
| State     | ID                         | Version                      | Source                                            | Signature                                |
	|:--------- |:-------------------------- |:---------------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                  | 1.12.2                       | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | mcp                        | 9.42                         | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | FML                        | 8.0.99.99                    | forge-1.12.2-14.23.3.2655-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                      | 14.23.3.2655                 | forge-1.12.2-14.23.3.2655-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | spongeapi                  | 7.1.0-SNAPSHOT-7d8a938       | spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar       | None                                     |
	| UCHIJAAAA | sponge                     | 1.12.2-2655-7.1.0-BETA-3065  | spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar       | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| UCHIJAAAA | techguns_core              | 1.12.2-1.0                   | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | antixray                   | 1.2.7                        | AntiXray-1.2.7.jar                                | None                                     |
	| UCHIJAAAA | securitycraft              | v1.8.4.1                     | [1.12.x]SecurityCraft+v1.8.4.1.jar                | None                                     |
	| UCHIJAAAA | appliedenergistics2        | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar             | None                                     |
	| UCHIJAAAA | baubles                    | 1.5.2                        | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCHIJAAAA | betteranimals              | 1.2                          | betteranimals-1.3.jar                             | None                                     |
	| UCHIJAAAA | mantle                     | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                          | None                                     |
	| UCHIJAAAA | endercore                  | 1.12.2-0.5.22                | EnderCore-1.12.2-0.5.22.jar                       | None                                     |
	| UCHIJAAAA | jei                        | 4.9.1.168                    | jei_1.12.2-4.9.1.168.jar                          | None                                     |
	| UCHIJAAAA | enderio                    | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | enderiointegrationtic      | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | tconstruct                 | 1.12.2-2.9.1.65              | TConstruct-1.12.2-2.9.1.65.jar                    | None                                     |
	| UCHIJAAAA | codechickenlib             | 3.1.8.341                    | CodeChickenLib-1.12.2-3.1.8.341-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux               | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore                   | 4.3.10                       | CoFHCore-1.12.2-4.3.10.5-universal.jar            | None                                     |
	| UCHIJAAAA | cofhworld                  | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar           | None                                     |
	| UCHIJAAAA | thermalfoundation          | 2.3.10                       | ThermalFoundation-1.12.2-2.3.10.6-universal.jar   | None                                     |
	| UCHIJAAAA | thermalexpansion           | 5.3.10                       | ThermalExpansion-1.12.2-5.3.10.15-universal.jar   | None                                     |
	| UCHIJAAAA | betterwithmods             | ${version}                   | BetterWithMods-1.12-2.1.16.jar                    | None                                     |
	| UCHIJAAAA | chickenchunks              | 2.4.1.71                     | ChickenChunks-1.12.2-2.4.1.71-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | clib                       | 1.0.2.31                     | CLib-1.0.2.31-universal.jar                       | None                                     |
	| UCHIJAAAA | enderiobase                | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | enderioconduits            | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | enderiointegrationforestry | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | enderiointegrationticlate  | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | ftblib                     | 5.0.2.11                     | FTBLib-5.0.2.11.jar                               | None                                     |
	| UCHIJAAAA | enderiomachines            | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | enderiopowertools          | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJAAAA | zerocore                   | 1.12-0.1.2.1                 | zerocore-1.12-0.1.2.1.jar                         | None                                     |
	| UCHIJAAAA | bigreactors                | 1.12.2-0.4.5.48              | ExtremeReactors-1.12.2-0.4.5.48.jar               | None                                     |
	| UCHIJAAAA | waila                      | 1.8.23                       | Hwyla-1.8.23-B38_1.12.jar                         | None                                     |
	| UCHIJAAAA | ic2                        | 2.8.73-ex112                 | industrialcraft-2-2.8.73-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | inventorytweaks            | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | thaumcraft                 | 6.1.BETA13                   | Thaumcraft-1.12.2-6.1.BETA13.jar                  | None                                     |
	| UCHIJAAAA | omlib                      | 3.0.0-140                    | omlib-1.12.2-3.0.0-140.jar                        | None                                     |
	| UCHIJAAAA | openmodularturrets         | 3.0.0-236                    | openmodularturrets-1.12.2-3.0.0-236.jar           | None                                     |
	| UCHIJAAAA | pneumaticcraft             | 1.12.2-0.6.3-181             | pneumaticcraft-repressurized-1.12.2-0.6.3-181.jar | None                                     |
	| UCHIJAAAA | simplyenchanting           | 1.0.3                        | SimplyEnchanting-1.12-1.0.3(1).jar                | None                                     |
	| UCHIJAAAA | techguns                   | 2.0.1.0                      | techguns-1.12.2-2.0.1.0.jar                       | None                                     |
	| UCHIJAAAA | battlelog                  | 1.0.0                        | BattleLog.jar                                     | None                                     |
	| UCHIJAAAA | catclearlag                | 0.8.3                        | CatClearLag-0.8.3.jar                             | None                                     |
	| UCHIJAAAA | commandsigns               | 2.4                          | commandsigns-2.4.jar                              | None                                     |
	| UCHIJAAAA | flexiblelogin              | 0.17.3                       | flexiblelogin-0.17.3.jar                          | None                                     |
	| UCHIJAAAA | ftbutilities               | 5.0.2.11                     | FTBUtilities-5.0.2.11.jar                         | None                                     |
	| UCHIJAAAA | jobslite                   | 1.8.1                        | JobsLite-7.1.0-1.8.1.jar                          | None                                     |
	| UCHIJAAAA | mmcreboot                  | 2.2.2                        | MMCReboot-2.2.2-API-7.jar                         | None                                     |
	| UCHIJAAAA | mmcrestrict                | 1.4.3                        | MMCRestrict-1.4.3-API-7.jar                       | None                                     |
	| UCHIJAAAA | modcontrol                 | 1.5.1                        | ModControl-MC1.12-1.5.1.jar                       | None                                     |
	| UCHIJAAAA | nucleus                    | 1.3.13-S7.0                  | Nucleus-1.3.13-S7.0-MC1.12.2-plugin.jar           | None                                     |
	| UCHIJAAAA | pixelautomessages          | 1.0.3                        | PixelAutoMessages-1.0.3-b15.jar                   | None                                     |
	| UCHIJAAAA | pjc                        | 0.2.1                        | projectcore-7.0.0-0.2.1.jar                       | None                                     |
	| UCHIJAAAA | pjw                        | 0.12.2                       | projectworlds-7.1.0-0.12.2.jar                    | None                                     |
	| UCHIJAAAA | serverlistplus             | 3.4.7                        | ServerListPlus-3.4.7-Universal.jar                | None                                     |
	| UCHIJAAAA | totaleconomy               | 1.8.0                        | TotalEconomy-1.8.0.jar                            | None                                     |
	| UCHIJAAAA | universalminecraftapi      | 0.2                          | UniversalMinecraftAPI-sponge.jar                  | None                                     |
	| UCHIJAAAA | worldedit                  | 6.1.9-SNAPSHOT               | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar          | None                                     |
```

**Issue Description**
Me ocurre un crash al cargar una parte del mundo y se cierra el Servidor.
Crash Server Error with Loading World

[crash-2018-05-22_23.41.48-server.txt](https://github.com/SpongePowered/SpongeForge/files/2029499/crash-2018-05-22_23.41.48-server.txt)

To aid searching:

```
java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.chunk.Chunk.getSurroundingChunks(Chunk.java:4903)
	at net.minecraft.world.chunk.Chunk.handler$onTickHead$zol000(Chunk.java:4563)
	at net.minecraft.world.chunk.Chunk.onTick(Chunk.java)
	at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:2006)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by XakepSDK** [comment]
Use gist for crash reports, no one wants download files.

**Comment by Aaron1011** [comment]
Here's the log that @MacKey-255 posted: https://gist.githubusercontent.com/Aaron1011/b173e94103c8f147c44b61418c18e4a7/raw/63be9e8be7fe967048750e5802e980e2d1c7486e/gistfile1.txt

**Comment by ryantheleach** [comment]
And remapped: https://gist.github.com/ryantheleach/345319d38743b6ee2586f186001d8109

**Comment by ryantheleach** [comment]
@MacKey-255 Apologies for the delay of any meaningful response, I know that can be frustrating.

But with the current information you have provided, it's very vague and hard to debug, without knowing a modpack or specific mod combination that will cause this.

If you have updated information, it would help debug this, otherwise a modpack, or example world that contains this issue, or some form of step by step to reproduce it.

Otherwise, it's completely possible this bug has been fixed already, in a later version of Sponge, so I recommend trying some later versions and seeing if it's resolved.

Can you reproduce this issue without Sponge?
