### ISSUE TITLE
Some Chinese username could't be recognized as valid username.

### ISSUE THREAD

**Issue by Jecvay** [SpongePowered/SpongeForge#2178]
- SpongeForge version: 1.12.2-2703-7.1.0-BETA-3119
- Forge version: 14.23.4.2703 
- Java version: 1.8
- Operating System: Windows 10 1803

Some Chinese username could't be recognized as valid username.
as an example, when username='测试',
this issue happened.

is this issue relation with "com.google.common.base.Preconditions.checkArgument" ?

```
> econ set 测试 100
[22:48:47] [Server thread/INFO] [nucleus]: Server ran the command: /econ set 测试 100
[22:48:47] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Error occurred while executing command: Invalid username 测试
[22:48:47] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'econ set 测试 100' for source DedicatedServer: Invalid username 测试
java.lang.IllegalArgumentException: Invalid username 测试
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:60) ~[SpongeUserStorageService.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.getValue(GenericArguments.java:1154) ~[GenericArguments$UserCommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_151]
        at org.spongepowered.api.command.args.PatternMatchingCommandElement.getExactMatch(PatternMatchingCommandElement.java:102) ~[PatternMatchingCommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.PatternMatchingCommandElement.parseValue(PatternMatchingCommandElement.java:59) ~[PatternMatchingCommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.SelectorCommandElement.parseValue(SelectorCommandElement.java:57) ~[SelectorCommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.parseValue(GenericArguments.java:1134) ~[GenericArguments$UserCommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:83) ~[CommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.parse(GenericArguments.java:1178) ~[GenericArguments$UserCommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.GenericArguments$SequenceCommandElement.parse(GenericArguments.java:311) ~[GenericArguments$SequenceCommandElement.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.spec.CommandSpec.populateContext(CommandSpec.java:340) ~[CommandSpec.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.parse(ChildCommandElementExecutor.java:194) ~[ChildCommandElementExecutor.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.spec.CommandSpec.populateContext(CommandSpec.java:340) ~[CommandSpec.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:387) ~[CommandSpec.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2703-7.1.0-BETA-3119]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2703-7.1.0-BETA-3119]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
>


```

**Comment by axin0452** [comment]
This is a very serious problem.

**Comment by phit** [comment]
am I missing something? usernames in minecraft are limited to 

>Allowed characters: 
>
>* A-Z (upper and lower case)
>* 0-9
>* The only allowed special character is _ (underscore) 



https://help.mojang.com/customer/en/portal/articles/928638-minecraft-usernames

**Comment by liach** [comment]
vanilla can allow unicode usernames.

**Comment by liach** [comment]
@phit In China, there are Chinese usernames in the China version of Minecraft. https://minecraft.gamepedia.com/Minecraft_China

**Comment by liach** [comment]
@Jecvay 试试看名字长一点（三个字）能不能行

https://github.com/SpongePowered/SpongeCommon/blob/a17a93e23d7cc29bbcf69c3f8fb87b3265cc8a0d/src/main/java/org/spongepowered/common/service/user/SpongeUserStorageService.java#L60

**Comment by phit** [comment]
@liach forgot that they had a different auth system, thanks

**Comment by liach** [comment]
In fact @phit it should be username length difference. I am not sure if Chinese users can have 1 character user names.

**Comment by Jecvay** [comment]
@liach 可以的啦, 谢谢大神

**Comment by XakepSDK** [comment]
```
user@arch ~ % jshell
|  Welcome to JShell -- Version 10.0.1
|  For an introduction type: /help intro

jshell> "测试"
$1 ==> "测试"

jshell> $1.length()
$2 ==> 2

jshell> 
```

I even can't imagine, how this can be fixed.

**Comment by Jecvay** [comment]
@XakepSDK what did you mean ?

do you mean len("测试") == 2 is wrong or something else ?

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/989a541950ef28198015e626dfe38fa5539cb9d6/src/main/java/org/spongepowered/common/service/user/SpongeUserStorageService.java#L60

If Mojang indeed allow usernames to be < 3 characters, it should be a pretty easy fix to just make sure it's a > 0 length username.

**Comment by XakepSDK** [comment]
@Jecvay just to be sure, that `测试` is 2 characters length string. For users from China this can be obvious, but not for me or any other developer that knows nothing about Chinese characters in unicode.
@ryantheleach only in China, iirc this issue.

**Comment by ryantheleach** [comment]
@XakepSDK My point was that we shouldn't set it to '2' just because we think, but don't have evidence of it being the minimum, 3 was clearly incorrect, and it was documented.

I think > 0 is fine for validation, and I also question if there are other issues in Sponge when dealing with the alternate authentication implementations. It may also have some unintended consequences potentially with NPC's or something.

**Comment by yushijinhun** [comment]
> I think > 0 is fine for validation.

I agree with you.

In fact, there isn't any technological difficulty in supporting 1-character or 2-character usernames. It is totally a man-made restriction set by Mojang.

However, aside from Mojang's authentication system, there are offline users and users who use a different authentication system. We should give them the right to choose whatever username they like.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Jecvay! I've moved your issue to [SpongePowered/SpongeCommon#1971](https://github.com/SpongePowered/SpongeCommon/issues/1971).
