### ISSUE TITLE
Villager Career Mismatch! 

### ISSUE THREAD

**Issue by flamechair** [SpongePowered/SpongeForge#2226]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3182
- Forge version: 2705 1.12.2
- Java version: N/A
- Operating System: N/A

- Plugins/Mods:
[04:48:49] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Mods (79): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, AbyssalCraft, AbyssalCraft Integration, Aether Legacy, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, AutoRegLib, Baubles, Bookshelf, Chameleon, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Cyclops Core, Dark Utilities, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EvilCraft, EvilCraft-Compat, Extra Utilities 2, Guide-API, Hammer Core, Improvable Skills, Inventory Tweaks, Iron Chest, Just Enough Items, LagGoggles, Less Forgiving Void, McJtyLib, NetherEx, Not Enough Items, OpenBlocks, OpenModsLib, OpenModsLib Core, Quark, RFTools, Redstone Flux, Roguelike Dungeons, Storage Drawers, TOP Addons, TeamLapen Library, Thaumcrafft Inventory Scanning, Thaumcraft, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tree Chopper, UniDict, Unlimited Chisel Works, Vampirism, VampirismIntegrations, WanionLib, WorldEdit

[04:49:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Plugins (16): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActionBroadcaster, CarrotShop, ClearMob, EconomyLite, GriefPrevention, LuckPerms, MMCRestrict, MagiBridge, Nucleus, ProjectCore, ProjectPortals, Rankup

**Issue Description** Upon booting up the server, it crashes during startup with error:
```
[19:39:17] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [server.jar:?]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [server.jar:?]
Caused by: java.lang.ExceptionInInitializerError
at net.minecraftforge.fml.common.registry.ForgeRegistries.init(ForgeRegistries.java:62) ~[ForgeRegistries.class:?]
at net.minecraftforge.fml.common.registry.ForgeRegistries.<clinit>(ForgeRegistries.java:42) ~[ForgeRegistries.class:?]
at net.minecraft.entity.EntityList.func_191302_a(EntityList.java:136) ~[vi.class:?]
at net.minecraft.stats.StatList.func_151182_a(StatList.java:304) ~[qs.class:?]
at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:450) ~[vi$a.class:?]
at net.minecraft.entity.EntityList.func_191305_a(EntityList.java:431) ~[vi.class:?]
at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:360) ~[vi.class:?]
at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:505) ~[ni.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
... 12 more
Caused by: java.lang.NullPointerException
at org.spongepowered.mod.registry.SpongeForgeVillagerRegistry.syncProfession(SpongeForgeVillagerRegistry.java:78) ~[SpongeForgeVillagerRegistry.class:1.12.2-2705-7.1.0-BETA-3182]
at org.spongepowered.mod.registry.SpongeForgeVillagerRegistry.registerForgeCareer(SpongeForgeVillagerRegistry.java:130) ~[SpongeForgeVillagerRegistry.class:1.12.2-2705-7.1.0-BETA-3182]
at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.handler$registerForgeCareer$bbl000(VillagerRegistry.java:569) ~[VillagerRegistry$VillagerProfession.class:?]
at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.register(VillagerRegistry.java:218) ~[VillagerRegistry$VillagerProfession.class:?]
at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.access$500(VillagerRegistry.java:197) ~[VillagerRegistry$VillagerProfession.class:?]
at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerCareer.<init>(VillagerRegistry.java:249) ~[VillagerRegistry$VillagerCareer.class:?]
at net.minecraftforge.fml.common.registry.VillagerRegistry.init(VillagerRegistry.java:151) ~[VillagerRegistry.class:?]
at net.minecraftforge.fml.common.registry.VillagerRegistry.<init>(VillagerRegistry.java:59) ~[VillagerRegistry.class:?]
at net.minecraftforge.fml.common.registry.VillagerRegistry.<clinit>(VillagerRegistry.java:53) ~[VillagerRegistry.class:?]
at net.minecraftforge.fml.common.registry.ForgeRegistries.init(ForgeRegistries.java:62) ~[ForgeRegistries.class:?]
at net.minecraftforge.fml.common.registry.ForgeRegistries.<clinit>(ForgeRegistries.java:42) ~[ForgeRegistries.class:?]
at net.minecraft.entity.EntityList.func_191302_a(EntityList.java:136) ~[vi.class:?]
at net.minecraft.stats.StatList.func_151182_a(StatList.java:304) ~[qs.class:?]
at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:450) ~[vi$a.class:?]
at net.minecraft.entity.EntityList.func_191305_a(EntityList.java:431) ~[vi.class:?]
at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:360) ~[vi.class:?]
at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:505) ~[ni.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
... 12 more
```

No crash-report available because the server crashes before its able to dump, server log located here: https://gist.github.com/iamtpage/cce239903b7e2cf8d1d1f251fed3467f

**Comment by gabizou** [comment]
Also, disable foam fix block pos modification in the config (noticed from the log).

**Comment by flamechair** [comment]
Done, same error.

**Comment by flamechair** [comment]
Hi @gabizou 

While testing this the server can indeed start up, but now when villages spawn this error appears:

```
/****************************************************************/
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Sponge Forge Career Mismatch! */
> [21:03:42] [Server thread/ERROR] [Sponge]: /****************************************************************/
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Sponge is attemping to recover from a mismatch from a Forge mod provided */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* VillagerCareer and Sponge's Career implementation. */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Due to the issue, Sponge is printing out all this information to assist sponge */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* resolving the issue. Please open an issue on github for SpongeForge */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Forge Profession : smith */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Career 0 : armor */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Career 1 : weapon */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Career 2 : tool */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Sponge Profession : minecraft:smith */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* */
> [21:03:42] [Server thread/ERROR] [Sponge]: /* Villager career id attempted: 1 */
> [21:03:42] [Server thread/ERROR] [Sponge]: /****************************************************************/
```

Is this a separate issue or does this fall under this issue?

**Comment by gabizou** [comment]
Still falls under this issue.

**Comment by gabizou** [comment]
Should be fixed in SpongeForge 3186 (currently building on Jenkins to deploy). 

https://github.com/SpongePowered/SpongeForge/commit/4780cb07edaa9f4e19ab47eb5fc32fb0ebd5c33e

**Comment by flamechair** [comment]
Can confirm! Tested 5 village generations, 0/5 caused errors to report in the console. Thanks!
