### ISSUE TITLE
Crash during the chunk generation of the overworld (Lost Cities)

### ISSUE THREAD

**Issue by Vitali8** [SpongePowered/SpongeForge#2258]
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3204
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: 1.8.0_162
- Operating System: Linux

- Mods: baubles, guide api, blood magic, blood arsenal, applied energistics2, bdlib, ae2stuff, better questing, biomes o plenty, codechickenlib, redstoneflux, brandonscore, ic2, sonarcore, calculator, jei, crafttweaker, customnpcs, draconic evolution, endercore, thaumcraft, forestry, mantle, TConstruct, enderIO, ender zoo, extrautils2, hardcore darkness, immersive engineering, immersive cables, immersive petroleum, immersive tech, ironchest, jeibees, _lostcities_, nei, better questing_npc integration, nuclearcraft, flammpfeil.slashblade, better questing_standard,  thaumkatana, twilightforest, wawla.
- Plugins: luckperms, nucleus, economylite, magibridge.

**Issue Description**
During the server startup and attempt to generate a world, crash occurs, when I select Lost City as a generator for the overworld in config (level-type=lostcities_bop).
Otherwise, when the mod tries to create its own dimension by default, an error occurs that does not interrupt the server.
[Server's crash](https://gist.github.com/Vitali8/9030e792c2a58f7ee892d9fb4fdf5822).

**Comment by Sir-Will** [comment]
I get this crash when I try to create or generate the dimension in a seperate dimension:
```
java.lang.NullPointerException: Exception in server tick loop
	at mcjty.lostcities.dimensions.world.LostWorldProvider.getSaveFolder(LostWorldProvider.java:28)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:759)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:4655)
	at net.quetzi.morpheus.helpers.MorpheusEventHandler.loggedOutEvent(MorpheusEventHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1753_MorpheusEventHandler_loggedOutEvent_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:293)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:670)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:644)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:579)
	at net.minecraft.server.management.PlayerList.redirect$onFirePlayerLoggedOutCall$bba000(PlayerList.java:2226)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.lostcities.dimensions.world.LostWorldProvider.getSaveFolder(LostWorldProvider.java:28)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:759)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:4655)
	at net.quetzi.morpheus.helpers.MorpheusEventHandler.loggedOutEvent(MorpheusEventHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1753_MorpheusEventHandler_loggedOutEvent_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:293)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:670)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:644)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:579)
	at net.minecraft.server.management.PlayerList.redirect$onFirePlayerLoggedOutCall$bba000(PlayerList.java:2226)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjh000(MinecraftServer.java:4002)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)
```
spongeforge-1.12.2-2705-7.1.0-BETA-3315

**Comment by gabizou** [comment]
https://github.com/McJtyMods/LostCities/issues/142

Issue with LostCities.

**Comment by Shybella** [comment]
Same with meecreeps here https://github.com/McJtyMods/MeeCreeps/issues/44
