### ISSUE TITLE
Cyclic Spawn Seeker causes server crash with cause tracker

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2259]
Using the Spawner Seeker in the extra planets dimension causes the server to crash.

```
java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)
	at java.util.ArrayDeque.pop(ArrayDeque.java:517)
	at org.spongepowered.common.event.tracking.PhaseStack.pop(PhaseStack.java:76)
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:202)
	at net.minecraft.world.gen.ChunkProviderServer.handler$onProvideChunkEnd$zmd000(ChunkProviderServer.java:698)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbg000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)
	at java.util.ArrayDeque.pop(ArrayDeque.java:517)
	at org.spongepowered.common.event.tracking.PhaseStack.pop(PhaseStack.java:76)
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:202)
	at net.minecraft.world.gen.ChunkProviderServer.handler$onProvideChunkEnd$zmd000(ChunkProviderServer.java:698)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbg000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: DIM-15
	All players: 1 total; [EntityPlayerMP['_Kaasblokje_'/1281651, l='DIM-15', x=-5358.08, y=80.99, z=903.10]]
```
Log: https://gist.github.com/Sir-Will/0400d43d70ff7f1e00b932493a88d0f2

spongeforge-1.12.2-2705-7.1.0-BETA-3233
forge-1.12.2-14.23.4.2705-universal
Cyclic-1.12.2-1.15.8
GalacticraftCore-1.12.2-4.0.1.177
Galacticraft-Planets-1.12.2-4.0.1.177
ExtraPlanets-1.12.2-0.3.8

**Comment by Aaron1011** [comment]
There's at least one issue here - possibly more. I've opened an issue for the initial stacktrace, which is due to Cyclic modifying the world off the main thread: https://github.com/PrinceOfAmber/Cyclic/issues/863

**Comment by wormzjl** [comment]
I'm getting a console spam which might be related
https://gist.githubusercontent.com/wormzjl/a13a9b67a04567bde4b0e1a5f722a515/raw/49dcb736ed435c1c338e4e3921475dd5f6fa3659/gistfile1.txt

**Comment by Aaron1011** [comment]
@wormzjl  That appears to be the same issue

**Comment by gabizou** [comment]
@wormzjl Looking over the log, it's going to be an expensive test (making exceptions for every PhaseState entry, I need you to enable `generate-stacktrace-per-phase` in the tracker config.

Provide the new log at that point when you start seeing the spam from runaway phases. 

What it increasingly looks like though is that someone is loading chunks async and syncing them back to the world in another thread, which ends up causing dirty stacks on sponge's end, therefor causing the runaway. 

I can add some better thread checks, but it does come down to the point that someone (a mod) is trying to load chunks asynchronously on their own and not using the proper methods to do so as Forge somewhat exposes that functionality.

**Comment by gabizou** [comment]
@Sir-Will If you want to give it a try, there's a new build with better thread checks for async block changes that sponge will properly warn about async block changes, and prevent spamming issues in these cases.

**Comment by Sir-Will** [comment]
@gabizou It didn't crash so far, going to unban the item and see if players are able to get it to crash.

**Comment by gabizou** [comment]
IT won't crash with the newer builds now as it will simply print out the exception stack trace and whatnot, but it will explicitly ignore the requested block change and return `false` (though, almost no one ever checks for the return value except some rare instances of vanilla code).
