### ISSUE TITLE
Sponge Logging

### ISSUE THREAD

**Issue by sfxworks** [SpongePowered/SpongeForge#2262]
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3151
- Forge version:  14.23.4.2705
- Java version: [java 8 alpine](https://hub.docker.com/_/openjdk/)
- Operating System: [Container-Optimized OS](https://cloud.google.com/container-optimized-os/docs/)

- Plugins/Mods:
```
> sponge mods
Mods (94): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Solar Panels, Ambience, Applied Energistics 2, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Brandon's Core, BuildCraft, BuildCraft Compat, BuildCraft Lib, CoFH Core, CoFH World, CodeChicken Lib, ComputerCraft, CustomNPCs, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Ex Compressum, Ex Nihilo Creatio, Extra Cells 2, Extra Planets, Extreme Reactors, Faction Mod, FoamFix, Galacticraft Core, Galacticraft Planets, ICBM-Classic, Immersive Engineering, IndustrialCraft 2, Inventory Tweaks, Iron Chest, It's the little things, JourneyMap, Just Enough Items, MJRLegendsLib, Malisis Advert, MalisisCore, Mantle, Mekanism, MekanismGenerators, MekanismTools, Micdoodle8 Core, NoMoreRecipeConflict, NuclearCraft, OMLib, Open Glider, Open Modular Turrets, OpenBlocks, OpenModsLib, OpenModsLib Core, PlusTiC, Quark, Random Things, Reborn Core, Redstone Arsenal, Redstone Flux, SG Craft, Simply Jetpacks 2, Steve's Carts 2, TESLA, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, What Are We Looking At, Wireless Crafting Terminal 2, Zero CORE, p455w0rd's Library
> sponge plugins
Plugins (28): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Aliases, BattleLog, ClearMob, CraftBook, FriskStick, Holograms, ItemChat, LuckPerms, MMCReboot, Nucleus, PayRespects, Plan, ProjectCore, ProjectPortals, ProjectWorlds, ServerListPlus, SleepVote, Total Economy, Vigilate, VoxelSniper, Web-API, Web-API API, WorldEdit, spark
```

**Issue Description**

When enabling logging for chunk loading/unloading in the config for the overworld, it outputs, but I get a lot more STDERR output now... 

I am attempting to gather more insight on what is causing performance issues. 

```
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (-8, 12 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (-3, 29 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (7, 26 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (13, 25 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (2, 29 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (-8, 7 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (-491, 448 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (4, 9 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logChunkGCQueueUnload(SpongeHooks.java:229)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.world.WorldServer.doChunkGC(WorldServer.java:2846)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.handler$onUpdateTimeLightAndEntitiesHead$zjm000(MinecraftServer.java:3784)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at java.lang.Thread.run(Thread.java:748)
[01:11:02] [Server thread/INFO] [Sponge]: Chunk GC Queued Chunk At [0] (-5, 27 for unload)
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]: java.lang.Throwable
[01:11:02] [Server thread/INFO] [STDERR]: [org.spongepowered.common.util.SpongeHooks:logStack:102]:     at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:101)
```

**Comment by phit** [comment]
set `log-stacktraces` to false in your global.conf

**Comment by ryantheleach** [comment]
This is by (possibly lazy) design, we could look into moving it from STDERR, to SPONGE, but enabling stack trace logging for Chunk GC, it's literally to enable this extra output, and the mechanism for doing so, is by using throwables to grab and print the stack for us.

Also note that the logging level remains at INFO, even though the logger is set to STDERR but it's using the logging frameworks options for determining the correct logging level for a raw throwable.

This method of logging the stack traces is ~ 3 years old in the codebase.

The Stack Traces can be disabled specifically by using the config option @phit mentions above.
