### ISSUE TITLE
java.lang.IndexOutOfBoundsException: writerIndex(25990) Server Crash

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2276]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3263.jar
- Forge version: 2709
- Java version:  1.8 update 171
- Operating System: Windows Server 2012 R2

- Plugins/Mods: Mods (156): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Advanced Generators, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FastWorkbench, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MeeCreeps, Mercurius, MineTogether, MineTogetherServer, Mod Tweaker, Morph, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PneumaticCraft: Repressurized, PortalGun, Psi, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

Plugins (26): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Broadcast, CarrotShop, DailyRewards, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LuckPerms, MMCRestrict, MagiBridge, NuVotifier, Nucleus, PayDay, Plan, SeriousVote, ServerListPlus, TreeDestroyage, Unity, WorldEdit, spark

**Issue Description**

Not sure how to reproduce. Randomly happened with players online. I am not even sure if this is a Sponge issue.

https://pastebin.com/raw/W0yzvUf6

**Comment by Shybella** [comment]
https://pastebin.com/raw/xeeUagKj

**Comment by Shybella** [comment]
I am not experiencing this anymore. I will close and reopen if the issue comes up again.

**Comment by Shybella** [comment]
https://pastebin.com/raw/1tFRQTJH

SF: 3311

**Comment by Shybella** [comment]
Happened again today.

**Comment by Aaron1011** [comment]
@Shybella This will be fixed in the next SpongeForge build.

Surprisingly, this was actually a *Vanilla* bug. However, it would only be triggered when a large amount of data was stored per chunk (e.g. a large number of block ids in use in a particular chunk).

**Comment by Shybella** [comment]
https://pastebin.com/raw/0DUUmyJy

Back again on SF: 3328

**Comment by Aaron1011** [comment]
Another crash was reported on Discord: https://pastebin.com/EiDSRygE

**Comment by Aaron1011** [comment]
@Shybella: I've added some debugging information to the latest SpongeForge build. The next time you get an exception, the stacktrace should tell you the offending chunk.

**Comment by Shybella** [comment]
I will be placing this on live today. The crash is really rare so it may take some time. Or the chunk rarely gets loaded.

**Comment by XakepSDK** [comment]
From discord: https://hastebin.com/acekizezek.pl

**Comment by ryantheleach** [comment]
Some people have been reporting this issue that have JEID installed.

For reference:

https://minecraft.curseforge.com/projects/jeid

>JustEnoughIDs is a lightweight mod that removed the block, item, and biome ID limits by using the 1.13 chunk format in 1.12.

https://github.com/DimensionalDevelopment/JustEnoughIDs/tree/master/src/main/java/org/dimdev/jeid

Which mixes into the same classes we do, so things might get a little fuzzy, or maybe our fix for vanilla breaks their mod?

https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/master/src/main/java/org/dimdev/jeid/mixin/core/MixinBlockStateContainer.java

**Comment by Aaron1011** [comment]
The endless parade of SPacketChunkData bugs continues:

So far, I've identified three distinct bugs, all of which have the potential to cause this kind of crash:

* A Vanilla bug, which I've patched in Sponge [here](https://github.com/SpongePowered/SpongeCommon/blob/cd5ff6beb7850b7b75451b35530a3b18a99a935e/src/main/java/org/spongepowered/common/mixin/core/world/chunk/MixinBlockStateContainer.java#L76-L95)
* A JustEnoughIDs bug, which I've fixed in https://github.com/DimensionalDevelopment/JustEnoughIDs/commit/92a54da42fc89089dacd15a1bf4edf5dffc44ba4
* A bug with a currently unknown cause, reported on Discord: https://gist.githubusercontent.com/Aaron1011/d6f8c3bf4718d877e4b6f164bb27b94c/raw/ec32b91550d18f5ff9ee9e3547ced357a323903e/gistfile1.txt

The last crash is definitely a separate bug - the user is running a build that contains my fix for the first bug, and is not running JustEnoughIDs at all.

**Comment by ryantheleach** [comment]
@Aaron1011 That vanilla bug might be worth PR'ing to forge, you might get more eyes over it.

**Comment by Shybella** [comment]
Yeah, it's back everyday now. Nothing abnormal is appearing in the chunks. Most of them are empty normal generated chunks.

```Time: 8/19/18 12:50 PM
Description: Exception ticking world

java.lang.RuntimeException: Exception creating chunk packet for chunk at '2 -345'!
	at net.minecraft.network.play.server.SPacketChunkData.redirect$onExtractChunkData$zja000(SourceFile:547)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:40)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: writerIndex(12602) + minWritableBytes(8) exceeds maxCapacity(12605): UnpooledHeapByteBuf(ridx: 0, widx: 12602, cap: 12605/12605)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:275)
	at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:1000)
	at net.minecraft.network.PacketBuffer.writeLong(PacketBuffer.java:1069)
	at net.minecraft.network.PacketBuffer.func_186865_a(PacketBuffer.java:128)
	at net.minecraft.world.chunk.BlockStateContainer.func_186009_b(BlockStateContainer.java:126)
	at net.minecraft.network.play.server.SPacketChunkData.func_189555_a(SourceFile:122)
	at net.minecraft.network.play.server.SPacketChunkData.redirect$onExtractChunkData$zja000(SourceFile:545)
	... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.network.play.server.SPacketChunkData.redirect$onExtractChunkData$zja000(SourceFile:547)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:40)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)```

**Comment by Shybella** [comment]
Happening again in a empty area. This is happening randomly there is not a pattern to the crashes.

```Time: 8/23/18 12:09 PM
Description: Exception ticking world

java.lang.RuntimeException: Exception creating chunk packet for chunk at '-510 574'!
	at net.minecraft.network.play.server.SPacketChunkData.redirect$onExtractChunkData$zja000(SourceFile:547)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:40)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: writerIndex(27062) + minWritableBytes(8) exceeds maxCapacity(27065): UnpooledHeapByteBuf(ridx: 0, widx: 27062, cap: 27065/27065)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:275)
	at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:1000)
	at net.minecraft.network.PacketBuffer.writeLong(PacketBuffer.java:1069)
	at net.minecraft.network.PacketBuffer.func_186865_a(PacketBuffer.java:128)
	at net.minecraft.world.chunk.BlockStateContainer.func_186009_b(BlockStateContainer.java:126)
	at net.minecraft.network.play.server.SPacketChunkData.func_189555_a(SourceFile:122)
	at net.minecraft.network.play.server.SPacketChunkData.redirect$onExtractChunkData$zja000(SourceFile:545)
	... 9 more

**Comment by sfxworks** [comment]
My issue referenced by Shybella seems related.

**Comment by Aaron1011** [comment]
@Shybella: Can you upload your entire crash report?

**Comment by Shybella** [comment]
https://pastebin.com/raw/esyB0zUL

Sent this one because of the phasetracker error others don't have it

**Comment by Aaron1011** [comment]
@Shybella: After taking a look at all of the coremods you're running, I didn't find any that even touched the relevant classes (SPacketChunkData and net.minecraft.world.chunk.BlockStateContainer).

At this point, there are two possibilities:

* I've missed something, and one of those coremods actually modifies one of those classes
* There's yet another Vanilla bug to deal with.

**Comment by Aaron1011** [comment]
@Shybella: Are you able to join IRC/Discord to discuss this further?

**Comment by Shybella** [comment]
Yes, I am XXMINECRAFTGODXX.

**Comment by Shybella** [comment]
Reference https://github.com/SpongePowered/SpongeForge/issues/2405

**Comment by phit** [comment]
closing in favor of the newer issue
