### ISSUE TITLE
No block drops on mining 

### ISSUE THREAD

**Issue by Y0ungSandwich** [SpongePowered/SpongeForge#2300]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3293
- Forge version: 1.12.2-2705
- Java version: 8
- Operating System:Centos

- Plugins/Mods: Nucleus, Villager Shops, Grief Prevention, EconomyLite, LuckPerms

Mining/Breaking any block destroys the block but does not drop an item.

https://gist.github.com/Y0ungSandwich/f73ee066a3f7648817bdef8244bb2177

**Comment by Shybella** [comment]
lots of Phase Tracker errors.

Does this happen on build 3292?

**Comment by Y0ungSandwich** [comment]
It is indeed happening in 3292 as well as on 3291

**Comment by gabizou** [comment]
These aren't the phase tracker errors that I'm used to seeing. I see a lot of spam from:
```
[16:38:10] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3293]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjh000(MinecraftServer.java:3987) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_171]
	at astikoor.packets.SPacketActionKey$ActionKeyPacketHandler.lambda$onMessage$1(SPacketActionKey.java:44) ~[SPacketActionKey$ActionKeyPacketHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
```
Which the last bit is the actual problem with the mod's packet handling. Not sure what mod `astikoor.packets.SPacketActionKey` comes from, but that's what's causing the spam. Maybe a recent mod update?

**Comment by Y0ungSandwich** [comment]
Not in the past few weeks and this issue only started when I updated to the latest build this afternoon seeing if there was a fix already for https://github.com/SpongePowered/SpongeForge/issues/2301

**Comment by bloodmc** [comment]
Latest SF working fine after forge event refactor.

https://github.com/SpongePowered/SpongeForge/commit/59ffec9539cff0462c395c2a2273ba6dd7fb370f
