### ISSUE TITLE
Error: "Completing incorrect phase" - "state engine was in incorrect state"

### ISSUE THREAD

**Issue by ylluminate** [SpongePowered/SpongeForge#2303]
SpongeForge : 1.12.2-2705-7.1.0-BETA-3206
Minecraft Forge : 14.23.4.2705
Java version: 1.8.0_171
OS: Ubuntu 18.04

Got this near the end
```
[23:48:36] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
```

Performed an upgrade from an older version of Sponge and Forge and then during the world load the following error occurred wherein it instructed me to report it:
```
[23:48:31] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for level 11 (oldworld)
[23:48:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 13%
[23:48:36] [Server thread/ERROR] [Sponge]: /*******************************************************************************************************************/
[23:48:36] [Server thread/ERROR] [Sponge]: /*                                           Completing incorrect phase                                            */
[23:48:36] [Server thread/ERROR] [Sponge]: /*******************************************************************************************************************/
[23:48:36] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system is very dependent on knowing when a change to any world                                */
[23:48:36] [Server thread/ERROR] [Sponge]: /* takes place, however, we are attempting to complete a "phase" other than the one                                */
[23:48:36] [Server thread/ERROR] [Sponge]: /* we most recently entered. This is an error usually on Sponge's part, so a report                                */
[23:48:36] [Server thread/ERROR] [Sponge]: /* is required on the issue tracker on GitHub.                                                                     */
[23:48:36] [Server thread/ERROR] [Sponge]: /*******************************************************************************************************************/
[23:48:36] [Server thread/ERROR] [Sponge]: /* Expected to exit phase: GenerationPhase{}{PopulatorGenerationPhaseState:POPULATOR_RUNNING}                      */
[23:48:36] [Server thread/ERROR] [Sponge]: /* But instead found phase: GenerationPhase{}{WorldSpawnerPhaseState:WORLD_SPAWNER_SPAWNING}                       */
[23:48:36] [Server thread/ERROR] [Sponge]: /* StackTrace:                                                                                                     */
[23:48:36] [Server thread/ERROR] [Sponge]: /* java.lang.Exception: null                                                                                       */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:275)   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:188)                   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:439)                           */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:252) */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)                                              */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)                                               */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)                     */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3589)                            */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:820)                */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:762)                            */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3541)                                */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)                       */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)                                          */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Thread.java:748)                                                                       */
[23:48:36] [Server thread/ERROR] [Sponge]: /*  Phases Remaining:                                                                                              */
[23:48:36] [Server thread/ERROR] [Sponge]: /*   - Phase: GenerationPhase{}{WorldSpawnerPhaseState:WORLD_SPAWNER_SPAWNING}                                     */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                    */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - Source: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}  */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*   - Phase: GenerationPhase{}{PopulatorGenerationPhaseState:POPULATOR_RUNNING}                                   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                    */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - PopulatorType: SpongePopulatorType{id=minecraft:animal, name=animal, modid=minecraft}                     */
[23:48:36] [Server thread/ERROR] [Sponge]: /*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                         */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                    */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                         */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                    */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                         */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                    */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - Source: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}  */
[23:48:36] [Server thread/ERROR] [Sponge]: /*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
[23:48:36] [Server thread/ERROR] [Sponge]: /*                                                                                                                 */
[23:48:36] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                              */
[23:48:36] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-SNAPSHOT-d453c3e                                                                              */
[23:48:36] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2705-7.1.0-BETA-3206                                                                       */
[23:48:36] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.4.2705                                                                                  */
[23:48:36] [Server thread/ERROR] [Sponge]: /*******************************************************************************************************************/
> /*******************************************************************************************************************/
/*                                           Completing incorrect phase                                            */
/*******************************************************************************************************************/
/* Sponge's tracking system is very dependent on knowing when a change to any world                                */
/* takes place, however, we are attempting to complete a "phase" other than the one                                */
/* we most recently entered. This is an error usually on Sponge's part, so a report                                */
/* is required on the issue tracker on GitHub.                                                                     */
/*******************************************************************************************************************/
/* Expected to exit phase: GenerationPhase{}{PopulatorGenerationPhaseState:POPULATOR_RUNNING}                      */
/* But instead found phase: GenerationPhase{}{WorldSpawnerPhaseState:WORLD_SPAWNER_SPAWNING}                       */
/* StackTrace:                                                                                                     */
/* java.lang.Exception: null                                                                                       */
/*     org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:275)   */
/*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:188)                   */
/*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:439)                           */
/*     org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:252) */
/*     net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)                                              */
/*     net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)                                               */
/*     net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)                     */
/*     net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3589)                            */
/*     org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:820)                */
/*     org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:762)                            */
/*     net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3541)                                */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)                       */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)                                          */
/*     java.lang.Thread.run(Thread.java:748)                                                                       */
/*  Phases Remaining:                                                                                              */
/*   - Phase: GenerationPhase{}{WorldSpawnerPhaseState:WORLD_SPAWNER_SPAWNING}                                     */
/*     Context:                                                                                                    */
/*     - Source: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}  */
/*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
/*   - Phase: GenerationPhase{}{PopulatorGenerationPhaseState:POPULATOR_RUNNING}                                   */
/*     Context:                                                                                                    */
/*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
/*     - PopulatorType: SpongePopulatorType{id=minecraft:animal, name=animal, modid=minecraft}                     */
/*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                         */
/*     Context:                                                                                                    */
/*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
/*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                         */
/*     Context:                                                                                                    */
/*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
/*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                         */
/*     Context:                                                                                                    */
/*     - Source: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}  */
/*     - World: WorldServer{Name=oldworld, DimensionId=11, DimensionType=minecraft:overworld, DimensionTypeId=0}   */
/*                                                                                                                 */
/* Minecraft : 1.12.2                                                                                              */
/* SpongeAPI : 7.1.0-SNAPSHOT-d453c3e                                                                              */
/* SpongeForge : 1.12.2-2705-7.1.0-BETA-3206                                                                       */
/* Minecraft Forge : 14.23.4.2705                                                                                  */
/*******************************************************************************************************************/
[23:48:36] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.world.DifficultyInstance.func_180169_a(SourceFile:83) ~[ua.class:?]
	at net.minecraft.world.DifficultyInstance.<init>(SourceFile:19) ~[ua.class:?]
	at net.minecraft.world.World.func_175649_E(World.java:3834) ~[amu.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:292) ~[anb.class:?]
	at org.spongepowered.common.world.gen.populators.AnimalPopulator.populate(AnimalPopulator.java:51) ~[AnimalPopulator.class:1.12.2-2705-7.1.0-BETA-3206]
	at org.spongepowered.api.world.gen.Populator.populate(Populator.java:97) ~[Populator.class:1.12.2-2705-7.1.0-BETA-3206]
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:247) ~[SpongeChunkGeneratorForge.class:1.12.2-2705-7.1.0-BETA-3206]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3589) ~[MinecraftServer.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:820) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3206]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:762) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3206]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3541) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[23:48:36] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/minecraft/server/./crash-reports/crash-2018-07-13_23.48.36-server.txt
[23:48:36] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server

...

[23:48:36] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[23:48:36] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[23:48:36] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[23:48:36] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
```

**Comment by gabizou** [comment]
Once build 3304 is published from jenkins, can you give that a try (maybe not on production, as the build number jump is quite high).

**Comment by ylluminate** [comment]
Thanks so much @gabizou. I'll give it a go. Is this going to go into the 1.12.2 branch?

**Comment by gabizou** [comment]
This is in `stable-7` branch.
