### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by IronworksProductions** [SpongePowered/SpongeForge#2306]
**I am currently running**

- SpongeForge version: latest
- Forge version: 2705
- Java version: 1.8
- Operating System:ubuntu

- Plugins/Mods:[1.12.x] SecurityCraft v1.8.4.1.jar
[1.12]SimpleBedrolls-1.2.1.jar
1.12.2
ActuallyAdditions-1.12.2-r133.jar
ActuallyBaubles-1.12-1.1.jar
AdvancedRocketry-1.12.2-1.4.0-88-universal.jar
adventurepack-1.5.jar
AkashicTome-1.2-10.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
AppleSkin-mc1.12-1.0.9.jar
appliedenergistics2-rv5-stable-11.jar
AppliedFluidics-1.12.2-2.0.2.jar
Aroma1997Core-1.12.2-2.0.0.0.b148.jar
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b68.jar
astralsorcery-1.12.2-1.8.5.jar
AutoRegLib-1.3-16.jar
Avaritia-1.12-3.2.0.13-universal.jar
AvaritiaTweaks-1.12.2-1.1.jar
badwithernocookiereloaded-1.12.2-2.12.jar
base-1.12.2-3.7.1.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
bedpatch-2.2-1.12.2.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
BetterFps-1.4.8.jar
BetterQuesting-3.5.256.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
binnie-mods-1.12.2-2.5.0.154.jar
blockcraftery-0.1.3.jar
BloodMagic-1.12.2-2.2.10-93.jar
Bookshelf-1.12.2-2.3.539.jar
Botania r1.10-354.jar
BrandonsCore-1.12-2.4.0.152-universal.jar
Ceramics-1.12-1.3.4.jar
Chameleon-1.12-4.1.3.jar
ChanceCubes-1.12.2-3.1.0.217.jar
Chisel-MC1.12.2-0.2.0.31.jar
CLib-1.0.2.31-universal.jar
Clumps-3.0.0.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
CoFHCore-1.12.2-4.3.10.5-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
CommonCapabilities-1.12-1.4.0.jar
ComputerCraft1.80pr1.jar
Controlling-3.0.6.jar
CraftingTweaks_1.12.2-8.1.8.jar
CraftTweaker2-1.12-4.1.6.jar
CTM-MC1.12-0.2.3.12.jar
cucumber-1.12-1.1.0.jar
CustomBackgrounds-MC1.12-1.1.1.jar
CustomMainMenu-MC1.12.2-2.0.8.jar
CyclopsCore-1.12.2-0.11.5.jar
Dalek Mod
Dalek-Mod-Update-48.jar
DankNull-1.12-1.4.33.jar
DarkUtils-1.12.2-1.8.207.jar
DefaultOptions_1.12.2-9.2.5.jar
diethopper-1.1.jar
DiscordSuite-2.0.0.jar
dismantler-0.1.jar
Draconic-Evolution-1.12-2.3.10.284-universal.jar
ElevatorMod-1.12.2-1.3.6.jar
elulib-0.1.12.jar
EnchantingTable-1.12-1.1.2.jar
EnderCore-1.12.2-0.5.18.jar
EnderIO-1.12.2-5.0.20.jar
EnderStorage-1.12.2-2.4.2.126-universal.jar
endertanks-1.12.0-1.6.5.jar
environmentaltech-1.12.2-2.0.9c.jar
etlunar-1.12.2-2.0.9a.jar
ExtraRails-1.12-1.3.0.jar
extrautils2-1.12-1.7.5.jar
ExtremeReactors-1.12.2-0.4.5.48.jar
FastWorkbench-1.12.2-1.3.1.jar
fluxnetworks-1.12.2-3.0.8.jar
foamfix-0.9.9.1-1.12.2-anarchy.jar
forestry_1.12.2-5.8.0.259.jar
Forgelin-1.6.0.jar
ForgeMultipart-1.12.2-2.4.2.60-universal.jar
FTBLib-5.0.0.14.jar
FTBUtilities-5.0.0.11.jar
FullscreenWindowed-1.12-1.6.0.jar
gendustry-1.6.5.8-mc1.12.2.jar
Guide-API-1.12-2.1.5-60.jar
HammerCore-1.12.2-2.0.0.3.jar
Harvest-1.12-1.2.6-18.jar
Hwyla-1.8.25-B40_1.12.jar
IBEEditor-1.12.2-1.0.0-alpha5.jar
ICBM-classic-1.12.2-3.1.0b38.jar
ImmersiveEngineering-0.12-80.jar
immersivepetroleum-1.12.2-1.1.9.jar
industrialcraft-2-2.8.73-ex112.jar
IndustrialWires-1.6-25.jar
IntegratedDynamics-1.12.2-0.11.9.jar
IntegratedTunnels-1.12.2-1.5.5.jar
InventoryTweaks-1.64-dev.jar
IronBackpacks-1.12.2-3.0.5-6.jar
ironchest-1.12.2-7.0.40.824.jar
itemscroller-1.12.0-0.11.0.jar
itlt-1.12-1.0.0.jar
jei_1.12.2-4.8.5.159.jar
jeibees-0.9.0.5-mc1.12.2.jar
jeiintegration_1.12.2-1.5.1.36.jar
journeymap-1.12.2-5.5.2.jar
LibVulpes-1.12.2-0.2.8-29-universal.jar
LLOverlayReloaded-1.1.4-mc1.12.jar
Mantle-1.12-1.3.1.21.jar
MapMakingTools-1.12-2.5.0.103-universal.jar
MatterOverdrive-1.12.2-0.6.0.157-universal.jar
mcef-1.12.2-0.9.jar
mcjtylib-1.12-2.6.7.jar
MCMultiPart-2.5.1.jar
Mekanism-1.12.2-9.4.13.349.jar
MekanismGenerators-1.12.2-9.4.13.349.jar
MekanismTools-1.12.2-9.4.13.349.jar
metamorph-1.1.5-1.12.2.jar
Morph-o-Tool-1.2-16.jar
Morpheus-1.12-3.3.2.jar
MrTJPCore-1.12.2-2.1.3.35-universal.jar
MTLib-3.0.4.jar
mysticalagradditions-1.12-1.2.8.jar
mysticalagriculture-1.12-1.6.9.jar
natura-1.12.2-4.3.2.42.jar
NetherPortalFix_1.12.1-5.3.13.jar
NoMobSpawningOnTrees-1.2.1-mc1.12.jar
NotEnoughIDs-1.5.4.2.jar
NotEnoughItems-1.12.2-2.4.1.233-universal.jar
NuclearCraft-2.10j--1.12.2.jar
oeintegration-2.3.2.jar
omlib-1.12.2-3.0.0-140.jar
ompd-1.12.2-3.0.0-35.jar
OpenBlocks-1.12.2-1.7.6.jar
OpenComputers-MC1.12.2-1.7.2.67.jar
OpenGlider-1.12.1-1.1.0.jar
OpenModsLib-1.12.2-0.11.5.jar
openmodularturrets-1.12.2-3.0.0-243.jar
OreExcavation-1.4.113.jar
p455w0rdslib-1.12-2.0.29.jar
Placebo-1.12.2-1.3.2.jar
practicallogistics2-1.12.2-3.0.1.jar
ProjectE-1.12-PE1.2.0.jar
ProjectRed-1.12.2-4.9.1.92-Base.jar
ProjectRed-1.12.2-4.9.1.92-compat.jar
ProjectRed-1.12.2-4.9.1.92-fabrication.jar
ProjectRed-1.12.2-4.9.1.92-integration.jar
ProjectRed-1.12.2-4.9.1.92-lighting.jar
ProjectRed-1.12.2-4.9.1.92-mechanical.jar
ProjectRed-1.12.2-4.9.1.92-world.jar
PTRLib-1.0.2.jar
questbook-3.1.1-1.12.jar
QuickLeafDecay-MC1.12.1-1.2.4.jar
randompatches-1.12.2-1.1.0.0.jar
RandomThings-MC1.12.2-4.1.5.jar
randomtweaks-1.12.2-1.19.0.0.jar
rangedpumps-0.5.jar
ReAuth-3.5.2.jar
RebornCore-1.12.2-3.6.14.229-universal.jar
RebornStorage-1.12.2-3.0.5.41.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
refined_avaritia-1.12.2-2.0.jar
refinedstorage-1.5.32.jar
refinedstorageaddons-0.2.jar
ResourceLoader-MC1.12.1-1.5.3.jar
rftools-1.12-7.33.jar
rftoolsctrl-1.12-1.8.1.jar
rftoolsdim-1.12-5.53.jar
rftoolspower-1.12-0.1.1.jar
SBM-WoodenShears-1.12-0.0.1b8.jar
secretroomsmod-1.12.2-5.6.2.jar
SGCraft-1.3-mc1.12.2.jar
SGExtraParts-1.12-1.4.1-34.jar
ShadowMC-1.12-3.8.0.jar
shetiphiancore-1.12.0-3.5.6.jar
SilentLib-1.12.2-2.3.2-109.jar
SilentsGems-1.12.2-2.7.2b-270.jar
SimplyConveyors-4.0.4.jar
sonarcore-1.12.2-5.0.9.jar
SoulShards-TOW-1.12-2.7.6-56.jar
StandardExpansion-3.4.141.jar
StevesCarts-1.12.2-2.4.18.92.jar
stg-1.12.2-1.2.3.jar
StorageDrawers-1.12.2-5.3.6.jar
TConstruct-1.12.2-2.9.1.65.jar
Thaumcraft-1.12.2-6.1.BETA10.jar
TheBetweenlands-3.3.9-universal.jar
ThermalCultivation-1.12.2-0.1.5.3-universal.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalExpansion-1.12.2-5.3.10.15-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar
Tinkers' Addons-1.12.1-1.0.7.jar
TinkerToolLeveling-1.12-1.0.3.jar
Toast Control-1.12.2-1.4.1.jar
TombManyGraves-1.12-4.1.0.jar
tombmanygraves2api-1.12.2-1.0.0.jar
tombmanypluginsthebetweenlands-1.0.0.jar
torchmaster_1.12.2-1.6.1.53.jar
Traverse-1.12.1-1.3.1.jar
twilightforest-1.12.2-3.7.424-universal.jar
valkyrielib-1.12.2-2.0.9b.jar
WAIM-1.0.0.jar
webdisplays-1.12.2-1.0.jar
worldedit-forge-mc1.12-6.1.8-dist.jar
WorldProtector (1.12).jar
zerocore-1.12-0.1.2.1.jar

**Issue Description**

 crash report:https://gist.github.com/nacjm/54fad731e7cd303b20262efac341239e
server log:https://gist.github.com/nacjm/69428e38a92dc694ce3c61f69469f85f

**Comment by gabizou** [comment]
Stacktrace from crash log:
```
[20:04:38] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.LootTableLoadEvent@62d4eca1:
java.lang.NullPointerException: null
	at com.swdteam.common.event.EventLoots.lootLoad(EventLoots.java:24) ~[EventLoots.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_362_EventLoots_lootLoad_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:662) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:597) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:730) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1174) [ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156) [bfv$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72) [bfv$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53) [bfv$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [minecraft_server.1.12.2.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40) [bfv.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:49) [bfv.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35) [bfv.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155) [oo.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:794) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3304]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:762) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3304]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3541) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
First line is mod code as the event is thrown from Forge (not sponge) and the mod code is crashing. Also, don't say the "latest" version, that means nothing to me. I still don't even know what version of sponge you're running (and yes, it is located in your log file, just next time use whatever spits out from `/sponge version`).
