### ISSUE TITLE
Server crashes when player entering new MystCraft world ("age")

### ISSUE THREAD

**Issue by 3TUSK** [SpongePowered/SpongeForge#2307]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3291
- Forge version: 14.23.4.2732
- Java version: OpenJDK 1.8.0_171
- Operating System: Debian

- Plugins/Mods: Bauble Of Undying, Baubles, Baubley Heart Canisters, Charset, Electroblob's Wizardry, FoamFix, FoamFixCore, Forestry, Just Enough Items, Mantle, Millenaire, Mystcraft, No World Gen 5 You, Serene Seasons, Signals, SimpleLogic, The Twilight Forest, Tinkers' Construct, Tough As Nails; LuckPerms, Nucleus

**Issue Description**  
Server crashes at the time player entering a newly created MystCraft world ("age"), by placing a new "linking book" on ground, and click the window on the right side of GUI opened. Forwarded from XCompWiz/Mystcraft-Issues#285. This issue looks similar to #2213, while the stacktrace are different, which makes hard to determine if they are indeed the same issue. Thus here is a separate issue ticket in case there is/are new issue(s) discovered.

https://paste.ubuntu.com/p/h3ms5w4MsP/

**Comment by 3TUSK** [comment]
While #2213 is closed, using SpongeForge build 3376 (`spongeforge-1.12.2-2705-7.1.0-BETA-3376.jar`) alongside with Forge 1.12.2-14.23.4.2747 still does not allow player entering new "age". When a player is trying to do so, server will hang for a uncertain period of time and crash.  

<details>
<summary>Sample log output</summary>

```
[15:14:37] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3376]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3967) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at org.spongepowered.common.world.WorldManager.getWorld(WorldManager.java:319) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3376]
        at org.spongepowered.common.world.WorldManager.createWorldProperties(WorldManager.java:393) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3376]
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:801) ~[DimensionManager.class:?]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:4641) ~[MinecraftServer.class:?]
        at com.xcompwiz.mystcraft.linking.LinkController.travelEntity(LinkController.java:48) ~[LinkController.class:?]
        at com.xcompwiz.mystcraft.item.ItemLinking.activate(ItemLinking.java:89) ~[ItemLinking.class:?]
        at com.xcompwiz.mystcraft.item.ItemAgebook.activate(ItemAgebook.java:135) ~[ItemAgebook.class:?]
        at com.xcompwiz.mystcraft.tileentity.TileEntityBookRotateable.link(TileEntityBookRotateable.java:55) ~[TileEntityBookRotateable.class:?]
        at com.xcompwiz.mystcraft.inventory.ContainerBook.processMessage(ContainerBook.java:303) ~[ContainerBook.class:?]
        at com.xcompwiz.mystcraft.network.packet.MPacketGuiMessage.lambda$onMessage$0(MPacketGuiMessage.java:65) ~[MPacketGuiMessage.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        … 7 more
```

</details>

Full crash report: https://paste.ubuntu.com/p/c7kCshtBdb/
Full `debug.log`: https://paste.ubuntu.com/p/rWwtpnnzh4/

**Comment by zhehedream** [comment]
This problem still exists on sponge 3377 with forge 2705.

**Comment by 3TUSK** [comment]
Just did a quick test, and I confirm that using SpongeForge 1.12.2-2705-7.1.0-BETA-3383 alongside with Forge 1.12.2-14.23.4.2747 does solve the issue. Can we consider this is fixed now?

**Comment by 3TUSK** [comment]
Guess we can close this for now, per XCompWiz/Mystcraft-Issues#285. Reopen when the same error reappears.
