### ISSUE TITLE
weird java.lang.NoClassDefFoundError on low-spec server

### ISSUE THREAD

**Issue by Lollyde** [SpongePowered/SpongeForge#2333]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3330
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: 
```openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
- Operating System: Ubuntu 16.04.4
- System Info: 3GB RAM, "1 vCPU" (hosting on DigitalOcean)
- Plugins/Mods:
 none, this is off of a *fresh* installation of forge

**Issue Description**

Installing forge with `java -jar forge-1.12.2-14.23.4.2705-installer.jar -installServer`
agreeing to EULA
launching the server *no mods* with `java -jar forge-1.12.2-14.23.4.2705-universal.jar`
-> server launches successfully.
stopping server
copying `spongeforge-1.12.2-2705-7.1.0-BETA-3330.jar` to the mods directory
launching the server with `java -jar forge-1.12.2-14.23.4.2705-universal.jar` again
startup process hangs for a very long time (~ 10 minutes) at `[Server thread/INFO] [Sponge]: Creating injector in stage 'PRODUCTION'`
proceeds to crash before startup is finished

**Note**

those steps do work on an upscaled server with both more ram and CPU, using the exact same files.

```
[12:33:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[12:33:21] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[12:33:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[12:33:21] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2705 for Minecraft 1.12.2 loading
[12:33:21] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_171, running on Linux:amd64:4.4.0-130-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[12:33:21] [main/INFO] [FML]: Searching /home/minecraft2/./mods for mods
[12:33:21] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.12.2-2705-7.1.0-BETA-3330.jar
[12:33:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:33:21] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[12:33:22] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/home/minecraft2/./mods/spongeforge-1.12.2-2705-7.1.0-BETA-3330.jar Service=LaunchWrapper Env=SERVER
[12:33:22] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[12:33:23] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[12:33:23] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[12:33:23] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[12:33:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:33:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:33:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:33:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:33:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[12:33:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:33:27] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[12:33:27] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@72ba28ee
[12:33:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:33:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:33:29] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[12:33:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:33:29] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[12:33:45] [main/WARN] [mixin]: Static binding violation: PRIVATE overwrite method initializeConnectionToPlayer in mixins.common.core.json:server.MixinPlayerList cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[12:33:46] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[12:34:07] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12.2
[12:34:08] [Server thread/INFO] [FML]: MinecraftForge v14.23.4.2705 Initialized
[12:34:08] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[12:34:08] [Server thread/INFO] [FML]: Replaced 1036 ore ingredients
[12:34:08] [Server thread/INFO] [Sponge]: Found mcmod.info at jar:file:/home/minecraft2/./mods/spongeforge-1.12.2-2705-7.1.0-BETA-3330.jar!/mcmod.info
[12:34:09] [Server thread/INFO] [Sponge]: Creating injector in stage 'PRODUCTION'
[12:44:39] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/spongepowered/common/data/processor/data/item/ItemFireworkEffectDataProcessor
	at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:198) ~[SpongeGameRegistry.class:1.12.2-2705-7.1.0-BETA-3330]
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:170) ~[SpongeMod.class:1.12.2-2705-7.1.0-BETA-3330]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:377) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.common.data.processor.data.item.ItemFireworkEffectDataProcessor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/common/data/processor/common/AbstractItemSingleDataProcessor
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_171]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_171]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.common.data.processor.common.AbstractItemSingleDataProcessor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_171]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_171]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 14 more
[12:45:25] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[12:45:25] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: org/spongepowered/mod/event/StateRegistry
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:559)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:855)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:507)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: org.spongepowered.mod.event.StateRegistry
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:45:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:45:48] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 6 more
[12:45:48] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.OutOfMemoryError: Java heap space
[12:45:48] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[12:45:48] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
```

**Comment by SimonFlash** [comment]
> [12:45:48] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.OutOfMemoryError: Java heap space

Though 3 GB of RAM should be sufficient, the stacktrace is quite clear. I would question whether 3 GB is actually being allocated to the JVM here, as it seems highly unlikely that you would be receiving that otherwise given that no mods are installed.

If you're looking for assistance with figuring out what's happening here, the best place is on the Sponge Discord or forums.

**Comment by Lollyde** [comment]
ah, thank you, I must have missed that line. I'll try allocating more with `-Xmx` and report back on wether it worked or not.


EDIT: 
well damn, that was it, load time was improved significantly and it loaded properly. thank you for pointing it out!
