### ISSUE TITLE
Server stop error

### ISSUE THREAD

**Issue by fcpwiz** [SpongePowered/SpongeForge#2336]
SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3320.jar
Forge version: forge-1.12.2-14.23.4.2705-universal.jar
Java version: 8 64 bit
Operating System: Linux
Plugins/Mods:
Plugins (21): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Aliases, CatClearLag, Denizen2Sponge, FoxCore, FoxGuard, GriefPrevention, Holograms, LuckPerms, MMCRestrict, MagiBridge, Nucleus, PlaceholderAPI, RankUpper, TabManager, Tattle, VoxelSniper, WorldEdit

Mods (110): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Generators, Advanced Solar Panels, Applied Energistics 2, Astral Sorcery, AutoRegLib, BD Lib, Baubles, BiblioCraft, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Botania, Chameleon, ChickenChunks, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Cucumber Library, Cyclops Core, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Energy Converters, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Fluxx Stuff, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Genetics Reborn, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Tweaks, Iron Chest, IvToolkit, Just Enough Items, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, Minecraft Multipart Plugin, MrTJPCore, Mystical Agradditions, Mystical Agriculture, OpenBlocks, OpenModsLib, OpenModsLib Core, PlusTiC, ProjectRed Core, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, Psi, RFTools, Random Things, Recurrent Complex, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, Storage Drawers, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, WanionLib, Zero CORE, projectred-expansion, projectred-relocation, projectred-transportation

**Issue Description**

I get this error when stopping the server: 

> [18:30:21] [Server Shutdown Thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@11e1eff7:
java.lang.RuntimeException: Attempt made to initialize overworld!

https://gist.github.com/fcpwiz/31645acd80c5723ecb80419a3e09c0b8

**Remapped:** https://gist.github.com/ryantheleach/6e419284f4348fb17c6433c749450055

**Comment by ryantheleach** [comment]
This might possibly be a morpheus error? 
```
[18:30:21] [Server Shutdown Thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@11e1eff7:
java.lang.RuntimeException: Attempt made to initialize overworld!
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:743) ~[DimensionManager.class:?]
at net.minecraft.server.MinecraftServer.getWorld(MinecraftServer.java:4655) ~[MinecraftServer.class:?]
at net.quetzi.morpheus.helpers.MorpheusEventHandler.loggedOutEvent(MorpheusEventHandler.java:38) ~[MorpheusEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1103_MorpheusEventHandler_loggedOutEvent_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) [EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:649) [EventBus.class:?]
at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostPlayerLoggedOutEvent(SpongeToForgeEventFactory.java:848) [SpongeToForgeEventFactory.class:1.12.2-2705-7.1.0-BETA-3320]
at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:276) [SpongeToForgeEventFactory.class:1.12.2-2705-7.1.0-BETA-3320]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:337) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3320]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:428) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3320]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3320]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3320]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3320]
at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$zim000(NetHandlerPlayServer.java:2400) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:847) [pa.class:?]
at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:453) [gw.class:?]
at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:291) [pa$2.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at net.minecraft.server.MinecraftServer.redirect$onCall$zjh000(MinecraftServer.java:3976) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.callFromMainThread(MinecraftServer.java:1383) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.addScheduledTask(MinecraftServer.java:1395) [MinecraftServer.class:?]
at net.minecraft.network.NetHandlerPlayServer.disconnect(NetHandlerPlayServer.java:287) [pa.class:?]
at net.minecraft.server.management.PlayerList.removeAllPlayers(PlayerList.java:1083) [pl.class:?]
at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:4689) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579) [MinecraftServer$4.class:?]
```

**Comment by Aaron1011** [comment]
The latest SpongeForge build contains a fix that night resolve this.

**Comment by phit** [comment]
@fcpwiz still an issue?

**Comment by fcpwiz** [comment]
Not an issue anymore with latest. Thanks!
