### ISSUE TITLE
Dungeon Mobs Reborn errors and crash

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2431]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3433
- Forge version: 14.23.4.2747
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
- Operating System: Debian 9

- Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, QuestItemHelper, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest, VirtualTool, Wasted, WorldEdit, spark
- Mods (52): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Auto Crafter, Better Questing, BiblioCraft, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Dungeon Mods, Ex Nihilo Creatio, Fishing Net Mod, Hammer Core, HoloInventory, Immersive Engineering, Immersive Tech, InstantUnify, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, Mantle, McJtyLib, Mekanism, MrCrayfish's Furniture Mod, Parachronology, QuestUtils, Quick Leaf Decay, Redstone Arsenal, Redstone Flux, Solar Flux Reborn, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

**Issue Description**
If you break a trap with blades in the creativity mode, then the console will have a lot of errors. One of the monsters attacking the player caused the crash of the server. See logs.
[logs.zip](https://github.com/SpongePowered/SpongeForge/files/2355975/logs.zip)

**Comment by gabizou** [comment]
I don't know how you're getting stack traces to show up as MCP named instead of SRG named, but your issue is a mod that is calling a client method on the server:
```
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at com.gw.dm.entity.EntityIllithid.attackEntityAsMob(EntityIllithid.java:276) ~[EntityIllithid.class:?]
```
Not a sponge issue.

**Comment by SawFowl** [comment]
@gabizou This error does not occur if Sponge is not installed..

**Comment by gabizou** [comment]
@Mr-Krab The crash that is literally about the entity calling a client only method:
```
java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
    at com.gw.dm.entity.EntityIllithid.attackEntityAsMob(EntityIllithid.java:276)
    at net.minecraft.entity.ai.EntityAIAttackMelee.checkAndPerformAttack(EntityAIAttackMelee.java:178)
    at net.minecraft.entity.ai.EntityAIAttackMelee.updateTask(EntityAIAttackMelee.java:167)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2352)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:45)
    at com.gw.dm.EntityDungeonMob.onLivingUpdate(EntityDungeonMob.java:47)
    at com.gw.dm.entity.EntityIllithid.onLivingUpdate(EntityIllithid.java:266)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2172)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:161)
    at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zlp000(WorldServer.java:2982)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:4154)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1952)
    at net.minecraft.world.World.updateEntities(World.java:6601)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:2295)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```
The method in question is `net/minecraft/entity/player/InventoryPlayer.armorItemInSlot()`, which I hate to say, is client only. 

And looking at a decompiled version of their code, it's pretty evident that the method is being called regardless whether the entity is on a server or not:

<img width="654" alt="screen shot 2018-09-06 at 2 46 13 am" src="https://user-images.githubusercontent.com/1203877/45149732-1f5dbd00-b17f-11e8-8b14-45be491e6fff.png">


The other errors that are showing up in your log are something else that I'm already working on a fix since I saw it reported. But, go ahead and try with latest again. If there's an exception specifically about entity captures spamming, then post it as a new issue please.

**Comment by SawFowl** [comment]
@gabizou Thank you. I also made a request to the developers of the mod. And for the moment, turned off the spawn of a problem mob.
