### ISSUE TITLE
1.12.2 when a player create a FTBteam the server will crash

### ISSUE THREAD

**Issue by OldKingisdie** [SpongePowered/SpongeForge#2455]
**I am currently running**

- SpongeForge version: sponge-3456
- Forge version: 2705
- Java version: java8
- Operating System:linux
- Plugins/Mods:

FTBLib-5.1.0.22
FTBUtilities-5.1.0.27

**Issue Description**

Server crash when player create a FTBteam  

```
[15:00:45] [Server thread/INFO] [nucleus]: h9ouy 执行指令: /team request_invite louisahdyer
[15:00:49] [Server thread/INFO] [nucleus]: h9ouy 执行指令: /team create h9ouy orange
[15:00:49] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'team create h9ouy orange' for source EntityPlayerMP['h9ouy'/155, l='world', x=-6734.70, y=45.00, z=-8604.30]: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:164) ~[MinecraftCommandWrapper.class:1.12.2-2705-7.1.0-BETA-3456]
	at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:145) ~[MinecraftCommandWrapper.class:1.12.2-2705-7.1.0-BETA-3456]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3456]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3456]
	at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:1083) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2705-7.1.0-BETA-3456]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlf000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3456]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
```

**Comment by phit** [comment]
update ftb utilities
