### ISSUE TITLE
 [1.12.2] A lot of warnings for BetterWithMods.

### ISSUE THREAD

**Issue by STRL1T** [SpongePowered/SpongeForge#2538]
SpongeForge version: 2768-7.1.5

Forge version: 2768

Java version: 8

Operating System: Win 10

Plugins/Mods:
Just Enogh Items
Immersive Engineering
Spongeforge
CodeChickenCore
Better With Mods
Nucleus
GriefPrevention

P.S, The author of the mod reported that these reports are not related to the mistakes of his mod.

[latest.log](https://github.com/SpongePowered/SpongeForge/files/2707596/latest.log)
the rest of the mods and plugins do not matter, because without all the mods except SpongeCore + Better With Mods, there are warnings at launch. Scares.)

**Comment by STRL1T** [comment]
P.S, The author of the mod reported that these reports are not related to the mistakes of his mod.

**Comment by phit** [comment]
I don't see any warnings thrown by Sponge?

**Comment by STRL1T** [comment]
> Я не вижу никаких предупреждений от Губки?

19:35:46] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/redstone/jungle_fence_gate
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:jungle_fence_gate'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:803) [WorldManager.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:771) [WorldManager.class:1.12.2-2768-7.1.4]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3545) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]


And such a warning before running more than 100

**Comment by phit** [comment]
those are thrown by Vanilla due to missing recipes for advancements, there is nothing for Sponge to fix

**Comment by STRL1T** [comment]
> those are thrown by Vanilla due to missing recipes for advancements, there is nothing for Sponge to fix

How can I hide these suggestions / warnings?

**Comment by phit** [comment]
you don't, whatever is removing/replacing those recipes also needs to adjust the vanilla advancements
either way this has nothing to do with Sponge
