### ISSUE TITLE
Server crash due to console spam with InvWrapper

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2556]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5-RC3516
- Forge version: 1.12.2-14.23.5.2796
- Java version: 1.8.0_191-b12
- Operating System: CentOS

- Plugins/Mods:
Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AdamantineShield, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, Nucleus, Server Backup, Total Economy, WrapperPing, spark

Mods (270): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, AE2 Stuff, AE2 Wireless Terminals (AE2WTLib), AI Improvements, Actually Additions, Actually Addon, Actually Baubles, Advanced Generators, AgriCraft, Akashic Tome, AngelRing 2 Bauble, AppleCore, AppleSkin, Applied Energistics 2, Armory Expansion, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, Attribute Fix, AutoRegLib, B.A.S.E, BD Lib, Backpack, Baubles, Baubley Heart Canisters, Better Builder's Wands, Better Than Mending, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, BloodyLib, Bookshelf, Botania, Brandon's Core, CC: Tweaked, Ceramics, Chameleon, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Computronics, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Culinary Construct, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Electroblob's Wizardry, Elevator Mod, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Creepers, Environmental Tech, Exchangers, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTBLib, FastFurnace, FastWorkbench, Fence Jumper, Floralchemy, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Gotta Go Fast, Guide-API, Hooked, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, Industrial Wires, InfinityLib, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Generators, JAOPCA, JAOPCAAgriculture, JEI Bees, Just Enough Dimensions, Just Enough Items, Just Enough Reactors, JustEnoughIDs, KJ Lib, KleeSlabs, LagGoggles, LibEx, LibrarianLib, LibrarianLib Stage 2, Lost Souls, LunatriusCore, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MetalChests, MineColonies, Minecraft Multipart Plugin, Mob Totems, Mod Tweaker, Modpack Config Checker, Morpheus, MrTJPCore, Multi Mob Core, Mystical Agradditions, Mystical Agradditions Compat, Mystical Agriculture, Mystical Agriculture Tiered Crystals, MysticalLib, Nature's Compass, NetherEx, No Mob Spawning on Trees, NuclearCraft, Nutrition, OreDictInit, OreExcavation, OreExcavation Integration, PackCrashInfo, Pam's HarvestCraft, Pink Flamingo, Placebo, Plants, PlusTiC, PneumaticCraft: Repressurized, PortalGun, Portality, Pressure Pipes, Primitive Mobs, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Psi, Quark, Quark Oddities, QuarryPlus, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RandomPatches, RandomTweaks, Ranged Pumps, Real Filing Cabinet, Reborn Core, Redstone Arsenal, Redstone Flux, Reliquary, Roguelike Dungeons, Roots 2, Rustic, Schematica, ShadowMC, Shadowfacts' Forgelin, Shield Parrying, Signals, Simply Jetpacks 2, Soul Shards Respawn, SpongeForge, StepUp, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, Structurize, Subterranean Waters, Surge, SwingThroughGrass, TOP Addons, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Periphery, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Transport, Traverse, Underground Biomes, UniDict, Universal Modifiers, Valkyrie Lib, WAIM, WanionLib, WarpDrive, WarpDriveCore, Water Strainer, Waystones, Wetstone, Wireless Crafting Terminal 2, WirelessCharger, Wizardry, Woot, WorldEdit, Worley's Caves, WrapUp, Zero CORE, asielib, careerbees, iChunUtil, p455w0rd's Library, projectred-compat

Notable mods:
TConstruct-1.12.2-2.12.0.113

**Issue Description**
Server crashed from out of memory due to console spam of warnings related to InvWrapper:
```
[16:19:43] [Server thread/DEBUG] [enderio]: ServerChannelRegister: Saving channel 666
[16:19:51] [luckperms-hikari housekeeper/DEBUG] [me.lucko.luckperms.lib.hikari.pool.HikariPool]: luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)
[16:19:59] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 175
[16:19:59] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 176
...
[16:19:59] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 397
[16:19:59] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 398
[16:19:59] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 399
[16:20:00] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 175
[16:20:00] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 176
[16:20:00] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 177
[16:20:00] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 178
...
[16:23:01] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 397
[16:23:01] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 398
[16:23:01] [Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraftforge.items.wrapper.InvWrapper at index 399
[16:23:01] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: mouse961 lost connection: Disconnected
[16:23:01] [Server thread/INFO] [betterchunkloader]: Unloaded all online chunkloaders for Player: mouse961
[16:23:01] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: mouse961 left the game
[16:23:01] [Server thread/TRACE] [FML]: Handshake channel activating
[16:23:01] [Server thread/DEBUG] [FML]: FMLHandshakeServerState: null->FMLHandshakeServerState$1:START
[16:23:01] [Server thread/DEBUG] [FML]:   Next: HELLO
[16:23:01] [Server thread/WARN] [net.minecraft.network.NetworkManager]: handleDisconnection() called twice
[16:23:01] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /**************************************************************************************************/
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*                               Illegal Async PhaseTracker Access                                */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /**************************************************************************************************/
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* Sponge adapts the vanilla handling of various processes, such as setting a block               */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* or spawning an entity. Sponge is designed around the concept that Minecraft is                 */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* primarily performing these operations on the "server thread". Because of this                  */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* Sponge is safeguarding common access to the PhaseTracker as the entrypoint for                 */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* performing these sort of changes.                                                              */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*                                                                                                */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* java.lang.Exception: Async Block Change Detected                                               */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.switchToPhase(PhaseTracker.java:179)  */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.buildAndSwitch(PhaseContext.java:254) */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:509)             */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:5214)               */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579)                      */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /**************************************************************************************************/
[16:23:01] [Server Shutdown Thread/INFO] [THAUMCRAFT]: Removing aura cache for world 0
[16:23:01] [Server Shutdown Thread/TRACE] [justenoughdimensions]: WorldEvent.Unload - DIM: 0
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*************************************************************************************************/
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*                               Illegal Async PhaseTracker Access                               */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*************************************************************************************************/
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* Sponge adapts the vanilla handling of various processes, such as setting a block              */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* or spawning an entity. Sponge is designed around the concept that Minecraft is                */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* primarily performing these operations on the "server thread". Because of this                 */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* Sponge is safeguarding common access to the PhaseTracker as the entrypoint for                */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* performing these sort of changes.                                                             */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*                                                                                               */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /* java.lang.Exception: Async Block Change Detected                                              */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:224) */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:565)         */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:537)            */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:5214)              */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579)                     */
[16:23:01] [Server Shutdown Thread/ERROR] [Sponge]: /*************************************************************************************************/
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ConcurrentModificationException
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ArrayDeque$DescendingIterator.next(ArrayDeque.java:700)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.event.SpongeCauseStackManager.checkProviders(SpongeCauseStackManager.java:126)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:93)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.event.SpongeCauseStackManager.popCauseFrame(SpongeCauseStackManager.java:228)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.event.SpongeCauseStackManager$CauseStackFrameImpl.close(SpongeCauseStackManager.java:493)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:339)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:512)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:5214)
[16:23:01] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579)
```

The index goes from 175 to 399, then restart to 175 until server crashes.
First occurrence was at line 225212, 16:19:59
Crash was at line 435862, 16:23:01
That's 210k lines in 3 minutes, or ~1157 lines per seconds.

There was a single player on the server:
- player was using a Builder's wand to upgrade his Tinker's smeltery with an internal size of 5x5x16 (400)
- a hopper was pushing Thermal Foundation Destabilized clathrate into the controller
- a ProjectRed Timer was triggering faucets to make redstone blocks

![image](https://user-images.githubusercontent.com/4776032/51091034-0eeccd00-1785-11e9-8ec0-debb1aa2f4be.png)

I'm not sure what the InvWrapper error is trying to say, and we've not been able to reproduce it. Any throught on that?

**Comment by phit** [comment]
i believe this was fixed with https://github.com/SpongePowered/SpongeForge/commit/47ae1f09fbda905f1bc5f43a3bafb006e0ff1890
