### ISSUE TITLE
OTG additional world generation

### ISSUE THREAD

**Issue by EasterncheesE** [SpongePowered/SpongeForge#2562]
Minecraft version: 1.12.2
Forge version: 2768
Spongeforge version: spongeforge-1.12.2-2768-7.1.4

This issue is continuation of previous issue (which i believe got fixed now). Previous issue link:
https://github.com/SpongePowered/SpongeForge/issues/2561

The first issue was about unable to create additional dimensions with OTG or Projectworld (with OTG generator) without a crash.
So far, after i got experimental build of OTG, the worlds are created.

When i do /otg dim -c Caves (a command to create dimension), the dimension is not seen by ProjectWorlds. So when i try to tp here (otg tp Caves), i get this error.
Please see the attached error log. As soon as log shows "This is an error usually on Sponge's part, so a report is required on the issue tracker on GitHub.", i post it here.
https://pastebin.com/TAbcCaCf

After i get disconnected on trying to tp to the world, server is not crashing. So when i try teleport there again, i get this: 
https://pastebin.com/Y1fzffFy
Also, it makes about 126mb of this line:

[10:00:31] [Server thread/INFO] [OTG]: SaveToDisk waiting on Populate. Although other mods could be causing this and there may not be any problem, this can potentially cause an endless loop!

 before forge shuts down the server for too long lag.

**Comment by gabizou** [comment]
So, what looks like is happening is a re-entrance of chunk generation with OTG and it causes a StackOverflowError, at which point Sponge kinda has no choice but to make it known (hence the massive spam logs, because if it keeps happening, various bits of what powers all events on sponge are out of sync).

The log already makes it self explanatory:
```
Caused by: java.lang.StackOverflowError
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) ~[?:1.8.0_101]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:147) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]
	at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97) ~[SpongeGenerationPopulator.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:248) ~[SpongeChunkGenerator.class:1.12.2-2768-7.1.4]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:488) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105) ~[OTGChunkGenerator.class:?]

```
What I believe is happening here though is that OTG is ignoring any sort of checks for whether the requested chunk is being generated, which then causes recursive calls to the world generation objects to generate said chunk. 

Reference to the [ForgeWorld#getChunk](https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B-v7-dev/platforms/forge/src/main/java/com/pg85/otg/forge/ForgeWorld.java#L488).

Have you tried creating the world with OTG's settings and using a plugin like Nucleus to teleport to that world?

**Comment by EasterncheesE** [comment]
Well, let me explain what i tried:

I use sponge with nucleus and ProjectWorlds.
So ProjectWorlds can create dimensions with generator settings. So when i try to make OTG world with it, it created default OTG world, because it lacks the ability to tell OTG which exactly preset should it generate (as far as i understood it).
When i try to create dimension with OTG, then it's created and i see e.g. DIM3 folder in server world folder.
However, ProjectWorlds doesn't seem to recognise, so when i make /world list, it's not on the list, while i can still see it in the list with /otg dim -l.

So, i have DIM3 created with /otg -c DIM3 command and it generates what i need (checked with no sponge installed, everything works fine). 
Upon trying to teleport to the world with ProjectWorlds/Nucleus, i get this error and kicked from server. When i reenter, i still appear to be at overworld. So server doesn't crash on first attempt. 
When i try enter dimension again, server crashes.

If i create new world with OTG command and restart server, it crashes on startup as Sponge tries to load spawn area for each world by default config. 
I have tried reproduce everything once again, here are the error and crash report links and explanation + pictures on what i did:
https://pastebin.com/giyRjDEi

**Comment by EasterncheesE** [comment]
Without sponge, i can create world with no problem.

Also, overworld is created with OTG+Sponge with no problem, except the fact that custom biome is not applied (My custom biome name is DestroyedWorld, while i see plains, when both OTG and Sponge are installed).

**Comment by RikAzerion** [comment]
Hey guys, OTG dev here, thanks for looking into this. We're currently working on Forge and Spigot so SpongeForge is on the backburner atm, there are some known bugs and we have told people that we won't be looking into SpongeForge-specific problems until we're done with Forge and Spigot. That being said, please try the latest development builds posted on the forge-dev channel of the OTG discord, as fixes for Forge/Spigot may very well impact SpongeForge.

As for "SaveToDisk waiting on Populate", this happens because 2 threads that need to be synchronized are unable to do so, most likely because one of the threads is stuck (doing some never-ending operation) or dead (something went wrong but didn't crash the server). In this case the thread that saves the server is waiting on the thread that generates the terrain to finish its generation cycle, which never appears to happen.

**Comment by Zidane** [comment]
@EasterncheesE Re-test with the latest SF and let us know if this is till happening.

**Comment by PG85** [comment]
*Coincidentally, just cleaned up the OTG repo's issues, have had this issue reported a number of times. Apparently the way OTG is fetching chunks causes cascading chunk population for Sponge, where it doesn't for Forge. Let me know if I can assist.

**Comment by domingothegamer** [comment]
I'm not the same guy, but I can say that this problem still happens.
I went ahead and did a clean ForgeSponge Server setup with just Nucleus, LuckPerms, TotalEconomy (Latest versions for each) for basics and then the latest OTG Dev version from their discord while also using the latest Sponge/Forge builds.

Minecraft version: 1.12.2
Forge version: 2838
Spongeforge version: spongeforge-1.12.2-2838-7.1.7-RC3777
OTG version: OpenTerrainGenerator-1.12.2_-_v7_DEV_r25

Debug Log (First Run with created worlds and dims): https://pastebin.com/Lm7xJXeu

Small step through, created world with nucleus with applied generator otg, but as op says it's seen as a non-otg world so it goes default gen due to no presets or something along those lines. I created world through otg and it does create the world. No crashes until you teleport into the world created through OTG.

Same problems still occurs like the op had. No improvements besides a small difference in behavior that instead of kicking the user out of the server immediately, it does load some chunks as some get through the loop, but inevitably under 1 minute or less, crashes with the same text..

SaveToDisk waiting on Populate

One thing I'm not sure if op mentioned, but you can have a working OTG world if you create the main world with OTG in level type via server properties with a fresh world folder, fully generated. It does work and behave like it should supposively detecting and applying presets (Biome Bundle as well), sponge's worldgen doesn't mind it seems; it even recognizes it in nucleus with OTG generator in the world list if you do it this way. However, a small minor thing, every restart does show that it finds missing ids for registry biome. Part of that Log here: https://pastebin.com/wBRHe8L9

I will also note that from OTG's dev version 24 to 25 in minor dimension bugs, it did fix a problem inadvertently. When you create a overworld with nucleus, the next reboot on the server would give a null error from OTG due to it being listed in dimensions text file for OTG, having a null value. If you replace null with 0, it works afterward. That was the work around. But it's all good now it seems.

Anyway, that's what I got for now. Just waiting patiently to get the best of both worlds with Sponge and OTG hopefully. Willing to do any tests if needed.

**Comment by SirSpence99** [comment]
Is there an update on this? Even an update that just says what is probably going wrong on Sponge's side (or what OTG is doing that causes this issue.) would be helpful.

If not, is there anything I (or others) can do to help fix/find the problem?

This appears to be the offending code. These 6 lines appear over a hundred times in my crash log.


`at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)`
	
`at net.minecraft.world.World.func_72964_e(World.java:310)`
	
`at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:501)`
	
`at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185932_a(OTGChunkGenerator.java:105)`
	
`at org.spongepowered.common.world.gen.SpongeGenerationPopulator.populate(SpongeGenerationPopulator.java:97)`
	
`at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:249)`

This is the actual error:
`java.lang.StackOverflowError: Exception generating new chunk`


SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3616.jar)

I'm not familiar enough with sponge for me to work through the problem and identify the issue without some direction. If given some direction, I can take a look and attempt to solve it.

**Comment by Zidane** [comment]
I had a long chat with PG85 from OTG. Unfortunately, to make certain features work, OTG has to replace some core engine classes (WorldProvider, WorldInfo to name a few) to wrap the true versions and add on new features. Sponge strongly discourages this practice as it inherently makes the mod in question incompatible with us (for sure) and others out there potentially. Mystcraft is another mod who does this.

An easy solution, which admit-tingly requires work, would be to switch OTG over to Mixin. PG could add on OTG-specific features right on to the classes without changing out what the base game is doing which would end up as cleaner code overall, more streamlined code, and ensure mod compatibility. Especially since the mod already does raw ASM.

Another solution would be to remove the world management features from OTG and add a "features" mod and return OTG to being a world generator. Just like the mod it forked called TerrainControl. Then one can easily use a world management mod/plugin (Sponge + Nucleus) to set the generator to be OTG for a world and have generation proceed.

I gave this advice to PG and offered assistance from our community on the transition (such as getting Mixin setup/etc).

At this point, it is entirely in his hands.
