### ISSUE TITLE
/dimensiontp or rockets in general wont work. 

### ISSUE THREAD

**Issue by SebaSphere** [SpongePowered/SpongeForge#2587]
**I am currently running**

- SpongeForge version: latest / issue is in every version
- Forge version: .2795
- Java version: 1.12.2
- Operating System: Linux 

- Plugins/Mods: 
https://minecraft.curseforge.com/projects/terras-starlight

Galacticraft and Sponge Conflict

**Issue Description**

When I try to do /dimensiontp, I get this error 
https://pastebin.com/gtRLKJDe

**Comment by phit** [comment]
as I just tested rockets extensively I know for a fact they do work fine (unless you have an dim id conflict)

https://github.com/SpongePowered/SpongeForge/issues/2580#issuecomment-457967333

so I'm gonna need more information on how to reproduce this and what versions you are using

**Comment by SebaSphere** [comment]
https://github.com/micdoodle8/Galacticraft/issues/3625 
Issue on the galacticraft page

**Comment by SebaSphere** [comment]
@phit Im unable to go to the celestial screen. Im using galacticraft version .181

**Comment by phit** [comment]
> @phit Im unable to go to the celestial screen. Im using galacticraft version .181

again, I'm gonna need more information on how to reproduce this and what versions you are using as this does not happen with gc and sponge alone, you did not even include your sponge version

**Comment by CinnamonLambda** [comment]
#2580 I have my reasons for blaming AE2.

**Comment by gabizou** [comment]
You have a corrupt `level_sponge.dat` file. Remove it and restart.

```
[16:07:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.RuntimeException: Attempt failed when reading Sponge level data for [DIM-2543] from file [level_sponge.dat]!
[16:07:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at net.minecraft.world.storage.SaveHandler.loadSpongeDatData(SaveHandler.java:619)
[16:07:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$bcm000(SaveHandler.java:1071)
[16:07:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: ... 33 more
[16:07:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.util.zip.ZipException: Not in GZIP format
[16:07:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
```

**Comment by SebaSphere** [comment]
Ok lemme try that

**Comment by SebaSphere** [comment]
https://pastebin.com/735SuXs7

**Comment by SebaSphere** [comment]
Nope still doesn't work. Already tried removing that specific dimension a few times.

**Comment by SebaSphere** [comment]
1.12.2-2768-7.1.5-RC3542

Sponge version

**Comment by SebaSphere** [comment]
Without Sponge, Galacticraft works completely fine, When I have it, its not possible to get to celestial screen

**Comment by SebaSphere** [comment]
Also I should probably make It clear rockets are able to launch but once you reach the max attitude, rocket disappears. Cant get to celestial screen at all
