### ISSUE TITLE
sponge problem 

### ISSUE THREAD

**Issue by jakub96124124** [SpongePowered/SpongeForge#2591]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2768-7.1.5-RC3553
- Forge version:  forge-1.12.2-14.23.5.2779-universal
- Java version:  8.201
- Operating System:

org.spongepowered.api.service.pagination.PaginationService.builder()Lorg/spongepowered/api/service/pagination/PaginationBuilder;
[10:39:20] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'help' for source DedicatedServer: org.spongepowered.api.service.pagination.PaginationService.builder()Lorg/spongepowered/api/service/pagination/PaginationBuilder;
java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationService.builder()Lorg/spongepowered/api/service/pagination/PaginationBuilder;
        at au.id.rleach.betterhelp.SpongeHelpCommand.lambda$create$4(SpongeHelpCommand.java:73) ~[SpongeHelpCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5-RC3553]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5-RC3553]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5-RC3553]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
**Issue Description**

**Comment by ImMorpheus** [comment]
Remove BetterHelp.
It was made for API 4

**Comment by jakub96124124** [comment]
Thank woking
