### ISSUE TITLE
testNoArgsFunctional failed

### ISSUE THREAD

**Issue by sorrowloki** [SpongePowered/SpongeForge#2593]
Hello all! Just try to build through gradlew on my system. During building I had this: 

- SpongeForge version:  latest stable-7 branch
- Java version: openjdk version "1.8.0_171"
- Operating System: Debian 8 

org.spongepowered.api.command.CommandSpecTest > testNoArgsFunctional FAILED
    java.lang.IllegalStateException: Sponge has not been initialized!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at org.spongepowered.api.Sponge.check(Sponge.java:77)
        at org.spongepowered.api.Sponge.getCauseStackManager(Sponge.java:269)
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:338)
        at org.spongepowered.api.command.CommandSpecTest.testNoArgsFunctional(CommandSpecTest.java:57)

Full report: https://gist.github.com/sorrowloki/8a84b376c91735e648efdfa38daf63d8

**Comment by sorrowloki** [comment]
Sorry, this is for SpongeAPI. My mistake.

**Comment by dualspiral** [comment]
~move to sa

**Comment by limbo-app** [comment]
Hey @sorrowloki! I've moved your issue to [SpongePowered/SpongeAPI#1962](https://github.com/SpongePowered/SpongeAPI/issues/1962).
