### ISSUE TITLE
Rare crash on login

### ISSUE THREAD

**Issue by bluelightning32** [SpongePowered/SpongeForge#2622]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3563.jar
- Forge version: forge-1.12.2-14.23.5.2781-universal.jar
- Java version: 1.8.0_201
- Operating System: Fedora 29

- Plugins/Mods:
```
> /sponge plugins
[23:03:18] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (9): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Inventory Sync, JdaLibraryLoader, LuckPerms, Nucleus, UltimateChat
```
- I also have the mods from version 1.55 of Enigmatica Expert 2.

**Issue Description**
My server crashed when a player tried to login. This has only happened once. The player has logged in without problems before. After the crash the server automatically rebooted and the player logged in without problems.

Tail of server log: https://gist.github.com/bluelightning32/ed482d0d840a527d2029c497a177dfff
Crash report: https://gist.github.com/bluelightning32/0d3bf834f13010cc2c51ccfe3df80d38
```
[12:13:17] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: REDACTED moved too quickly! 715.0681625190313,-7.0,-1107.7939765345977
[12:13:17] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_201]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3563]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3967) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.func_175089_a(NetHandlerPlayServer.java:627) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147364_a(NetHandlerPlayServer.java:598) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:530) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) ~[lk$a.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3563]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[12:13:17] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[12:13:17] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:161) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165) ~[ou.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more
[12:13:17] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/minecraft-enigmatica/enigmatica_expert_2/node2/server/./crash-reports/crash-2019-02-21_12.13.17-server.txt
```

**Comment by bluelightning32** [comment]
It reproduced again. I upgraded the system a while ago to Enigmatica Expert 2 version 1.57. The sponge, forge, java, and OS versions are still the same.

```
java.lang.NullPointerException: Exception ticking world
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:161)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by phit** [comment]
is your server behind velocity? if so https://github.com/SpongePowered/SpongeForge/issues/2651

**Comment by bluelightning32** [comment]
Yes, it is.
