### ISSUE TITLE
Enchantment fatal error sponge

### ISSUE THREAD

**Issue by byalexeykh** [SpongePowered/SpongeForge#2627]
**I am currently running**

- SpongeForge version: 
- Forge version:  forge-1.12.2-14.23.5.2815-universal
- Java version: Java:1.8.0_191 (Java 8)
- Operating System: Windows 10

- Plugins/Mods: 

Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AppleCore, Aroma1997Core, AromaBackup, AromaBackuprecovery, Backpack, Baubles, Botania, ChickenChunks, Clumps, CodeChicken Lib, CoroUtil Library, Emoticons, Extended Mod Config, Extended Renderer, FTB Library, Forestry, Gravestone Mod, GregTech Community Edition, Hammer Core, Immersive Engineering, Inventory Tweaks, Iron Chest, IvToolkit, Just Enough Items, Lycanites Arctic Mobs, Lycanites Demon Mobs, Lycanites Desert Mobs, Lycanites Elemental Mobs, Lycanites Forest Mobs, Lycanites Freshwater Mobs, Lycanites Inferno Mobs, Lycanites Jungle Mobs, Lycanites Mobs, Lycanites Mountain Mobs, Lycanites Plains Mobs, Lycanites Saltwater Mobs, Lycanites Shadow Mobs, Lycanites Swamp Mobs, Mantle, Morpheus, NetherPortalFix, OMLib, Open Modular Turrets, Pam's HarvestCraft, Railcraft, Realistic Item Drops, Recurrent Complex, Sampling Performance Profiler, Secret Rooms 5, SecretRooms Hooks, Special AI, Spice of Life: Carrot Edition, SpongeForge, Tinkers' Construct, Tree Chopper, YABBA, Zombie Awareness

Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActionBroadcaster, FlexibleLogin, LuckPerms, RedProtect

**Issue Description**
I think that this is due to the enchantment of tools and the gregTech mod. The problem appeared when I enchanted my tools and armor.

`Caused by: java.lang.NullPointerException
	at gregtech.api.enchants.EnchantmentEnderDamage.func_151368_a(EnchantmentEnderDamage.java:46) ~[EnchantmentEnderDamage.class:?]
	at net.minecraft.enchantment.EnchantmentHelper$DamageIterator.func_77493_a(EnchantmentHelper.java:450) ~[alm$a.class:?]
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:124) ~[alm.class:?]
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134) ~[alm.class:?]
	at net.minecraft.enchantment.EnchantmentHelper.func_151385_b(EnchantmentHelper.java:604) ~[alm.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:4045) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2704) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more`

Full log: https://gist.github.com/byalexeykh/fe3f5d839148a51ab57c76ebe2f9a75c

**Comment by ImMorpheus** [comment]
https://github.com/GregTechCE/GregTech/issues/597#issuecomment-468430213
