### ISSUE TITLE
NoSuchMethodError When debugging mod at SpongeForge

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2665]
**I am currently running**

- SpongeForge version: https://github.com/SpongePowered/SpongeForge/tree/cbe2853edd4846ab086370f0a1dd94b55fa919ef
- Forge version: 1.12.2 14.23.5.2768
- Java version: 8
- Operating System: win10

- Plugins/Mods:

**Issue Description**
When I use the same way as the plugin to make SpongeForge dependent my mod, i get NoSuchMethodError after running.
```
[21:38:48] [Server thread/DEBUG] [org.apache.ibatis.datasource.pooled.PooledDataSource]: Returned connection 473261442 to pool.
[21:38:48] [Server thread/INFO] [STDOUT]: [halo.mfbl.common.CacheManager:loadCache:92]: loadGoodsCache done..
[21:38:48] [Server thread/WARN] [Sponge]: holograms: It is no longer required to include the plugin id when specifying a Key id through Key.Builder#id. This is deprecated and may be removed later. The plugin id will be retrieved from the current PluginContainer in the cause stack. Key: holograms:is-hologram
[21:38:48] [Server thread/INFO] [STDOUT]: [halo.mfbl.init.ModEntities:registerEntities:43]: registerEntities
[21:38:48] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Magic tribe (mfbl)

Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at halo.mfbl.init.ModItems.registerItem(ModItems.java:140) ~[mfbl_mod.main/:?]
	at halo.mfbl.init.ModItems.registerItem(ModItems.java:134) ~[mfbl_mod.main/:?]
```
I found that there is really no such method under the java file: `SpongeForge\.gradle\minecraft\forgeSrc-1.12.2-14.23.5.2768-PROJECT(SpongeForge).jar`

So I'm curious, is this forgeSrc file different from the one we used for mod development?

full log:
https://gist.github.com/zhourui123/5751d2c0f3f3acb4b5365d5c802cf42e

I tried to replace the forgeSrc(SpongeForge).jar with 
`user\.gradle\caches\minecraft\net\minecraftforge\forge\1.12.2-14.23.5.2768\snapshot\20171003\forgeSrc-1.12.2-14.23.5.2768.jar` ,
 But SpongeForge has plenty of unfound method problems.

I believe you can understand what is going on by looking at it, but I really don't know how to solve it, please give me some advice, very very thank you!!

**Comment by phit** [comment]
you need to match mcp mappings between your mod and spongeforge

**Comment by zhourui123** [comment]
@phit Sorry, i don't think you have read my question carefully, i think mcp is:  `a <-> func_72838_d <->spawnEntityInWorld`, but at runtime, it's all mcp already,  question is, **Why are there no 'setUnlocalizedName'  method in Item? even testmods cann't call this method, you can try it.**

**Comment by zhourui123** [comment]
My fault! i shouldn't use snapshot version of mcp mapping. sorry for bother your time.
