### ISSUE TITLE
ClassCastException with topography mod

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2691]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3616
- Forge version: 14.23.5.2824
- Java version: 1.8.0_201
- Operating System: CentOS

- Plugins/Mods:
SkyFactory 4 1.0.1
Mods (195): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Carry On, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, LagGoggles, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

Plugins (19): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MagiBridge, Nucleus, Prism, Server Backup, SkyClaims, Total Economy, WrapperPing, spark

Notable versions:
LuckPerms v4.4.4
Topography-1.12.2-1.4.5

**Issue Description**
Whenever a player joins for the first time, the topography mods try to execute commands.
Some (the first ones?) will ends in ClassCastException, other will work fine.
Running the same command from console works fine.

```
[16:54:18] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'function triumph:startingItems' for source org.spongepowered.common.command.WrapperCommandSource$Located@615d2f96: java.lang.ClassCastException: me.lucko.luckperms.sponge.service.proxy.api7.PermissionServiceProxy cannot be cast to org.spongepowered.common.service.permission.SpongePermissionService
java.lang.RuntimeException: java.lang.ClassCastException: me.lucko.luckperms.sponge.service.proxy.api7.PermissionServiceProxy cannot be cast to org.spongepowered.common.service.permission.SpongePermissionService
	at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:164) ~[MinecraftCommandWrapper.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:145) ~[MinecraftCommandWrapper.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.6-RC3616]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	at net.minecraft.command.FunctionObject$CommandEntry.func_194145_a(SourceFile:58) [bm$b.class:?]
	at net.minecraft.advancements.FunctionManager$QueuedCommand.func_194222_a(SourceFile:179) [nt$a.class:?]
	at net.minecraft.advancements.FunctionManager.func_194019_a(SourceFile:116) [nt.class:?]
	at com.bloodnbonesgaming.topography.event.EventSubscriber.playerLoginEvent(EventSubscriber.java:227) [EventSubscriber.class:?]
...
Caused by: java.lang.ClassCastException: me.lucko.luckperms.sponge.service.proxy.api7.PermissionServiceProxy cannot be cast to org.spongepowered.common.service.permission.SpongePermissionService
	at org.spongepowered.common.command.WrapperCommandSource.getContainingCollection(WrapperCommandSource.java:79) ~[WrapperCommandSource.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.common.service.permission.base.SpongeBaseSubject.asSubjectReference(SpongeBaseSubject.java:53) ~[SpongeBaseSubject.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.common.command.AndPermissionLevelSubject.<init>(AndPermissionLevelSubject.java:53) ~[AndPermissionLevelSubject.class:1.12.2-2768-7.1.6-RC3616]
...
```

Full server debug log:
https://gist.github.com/LemADEC/bed3b9775adeec1683c0f95da3e94e36

**Comment by KingDan27** [comment]
Erm i remember seeing this come up (could be wrong deleted the old crashes already) and it was actually foamfix that need this config option changed from b:patchChunkSerialization=true to b:patchChunkSerialization=false. If you haven’t yet check this setting is set correctly
