### ISSUE TITLE
ClassCastException with Cyclic automated user 

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2698]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3661
- Forge version: 1.12.2-14.23.5.2824-
- Java version: 1.8
- Operating System: CentOS

- Plugins/Mods:
SkyFactory4 1.0.1
Mods (194): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Carry On, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers
Plugins (19): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MagiBridge, Nucleus, Prism, Server Backup, SkyClaims, Total Economy, WrapperPing, spark

Including Cyclic-1.12.2-1.19.3

**Issue Description**
When an Automated user is activated, console is spamming ClassCastException, eventually causing a server timeout.
While this is happening, players are able to dup by placing blocks without consuming their item in hand.

https://gist.github.com/LemADEC/e8bee499a4f2f8f645cd6848a1c93377

Just before it happens, an error is raised regarding forge Fakeplayer?
```
[15:06:21] [Server thread/WARN] [Sponge]: No entity type is registered for class net.minecraftforge.common.util.FakePlayer
[15:06:21] [Server thread/ERROR] [cyclicmagic]: Automated User Error
[15:06:21] [Server thread/ERROR] [cyclicmagic]: org.spongepowered.common.event.tracking.phase.tick.TileEntityTickContext cannot be cast to org.spongepowered.common.event.tracking.phase.packet.PacketContext
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: java.lang.ClassCastException: org.spongepowered.common.event.tracking.phase.tick.TileEntityTickContext cannot be cast to org.spongepowered.common.event.tracking.phase.packet.PacketContext
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1224)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at com.lothrazar.cyclicmagic.block.autouser.TileEntityUser.rightClickBlock(TileEntityUser.java:254)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at com.lothrazar.cyclicmagic.block.autouser.TileEntityUser.func_73660_a(TileEntityUser.java:149)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:235)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:3656)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zmj000(WorldServer.java:3643)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.world.World.func_72939_s(World.java:7832)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2790)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[15:06:21] [Server thread/INFO] [STDERR]: [com.lothrazar.cyclicmagic.block.autouser.TileEntityUser:func_73660_a:156]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by phit** [comment]
this also happens with a few other block placers ive been told
