### ISSUE TITLE
Adv Rocketry going to the moon makes everyone unable to login

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2708]
**I am currently running**

- SpongeForge version: 3616

- Plugins/Mods: adv rocketry

**Issue Description**
a user gets the advancement for going to the moon from advanced rocketry, after they get it nobody is able to login

```
[21:08:52] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /85.255.237.43:38860
java.lang.IllegalStateException: The advancement is not yet initialized
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.advancements.AdvancementProgress.getOptionalAdvancement(SourceFile:816) ~[k.class:?]
	at net.minecraft.advancements.AdvancementProgress.updateProgressMap(SourceFile:616) ~[k.class:?]
	at net.minecraft.advancements.AdvancementProgress.handler$onUpdate$zzm000(SourceFile:608) ~[k.class:?]
	at net.minecraft.advancements.AdvancementProgress.func_192099_a(SourceFile:45) ~[k.class:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:379) ~[np.class:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192740_f(PlayerAdvancements.java:149) ~[np.class:?]
	at net.minecraft.advancements.PlayerAdvancements.<init>(PlayerAdvancements.java:56) ~[np.class:?]
	at net.minecraft.server.management.PlayerList.func_192054_h(PlayerList.java:1137) ~[pl.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:183) ~[oq.class:?]
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:504) ~[pl.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135) ~[pc.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63) ~[pc.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[21:08:52] [Server thread/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: com.mojang.authlib.GameProfile@1d7cd338[id=....) lost connection: Internal server error
```

https://github.com/zmaster587/AdvancedRocketry/blob/b9733aaa946a6c4315a74b8e4d15a087dbff2324/src/main/java/zmaster587/advancedRocketry/achievements/ARAchivements.java

**Comment by phit** [comment]
havent validated if this happen with just adv rocketry, will test when i have the time, mostly making this issue as a note for myself
