### ISSUE TITLE
If a space station exists, going to the nether crashes the server

### ISSUE THREAD

**Issue by bluelightning32** [SpongePowered/SpongeForge#2737]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2825-7.1.6-RC3693.jar
- Forge version: forge-1.12.2-14.23.5.2836-universal.jar
- Java version: 1.8.0_212-b04
- Operating System: Fedora 29

- Plugins/Mods:
```
> /sponge plugins
[14:23:14] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (10): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Inventory Sync, JdaLibraryLoader, LuckPerms, Sledgehammer, UltimateChat, spark
```
```
> /sponge mods
[14:23:25] [Server thread/INFO] [minecraft/DedicatedServer]: Mods (260): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, A Lib, Actually Additions, Actually Baubles, Akashic Tome, Alchemistry, Animania, AppleCore, AppleSkin, ArchitectureCraft, Aroma1997Core, AromaBackup, AromaBackuprecovery, Artisan Worktables, Astral Sorcery, Athenaeum, AutoPickup, AutoRegLib, Avaritia, B.A.S.E, BD Lib, Baubles, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bloodmoon, Bonsai Trees, Bookshelf, Botania, Botanic Additions, Brandon's Core, Ceramics, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Drawers, ContentTweaker, CookieCore, Corail Tombstone, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cucumber Library, Custom Starting Gear, Cyclic, Cyclops Core, DDSS Utils, Dark Utilities, DiscordIntegration, Doomlike Dungeons, Draconic Evolution, DungeonTactics, EnderStorage, Environmental Tech, EvilCraft, EvilCraft-Compat, Exchangers, Extended Crafting, Extra Alchemy, Extra Planets, Extra Utilities 2, Extreme Reactors, FTB Library, FTB Utilities, Farseek, Fast Leaf Decay, FastWorkbench, Fishing Net Mod, FluidTank, FluidTank_AE2, FluidTank_TheOneProbe, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, GenDustry, Gendustry JEI Addon, Guide-API, Guidebook, Hammer Core, HelpFixer, Hooked, Hunger Overhaul, Hunting Dimension, Ice and Fire, Immersive Engineering, Industrial Foregoing, Infernal Mobs, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Chest, IvToolkit, JourneyMap, Just Another Rotten Flesh to Leather Mod, Just Enough Items, LLibrary, LagGoggles, Lapis Stays in the Enchanting Table, LibEx, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, Loot Bags, LootTweaker, MJRLegendsLib, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanica, Mekanica: Generators, Mekanica: Tools, MekanismOres, Micdoodle8 Core, Minecraft Multipart Plugin, Mob Properties Randomness, Mod Tweaker, More Libs, More Plates, Morpheus, Mowzie's Mobs, MrCrayfish's Furniture Mod, MrTJPCore, Multi Mob Core, Mystical Agradditions, Mystical Agriculture, Mystical Lib, Natura, NetherEx, NotEnoughIDs, NuclearCraft, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Overloaded, Pam's Cookables, Pam's HarvestCraft, Pickle Tweaks, Placebo, PlusTiC, PneumaticCraft: Repressurized, Primitive Mobs, Progressive Bosses, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Prometheus Integration, Quark, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RailsPlus, RandomPatches, Reborn Core, RebornStorage, Redstone Flux, Refined Avaritia, Refined Storage, Refined Storage Addons, Rex's Additional Structures, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roguelike Dungeons, Rough Mobs 2, Ruins Mod, Rustic, Shadowfacts' Forgelin, Simply Jetpacks 2, Solar Flux Reborn, Special AI, Spice of Life: Carrot Edition, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, Storage Tech, Streams, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers Alloying Addon, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, Tweakers Construct, Underground Biomes, UniDict, Universal Modifiers, V0id's Smart Backpacks, Valkyrie Lib, VanillaFix, ViesCraft, Vulcanite, WanionLib, Worley's Caves, XNet, Zero CORE, Zoesteria Biomes, galacticrafttweaker, p455w0rd's Library, projectred-compat
```

**Issue Description**
A player created a Galaticraft space station on my server. Now when other players go to the nether, the server crashes. The space station should have nothing to do with the nether. The dimension ids are different.

Before the server crashes, it slowly chews up memory, up to the maximum configured on the command line (10GB). The server is unresponsive during that time, even from the console. The crash report shows a thread trying to allocate memory. I've run jstack while the process is hung but before the crash. That thread shows up on each jstack then, but not at all when the server is functioning properly:
```
java.lang.OutOfMemoryError: Java heap space
    at java.util.HashMap.resize(HashMap.java:704)
    at java.util.HashMap.putVal(HashMap.java:663)
    at java.util.HashMap.put(HashMap.java:612)
    at java.util.HashSet.add(HashSet.java:220)
    at micdoodle8.mods.galacticraft.core.dimension.SpinManager.refresh(SpinManager.java:266)
    at micdoodle8.mods.galacticraft.core.dimension.SpinManager.readFromNBT(SpinManager.java:871)
    at micdoodle8.mods.galacticraft.core.dimension.SpinManager.updateSpin(SpinManager.java:501)
    at micdoodle8.mods.galacticraft.core.dimension.WorldProviderSpaceStation.updateWeather(WorldProviderSpaceStation.java:54)
    at micdoodle8.mods.galacticraft.core.dimension.WorldProviderOverworldOrbit.updateWeather(WorldProviderOverworldOrbit.java:207)
    at net.minecraft.world.World.updateWeather(World.java:2564)
    at net.minecraft.world.WorldServer.updateWeather(WorldServer.java:1236)
    at net.minecraft.world.World.tick(World.java:2541)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:179)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

If I remove the spacestation by deleting the world/galacticraft/spacestation_2.dat, the server no longer crashes.

The crash reproduces with spongeforge-1.12.2-2825-7.1.6-RC3693.jar and spongeforge-1.12.2-2768-7.1.6-RC3616.jar. It does not reproduce with just forge.

Before the crash, it says -1 is the space station:
```
[13:56:02] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (Space Station)
```

I'm not sure what the space station dimension ID should be. This file says -26 or -27:
```
[minecraft@mihoshi galacticraft]$ nbtutil --path spacestation_2.dat --printtree
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
 + spacestation_2.dat [1 entries]
   + data: 8 entries
     + allowedAll: 0
     + dimensionIdDynamic: -27
     + dimensionIdStatic: -26
     + homePlanet: 0
     + owner: FinwickShortail
     + spaceStationName: Kobold Incoperated Space Station
     + allowedPlayers: 1 entry
     | + 1 entry
     |   + allowedPlayer: FinwickShortail
     + dataCompound: 0 entries
/galacticraft/spacestation_2.dat: OK
```

This file says the dimension id should be 2:
```
[minecraft@mihoshi DIM_SPACESTATION2]$ nbtutil --path level_sponge.dat --printtree 
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
 + level_sponge.dat [1 entries]
   + SpongeData: 10 entries
     + GenerateBonusChest: 0
     + HasCustomDifficulty: 0
     + serializationBehavior: 1
     + DataVersion: 1
     + dimensionId: 2
     + UUIDLeast: -8277861704678658793
     + UUIDMost: 4071144585592065643
     + dimensionType: galacticraftcore:space_station
     + portalAgentType: net.minecraft.world.Teleporter
     + PlayerIdTable: 1 entry
       + 2 entries
         + UUIDLeast: -6864555874024194320
         + UUIDMost: 5221408766401859546
/DIM_SPACESTATION2/level_sponge.dat: OK
Operation complete.  Nodes succeeded: 1  Nodes failed: 0
```

[Server log](https://gist.github.com/bluelightning32/60dd9b9f02b0d05e4c69c32e36b51e4b)
[Crash report](https://gist.github.com/bluelightning32/6c9b0255d57c75732206765f337adf9d)

**Comment by bluelightning32** [comment]
When the player actually goes to the space station, the log has this:
```
[14:51:45] [Server thread/INFO] [Sponge]: Loading world [DIM_SPACESTATION2] (Space Station)
```

**Comment by bluelightning32** [comment]
The dimension types looks correct in the level_sponge.dat files:
```
[minecraft@mihoshi world]$ nbtutil  --printtree --path DIM-1/level_sponge.dat | grep dimensionType
     + dimensionType: nex:nether
[minecraft@mihoshi world]$ nbtutil  --printtree --path DIM_SPACESTATION2/level_sponge.dat | grep dimensionType
     + dimensionType: galacticraftcore:space_station
```

**Comment by bluelightning32** [comment]
I found a workaround. Put this into config/sponge/worlds/nex/nether/DIM-1/world.conf
```
sponge {
    world {
        # If 'true', this world will load on startup.
        load-on-startup=true
    }
}
```

It's usually there by default, but I accidentally deleted it when I upgraded the server.

With that line, the server loads the nether early and with the correct dimension type:
```
[16:20:54] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (Nether)
```

**Comment by Zidane** [comment]
I'll investigate this. It seems that Galacticcraft grabbed the Nether as a space station (0.o). No matter if the Nether is set to load, the Nether's dimension id and type are registered regardless. Something real funky going on here..

**Comment by Zidane** [comment]
Actually give this another shot with the latest SF and let me know if it still happens.

**Comment by bluelightning32** [comment]
Still reproduces in spongeforge-1.12.2-2825-7.1.6-RC3713.jar. I'll try a later build.

**Comment by bluelightning32** [comment]
It's fixed in spongeforge-1.12.2-2825-7.1.6-RC3741.jar. Thanks!

**Comment by bluelightning32** [comment]
I spoke too soon. The log message is gone, but it still uses up all the memory and crashes.

https://drive.google.com/open?id=1-gL23b2ZbYmmHUlkmnavWs0RcUmUsmjY

**Comment by phit** [comment]
https://gist.github.com/phit/ce5312b5762bf25a1f4bdeea2c860bd6

**Comment by Zidane** [comment]
Can you retest on latest SF and give me new logs? It won't be fixed but will help me narrow this down.

**Comment by bluelightning32** [comment]
I already tested with 7.1.6-RC3741. I can't find any newer build.

**Comment by Zidane** [comment]
https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2825-7.1.6-RC3755/spongeforge-1.12.2-2825-7.1.6-RC3755.jar

**Comment by bluelightning32** [comment]
Thanks. I was still using http://files.minecraftforge.net/spongepowered. I didn't realize you switched your build server again. 

Here is the debug.log from testing with spongeforge-1.12.2-2825-7.1.6-RC3757.jar.
https://drive.google.com/file/d/1WfMuk9SX57-rYZjqmedY97eB64JEYnhL/view?usp=sharing

**Comment by Zidane** [comment]
I have made another code change that should fix the duplicate save event when shutting down

Now with that out of the way, you have even more issues that I don't think are Sponge related:

[19:01:14] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (nex:nether/-1)
[19:04:10] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (galacticraftcore:space_station/-1)

I explictly changed the log entries in SpongeCommon for this reason and this reason alone. When your Nether loads, it is a nex:nether DimensionType. Sometime afterwards, Galacticraft is changing the DimensionType to galacticraftcore:space_station. This is likely the root of your issues.

**Comment by Zidane** [comment]
Actually I am now convinced that this is a far deeper issue that exists in how Forge handles adding new DimensionTypes to the game. It isn't their fault, it is a quirk of the JVM. I am closing this issue in favor of the other one as the other part, duplicate saving, was resolved.

https://github.com/SpongePowered/SpongeForge/issues/2812#issuecomment-500548560

**Comment by bluelightning32** [comment]
I filed a new bug for this:
https://github.com/micdoodle8/Galacticraft/issues/3775

**Comment by radfast** [comment]
> Now with that out of the way, you have even more issues that I don't think are Sponge related:

> [19:01:14] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (nex:nether/-1)
> [19:04:10] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (galacticraftcore:space_station/-1)

> I explictly changed the log entries in SpongeCommon for this reason and this reason alone. When your Nether loads, it is a nex:nether DimensionType. Sometime afterwards, Galacticraft is changing the DimensionType to galacticraftcore:space_station. This is likely the root of your issues.

Thank you very much @Zidane @bluelightning32 this has led to us finding and fixing a long-standing bug in Galacticraft.  When creating a new SpaceStation dimension, due to a typo, we were setting the DimensionType of the wrong dimension, -1 instead of the intended Galacticraft space station dimension ID.
