### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by mistek131995** [SpongePowered/SpongeForge#2755]
- SpongeForge version: 1.12.2-2825-7.1.6-RC3708
- Forge version: 14.23.5.2838
- Java version: 8 211 build 1.8.0_211-b12
- Operating System: Windows Server 2012 x64

```
[08:34:43] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:305) [SpongeImplHooks.class:1.12.2-2825-7.1.6-RC3708]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3965) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
	at com.jolteffect.thermalsolars.items.ItemTitaniumHammer.func_180614_a(ItemTitaniumHammer.java:223) ~[ItemTitaniumHammer.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:2992) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:963) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zjb000(NetHandlerPlayServer.java:2430) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2825-7.1.6-RC3708]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
```

**Comment by phit** [comment]
thermalsolars is calling a client only method on the server, report it to them nothing to do with Sponge
