### ISSUE TITLE
Error when start server. Instant-Massive-Structures-Mod 1.12.2

### ISSUE THREAD

**Issue by TheLimmo** [SpongePowered/SpongeForge#2771]
Instant-Massive-Structures-Mod 1.12.2

https://pastebin.com/5T70JFCt

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SignPictureCorePlugin (SignPicture-Mod-1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 23.05.19 19:02
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 32 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@435ce306 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 40 more
Caused by: java.lang.RuntimeException: Attempted to load class bsb for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6663201880 bytes (6354 MB) / 6848774144 bytes (6531 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 2 total; -Xms6G -Xmx9G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version      | Source                                                      | Signature                                |
	|:----- |:---------------------- |:------------ |:----------------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft              | 1.12.2       | minecraft.jar                                               | None                                     |
	| UC    | mcp                    | 9.42         | minecraft.jar                                               | None                                     |
	| UC    | FML                    | 8.0.99.99    | forge-1.12.2-14.23.5.2768-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                  | 14.23.5.2768 | forge-1.12.2-14.23.5.2768-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | obfuscate              | 0.2.6        | minecraft.jar                                               | None                                     |
	| UC    | architecturecraft      | @VERSION@    | architecturecraft-1.12-2.68.jar                             | None                                     |
	| UC    | mts                    | 12.2.1       | MinecraftTransportSimulator_1.12.2_12.2.1.jar               | None                                     |
	| UC    | unuparts               | 1.6.1        | UNUPartsPackMTS1.10.2_12.2.0_1.6.1.jar                      | None                                     |
	| UC    | blackthorne            | 1.6.1        | BlackThorneEmpireVehiclesMTSIR1.10.2_12.2.0_1.4.1_1.6.1.jar | None                                     |
	| UC    | customnpcs             | 1.12         | CustomNPCs_1.12.230Jan19.jar                                | None                                     |
	| UC    | ptrmodellib            | 1.0.0        | Decocraft-2.5.5_1.12.2.jar                                  | None                                     |
	| UC    | props                  | 2.5.5        | Decocraft-2.5.5_1.12.2.jar                                  | None                                     |
	| UE    | imsm                   | 1.12         | Instant-Massive-Structures-Mod-1.12 (1).jar                 | None                                     |
	| U     | mtsseagullcivilpack    | 2.0.0        | MTS+Seagull's+civil+pack+1.11.0.jar                         | None                                     |
	| U     | mtsseagulltrinpartpack | 1.0.0        | MTS+seagull's+trin+parts+pack+1.4.0.jar                     | None                                     |
	| U     | mtsofficialpack        | 8.0.0        | MTS_Official_Pack_V08.jar                                   | None                                     |
	| U     | rcroads                | 0.3.0        | RC+Roads+0.3.0.jar                                          | None                                     |
	| U     | rebelcraft             | 0.1          | RebelCraftV022.jar                                          | None                                     |
	| U     | signpic                | 2.8.1        | SignPicture-Mod-1.12.2.jar                                  | None                                     |
	| U     | t3gssksignspack        | 1.0.1        | tim3gameseuropeansignspack1.0.1.jar                         | None                                     |
	| U     | vehicle                | 0.33.0       | vehicle-mod-0.33.0-1.12.2.jar                               | None                                     |
	| U     | imvoice                | 0.7.0        | voicechat-1.12.2-0.7.0.jar                                  | None                                     |
	| U     | worldedit              | 6.1.8        | worldedit_forge_mc1.12_6.1.8_dist.jar                       | None                                     |

	Loaded coremods (and transformers): 
SignPictureCorePlugin (SignPicture-Mod-1.12.2.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by phit** [comment]
none of these include sponge, and you ignored the issue template

**Comment by TheLimmo** [comment]
И что мне делать?
