### ISSUE TITLE
Stable - Start up crash - Critical injection failure: Redirector - Tinkers construct

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2805]
**I am currently running**

- SpongeForge version: 7.1.6 STABLE
- Forge version: 2815
- Java version: 8
- Operating System: Debian 9
- Modpack: SevTech 3.1.1

- Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, CatClearLag, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, RankUpper, Sledgehammer, TimeWarp

- Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Block of Charcoal, AbyssalCraft, AbyssalCraft Integration, Actually Additions, Actually Baubles, Advanced Generators, Advanced Mortars, Antique Atlas, AppleCore, AppleSkin, Applied Energistics 2, ArmoreableMobs, Aroma1997Core, AstikorCarts, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, BNBGamingLib, Baubles, Bedrock-B-Gone, Better Builder's Wands, Better With Lib, Better With Mods, Better with Addons, BiblioCraft, Blood Magic: Alchemical Wizardry, BnBGamingCore, Bonsai Trees, Bookshelf, BuildCraft, BuildCraft Builders, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, Building Gadgets, CD4017BE_lib, Caliper, Ceramics, Chameleon, Chargers, Chisel, Chisels & Bits, Clumps, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Despawning Spawners, Dimension Stages, Dimensional Control, Dung Pipe, Elevator Mod, EmberRoot Zoo, Ender Utilities, EnderStorage, Environmental Tech, Extended Crafting, Extra Planets, Farming for Blockheads, Farseek, FastFurnace, FastWorkbench, Ferdinand's Flowers, FindMe, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, Game Stages, Geolosys, Gobble Core, Guide-API, Harvest, Horse Power, Hunting Dimension, Immersive Craft, Immersive Engineering, Immersive Petroleum, Immersive Tech, Improved Backpacks, In-Game wiki Mod, InControl, Inductive Logistics, Industrial Foregoing, Info Accessories, Integrated Dynamics, IntegratedDynamics-Compat, Inventory Tweaks, Iron Backpacks, Iron Chest, Iron Jetpacks, Item Stages, IvToolkit, JourneyMap, Just A Raft Mod, Just Enough Items, Just a Few Fish, JustEnoughIDs, KleeSlabs, LibEx, Loot Table Tweaker, MJRLegendsLib, MTLib, Mantle, McJtyLib, MekaTweaks, Mekanism, Mercurius, Micdoodle8 Core, Minecraft Multipart Plugin, Mo' Bends, Mo' Villages, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, Modular Machinery, Modular Routers, Morpheus, Multiblockstages, Mundane Redstone, Mystical Agradditions, Mystical Agradditions Compat, Mystical Agriculture, Natura, Nature's Compass, NetherEx, No World Gen 5 You, Nutrition, Ocean Floor Classic, Ore Stages, OreExcavation, OreExcavation Integration, Overloaded, Pickle Tweaks, Placebo, Player Skin Mobs, PneumaticCraft: Repressurized, Power Adapters, Prestige, PrimalChests, PrimalCore, Progression Tweaks, Prospectors, QuantumStorage, Quark, Quick Leaf Decay, RFTools, RFTools Control, RandomPatches, Ranged Pumps, Realistic Item Drops, Reborn Core, RebornStorage, RecipeStages, Recurrent Complex, Redstone Flux, Refined Storage, Refined Storage Addons, Road Runner, Rustic, Sampling Performance Profiler, Scannable, SevTweaks, Shadowfacts' Forgelin, Simple Generators, Simple Storage Network, SimpleAutoRun, Simply Arrows, Smooth Font Core, Spartan Shields, Spatial Server Mod, SpongeForge, Steve's Carts 2, Storage Drawers, Streams, Stuff A Sock In It, Super Sound Muffler, SwingThroughGrass, TallGates, Tesla Core Lib, Tesla Core Lib Registries, The Beneath, The Betweenlands, The Twilight Forest, The Weirding Gadget, Thirsty Bottles, Tinker Stages, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, To the Bat Poles!, Totemic, Translocators, Traverse, Triumph, Trumpet Skeleton, Tumbleweed, Ultimate Car Mod, Universal Modifiers, Valkyrie Lib, ViesCraft, Villager Trade Tables, Waddles, Waila, Waila Stages, WanionLib, Water Control Extreme, Water Strainer, What Are We Looking At, Wild Crops, Wither Skeleton Tweaks, Wopper, World Stripper, WorldEdit, XNet, YNot, Yoyos, ZenStages, animalium, death_compass, fat_cat, galacticrafttweaker, magma_monsters, mob_grinding_utils, playerbosses, primal_tech, sev_tweaks_npc, uppers

**Issue Description**

Updating SevTech server to latest sponge stable results in the following start up crash:
https://pastebin.com/QgH6Sgyn

[2019-06-06-7.log](https://github.com/SpongePowered/SpongeForge/files/3262253/2019-06-06-7.log)

**Comment by Yorkforce** [comment]
Still occuring on 3768

[crash-2019-06-07_17.01.52-server.txt](https://github.com/SpongePowered/SpongeForge/files/3266500/crash-2019-06-07_17.01.52-server.txt)

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3266501/latest.log)

[debug.log](https://github.com/SpongePowered/SpongeForge/files/3266502/debug.log)

**Comment by gabizou** [comment]
I'm going to need you to find out which mods specifically combined with SpongeForge cuase the problem. A coremod is modifying the Forge class which breaks Sponge's injection. Running Tinkers Construct and SpongeForge alone doesn't break (as it shouldn't).


For future readers: Please read the actual log as it shows what class was not available:
```
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$afterCanFlowInto$bcm000(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;I)Z in mixins.forge.core.json:forge.fluids.MixinBlockFluidClassic failed injection check, (0/1) succeeded. Using refmap mixins.forge.refmap.json
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.buildEvents(EventSubscriptionTransformer.java:106)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:82)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.Class.getDeclaredMethods0(Native Method)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.Class.privateGetPublicMethods(Class.java:2902)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.Class.getMethods(Class.java:1615)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.reflect.Method.invoke(Method.java:498)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.reflect.Method.invoke(Method.java:498)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[20:13:32] [Server thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:   at java.lang.Thread.run(Thread.java:748)
[20:13:32] [Server thread/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber crazypants.enderio.base.fluid.Fluids for modid enderio
java.lang.NoClassDefFoundError: com/enderio/core/common/fluid/BlockFluidEnder
    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_201]
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_201]
    at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_201]
    at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_201]
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
    at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) [AutomaticEventSubscriber.class:?]
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599) [FMLModContainer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
    at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: com.enderio.core.common.fluid.BlockFluidEnder
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
    ... 39 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fluids/BlockFluidClassic
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_201]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_201]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
    ... 39 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fluids.BlockFluidClassic
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_201]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_201]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
    ... 39 more
```

Someone is modifying `net.minecraftforge.fluids.BlockFluidClassic` and causing Sponge's redirect to fail, leading to modded block liquids to fail to classload (because their superclass didn't load).

**Comment by gabizou** [comment]
So, re-testing this with SevTech: Ages 3.1.1 and Sky Odyssey 1.1.0 still starts up fine with 3768...

Can you zip up the mods, config, and any other support files to reproduce the issue without the world?

**Comment by gabizou** [comment]
Nevermind. Update your Forge...

    | LC    | forge                    | 14.23.5.2815             | FTBserver-1.12.2-2815-universal.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
is what is distributed, SpongeForge already builds against specific build numbers for a reason. It's currently building against Forge 2825, which has [this very important commit that would otherwise change our redirect](https://github.com/MinecraftForge/MinecraftForge/commit/af4fcd73a47cca997822b30ea3578d976fc52c84#diff-7a4080f44d588c7e224a300aa0d942ecR284).

Not a sponge bug.

**Comment by Yorkforce** [comment]
Just wanted to add, there is no problem at all with RC3760.

I'll try updating forge, usually we just use whatever the modpack gives us but i can't foresee any major problems using 2825 instead of 2815. Thanks gabizou :)

**Comment by gabizou** [comment]
> Just wanted to add, there is no problem at all with RC3760.

Yes, because I implemented custom mod fluid tracking in the newer builds, and that has a *hard dependency requirement on a specific (or newer) version of Forge*. Of course rolling back versions will give you the ability to run older versions of Forge with SpongeForge building against a newer version. Just update Forge and call it a day...

**Comment by HenryLoenwind** [comment]
BTW: That is what the dependencies on the mod container are for...
