### ISSUE TITLE
As a user I'd like to see the plugins listed in the crash log.

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#2811]
This issue was originally submitted by @ryantheleach in [SpongePowered/SpongeCommon#1777](https://github.com/SpongePowered/SpongeCommon/issues/1777).
___
Forge already lists mods, api's and core mods in the minecraft crash log.

Could/Should we add a plugin section to say what plugins were enabled?

**Comment by Zidane** [comment]
Closed in latest SF

**Comment by Zidane** [comment]
Example:

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/8/19 2:46 PM
Description: Exception ticking world entities

java.lang.RuntimeException
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zme000(WorldServer.java:3269)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:4543)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:871)
	at net.minecraft.world.World.updateEntity(World.java:2142)
	at net.minecraft.world.World.updateEntities(World.java:7176)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:2377)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:415)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zme000(WorldServer.java:3269)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -2083747434342260854
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (84,64,252), Chunk: (at 4,4,12 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 913 game time, 913 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 176850 (now: false), thunder time: 135087 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zme000(WorldServer.java:3269)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:4543)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:871)
	at net.minecraft.world.World.updateEntity(World.java:2142)

-- Entity being ticked --
Details:
	Entity Type: minecraft:chicken (net.minecraft.entity.passive.EntityChicken)
	Entity ID: 2
	Entity Name: Chicken
	Entity's Exact location: -95.50, 93.00, 68.50
	Entity's Block location: World: (-96,93,68), Chunk: (at 0,5,4 in -6,4; contains blocks -96,0,64 to -81,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:7176)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:2377)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -2083747434342260854
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (84,64,252), Chunk: (at 4,4,12 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 913 game time, 913 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 176850 (now: false), thunder time: 135087 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjo000(MinecraftServer.java:4196)
	at net.minecraft.server.MinecraftServer.addServerInfoToCrashReport(MinecraftServer.java:991)
	at net.minecraft.server.dedicated.DedicatedServer.addServerInfoToCrashReport(DedicatedServer.java:386)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 511731336 bytes (488 MB) / 993001472 bytes (947 MB) up to 7621050368 bytes (7268 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2825 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State  | ID                  | Version      | Source                                                | Signature |
	|:------ |:------------------- |:------------ |:----------------------------------------------------- |:--------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                                         | None      |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                                         | None      |
	| LCHIJA | FML                 | 8.0.99.99    | forgeSrc-1.12.2-14.23.5.2825-PROJECT(SpongeForge).jar | None      |
	| LCHIJA | forge               | 14.23.5.2825 | forgeSrc-1.12.2-14.23.5.2825-PROJECT(SpongeForge).jar | None      |
	| LCHIJA | spongeapi           |              | SpongeForge.main                                      | None      |
	| LCHIJA | sponge              |              | SpongeForge.main                                      | None      |
	| LCHIJA | spongeforge         |              | SpongeForge.main                                      | None      |
	| LCHIJA | customitemdroptest  | 1.0          | SpongeForge.testmods.main                             | None      |
	| LCHIJA | grassswapper        | 1.0          | SpongeForge.testmods.main                             | None      |
	| LCHIJA | icommandsender-test | 1.0          | SpongeForge.testmods.main                             | None      |
	| LCHIJA | serverchateventtest | 1.0          | SpongeForge.testmods.main                             | None      |


	Plugins:

	| State  | ID                            | Version     | Source                                    | Signature |
	|:------ |:----------------------------- |:----------- |:----------------------------------------- |:--------- |
	| LCHIJA | activeitemdatatest            | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | advancement_test              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | boat_type_test                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | book_pages_test               | 1.0         | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | bucket_cancel_test            | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | cause-stack-test              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | change_block_test             | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | changeentityequipmenttest     | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | command-test                  | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | cooldowntracker               | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | copypasta                     | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | custominventorytest           | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | damageabledatatest            | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | damagesourcetest              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | data_translator_test          | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | deathtest                     | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | dispenserfiretest             | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | elytratest                    | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | enchantmenttest               | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | entityspawntest               | 0.1.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | flowerpottest                 | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | furnacesmelttest              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | get_user                      | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | humanaitest                   | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | ignitetest                    | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | individual-plugin-reload-test | 1.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | injection-test                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | instrumenttest                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | inventoryopenclosetest        | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | inventoryplugintest           | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | inventoryquerytest            | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | inventorysetoperationstest    | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | invulnerabilitytest           | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | itemtest                      | 1.0         | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | join_data_test                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | main_test                     | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | msg-channel-event-test        | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | metricheck                    | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | moveentitytest                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | myhomes                       | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | myranks                       | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | offlineinventorytest          | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | offlinelocationtest           | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | paginationtest                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | pardoneventtest               | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | parrotdatatest                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | pistontest                    | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | potion_type_test              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | record_test                   | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | respawnspectatortest          | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | scaledhealthtest              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | selector-test                 | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | selectortexttest              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | shulkertest                   | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | skulltest                     | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | stopsoundtest                 | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | targetaieventtest             | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | thrown-potion-test            | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | hoppereventtest               | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | villager_grief                | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | witherspawntest               | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | world-limit-test              | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | world-rename-test             | 0.0.0       | SpongeForge.SpongeCommon.testplugins.main | None      |
	| LCHIJA | nucleus                       | 1.10.0-S7.1 | Nucleus-1.10.0-S7.1-MC1.12.2-plugin.jar   | None      |

	Loaded coremods (and transformers): 
SpongeCoremod (unknown)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```
