### ISSUE TITLE
NoSuchFieldError isFake Crash

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#2813]
**I am currently running**

- SpongeForge version: 7.1.7-RC3777
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212
- Operating System: Centos 7

- Mods (206): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Phosphor Lighting Engine, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, RandomPatches, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Sampling Performance Profiler, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

- Plugins (36): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, AsciiEmotes, BacoMaster, BetterChunkLoader, CatClearLag, CommandUtils, EasyTexts, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyUI, KitSuiteEC, Lottery, LuckPerms, MMCRestrict, Market, NuVotifier, Nucleus, PlaceholderAPI, Player Glow, SeriousVote, SkyClaims, Sledgehammer, TabManager, TeslaCore, TeslaCrate, TeslaLibs, Unity, VoteParty, WelcomeRewards, spark

**Issue Description**
Updating from RC3776 to RC3777 causes the server to crash whenever someone tries to join.
Crash report can be viewed here: https://gist.github.com/kristi71111/6d5a68a1e84d5a53a96091c54ec425f8
If you require any more information please let me know

**Comment by gabizou** [comment]
Going to neee the full log, and start the server with -Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true to output the CLASSLOADER_TEMP folder. Either Sponge’s mixins are not applying, or another coremod is stripping Sponge’s field.

**Comment by kristi71111** [comment]
Full log from test instance with exact same setup.
Since I can't use gist or upload directly here since the file limit exceeds 10 MB's I am attaching a google drive link. If you require the CLASSLOADER_TEMP directory aswell please tell me and I will attach it.
Latest.log: [Here](https://drive.google.com/file/d/1iaYnDbQdv3iw3xISUlSiFJxcDhHkOM5B/view?usp=sharing)

**Comment by gabizou** [comment]
> If you require the CLASSLOADER_TEMP directory aswell please tell me and I will attach it.

Yes..... I do need it.

**Comment by kristi71111** [comment]
> > If you require the CLASSLOADER_TEMP directory aswell please tell me and I will attach it.
> 
> Yes..... I do need it.

CLASSLOADER_TEMP.zip: [Here](https://drive.google.com/file/d/1FdbfNZdBpY7MphypxwmZ-5yEC4Yoxy3K/view?usp=sharing)

**Comment by gabizou** [comment]
From the log:
```
[10:57:00] [main/WARN] [mixin]: Mixin apply failed mixins.common.realtime.json:MixinEntityPlayer_RealTime -> net.minecraft.entity.player.EntityPlayer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Error whilst instancing injection point org.spongepowered.asm.mixin.injection.points.BeforeConstant for CONSTANT
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Error whilst instancing injection point org.spongepowered.asm.mixin.injection.points.BeforeConstant for CONSTANT
	at org.spongepowered.asm.mixin.injection.InjectionPoint.create(InjectionPoint.java:637) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.InjectionPoint.parse(InjectionPoint.java:601) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.InjectionPoint.parse(InjectionPoint.java:574) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.InjectionPoint.parse(InjectionPoint.java:544) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.code.MethodSlice.parse(MethodSlice.java:477) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.code.MethodSlices.parse(MethodSlices.java:105) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:157) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:39) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:478) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1180) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:929) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:317) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_212]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [?:1.8.0_212]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_212]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_212]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_212]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_212]
	at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_212]
	at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_212]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [server.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [server.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at org.spongepowered.asm.mixin.injection.InjectionPoint.create(InjectionPoint.java:635) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	... 41 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: No constant discriminator could be parsed in @At("CONSTANT") args
	at org.spongepowered.asm.mixin.injection.points.BeforeConstant.<init>(BeforeConstant.java:186) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at org.spongepowered.asm.mixin.injection.InjectionPoint.create(InjectionPoint.java:635) ~[malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	... 41 more
```

Disable realtime optimization. It's failing to apply and the config option already has a warning about mod compatibility.
