### ISSUE TITLE
Player#respawnPlayer error

### ISSUE THREAD

**Issue by Zeon8** [SpongePowered/SpongeForge#2878]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6
- Java version: 1.8.0_201
- Operating System: Windows 10

- Mods:
guns-0.12.1-1.12.2
obfuscate-0.2.6-1.12.2
PUBGMC-1.5.4

**Issue Description**
When player killed plugin must force respawn player
```
  @Listener
  public void  onPlayerKilled(DestructEntityEvent.Death event, @First Player player){
        if(player.respawnPlayer()){
            player.offer(Keys.GAME_MODE,GameModes.SPECTATOR);
        }
  }
```
But error in console
```
[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:3895) ~[oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3639) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) ~[oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1318) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_180430_e(EntityPlayer.java:1946) ~[aed.class:?]
        at net.minecraft.block.Block.func_180658_a(Block.java:821) ~[aow.class:?]
        at net.minecraft.entity.Entity.redirect$onBlockFallenUpon$zec000(Entity.java:6009) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_184231_a(Entity.java:1132) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:215) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:838) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:585) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) ~[lk$a.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2825-7.1.6]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
```

**Comment by XakepSDK** [comment]
https://gist.github.com/

**Comment by KorewaLidesu** [comment]
That not even a full link, it just direct to the gist homepage, not your log

**Comment by Zidane** [comment]
Wait a sec,

Your listener is making it so that when an entity dies and a Player is in the cause, respawn that Player and offer them the spectator gamemode key...

If the Player is in the cause, that could mean the Player caused it's own death OR the death of another. Was this intentional?

Anyways, when a Player respawns their Player object is re-created (this is a Vanilla quirk). You must re-query the Player object in this case (from `Server` would work using the old Player object's UUID) and set the gamemode on that.
