### ISSUE TITLE
Asynchronous illumination problem

### ISSUE THREAD

**Issue by DJmanito** [SpongePowered/SpongeForge#2888]
This problem seems to appear in the newer version (I'm not sure, but the last minecart problem caused me to update to the latest version, and there were some problems before).
Players and animals walk into certain locations and then suddenly disappear in the client until they step out of the zone (which is also true in older versions).
After walking to a location, wildly brush error, and this area should not exist in the light.
`[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=Sponge - Async Light Thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:87)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.common.event.SpongeCauseStackManager.pushCauseFrame(SpongeCauseStackManager.java:205)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.redirect$impl$createEntityFromCompound$zlm000(AnvilChunkLoader.java:1394)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:528)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:485)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.redirect$impl$ProvideChunkForced$zlo000(ChunkProviderServer.java:1145)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.World.func_72964_e(World.java:310)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.World.func_175726_f(World.java:305)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.World.func_175625_s(World.java:7722)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at ic2.core.block.BlockTileEntity.getTe(BlockTileEntity.java:929)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at ic2.core.block.BlockTileEntity.getLightOpacity(BlockTileEntity.java:635)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightOpacity(BlockStateContainer.java:504)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.common.SpongeImplHooks.getBlockLightOpacity(SpongeImplHooks.java:2570)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.chunk.Chunk.func_150808_b(Chunk.java:5387)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.chunk.Chunk.asyncLighting$relightBlockAsync(Chunk.java:6224)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.chunk.Chunk.lambda$asyncLighting$onRelightBlock$3(Chunk.java:6201)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:44:49] [Sponge - Async Light Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)`

The problem has been resolved with asynchronous lighting turned off
However, we have not yet completed the specific test, because we have another question :"Unable to send server icon to client".
I have now returned spongeft-1.12.2-2825-7.1.6 and continue to turn off asynchronous lighting

My English is not very good. Please forgive me if there are some mistakes in my expression. The following is my original Chinese meaning:
这个问题出现在较新的版本(但是我不确定，上次因为矿车问题导致我更新到了最新版本,但是在这之前也存在一些可能相关的问题)
玩家和动物进入一些没有经过操作的原生"特殊"区域就会突然消失在其他玩家的客户端里，知道他们走出区域(这在较早的版本中也一直存在)
走到一个位置之后，疯狂刷报错(报错内容已经在上面贴出)，而这个区域不应该存在任何光照

**Comment by DJmanito** [comment]
These errors will continue as long as there is a player nearby who places/breaks or does something else.
只要附近有玩家放置/破坏或者其他操作，这些报错就会一直出现。

**Comment by liach** [comment]
hmm, ic2 querys light from tile entity, which sponge async lighting dislikes. consider turning it off.

跟工业冲突，关下异步光照计算

**Comment by Zidane** [comment]
As liach mentioned, IC2 when getting the light opactiy of a block is calling for a TileEntity which is not loaded which causes a Chunk to be loaded which fires an event which triggers the warning.

You will need to disable async lighting for this function of ic2 to work.
