### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by DJmanito** [SpongePowered/SpongeForge#2889]
I am currently running
-   Minecraft: 1.12.2
-   SpongeAPI: 7.1.0-fb496dbf0
-   Sponge: 1.12.2-7.1.6
-   SpongeForge: 1.12.2-2825-7.1.6
-   Minecraft Forge: 14.23.5.2838
-   JVM: 1.8.0_201/64-bit (Oracle Corporation)
-   OS: Windows Server 2016 (10.0/amd64)

``` [Netty Server IO #7/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
        at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_201]
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[NioSocketChannel.class:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [AbstractChannel$AbstractUnsafe.class:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [AbstractNioChannel$AbstractNioUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

I'm sure this has nothing to do with any plugins or mods.
This can happen even on the empty end.
I know this is caused by the network between the player and the server.
But sometimes this stuff comes up a lot, sometimes it's repeated hundreds of times in the log and in the background, tens of thousands of lines.
As a result, sometimes I can't work at all in the background and check the above contents. It will be very troublesome to read some information in the log, and most importantly, it will affect my mood.
Even in the latest version of spongeforge, this will happen
But we have another problem :"Unable to send server icon to client."
So I haven't used the latest version of spongeforge, but I've tried it, and it still shows up, sometimes just once, and sometimes, as it says above, indefinitely.
At present, it is known that if the player exits the server with the software directly shut down, then it must happen once. Although I know this is a normal situation, most people know this is a network problem and do not want to see him.
I asked this question on MCBBS in China, and they all replied that this is an old problem. I hope there can be a solution to this problem.

My English is not very good. Please forgive me if there are some mistakes in my expression. The following is my original Chinese meaning:
我确定这和任何插件或者模组无关，因为问题甚至可以发生在空的服务器端。
我知道这个是玩家和服务器的网络问题导致的。
但有时这个东西会出现很多次，有时它会在日志中重复数百次在后台，成千上万行。
因此，有时我根本无法在后台工作，查看上面的信息，并且在阅读日志的时候会很麻烦，最最重要的是，它会影响我的心情。
即使是最新版的spongeforge也会有这样的情况
但是因为我的另外一个问题:"Unable to send server icon to client. "
所以我没有使用最新版本的spongeforge,但是我试过，它依旧出现，有时只出现一次，有时会像上面说的，无限重复好久好久
目前已知，如果玩家退出服务器的时候是直接关闭的软件，那么就必定会出现一次.虽然我知道这是正常情况，但是通常情况大多数人都知道这是网络问题,并不想看到他。
我在中国的mcbbs上问过这个问题，他们都回答我这是老毛病，我希望可以有一个办法可以解决这个问题。

**Comment by DJmanito** [comment]
Or should I send this problem back to forge?Because this is an error report from FML.
还是说我应该把这个问题反馈给forge那边？因为这个是FML发出的报错。

**Comment by Zidane** [comment]
This is more likely an issue with the Netty version used in 1.12. Not a Sponge issue. @phit has some info on upgrading Netty on your local server install. The only time Netty will be bumped is on Mojang's or Forge's end (and won't happen with Forge...) and that is only on a major Minecraft version. Next chance would be 1.15
