### ISSUE TITLE
java.lang.IllegalAccessError: tried to access method net.minecraft.tileentity.TileEntity

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2896]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3856
- Forge version: forge-1.12.2-14.23.5.2838-universal
Draconic-Evolution-1.12.2-2.3.22.343-universal

**Issue Description**
Tried updating from 3768 to 3856 but getting the crash below on startup.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Draconic Evolution (draconicevolution)
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.tileentity.TileEntity.func_190560_a(Ljava/lang/String;Ljava/lang/Class;)V from class net.minecraftforge.fml.common.registry.GameRegistry
	at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:234)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.registerFeatureBlock(ModFeatureParser.java:248)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.registerMod(ModFeatureParser.java:207)
	at com.brandon3055.brandonscore.CommonProxy.registerModFeatures(CommonProxy.java:85)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.registerModFeatures(ModFeatureParser.java:178)
	at com.brandon3055.draconicevolution.DraconicEvolution.preInit(DraconicEvolution.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4720)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4720)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gabizou** [comment]
Can you package the `CLASSLOADER_TEMP` directory after adding `-Dlegacy.debugClassLoader=true -Dlegacy.debugClassLoaderSave=true`? Also a full log would be nice to have as there might be some other transformer in the chain causing the `TileEntity.register` method to be re-elevated from `public` to `private`.

**Comment by gabizou** [comment]
Going to need some sort of response, or trying on a newer version of SF... I still can't reproduce this in production and in dev...

**Comment by Zidane** [comment]
Closing. Will re-open when we have received a response.

**Comment by Sir-Will** [comment]
Still an issue with the latest version and the `CLASSLOADER_TEM` directory is not being created although both jvm flags are set.

https://gist.github.com/Sir-Will/0c93fa5b8fcf5aa312747e7380a2ff59

**Comment by Zidane** [comment]
Um, this is not coming from Sponge code:

```
2019-08-13 23:19:01 | [ERROR] Encountered an unexpected exception
2019-08-13 23:19:01 | [RAW] net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Draconic Evolution (draconicevolution)
2019-08-13 23:19:01 | [RAW] 
2019-08-13 23:19:01 | [RAW] Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.tileentity.TileEntity.func_190560_a(Ljava/lang/String;Ljava/lang/Class;)V from class net.minecraftforge.fml.common.registry.GameRegistry
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:234) ~[GameRegistry.class:?]
2019-08-13 23:19:01 | [RAW] 	at com.brandon3055.brandonscore.registry.ModFeatureParser.registerFeatureBlock(ModFeatureParser.java:248) ~[ModFeatureParser.class:?]
2019-08-13 23:19:01 | [RAW] 	at com.brandon3055.brandonscore.registry.ModFeatureParser.registerMod(ModFeatureParser.java:207) ~[ModFeatureParser.class:?]
2019-08-13 23:19:01 | [RAW] 	at com.brandon3055.brandonscore.CommonProxy.registerModFeatures(CommonProxy.java:85) ~[CommonProxy.class:?]
2019-08-13 23:19:01 | [RAW] 	at com.brandon3055.brandonscore.registry.ModFeatureParser.registerModFeatures(ModFeatureParser.java:178) ~[ModFeatureParser.class:?]
2019-08-13 23:19:01 | [RAW] 	at com.brandon3055.draconicevolution.DraconicEvolution.preInit(DraconicEvolution.java:54) ~[DraconicEvolution.class:?]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568) ~[LoadController.class:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) ~[Loader.class:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
2019-08-13 23:19:01 | [RAW] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
2019-08-13 23:19:01 | [RAW] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Zidane** [comment]
Gonna try something, sec.

**Comment by Zidane** [comment]
Yeah @Sir-Will I don't see anything we're doing that will affect this. All we do is inject into the register method to call our stuff that we've done, literally, for ages now.

https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/tileentity/TileEntityMixin.java#L87

**Comment by Sir-Will** [comment]
Found the issue. I removed the warn logging of `net.minecraft.tileentity.TileEntity$create` which caused this issue since the update.
Not sure what changed in sponge that this started to cause issues now.

**Comment by Zidane** [comment]
@Sir-Will Not sure what to say beyond us only using AT entries when we need to now (in favor of accessors) and tossing a bunch of overwrites. Both of which end up with the same net result. I think you have something else going on...
