### ISSUE TITLE
Sponge + Vazkii's Crucial modpack crash when making a nether portal

### ISSUE THREAD

**Issue by yagomont** [SpongePowered/SpongeForge#2921]
**I am currently running**

- SpangForge version: spongeforge-1.12.2-2838-7.1.7-RC3875.jar (happens on latest, too)
- Forge version: 2838
- Java version: Eclipse OpenJ9 212
- Operating System: Ubuntu Server

- Plugins/Mods:
Mods (84): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Additional Ender Blocks, Antique Atlas, AutoRegLib, B.A.S.E, BNBGamingLib, Bed Patch, BnBGamingCore, Bubble Column Elevator, Chameleon, Charm, Charset, Chunk Pregenerator, Clarity, Clumps, Comforts, Concrete Extends, ContentTweaker, Coralreef, Cosmetic Beds, CraftTweaker JEI Support, CraftTweaker2, Diet Hopper, Dynamic Surroundings, DynamicSurroundingsCore, Earthworks, Erosion, Extra Alchemy, Familiar Fauna, Fast Leaf Decay, FastWorkbench, FoamFix, FoamFixCore, Future MC, HammerX, Hat Stands, Ido - 1.12 movement enhancement, Inspirations, Just Enough Items, Just a Few Fish, LadyLib, LagGoggles, LibEx, Loot Table Tweaker, Lumen, MTLib, Mantle, Mod Tweaker, Multi Mob Core, Nether Chest, NetherEx, Not Enough Cats, Not Enough Scaffold, Ocean Floor Classic, Ore Stone Variants, OreLib Support Mod, Patchouli, Phosphor Lighting Engine, Plated, Primitive Mobs, Quark, Quark Oddities, RandomPatches, Redstone PCB, Redstone++, Sandro's Core, SpongeForge, Storage Drawers, Stygian End, Surge, SwingThroughGrass, Trap Expansion, Traverse, Triumph, Unmending, Wards, World Primer, Worley's Caves

Plugins (8): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Boop, MagiBridge, Nucleus, spark

**Issue Description**
The server crashes if you make a nether portal, the crash does only happen with Sponge installed.

https://gist.github.com/yagomont/a4c9c9ed682e0a23201c1f1a126c18b8

**Comment by yagomont** [comment]
With newest sponge the server just crashes on startup

**Comment by Zidane** [comment]
Need to see the log from the latest SpongeForge.

**Comment by yagomont** [comment]
https://gist.github.com/yagomont/0d063245331404891072e9d80992cec2
There's no crash log, the server just immediately dies after printing that last line
Oh, this is caused by LagGoggles according to #2924

**Comment by gabizou** [comment]
Yep, LagGoggles needs to update.

**Comment by yagomont** [comment]
Please reopen this, laggogles is the cause of the crash in latest, but the nether portal crash stays unresolved even without Lagoggles.

**Comment by Zidane** [comment]
The nether portal crash isn't us:

```
java.lang.NoClassDefFoundError: net.minecraft.client.multiplayer.WorldClient
        at knightminer.inspirations.tweaks.TweaksEvents.updatePortal(TweaksEvents.java:375) ~[TweaksEvents.class:?]
        at knightminer.inspirations.tweaks.TweaksEvents.updatePortalPlace(TweaksEvents.java:360) ~[TweaksEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_608_TweaksEvents_updatePortalPlace_PlaceEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1252) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1207) [EventBus.class:?]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostBlockPlaceEvent(SpongeToForgeEventFactory.java:794) [SpongeToForgeEventFactory.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:247) [SpongeToForgeEventFactory.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:337) [SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:446) [SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:415) [SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:247) [SpongeImpl.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:569) [spongeforge-1.12.2-2838-7.1.7-RC3875.jar:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:440) [spongeforge-1.12.2-2838-7.1.7-RC3875.jar:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.UnwindingState.unwind(UnwindingState.java:181) [UnwindingState.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.UnwindingState.unwind(UnwindingState.java:53) [UnwindingState.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:309) [spongeforge-1.12.2-2838-7.1.7-RC3875.jar:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:612) [PhaseContext.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:314) [spongeforge-1.12.2-2838-7.1.7-RC3875.jar:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:612) [PhaseContext.class:1.12.2-2838-7.1.7-RC3875]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:194) [PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3875]
        at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zkn000(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3875]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjb000(MinecraftServer.java:4715) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:819) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]
        ... 34 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@c795b732 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]
        ... 34 more
Caused by: java.lang.RuntimeException: Attempted to load class bsb for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]
```
The mod is literally calling WorldClient, a client class, on the server. We don't strip the classes, Forge does.

I'd prove this yet the project, Inspirations, code I can find on github does not match whatever version you are running on your server. It isn't even touching BlockPlace in his repo's code:

https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/tweaks/TweaksEvents.java

**Comment by Zidane** [comment]
I see, the mod developer removed the portal code triggering from the server in his latest release. I would bump to that @yagomont

**Comment by yagomont** [comment]
Alright, thank you!
