### ISSUE TITLE
The main server thread is dead without warning.

### ISSUE THREAD

**Issue by DJmanito** [SpongePowered/SpongeForge#2926]
I'm running:
Minecraft: 1.12.2
SpongeAPI: 7.1.0-0abc85a72
Sponge: 1.12.2-7.1.7-SNAPSHOT
SpongeForge: 1.12.2-2838-7.1.7-RC3880
Minecraft Forge: 14.23.5.2838
JVM: 1.8.0_201/64-bit (Oracle Corporation)
OS: Windows Server 2019

This problem may need a prior help to pinpoint the cause of the problem:
Server main thread asymptomatic jammed, no reaction, all the players immediately kicked out of the server, but the server still showing open, some timing plugin is still in work, but only in the console display, no actual effect, all players try to be prompt you have online (at the same time, the background will show XXX trying to connect to the server, but have online), no any other message, the server will also keep this state, until shutdown ("/stop "also no response).

This is what the console looks like when it's stuck, there's no real special explanation, it's stuck, okay:

```
[19:02:14] [pool-3-thread-882/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *Wu 暂时离开了游戏。
[19:04:56] [pool-3-thread-915/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *DJ_manito 暂时离开了游戏。
[19:06:15] [pool-3-thread-884/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *Wu 回来了。
[19:07:21] [Netty Server IO #9/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_201]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_201]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[19:07:21] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: DJ_manito lost connection: Internal Exception: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
[19:07:21] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [-] DJ_manito
[19:13:38] [pool-3-thread-915/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *ping_30266ms 暂时离开了游戏。
[19:14:24] [pool-3-thread-918/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *ping_30266ms 回来了。
[19:15:31] [Netty Server IO #2/INFO] [FML]: Client protocol version 2
[19:15:31] [Netty Server IO #2/INFO] [FML]: Client attempting to join with 33 mods : minecraft@1.12.2,ctgui@1.0.0,theoneprobe@1.4.28,crafttweakerjei@2.0.3,extracells@2.6.2,thermaldynamics@2.5.5,redstoneflux@2.1.0,customskinloader@14.9,smoothfont@mc1.12.2-2.0-alpha-11,jei@4.13.1.225,mtrm@1.2.2.30,cofhcore@4.6.3,nei@2.4.2,thermalfoundation@2.6.3,wawla@2.5.269,ic2@2.8.110-ex112,mcp@9.42,smoothfontcore@mc1.12.2-2.0-alpha-7,topaddons@1.12.2-1.10.1,appliedenergistics2@rv6-stable-6,jecharacters@1.12.0-3.3.0,FML@8.0.99.99,thermalexpansion@5.5.4,customnpcs@1.12,inventorytweaks@1.62-dev-76-4165ce4,cofhworld@1.3.1,waila@1.8.26,crafttweaker@4.1.19,durabilityshow@5.0.0,forge@14.23.5.2838,codechickenlib@3.2.2.354,torohealthmod@1.12.2-11,variedcommodities@1.12.2
[19:15:31] [Netty Server IO #2/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, spongeforge, dynmap, dupefixer, serverlistplus, titlebroadcaster, pixelvip, wolrdpc, pjb, pjc, giftcode, shabbyholograms, jointitle, placeholderapi, ambershop, inspector, redprotect, nucleus, newhonor, fastasyncworldedit, worldedit, mmclogger, luckperms, karoglansigneditor, epicbanitem, mmcrestrict, flexiblelogin, virtualchest, vcench, economylite, ultimatechat, pixelautomessages, mmcreboot, mmcrules, latch, sponge_login_fix] at CLIENT
[19:15:31] [Netty Server IO #2/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
[19:15:33] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[19:15:33] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Shi_chen [/180.110.124.169:7892] logged in with entity id [165653] in spawn (minecraft:overworld/3) at (0.5, 81.0, 0.5).
[19:15:33] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [+] Shi_chen
[19:16:52] [Netty Server IO #15/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@44589f53[id=d8d689ed-895b-3a74-b229-4ae1ab836c01,name=ping_30266ms,properties={},legacy=false] (/27.215.191.234:54700): 你已在线
[19:16:54] [Netty Server IO #0/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@5278f1b2[id=f22c5100-dfce-3b82-9bff-ad464a670ab7,name=Wu,properties={},legacy=false] (/58.42.172.218:27057): 你已在线
[19:16:57] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[19:17:00] [Netty Server IO #3/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@1a2dbb79[id=917bd45b-5039-3c6b-99b3-00d71abdfcbc,name=Shi_chen,properties={},legacy=false] (/180.110.124.169:4610): 你已在线
[19:17:10] [Netty Server IO #8/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@6b5ecc70[id=917bd45b-5039-3c6b-99b3-00d71abdfcbc,name=Shi_chen,properties={},legacy=false] (/180.110.124.169:4620): 你已在线
[19:17:12] [Netty Server IO #9/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@54d70666[id=d8d689ed-895b-3a74-b229-4ae1ab836c01,name=ping_30266ms,properties={},legacy=false] (/27.215.191.234:54716): 你已在线
[19:17:15] [Netty Server IO #12/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@592051[id=83860e27-ad24-375f-81c8-51103d8150ba,name=Prawn_Fat,properties={},legacy=false] (/112.86.254.255:62143): 你已在线
[19:17:47] [Netty Server IO #15/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@49564236[id=d8d689ed-895b-3a74-b229-4ae1ab836c01,name=ping_30266ms,properties={},legacy=false] (/27.215.191.234:54737): 你已在线
[19:20:16] [Netty Server IO #3/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@4af7a525[id=83860e27-ad24-375f-81c8-51103d8150ba,name=Prawn_Fat,properties={},legacy=false] (/112.86.254.255:62214): 你已在线
[19:21:06] [pool-3-thread-923/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *Wu 暂时离开了游戏。
[19:21:08] [pool-3-thread-883/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *ping_30266ms 暂时离开了游戏。
[19:21:10] [pool-3-thread-918/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *Shi_chen 暂时离开了游戏。
[19:21:11] [pool-3-thread-918/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *Prawn_Fat 暂时离开了游戏。
[19:22:46] [Netty Server IO #7/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@435fe902[id=f22c5100-dfce-3b82-9bff-ad464a670ab7,name=Wu,properties={},legacy=false] (/58.42.172.218:27475): 你已在线
```

这个问题可能需要前置的一个帮助才能准确的找到问题的原因:
服务器主线程无征兆卡死，没有任何反应，所有玩家都立即被踢出服务器，但是服务器依旧显示开启状态，一些定时插件依旧会在工作，但是仅仅只是在控制台显示提示信息，没有实际效果，玩家尝试连入全部被提示您已在线(同时后台也会显示出 xxx尝试连接服务器，但是已在线的提示)，没有任何其他信息提示，服务器也将会一直保持这个状态下去，直到人为关闭(“/stop”也无反应)。

上面是卡死的时候控制台的状态，没有什么实际的特殊说明，就这么卡死了。

**Comment by DJmanito** [comment]
Mods (26): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Applied Energistics 2, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Dynmap, Extra Cells 2, IndustrialCraft 2, Just Enough Items, MineTweakerRecipeMaker, Redstone Flux, SpongeForge, TOP Addons, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Varied Commodities

Plugins (37): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, FastAsyncWorldEdit, AmberShop, DupeFixer, EconomyLite, EpicBanItem, FlexibleLogin, GiftCode, Inspector, JoinTitle, KaroglanSignEditor, LuckPerms, MMCLogger, MMCReboot, MMCRestrict, MMCRules, New Honor, Nucleus, PixelAutoMessages, PixelVip, PlaceholderAPI, ProjectBorders, ProjectCore, RedProtect, ServerListPlus, ShabbyHolograms, SpongeLoginFix, Title Broadcaster, UltimateChat, VirtualChest, VirtualChestEnchantments, WorldEdit, latch, wolrdpc

**Comment by KorewaLidesu** [comment]
can you reproduce it?
or is it randomize?

**Comment by DJmanito** [comment]
I don't know how to reproduce it, so far it seems to be random.
Makes me feel like the main thread is going through an endless loop?

我不知道如何重现，目前看来貌似是随机的。
让我感觉貌似是主线程进入了一个死循环？

**Comment by gabizou** [comment]
Is the server in online mode?

**Comment by DJmanito** [comment]
No.

**Comment by gabizou** [comment]
Can you try with online mode and see if the crash happens in a day?

**Comment by DJmanito** [comment]
The running server may not be able to be replaced. I will change the Settings when testing the plug-in. If it is encountered, I will give timely feedback.

正在运行的服务器可能不能去更换，我会在测试插件的时候来更换设置，如果遇到了，我会及时反馈的。

**Comment by KorewaLidesu** [comment]
Get the issue anytime again?

**Comment by ImMorpheus** [comment]
> The running server may not be able to be replaced. I will change the Settings when testing the plug-in. If it is encountered, I will give timely feedback.

Closing this. I assume the issue didn't show up again
