### ISSUE TITLE
In which case do the following problem arise?

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2928]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3843
- Forge version: 2838
- Java version: java8
- Operating System:debian

- Plugins/Mods:

**Issue Description**

https://gist.github.com/zhourui123/e5a6f440c9d355481da59de3d3ea80f0
```
[19:51:59] [Server thread/ERROR] [Sponge]: SlotIndex out of LensBounds! Did the Container change after creation?
java.lang.IndexOutOfBoundsException: Index: 84
	at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.checkIndex(DynamicLensCollectionImpl.java:156) ~[DynamicLensCollectionImpl.class:1.12.2-2838-7.1.7-RC3843]
	at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.getLens(DynamicLensCollectionImpl.java:94) ~[DynamicLensCollectionImpl.class:1.12.2-2838-7.1.7-RC3843]
	at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.get(DynamicLensCollectionImpl.java:89) ~[DynamicLensCollectionImpl.class:1.12.2-2838-7.1.7-RC3843]
	at org.spongepowered.common.item.inventory.lens.impl.collections.SlotCollection.getSlot(SlotCollection.java:135) ~[SlotCollection.class:1.12.2-2838-7.1.7-RC3843]
	at org.spongepowered.common.item.inventory.lens.impl.DelegatingLens.<init>(DelegatingLens.java:61) ~[DelegatingLens.class:1.12.2-2838-7.1.7-RC3843]
	at org.spongepowered.common.item.inventory.util.ContainerUtil.generateAdapterLens(ContainerUtil.java:319) ~[ContainerUtil.class:1.12.2-2838-7.1.7-RC3843]
	at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:225) ~[ContainerUtil.class:1.12.2-2838-7.1.7-RC3843]
	at net.minecraft.inventory.Container.bridge$generateLens(Container.java:2011) ~[afr.class:?]
	at net.minecraft.inventory.Container.bridge$getRootLens(Container.java:2648) ~[afr.class:?]
	at net.minecraft.inventory.Container.impl$getAdapters(Container.java:2023) ~[afr.class:?]
	at net.minecraft.inventory.Container.bridge$getContainerSlot(Container.java:2436) ~[afr.class:?]
	at net.minecraft.inventory.Container.bridge$detectAndSendChanges(Container.java:2124) [afr.class:?]
	at net.minecraft.inventory.Container.func_75142_b(Container.java:2097) [afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1168) [pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:192) [PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3843]
	at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlc000(SourceFile:540) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:306) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3843]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:4707) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Faithcaio** [comment]
That happened when modifying a modded inventory with multiple sub-inventories.
This should be fixed with 3860+.
If it still happens with newer builds post the new error.

**Comment by zhourui123** [comment]
I would like to know if this problem will cause item loss, as many players have reported item loss

**Comment by Faithcaio** [comment]
Its not impossible, depends on the modded inventory.
