### ISSUE TITLE
Inventory: Conflicting default methods

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#2943]
Not sure what this is or what caused it. Sorry I can't be any more help. Let me know if there's something else you would like.

Java version: 1.8.0_221-b11
minecraft server.1.12.2
forge 1.12.2 14.23.5.2838 universal
spongeforge 1.12.2 2838 7.1.7 RC 3900
Windows 10

Sponge plugins:

GriefPrevention 4.3.0.692
KaroglanSignEditor 3.4.1
LuckPerms Sponge 4.4.29
Nucleus 1.13.2 S7.1
project core 7.2.0 0.3.0
project inventories 7.2.0 0.12.2
project portals 7.2.0 0.15.2
project worlds 7.2.0 0.13.1
TimeWarp 2.3 r7.0.0
worldedit sponge 7.1.0–6.1.10 SNAPSHOT

Mods:

Aroma1997Core 1.12.2 2.0.0.2 b165
AromaBackup 1.12.2 3.0.0.0 b125
BetterFps 1.4.8
BiblioCraft 2.4.5
Biomes O’ Plenty 7.0.1.2441
BuildCraft 7.99.24.2
CodeChickenLib 3.2.3.357
foamfix 0.10.5
Forestry 5.8.2.394
IndustrialCraft 2 2.8.187 ex112
ironchest 7.0.59.842
JEI 4.15.0.289
NotEnoughItems 2.4.3.245

**Server output**
```
[00:10:36] [Server thread/WARN] [Sponge]:   Add -Dsponge.debugcauseframes to your startup flags to enable further debugging output.
[00:10:36] [Server thread/ERROR] [Sponge]: /********************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /*                                    Cause Stack Frame Corruption!                                     */
[00:10:36] [Server thread/ERROR] [Sponge]: /********************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /* Found
 frames left on the stack. Clearing them all.                                                */
[00:10:36] [Server thread/ERROR] [Sponge]: /*                                                                                                      */
[00:10:36] [Server thread/ERROR] [Sponge]: /* Please add -Dsponge.debugcauseframes=true to your startup flags to enable further debugging output.  */
[00:10:36] [Server thread/ERROR] [Sponge]: /********************************************************************************************************/
> /********************************************************************************************************/
/*                                    Cause Stack Frame Corruption!                                     */
/********************************************************************************************************/
/* Found
 frames left on the stack. Clearing them all.                                                */
/*                                                                                                      */
/* Please add -Dsponge.debugcauseframes=true to your startup flags to enable further debugging output.  */
/********************************************************************************************************/
[00:10:36] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_221]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_221]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3900]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
        at jds.bibliocraft.tileentities.TileEntityDiscRack.bridge$getRootLens(TileEntityDiscRack.java) ~[TileEntityDiscRack.class:?]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.generateAdapterLens(ContainerUtil.java:285) ~[ContainerUtil.class:1.12.2-2838-7.1.7-RC3900]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:223) ~[ContainerUtil.class:1.12.2-2838-7.1.7-RC3900]
        at net.minecraft.inventory.Container.bridge$generateLens(Container.java:2009) ~[afr.class:?]
        at net.minecraft.inventory.Container.bridge$getRootLens(Container.java:2607) ~[afr.class:?]
        at net.minecraft.inventory.Container.impl$getAdapters(Container.java:2021) ~[afr.class:?]
        at net.minecraft.inventory.Container.bridge$getContainerSlot(Container.java:2426) ~[afr.class:?]
        at net.minecraft.inventory.Container.bridge$detectAndSendChanges(Container.java:2115) ~[afr.class:?]
        at net.minecraft.inventory.Container.func_75142_b(Container.java:2088) ~[afr.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1168) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3900]
        at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zko000(SourceFile:540) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
        Suppressed: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
                at jds.bibliocraft.tileentities.TileEntityDiscRack.bridge$getRootLens(TileEntityDiscRack.java) ~[TileEntityDiscRack.class:?]
                at net.minecraft.inventory.Slot.bridge$generateLens(Slot.java:2554) ~[agr.class:?]
                at net.minecraft.inventory.Slot.bridge$getRootLens(Slot.java:1596) ~[agr.class:?]
                at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.peekSequential(AdapterLogic.java:72) ~[AdapterLogic.class:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.item.inventory.adapter.impl.DefaultImplementedAdapterInventory.peek(DefaultImplementedAdapterInventory.java:107) ~[DefaultImplementedAdapterInventory.class:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.event.tracking.phase.packet.inventory.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:233) ~[BasicInventoryPacketState.class:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.event.tracking.phase.packet.inventory.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:63) ~[BasicInventoryPacketState.class:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:310) ~[spongeforge-1.12.2-2838-7.1.7-RC3900.jar:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616) ~[PhaseContext.class:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3900]
                at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zko000(SourceFile:540) ~[hv$1.class:?]
                at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
                at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
                at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
                at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
                at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3900]
                at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716) [MinecraftServer.class:?]
                at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
                at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
                at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
                at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
                at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
        Suppressed: java.lang.IllegalStateException: Cause Stack Frame Corruption! Attempted to pop a frame that was not on the stack.
                at org.spongepowered.common.event.SpongeCauseStackManager.popCauseFrame(SpongeCauseStackManager.java:281) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.event.SpongeCauseStackManager$CauseStackFrameImpl.close(SpongeCauseStackManager.java:489) ~[SpongeCauseStackManager$CauseStackFrameImpl.class:1.12.2-2838-7.1.7-RC3900]
                at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:201) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3900]
                at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zko000(SourceFile:540) ~[hv$1.class:?]
                at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
                at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
                at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
                at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
                at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3900]
                at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716) [MinecraftServer.class:?]
                at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
                at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
                at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
                at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
                at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[00:10:36] [Server thread/ERROR] [Sponge]: /***********************************************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /*                                                   Completing incorrect phase                                                    */
[00:10:36] [Server thread/ERROR] [Sponge]: /***********************************************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system is very dependent on knowing when a change to any world                                                */
[00:10:36] [Server thread/ERROR] [Sponge]: /* takes place, however, we are attempting to complete a "phase" other than the one                                                */
[00:10:36] [Server thread/ERROR] [Sponge]: /* we most recently entered. This is an error usually on Sponge's part, so a report                                                */
[00:10:36] [Server thread/ERROR] [Sponge]: /* is required on the issue tracker on GitHub.                                                                                     */
[00:10:36] [Server thread/ERROR] [Sponge]: /***********************************************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /* Expected to exit phase: Plugin{ScheduledTask}                                                                                   */
[00:10:36] [Server thread/ERROR] [Sponge]: /* But instead found phase: Packet{PrimaryInventoryClick}                                                                          */
[00:10:36] [Server thread/ERROR] [Sponge]: /* StackTrace:                                                                                                                     */
[00:10:36] [Server thread/ERROR] [Sponge]: /* java.lang.Exception: null                                                                                                       */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:389)                   */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:283)                                   */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616)                                           */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310)                                            */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716)                                       */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)                                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                       */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                          */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Unknown Source)                                                                                        */
[00:10:36] [Server thread/ERROR] [Sponge]: /*  Phases Remaining:                                                                                                              */
[00:10:36] [Server thread/ERROR] [Sponge]: /*   - Phase: Packet{PrimaryInventoryClick}                                                                                        */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                                    */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - Owner: EntityPlayerMP['elliot_z'/1131, l='Inglewood', x=-17.56, y=72.00, z=-59.09]                                        */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - Source: EntityPlayerMP['elliot_z'/1131, l='Inglewood', x=-17.56, y=72.00, z=-59.09]                                       */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - PacketPlayer: EntityPlayerMP['elliot_z'/1131, l='Inglewood', x=-17.56, y=72.00, z=-59.09]                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - Packet: CPacketClickWindow{windowId=22, slotId=4, usedButton=0, actionNumber=1, clickedItem=1xitem.record@0, mode=PICKUP} */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - IgnoreCreative: false                                                                                                     */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - ItemStackUsed: 1xtile.air@0                                                                                               */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - HighlightedSlotId: 0                                                                                                      */
[00:10:36] [Server thread/ERROR] [Sponge]: /*   - Phase: Plugin{ScheduledTask}                                                                                                */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                                    */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - Source: com.google.common.util.concurrent.ListenableFutureTask@6aba8fc                                                    */
[00:10:36] [Server thread/ERROR] [Sponge]: /*                                                                                                                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /*  StackTrace :                                                                                                                   */
[00:10:36] [Server thread/ERROR] [Sponge]: /* java.lang.Exception: Incorrect Phase Completion                                                                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:392)                   */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:283)                                   */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616)                                           */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310)                                            */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716)                                       */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)                                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                       */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                          */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Unknown Source)                                                                                        */
[00:10:36] [Server thread/ERROR] [Sponge]: /*                                                                                                                                 */
[00:10:36] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                              */
[00:10:36] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-20b5f1b02                                                                                                     */
[00:10:36] [Server thread/ERROR] [Sponge]: /* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                  */
[00:10:36] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2838-7.1.7-RC3900                                                                                          */
[00:10:36] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.5.2838                                                                                                  */
[00:10:36] [Server thread/ERROR] [Sponge]: /***********************************************************************************************************************************/
> /***********************************************************************************************************************************/
/*                                                   Completing incorrect phase                                                    */
/***********************************************************************************************************************************/
/* Sponge's tracking system is very dependent on knowing when a change to any world                                                */
/* takes place, however, we are attempting to complete a "phase" other than the one                                                */
/* we most recently entered. This is an error usually on Sponge's part, so a report                                                */
/* is required on the issue tracker on GitHub.                                                                                     */
/***********************************************************************************************************************************/
/* Expected to exit phase: Plugin{ScheduledTask}                                                                                   */
/* But instead found phase: Packet{PrimaryInventoryClick}                                                                          */
/* StackTrace:                                                                                                                     */
/* java.lang.Exception: null                                                                                                       */
/*     org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:389)                   */
/*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:283)                                   */
/*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616)                                           */
/*     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310)                                            */
/*     net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716)                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)                                                 */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                       */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                 */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                          */
/*     java.lang.Thread.run(Unknown Source)                                                                                        */
/*  Phases Remaining:                                                                                                              */
/*   - Phase: Packet{PrimaryInventoryClick}                                                                                        */
/*     Context:                                                                                                                    */
/*     - Owner: EntityPlayerMP['elliot_z'/1131, l='Inglewood', x=-17.56, y=72.00, z=-59.09]                                        */
/*     - Source: EntityPlayerMP['elliot_z'/1131, l='Inglewood', x=-17.56, y=72.00, z=-59.09]                                       */
/*     - PacketPlayer: EntityPlayerMP['elliot_z'/1131, l='Inglewood', x=-17.56, y=72.00, z=-59.09]                                 */
/*     - Packet: CPacketClickWindow{windowId=22, slotId=4, usedButton=0, actionNumber=1, clickedItem=1xitem.record@0, mode=PICKUP} */
/*     - IgnoreCreative: false                                                                                                     */
/*     - ItemStackUsed: 1xtile.air@0                                                                                               */
/*     - HighlightedSlotId: 0                                                                                                      */
/*   - Phase: Plugin{ScheduledTask}                                                                                                */
/*     Context:                                                                                                                    */
/*     - Source: com.google.common.util.concurrent.ListenableFutureTask@6aba8fc                                                    */
/*                                                                                                                                 */
/*  StackTrace :                                                                                                                   */
/* java.lang.Exception: Incorrect Phase Completion                                                                                 */
/*     org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:392)                   */
/*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:283)                                   */
/*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616)                                           */
/*     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310)                                            */
/*     net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716)                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)                                                 */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                       */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                 */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                          */
/*     java.lang.Thread.run(Unknown Source)                                                                                        */
/*                                                                                                                                 */
/* Minecraft : 1.12.2                                                                                                              */
/* SpongeAPI : 7.1.0-20b5f1b02                                                                                                     */
/* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                  */
/* SpongeForge : 1.12.2-2838-7.1.7-RC3900                                                                                          */
/* Minecraft Forge : 14.23.5.2838                                                                                                  */
/***********************************************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /*                                                                                   Phases Not Completed                                                                                    */
[00:10:36] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************************************************************/
[00:10:36] [Server thread/ERROR] [Sponge]: /* One or more phases were started but were not properly completed by the end of the server tick. They will be automatically closed, but this is an issue that should be reported to Sponge. */
[00:10:36] [Server thread/ERROR] [Sponge]: /*   - Phase: Plugin{ScheduledTask}                                                                                                                                                          */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                                                                                              */
[00:10:36] [Server thread/ERROR] [Sponge]: /*     - Source: com.google.common.util.concurrent.ListenableFutureTask@6aba8fc                                                                                                              */
[00:10:36] [Server thread/ERROR] [Sponge]: /*                                                                                                                                                                                           */
[00:10:36] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                                                                                        */
[00:10:36] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-20b5f1b02                                                                                                                                                               */
[00:10:36] [Server thread/ERROR] [Sponge]: /* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                                                                            */
[00:10:36] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2838-7.1.7-RC3900                                                                                                                                                    */
[00:10:36] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.5.2838                                                                                                                                                            */
[00:10:36] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************************************************************/
> /*********************************************************************************************************************************************************************************************/
/*                                                                                   Phases Not Completed                                                                                    */
/*********************************************************************************************************************************************************************************************/
/* One or more phases were started but were not properly completed by the end of the server tick. They will be automatically closed, but this is an issue that should be reported to Sponge. */
/*   - Phase: Plugin{ScheduledTask}                                                                                                                                                          */
/*     Context:                                                                                                                                                                              */
/*     - Source: com.google.common.util.concurrent.ListenableFutureTask@6aba8fc                                                                                                              */
/*                                                                                                                                                                                           */
/* Minecraft : 1.12.2                                                                                                                                                                        */
/* SpongeAPI : 7.1.0-20b5f1b02                                                                                                                                                               */
/* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                                                                            */
/* SpongeForge : 1.12.2-2838-7.1.7-RC3900                                                                                                                                                    */
/* Minecraft Forge : 14.23.5.2838                                                                                                                                                            */
/*********************************************************************************************************************************************************************************************/
```

**Comment by KorewaLidesu** [comment]
Same problem with #2939 but SecondaryInventoryClick instead of PrimaryInventoryClick

**Comment by Faithcaio** [comment]
`IncompatibleClassChangeError` 
This happens when a mod implements both `IInventory` and `IItemHandler`.
Caused by our `DefaultInventoryAdaptersMixin_Forge`
Also `IItemHandlerFabricMixin_Forge` and `IInventoryFabricMixin`


Not sure how to solve this...

**Comment by clienthax** [comment]
```
Caused by: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
at jds.bibliocraft.tileentities.TileEntityFramedChest.bridge$getRootLens(TileEntityFramedChest.java) ~[TileEntityFramedChest.class:?]
```

Same as this issue?

**Comment by gabizou** [comment]
> Same as this issue?

Yes.
