### ISSUE TITLE
Agricraft TileEntitySeedAnalyzer - Cause Stack Frame Corruption

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2944]
Getting this error after updating to 3902.

spongeforge-1.12.2-2838-7.1.7-RC3902

```
[23:06:11] [Server thread/ERROR]: [Sponge]: /********************************************************************************************************/
[23:06:11] [Server thread/ERROR]: [Sponge]: /*                                    Cause Stack Frame Corruption!                                     */
[23:06:11] [Server thread/ERROR]: [Sponge]: /********************************************************************************************************/
[23:06:11] [Server thread/ERROR]: [Sponge]: /* Found 
 frames left on the stack. Clearing them all.                                                 */
[23:06:11] [Server thread/ERROR]: [Sponge]: /*                                                                                                      */
[23:06:11] [Server thread/ERROR]: [Sponge]: /* Please add -Dsponge.debugcauseframes=true to your startup flags to enable further debugging output.  */
[23:06:11] [Server thread/ERROR]: [Sponge]: /********************************************************************************************************/
[23:06:11] [Server thread/FATAL]: [MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3902]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:4716) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
	at com.infinityraider.agricraft.tiles.analyzer.TileEntitySeedAnalyzer.bridge$getRootLens(TileEntitySeedAnalyzer.java) ~[TileEntitySeedAnalyzer.class:?]
	at org.spongepowered.common.item.inventory.util.ContainerUtil.generateAdapterLens(ContainerUtil.java:285) ~[ContainerUtil.class:1.12.2-2838-7.1.7-RC3902]
	at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:223) ~[ContainerUtil.class:1.12.2-2838-7.1.7-RC3902]
	at net.minecraft.inventory.Container.bridge$generateLens(Container.java:2009) ~[afr.class:?]
	at net.minecraft.inventory.Container.bridge$getRootLens(Container.java:2607) ~[afr.class:?]
	at net.minecraft.inventory.Container.impl$getAdapters(Container.java:2021) ~[afr.class:?]
	at net.minecraft.inventory.Container.bridge$getContainerSlot(Container.java:2426) ~[afr.class:?]
	at net.minecraft.inventory.Container.bridge$detectAndSendChanges(Container.java:2115) ~[afr.class:?]
	at net.minecraft.inventory.Container.func_75142_b(Container.java:2088) ~[afr.class:?]
	at com.infinityraider.agricraft.container.ContainerSeedAnalyzer.func_75142_b(ContainerSeedAnalyzer.java:57) ~[ContainerSeedAnalyzer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1168) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3902]
	at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlc000(SourceFile:540) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
	Suppressed: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
		at com.infinityraider.agricraft.tiles.analyzer.TileEntitySeedAnalyzer.bridge$getRootLens(TileEntitySeedAnalyzer.java) ~[TileEntitySeedAnalyzer.class:?]
		at net.minecraft.inventory.Slot.bridge$generateLens(Slot.java:2554) ~[agr.class:?]
		at net.minecraft.inventory.Slot.bridge$getRootLens(Slot.java:1596) ~[agr.class:?]
		at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.peekSequential(AdapterLogic.java:72) ~[AdapterLogic.class:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.item.inventory.adapter.impl.DefaultImplementedAdapterInventory.peek(DefaultImplementedAdapterInventory.java:107) ~[DefaultImplementedAdapterInventory.class:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.event.tracking.phase.packet.inventory.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:233) ~[BasicInventoryPacketState.class:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.event.tracking.phase.packet.inventory.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:63) ~[BasicInventoryPacketState.class:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:310) ~[_spongeforge-1.12.2-2838-7.1.7-RC3902.jar:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616) ~[PhaseContext.class:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3902]
		at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlc000(SourceFile:540) ~[hv$1.class:?]
		at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
		at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
		at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3902]
		at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:4716) [MinecraftServer.class:?]
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
	Suppressed: java.lang.IllegalStateException: Cause Stack Frame Corruption! Attempted to pop a frame that was not on the stack.
		at org.spongepowered.common.event.SpongeCauseStackManager.popCauseFrame(SpongeCauseStackManager.java:281) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.event.SpongeCauseStackManager$CauseStackFrameImpl.close(SpongeCauseStackManager.java:489) ~[SpongeCauseStackManager$CauseStackFrameImpl.class:1.12.2-2838-7.1.7-RC3902]
		at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:201) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3902]
		at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlc000(SourceFile:540) ~[hv$1.class:?]
		at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
		at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
		at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3902]
		at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:4716) [MinecraftServer.class:?]
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[23:06:11] [Server thread/ERROR]: [Sponge]: /*********************************************************************************************************************************************************************************************/
[23:06:11] [Server thread/ERROR]: [Sponge]: /*                                                                                   Phases Not Completed                                                                                    */
[23:06:11] [Server thread/ERROR]: [Sponge]: /*********************************************************************************************************************************************************************************************/
[23:06:11] [Server thread/ERROR]: [Sponge]: /* One or more phases were started but were not properly completed by the end of the server tick. They will be automatically closed, but this is an issue that should be reported to Sponge. */
[23:06:11] [Server thread/ERROR]: [Sponge]: /*   - Phase: Plugin{ScheduledTask}                                                                                                                                                          */
[23:06:11] [Server thread/ERROR]: [Sponge]: /*     Context:                                                                                                                                                                              */
[23:06:11] [Server thread/ERROR]: [Sponge]: /*     - Source: com.google.common.util.concurrent.ListenableFutureTask@7b9a7ad3                                                                                                             */
[23:06:11] [Server thread/ERROR]: [Sponge]: /*                                                                                                                                                                                           */
[23:06:11] [Server thread/ERROR]: [Sponge]: /* Minecraft : 1.12.2                                                                                                                                                                        */
[23:06:11] [Server thread/ERROR]: [Sponge]: /* SpongeAPI : 7.1.0-20b5f1b02                                                                                                                                                               */
[23:06:11] [Server thread/ERROR]: [Sponge]: /* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                                                                            */
[23:06:11] [Server thread/ERROR]: [Sponge]: /* SpongeForge : 1.12.2-2838-7.1.7-RC3902                                                                                                                                                    */
[23:06:11] [Server thread/ERROR]: [Sponge]: /* Minecraft Forge : 14.23.5.2838                                                                                                                                                            */
[23:06:11] [Server thread/ERROR]: [Sponge]: /*********************************************************************************************************************************************************************************************/
```

**Comment by KorewaLidesu** [comment]
Duplicated to #2943
