### ISSUE TITLE
sponge crashing ae2 

### ISSUE THREAD

**Issue by DeadlyGamer1** [SpongePowered/SpongeForge#2952]
**I am currently running**

- SpongeForge version: RC3908 also tried 3903
- Forge version:  14.23.5.2838 
- Java version: 8
- Operating System: linux

- Plugins/Mods:
it's in the crash report list of them

**Issue Description**
https://pastebin.com/raw/hCD6FqX7
I don't know how to reproduce but i do know i took out sponge and the problem was fixed. Once i installed sponge the server just start crashing, i don't know much information then that sorry.

**Comment by KorewaLidesu** [comment]
can you send me world file?
somethings with AE2 building make me interesting

**Comment by runescapejon** [comment]
I am having the same issue here, I had also took certain chunks that contain the issue. I'll upload the world file in a zip here


https://drive.google.com/open?id=1pdy2B7Namp9jOtmOXlANvIxiDkJzo4_P

Location: World: world, Co-ords: (-8617, 71, -4483)

EDIT: modpack link: https://www.technicpack.net/modpack/modded-network-mystical-times.871258

**Comment by KorewaLidesu** [comment]
>    at net.minecraft.world.World.redirect$impl$useInlinedMethodInsteadisoutsideBuildHeight$zlj000(World.java:7863)
    at net.minecraft.world.World.getTileEntity(World.java:2384)
    at appeng.block.networking.BlockCableBus.cb(BlockCableBus.java:354)
    at appeng.block.networking.BlockCableBus.getLightValue(BlockCableBus.java:186)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:510)
    at org.spongepowered.common.SpongeImplHooks.getChunkPosLight(SpongeImplHooks.java:2112)
    at net.minecraft.world.chunk.Chunk.getBlockLightOpacity(Chunk.java:4897)
    at net.minecraft.world.World.getBlockLightOpacity(World.java:3942)
    at appeng.parts.reporting.AbstractPartReporting.blockLight(AbstractPartReporting.java:259)
    at appeng.parts.reporting.AbstractPartReporting.getLightLevel(AbstractPartReporting.java:194)
    at appeng.parts.CableBusContainer.getLightValue(CableBusContainer.java:926)
    at appeng.block.networking.BlockCableBus.getLightValue(BlockCableBus.java:186)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:510)
    at org.spongepowered.common.SpongeImplHooks.getChunkPosLight(SpongeImplHooks.java:2112)
    at net.minecraft.world.chunk.Chunk.getBlockLightOpacity(Chunk.java:4897)
    at net.minecraft.world.World.getBlockLightOpacity(World.java:3942)
    at appeng.parts.reporting.AbstractPartReporting.blockLight(AbstractPartReporting.java:259)
    at appeng.parts.reporting.AbstractPartReporting.getLightLevel(AbstractPartReporting.java:194)

Broken on light detect with AE2 network.....

**Comment by Shybella** [comment]
https://pastebin.com/raw/FGCJAyLD

Also having this pop up
