### ISSUE TITLE
Phase tracker server stall

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2981]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3924
- Forge version: 14.23.5.2838
- Java version: Java 8 latest
- Operating System: Ubuntu 18.04 LTS

- Plugins/Mods:
 **Plugins (32):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, ActionBroadcaster, Buycraft, CarrotShop, Eagle Factions, GTS, GriefPrevention, Holograms, HuskyCrates, HuskyUI, ImpactorAPI, Info, LuckPerms, MMCRestrict, MineReset, NuVotifier, Nucleus, PlaceholderAPI, ProjectCore, ProjectPortals, ProjectWorlds, RankUpper, SeriousVote, SignEditor, TabManager, Total Economy, VoxelSniper, WorldEdit
**Mods (78):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Applied Energistics 2, BD Lib, Biomes O' Plenty, Classic Combat, CoFH World, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Extra Cells 2, Extreme Reactors, FTB Library, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, Guide-API, ICBM-Classic, Industrial Foregoing, Integration Foregoing, Just Enough Items, LagGoggles, MachineMuse's Modular Powersuits, Mantle, Mekanism, Mekanism: Generators, Mekanism: Tools, Micdoodle8 Core, Minecraft Multipart Plugin, Modular ForceField System, MrTJPCore, Netherending Ores, NoMoreRecipeConflict, Nuclear Physics, NuclearCraft, Numina, OMLib, Open Modular Turrets, OpenComputers, OpenComputers (Core), ProjectRed Core, ProjectRed Exploration, ProjectRed Integration, ProjectRed Transmission, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, TESLA, Tesla Core Lib, Tesla Core Lib Registries, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, UniDict, WanionLib, Woot, YABBA, Zero CORE, projectred-compat

I'm not sure about what exactly is causing the stall

https://pastebin.com/7mR1mXC6 Phase tracker exception

**Comment by gabizou** [comment]
Check your log. You didn't give us the actual crash log nor the full server log..

**Comment by ghost** [comment]
Sorry, I copied over the wrong pastebin link, my fault for not checking at all.

Crash Log: https://gist.github.com/OblivionNW/0eb92a8cd92ad23180416393a033e8c1
Phase tracker exception: https://pastebin.com/ZJ3m0SuF

**Comment by bigenergy** [comment]
I experienced similar problems after upgrading from 3902 to 3924. There is no such problem on 3902

**Comment by bigenergy** [comment]
My full debug log
SpongeForge 1.12.2-2838-7.1.7-RC3924
[debug.txt](https://github.com/SpongePowered/SpongeForge/files/3655185/debug.txt)

**Comment by gabizou** [comment]
So a few things:
```
[02:17:00] [Sponge - Async Light Thread/WARN] [Phosphor]: Something (likely another mod) has attempted to modify the world's state from the wrong thread!
This is *bad practice* and can cause severe issues in your game. Phosphor has done as best as it can to mitigate this violation, but it may negatively impact performance or introduce stalls.
In a future release, this violation may result in a hard crash instead of the current soft warning. You should report this issue to our issue tracker with the following stacktrace information.
(If you are aware you have misbehaving mods and cannot resolve this issue, you can safely disable this warning by setting `enable_illegal_thread_access_warnings` to `false` in Phosphor's configuration file for the time being.)
java.lang.IllegalAccessException: World is owned by 'Server thread' (ID: 21), but was accessed from thread 'Sponge - Async Light Thread' (ID: 175)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.acquireLock(LightingEngine.java:210) ~[LightingEngine.class:?]
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdatesForType(LightingEngine.java:186) ~[LightingEngine.class:?]
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:4905) ~[axw.class:?]
	at net.minecraft.world.WorldServer.asyncLightingImpl$getLightForAsync(WorldServer.java:6475) ~[oo.class:?]
	at net.minecraft.world.WorldServer.asyncLightingBridge$checkLightAsync(WorldServer.java:6242) ~[oo.class:?]
	at net.minecraft.world.WorldServer.asyncLightingBridge$updateLightAsync(WorldServer.java:6430) ~[oo.class:?]
	at net.minecraft.world.chunk.Chunk.asyncLighting$checkWorldLight(Chunk.java:6429) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.asyncLighting$checkLightAsync(Chunk.java:6118) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.asyncLighting$checkLightAsync(Chunk.java:6046) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.lambda$asyncLighting$onTickHead$1(Chunk.java:5871) ~[axw.class:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```
Disable sponge's async lighting if you have Phosphor, the two aren't meant to be used together.

Secondly:
```
[02:17:36] [Server thread/ERROR] [Sponge]: /************************************************************************************************************************************************************************************************************************************************/
[02:17:36] [Server thread/ERROR] [Sponge]: /*                                                                                                    Exception occurred during a PhaseState                                                                                                    */
[02:17:36] [Server thread/ERROR] [Sponge]: /************************************************************************************************************************************************************************************************************************************************/
[02:17:36] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best effort to not throw exceptions randomly                                                                                                                                                                */
[02:17:36] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most cases, something else triggered this                                                                                                                                                                 */
[02:17:36] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash by catching it. The following stacktrace                                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                                                                                                                                      */
[02:17:36] [Server thread/ERROR] [Sponge]: /************************************************************************************************************************************************************************************************************************************************/
[02:17:36] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: Tick{TileEntity}                                                                                                                                                                                         */
[02:17:36] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                                                                                                                                            */
[02:17:36] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@1b28ed99                                                                                                                                                                                            */
[02:17:36] [Server thread/ERROR] [Sponge]: /*                                                                                                                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /*  StackTrace :                                                                                                                                                                                                                                */
[02:17:36] [Server thread/ERROR] [Sponge]: /* java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=moisture, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=minecraft:soul_sand, properties=[]} */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)                                                                                                                            */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     ic2.core.crop.TileEntityCrop.updateTerrainHumidity(TileEntityCrop.java:621)                                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     ic2.core.crop.TileEntityCrop.performTick(TileEntityCrop.java:232)                                                                                                                                                                        */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     ic2.core.crop.TileEntityCrop.updateEntityServer(TileEntityCrop.java:200)                                                                                                                                                                 */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     ic2.core.block.TileEntityBlock.func_73660_a(TileEntityBlock.java:346)                                                                                                                                                                    */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)                                                                                                                                               */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:5228)                                                                                                                                                                  */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlg000(WorldServer.java:5212)                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.onTileEntityTick(WorldServer.java:6753)                                                                                                                                                                  */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     com.github.terminatornl.tiquality.tracking.tickexecutors.SpongeTickExecutor.onTileEntityTick(SpongeTickExecutor.java:35)                                                                                                                 */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.tileentity.TileEntity.tiquality_doUpdateTick(TileEntity.java:4156)                                                                                                                                                         */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     com.github.terminatornl.tiquality.tracking.TrackerBase.tickSimpleTickable(TrackerBase.java:227)                                                                                                                                          */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     com.github.terminatornl.tiquality.tracking.TickHub.onTileEntityTick(TickHub.java:63)                                                                                                                                                     */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlg000(WorldServer.java:6768)                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72939_s(World.java:1838)                                                                                                                                                                                  */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:4430)                                                                                                                                                                      */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                                                                                                                                    */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                                                                                                                       */
[02:17:36] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Thread.java:748)                                                                                                                                                                                                    */
[02:17:36] [Server thread/ERROR] [Sponge]: /*                                                                                                                                                                                                                                              */
[02:17:36] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                                                                                                                                           */
[02:17:36] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-13da4949c                                                                                                                                                                                                                  */
[02:17:36] [Server thread/ERROR] [Sponge]: /* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                                                                                                                               */
[02:17:36] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2838-7.1.7-RC3924                                                                                                                                                                                                       */
[02:17:36] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.5.2847                                                                                                                                                                                                               */
[02:17:36] [Server thread/ERROR] [Sponge]: /************************************************************************************************************************************************************************************************************************************************/
```
The stacktrace is showing someone's been transforming the methods to wrap around ticks, and furthermore, it looks like Tickquality is doing some tile entity tick wrapping to call the `WorldServer.tickUpdate` methods that Sponge is intentionally redirecting. The problem is that by re-routing the entirety of Sponge's phase entry during the tile's update bypasses Sponge's block tracking system, which builds a support for transactional processing (it achieves this by tracking blcok changes and propagates them to proxy the block states during the transaction process, after block events have been thrown). 

Because I don't know enough of what code changes are actually taking place on Tiquality's behalf to reroute Sponge's redirects and handling, I don't have a way to actually resolve this issue except to label it as incompatible since it's explicitly rewriting Sponge's redirects it seems.
