### ISSUE TITLE
Server Crashing With Spongeforge

### ISSUE THREAD

**Issue by disputed** [SpongePowered/SpongeForge#2988]
**I am currently running**
1.12.2 server with RL craft server pack
- SpongeForge version: Spongeforge-1.12.2-2705-8.0.0-BETA-3474
- Forge version: 1.12.2-14.23.5.2803
- Java version:  8 update 221
- Operating System: Win10 64

RL Craft 2.6.3 modpack as well as spongeforge is all that is currently installed
Without spongeforge server comes up with no issues.  Once spongeforge is installed the server crashes. 
I have already read about the issues with foamfix and have disabled every last setting that i could find that might cause this issue.

[crash-2019-09-29_16.59.10-server.txt](https://github.com/SpongePowered/SpongeForge/files/3668154/crash-2019-09-29_16.59.10-server.txt)

**Comment by disputed** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  CreativePatchingLoader (CreativeCore_v1.9.62_mc1.12.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  SpongeCoremod (spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 9/29/19 4:59 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.common.ForgeModContainer.preInit(ForgeModContainer.java:487)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 41 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.phosphor.json:common.MixinChunk$Sponge] from phase [DEFAULT] in config [mixins.phosphor.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 44 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Redirect annotation on redirect$setBlockStateCreateSectionSponge$zpl000 could not find any targets matching 'bridge$setBlockState' in the target class net.minecraft.world.chunk.Chunk. Using refmap mixins.phosphor.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:39)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:478)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1180)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:929)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:317)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.common.ForgeModContainer.preInit(ForgeModContainer.java:487)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjj000(MinecraftServer.java:3973)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6665851920 bytes (6357 MB) / 9652666368 bytes (9205 MB) up to 9652666368 bytes (9205 MB)
	JVM Flags: 2 total; -Xms7G -Xmx10G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2803 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version                     | Source                                        | Signature                                |
	|:----- |:--------------------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                   | 1.12.2                      | minecraft.jar                                 | None                                     |
	| LCH   | mcp                         | 9.42                        | minecraft.jar                                 | None                                     |
	| LCH   | FML                         | 8.0.99.99                   | HUDL_Server.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                       | 14.23.5.2803                | HUDL_Server.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy           | 1.0.0                       | minecraft.jar                                 | None                                     |
	| LC    | itemphysic                  | 1.4.0                       | minecraft.jar                                 | None                                     |
	| LC    | ivtoolkit                   | 1.3.3-1.12                  | minecraft.jar                                 | None                                     |
	| LC    | spongeapi                   | 8.0.0-SNAPSHOT-057a815      | spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar   | None                                     |
	| LC    | sponge                      | 1.12.2-2705-8.0.0-BETA-3474 | spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar   | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| LC    | foamfixcore                 | 7.7.4                       | minecraft.jar                                 | None                                     |
	| LC    | tnt_utilities_core          | 1.2.3                       | minecraft.jar                                 | None                                     |
	| LC    | dsurroundcore               | 3.5.4.3                     | minecraft.jar                                 | None                                     |
	| LC    | forgeendertech              | 1.12.2-4.4.22.2             | ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar | None                                     |
	| LC    | adhooks                     | 1.12.2-3.2.2.0              | AdHooks-1.12.2-3.2.2.0-build.0220.jar         | None                                     |
	| LC    | advanced-fishing            | 1.3.3                       | Advanced-Fishing-1.12.2-1.3.3.jar             | None                                     |
	| LC    | alcatrazcore                | 1.0.4                       | alcatrazcore-1.0.4.jar                        | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LC    | antiqueatlas                | 4.5.1                       | antiqueatlas-1.12.2-4.5.1.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LC    | anvilpatch                  | 1.0.0                       | anvilpatch-1.0.0.jar                          | None                                     |
	| LC    | aquaculture                 | 1.6.8                       | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LC    | carrots                     | 1.0.0b1                     | carrotslib-mc1.12.2-1.0.0b1.jar               | None                                     |
	| LC    | armorunder                  | 1.0.0                       | armorunder-mc1.12.2-1.0.0.jar                 | None                                     |
	| LC    | artemislib                  | 1.0.6                       | ArtemisLib-1.12.2-v1.0.6.jar                  | None                                     |
	| LC    | autoreglib                  | 1.3-32                      | AutoRegLib-1.3-32.jar                         | None                                     |
	| LC    | battletowers                | 1.6.5                       | BattleTowers-1.12.2.jar                       | None                                     |
	| LC    | baubles                     | 1.5.2                       | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LC    | mujmajnkraftsbettersurvival | 1.3.4                       | Better_Survival-1.3.4(1.12.1).jar             | None                                     |
	| LC    | bettercombatmod             | 1.5.6                       | BetterCombat-1.12.2-1.5.6.jar                 | None                                     |
	| LC    | bloodmoon                   | 1.5.3                       | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | cursedlib                   | 1.0.0                       | FlameLib-1.12.2-0.0.7.jar                     | None                                     |
	| LC    | bountifulbaubles            | 0.0.1                       | Bountiful Baubles-1.12.2-0.0.8.jar            | None                                     |
	| LC    | campfire                    | 1.2                         | campfire-1.12-v1.2.jar                        | None                                     |
	| LC    | carryon                     | 1.12.2                      | CarryOn MC1.12.2 v1.12.2.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LC    | toughasnails                | 3.1.0.141                   | ToughAsNails-1.12.2-3.1.0.141-universal.jar   | None                                     |
	| LC    | comforts                    | 1.4.1.2                     | comforts-1.12.2-1.4.1.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | reskillable                 | 1.12.2-GRADLE:BUILD         | Reskillable-1.12.2-1.12.5.jar                 | None                                     |
	| LC    | compatskills                | 1.12.2-1.16.2               | CompatSkills-1.12.2-1.16.2.jar                | None                                     |
	| LC    | coralreef                   | 2.0                         | CoralReef-2.5-1.12.2.jar                      | None                                     |
	| LC    | wearablebackpacks           | 3.1.2                       | WearableBackpacks-1.12.2-3.1.2.jar            | None                                     |
	| LC    | corpsecomplex               | 1.0.6                       | corpsecomplex-1.12.2-1.0.6.jar                | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | craftablechainmail          | 1.0                         | craftablechainmail-1.0.jar                    | None                                     |
	| LC    | craftablehorsearmour        | 1.3                         | CraftableHorseArmour-1.3.0-1.12.jar           | None                                     |
	| LC    | crafttweaker                | 4.1.19                      | CraftTweaker2-1.12-4.1.19.jar                 | None                                     |
	| LC    | jei                         | 4.15.0.268                  | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| LC    | crafttweakerjei             | 2.0.3                       | CraftTweaker2-1.12-4.1.19.jar                 | None                                     |
	| LC    | creativecore                | 1.9.9                       | CreativeCore_v1.9.62_mc1.12.2.jar             | None                                     |
	| LC    | defiledlands                | 1.4.2                       | defiledlands-1.12.2-1.4.2.jar                 | None                                     |
	| LC    | disenchanter                | 1.6                         | disenchanter-[1.12]1.6.jar                    | None                                     |
	| LC    | dldungeonsjbg               | 1.12.10                     | DoomlikeDungeons-1.12.10-MC1.12.2.jar         | None                                     |
	| LC    | dynamictrees                | 1.12.2-0.9.5                | DynamicTrees-1.12.2-0.9.5.jar                 | None                                     |
	| LC    | traverse                    | 1.6.0                       | Traverse-1.12.2-1.6.0-69.jar                  | None                                     |
	| LC    | dttraverse                  | 1.5                         | dttraverse-1.5.jar                            | None                                     |
	| LC    | enhancedvisuals             | 1.0                         | EnhancedVisuals_v1.2.4_mc1.12.2.jar           | None                                     |
	| LC    | familiarfauna               | 1.0.11                      | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LC    | firstaid                    | 1.6.10                      | firstaid-1.6.10.jar                           | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LC    | foamfix                     | 0.10.5-1.12.2               | foamfix-0.10.5-1.12.2.jar                     | None                                     |
	| LC    | foodexpansion               | 1.3                         | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| LC    | forgelin                    | 1.8.4                       | Forgelin-1.8.4.jar                            | None                                     |
	| LC    | tschipplib                  | 1.1.3                       | TschippLib MC1.12.2 v1.1.3.jar                | None                                     |
	| LC    | forgottenitems              | 1.1                         | ForgottenItems+MC1.12.2+v1.1.jar              | None                                     |
	| LC    | globalgamerules             | 2.2                         | GlobalGameRules-1.12.2-2.2.7.jar              | None                                     |
	| LC    | grapplemod                  | 1.12.2-v11.1                | grapplemod-v11.1-1.12.2.jar                   | None                                     |
	| LC    | llibrary                    | 1.7.19                      | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire                  | 1.7.1                       | iceandfire-1.7.1-1.12.2.jar                   | None                                     |
	| LC    | infernalmobs                | 1.7.6                       | InfernalMobs-1.12.2.jar                       | None                                     |
	| LC    | inventorytweaks             | 1.64+dev.146.2180b27        | InventoryTweaks-1.64+dev.146.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | levelup2                    | ${version}                  | Level Up! 2-1.1.23-1.12.jar                   | None                                     |
	| LC    | lostcities                  | 2.0.21                      | lostcities-1.12-2.0.21.jar                    | None                                     |
	| LC    | lostsouls                   | 1.1.4                       | lostsouls-1.12-1.1.4.jar                      | None                                     |
	| LC    | lycanitesmobs               | 2.0.0.7 - MC 1.12.2         | lycanitesmobs-1.12.2-2.0.0.7.jar              | None                                     |
	| LC    | mobends                     | 0.24                        | mobends-0.24_for_MC-1.12.jar                  | None                                     |
	| LC    | multimine                   | 1.6.1                       | MultiMine-1.12.2.jar                          | None                                     |
	| LC    | notreepunching              | 2.0.13                      | notreepunching-2.0.13.jar                     | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LC    | potioncore                  | 1.8_for_1.12.2              | PotionCore-1.8_for_1.12.2.jar                 | None                                     |
	| LC    | potionfingers               | r1.0-2                      | PotionFingers-r1.0-2.jar                      | None                                     |
	| LC    | qualitytools                | 1.0.7_for_1.12.2            | QualityTools-1.0.7_for_1.12.2.jar             | None                                     |
	| LC    | realistictorches            | 2.1.1                       | RealisticTorches-1.12.2-2.1.1.jar             | None                                     |
	| LC    | reccomplex                  | 1.4.8.2                     | RecurrentComplex-1.4.8.2.jar                  | None                                     |
	| LC    | roguelike                   | 1.8.0                       | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LC    | roughtweaks                 | 1.0                         | roughTweaks0.2.4-1.12.2.jar                   | None                                     |
	| LC    | ruins                       | 17.2                        | Ruins-1.12.2.jar                              | None                                     |
	| LC    | silentlib                   | 3.0.13                      | SilentLib-1.12.2-3.0.13+167.jar               | None                                     |
	| LC    | scalinghealth               | 1.3.36                      | ScalingHealth-1.12.2-1.3.36+140.jar           | None                                     |
	| LC    | sereneseasons               | 1.2.16                      | SereneSeasons-1.12.2-1.2.16-universal.jar     | None                                     |
	| LC    | sit                         | v1.2                        | sit-1.12.2-v1.2.jar                           | None                                     |
	| LC    | somanyenchantments          | 0.4.4                       | So+Many+Enchantments+V0.4.4.jar               | None                                     |
	| LC    | spartanweaponry             | beta 1.3.0                  | SpartanWeaponry-1.12.2-beta-1.3.0.jar         | None                                     |
	| LC    | spartanfire                 | 0.05                        | spartanfire-0.05.jar                          | None                                     |
	| LC    | spartanshields              | 1.5.4                       | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| LC    | spawnercontrol              | 1.6.3b                      | SpawnerControl-1.6.3b.jar                     | None                                     |
	| LC    | stg                         | 1.12.2-1.2.3                | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LC    | switchbow                   | 1.5.7                       | switchbow-1.5.7.jar                           | None                                     |
	| LC    | tanspit                     | 1.12.2-1.3                  | tanspit-1.12.2-1.3.jar                        | None                                     |
	| LC    | tickprofiler                | 1.12-0.0.7                  | TickProfiler-1.12-0.0.7.jar                   | None                                     |
	| LC    | tnt_utilities               | 1.2.3                       | tnt_utilities-mc1.12-1.2.3.jar                | None                                     |
	| LC    | toolbelt                    | 1.9.9                       | ToolBelt-1.12.2-1.9.9.jar                     | None                                     |
	| LC    | xat                         | 0.25.2                      | Trinkets and Baubles-1.12.2-0.25.2.jar        | None                                     |
	| LC    | trumpetskeleton             | 1.12-1.0.2.1                | trumpetskeleton-1.12-1.0.2.1.jar              | None                                     |
	| LC    | tumbleweed                  | 1.11-0.4.5                  | tumbleweed-1.11-0.4.5.jar                     | None                                     |
	| LC    | variedcommodities           | 1.12.2                      | VariedCommodities_1.12.2(15may18.jar          | None                                     |
	| LC    | waystones                   | 4.0.72                      | Waystones_1.12.2-4.0.72.jar                   | None                                     |
	| LC    | wolfarmor                   | 2.2.3.6                     | wolfarmor-1.12.2-2.2.3.1798-universal.jar     | None                                     |
	| LC    | xpbook                      | 0.0.3-beta                  | xpbook-1.12-0.0.3-beta.jar                    | None                                     |
	| LC    | xpfromharvest               | 1.1.0                       | xpfromharvest-1.12.2-1.1.0.jar                | None                                     |
	| LC    | orelib                      | 3.5.2.2                     | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround                   | 3.5.4.3                     | DynamicSurroundings-1.12.2-3.5.4.3.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | phosphor-lighting           | 1.12.2-0.2.6                | phosphor-1.12.2-0.2.6+build50-universal.jar   | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
LibLoader (# LibLoader.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
CreativePatchingLoader (CreativeCore_v1.9.62_mc1.12.2.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
SpongeCoremod (spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by JBYoshi** [comment]
> SpongeCoremod (spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar)

Sponge for API 8 is not yet ready. Use one of the 7.x.x builds for now.
