### ISSUE TITLE
Mod B3M and Sponge, crash server

### ISSUE THREAD

**Issue by MRLexanayseR** [SpongePowered/SpongeForge#2991]
**I am currently running**

- Sponge 1.12.2-2838-7.1.7-RC3926
- Forge 1.12.2-2838
- Java is OpenJDK 64-Bit Server VM, version 1.8.0_212
- Windows 10 Pro x64

- Plugins/Mods:
Plugins - 0
Mods - 1 (B3M) https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2945879-vrashenie-zemli-majnkraftskaya-longer-day-night

**Issue Description**

Sorry for my English. (Google Translate)
There was a problem with the mod B3M and Sponge. The server is clean, except for this mod and sponge there is nothing, but the server crashes after starting. 

Error from the console attached.
https://gist.github.com/MRLexanayseR/0d3f9d5bec4d283b56d883b5b880a9c2

**Comment by gabizou** [comment]
SpongeForge directly is incompatible with the class changes made by B3M:
```
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 13 more
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	... 15 more
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method modify$vanillaImpl$updateRainTimeStart$bba000(I)I in mixins.forge.core.json:world.WorldMixin_Forge failed injection check, (0/1) succeeded. Using refmap mixins.forge.refmap.json
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[19:25:52] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 18 more
```
And the transformer from B3M: 
```
      m = InsnFinder.getMethod(clazz, "updateWeatherBody", "()V");
      if (!isNull(m)) {
         index = InsnFinder.findInsnNode(m, 25, 0);
         if (index > -1) {
            InsnFinder.removeInsnNodes(m, index, m.instructions.size() - 5 - index);
            InsnFinder.removeInsnNode(m, index + 2);
            newInsns = new InsnList();
            newInsns.add(new MethodInsnNode(184, "sedridor/B3M/B3M_Core", "getInstance", "()Lsedridor/B3M/B3M_Core;", false));
            newInsns.add(new VarInsnNode(25, 0));
            newInsns.add(new MethodInsnNode(182, "sedridor/B3M/B3M_Core", "updateWeather", "(Lnet/minecraft/world/World;)V", false));
            InsnFinder.insertBefore(m, index, newInsns);
         }
      }
```
ends up clearing the entire method body that SpongeForge is trying to inject into [here](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/world/WorldMixin_Forge.java#L195-L203) to allow for the server override [here](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/world/WorldServerMixin_Forge.java#L153-L171).

Sorry to say that there's not really an option to add compatibility. One could technically implement the mod as a plugin or as a mod without actual class transformations.

**Comment by MRLexanayseR** [comment]
Sorry for my English. (Google Translate)
This is very sad. That nothing can be done with compatibility. But the fact is that the stable version of sponge 1.12.2-2825-7.1.6 works with the mod without errors and crashes. In the game, the mod itself also works fine, without crashes. I wanted to update the version of the sponge to the new 1.12.2-2838-7.1.7-RC3926, since there are many changes in the new version of the sponge, but it does not work. Therefore, if it works on the old version, can you still create compatibility? Thank you in advance.
