### ISSUE TITLE
Server won't start - Multiple entries with same key 

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/SpongeForge#2999]
Hello,

I noticed there were 3 already closed issues opened with similar title, but I'm having this issue when loading my plugin. 

Sponge API Version: 7.2.0-20190929.062928-29
Sponge Forge Version: spongeforge-1.12.2-2838-7.1.7-RC3927
Console Log:

```
[12:50:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Multiple entries with same key: dreadzone=Plugin{id=dreadzone, name=DreadZone, version=0.1.3, description=This plugin adds minigames!, url=http://salvadorzxa.com, authors=[SalvadorZXA], source=.\mods\DreadZone.jar} and dreadzone=Plugin{id=dreadzone, name=DreadZone, version=0.1.3, description=This plugin adds minigames!, authors=[SalvadorZXA], source=.\mods\DreadZone.jar}. To index multiple values under a key, use Multimaps.index.
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:50:40] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Salva\Desktop\Sponge 1.12.2 - Latest\.\crash-reports\crash-2019-10-07_12.50.40-server.txt
[12:50:40] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[12:50:40] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[12:50:40] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:367)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:454)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:415)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:253)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:261)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:266)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraft.server.dedicated.DedicatedServer.handler$postGameStoppingEvent$zmo000(DedicatedServer.java:1813)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraft.server.dedicated.DedicatedServer.func_71240_o(DedicatedServer.java)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589)
[12:50:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Thread.run(Unknown Source)
```

Attached is the [debug.log](https://github.com/SpongePowered/SpongeForge/files/3720913/debug.log)

**Edit:** This same error appears when creating a clean Gradle project. 
Main class:

```
package Main;

import org.spongepowered.api.plugin.Plugin;
import com.google.inject.Inject;
import java.util.logging.Logger;

import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.game.state.GameInitializationEvent;
import org.spongepowered.api.event.game.state.GameStartedServerEvent;

@Plugin(id = "testplugin", 
	name = "Test Plugin", 
	description = "Meant to test code!", 
	url = "http://salvadorzxa.com", 
	version = "0.2.0",
	authors = "SalvadorZXA")

public class Main {
	
    @Inject
    private Logger logger;

    @Listener
    public void onServerStart(GameStartedServerEvent event) {
        logger.info("Successfully running ExamplePlugin!!!");
    }

	@Listener
	public void onInit (GameInitializationEvent event){
		logger.info("Test Plugin loading...");
	}
}
```

build.gradle:

```
plugins {
    id 'java'
}

repositories {
    jcenter()
    maven {
        name = 'sponge-repo'
        url = 'http://repo.spongepowered.org/maven'
    }
}

dependencies {
    compile 'org.spongepowered:spongeapi:7.2.0-20191013.122231-30'
}
```

**Comment by JBYoshi** [comment]
Could you post the file `Sponge 1.12.2 - Latest\logs\debug.log`? That might help us figure out what's going wrong.

**Comment by SimonCROS** [comment]
Hello
I had the same error, I do not know how to fix it permanently, but it seems that it's because your plugin is loaded twice (see the table in crash-reports).
To solve it, I opened my jar with an archive utility, and deleted bin, because I saw that my main class was at two places in the jar, but only once in the project.

**Comment by JBYoshi** [comment]
Just saw the `debug.log`, and that appears to be the problem (or something like it).

```
[13:50:07] [Server thread/DEBUG] [FML]: Examining file TestPlugin.jar for potential mods
[13:50:07] [Server thread/DEBUG] [FML]: The mod container TestPlugin.jar appears to be missing an mcmod.info file
[13:50:07] [Server thread/DEBUG] [FML]: Identified a mod of type Lorg/spongepowered/api/plugin/Plugin; (Main.Main) - loading
[13:50:07] [Server thread/WARN] [Sponge]: Plugin 'testplugin' seems to be missing a valid mcmod.info metadata file. This is not a problem when testing plugins, however it is recommended to include one in public plugins.
Please see https://docs.spongepowered.org/master/en/plugin/plugin-meta.html for details.
[13:50:07] [Server thread/DEBUG] [FML]: Identified a mod of type Lorg/spongepowered/api/plugin/Plugin; (Main.Main) - loading
[13:50:07] [Server thread/WARN] [Sponge]: Plugin 'testplugin' seems to be missing a valid mcmod.info metadata file. This is not a problem when testing plugins, however it is recommended to include one in public plugins.
Please see https://docs.spongepowered.org/master/en/plugin/plugin-meta.html for details.
```

**Comment by clienthax** [comment]
Is this still an issue?,
If so can you upload the plugin jar?
