### ISSUE TITLE
Sponge 3844 Causes issue with mod Scaling health

### ISSUE THREAD

**Issue by TheParsley** [SpongePowered/SpongeForge#3010]
Sponge causes scaling health mod item "heart container" To add 2 hearts instead of one. The extra heart then makes the player go through the damage animation every time it heals up to the extra heart.

**Comment by ImMorpheus** [comment]
Please follow the issue template, it's actually rather important if you want to get dev attention to fix your issue.

Edit this issue with the required details / template, and I'll reopen and hide this comment.

**Comment by TheParsley** [comment]
I get this when i use the latest:
[09:52:12] [main/FATAL] [net.minecraft.server.MinecraftServer]: Failed to start the minecraft server
java.lang.IllegalStateException: Minecraft plugin container is not initialized
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.1.12.2.jar:?]
	at org.spongepowered.common.SpongeImpl.getMinecraftPlugin(SpongeImpl.java:174) ~[SpongeImpl.class:1.12.2-2838-7.1.7-RC3948]
	at net.minecraft.command.ServerCommandManager.bridge$wrapCommand(SourceFile:698) ~[dh.class:?]
	at net.minecraft.command.ServerCommandManager.func_71560_a(SourceFile:684) ~[dh.class:?]
	at net.minecraft.command.ServerCommandManager.<init>(SourceFile:22) ~[dh.class:?]
	at net.minecraft.server.MinecraftServer.func_175582_h(MinecraftServer.java:169) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:162) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:69) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1542) [MinecraftServer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2847-universal.jar:?]
