### ISSUE TITLE
Parsing error loading built-in advancement

### ISSUE THREAD

**Issue by husky2331** [SpongePowered/SpongeForge#3043]
Minecraft 1.12.2
- SpongeForge version: 1.12.2-2838-7.1.7
- Forge version: 2838
- Java version: ×
- Operating System: ×

- Plugins/Mods: creativecoredummy, dcs_asm, itemphysic, micdoodlecore, spongeapi, sponge, spongeforge, passableleavescore, gottagofast, techguns_core, dynamicswordskills, swordskillsapi, securitycraft, advancedsticks, advanced-fishing, mtsaircooled, alcatrazcore, arcane_essentials, armorplus, as_extraresources, asmodeuscore, avatarmod, gorecore, baubles, betterportals, bloodarsenal, bloodmagic, buildcraftcompat, buildcraftbuilders, buildcraftcore, buildcraftenergy, buildcraftfactory, buildcraftlib, buildcraftrobotics, buildcraftsilicon, buildcrafttransport, buildinggadgets, buycraft, chopdownupdated, clumps, comecloser, compatskills, conarm, extendedrenderer, coroutil, configmod, corpse, creativecore, cyberware, dse, divergentunderground, dwtmtspack, ebwizardry, enderpay, enderutilities, extraalchemy, extra_spells, fakejoinleave, firstaid, foamflower, forgelin, cfm, galacticraftplanets, galacticraftcore, galaxyspace, ivairlinerpack, grapplemod, guideapi, dcs_lib, dcs_climate, heroesexpansion, hungryanimals, icbmclassic, iconicfilmvehicles, igcm, mtsseagullmilitarypack, mts, universalmodcore, immersiverailroading, ic2, iv_tcp, iv_tep, iv_tpp, kinetic anti-cheat, libvulpes, locks, luckperms, lucraftcore, malisisadvert, malisisblocks, malisiscore, malisisdoors, malisisswitches, mantle, mca, mechsoldiers, mekanism, mekanismgenerators, mekanismtools, melvinssignpack, minerva, concheckrmd, powersuits, mmmpack, blueboyscaterpillarmtspack, mtsheavyindustrialbyadamrk, mtsofficialpack, jblavehaero, negativity, hellbound, netherbound, nhc, nomorepunchingtree, notreepunching, numina, overlord, harvestcraft, playerdatareset-plugin, playerrevive, potioncore, pymtech, realistic-chat, realistictorches, redcliffe, regeneration, reskillable, rewired, spartanshields, spartanweaponry, specialai, speedsterheroes, stellarapi, stellarsky, surge, tardis, tconstruct, techguns, the-fifth-world, theexpandedsignspack, thedragonlib, thutcore_compat, thutcore, thuttech, tinkertoolleveling, toolbelt, trackapi, trade, travellersbackpack, unloader, unucivil, unumilitary, unuparts, de.v10lator.v10verlap, teamlapen-lib, vampirism, vampirism_integrations, vending, vtb, wearablebackpacks, weather2, worldedit, worldlimiter, passableleaves, phosphor-lighting, rtg, immersiveengineering, weeping-angels

So basically I work on a server (I don't own it and it is hosted on MCProHosting) and I want to remove one error I can't find what it caused9. It seems like they are cause by wooden planks
Error message (it looks like it's same for evry plank): [21:32:42] [Server thread/ERROR] [minecraft/AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/building_blocks/jungle_planks
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:jungle_planks'
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:855) [WorldManager.class:1.12.2-2838-7.1.7]
at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:813) [WorldManager.class:1.12.2-2838-7.1.7]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by clienthax** [comment]
This generally means that another mod has been messing with vanilla recipes and has broken the advancement system during it, Not really a sponge problem.

**Comment by gatoborrachon** [comment]
sorry for necro an old issue, but it is the only issue i see an actual answer about that issue
> another mod has been messing with vanilla recipes and has broken the advancement system during

with this you mean that even if you change a vanilla recipe (from an item involved in the Advancements) with Crafttweaker, these soft-crashes will appear?
