### ISSUE TITLE
i get this error when i start the server

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3100]
java.lang.NullPointerException: null
        at org.spongepowered.common.world.WorldManager.setUuidOnProperties(WorldManager.java:951) ~[WorldManager.class:git-3d55264]
        at org.spongepowered.common.world.WorldManager.createWorldInfoFromSettings(WorldManager.java:809) ~[WorldManager.class:git-3d55264]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:751) ~[WorldManager.class:git-3d55264]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3628) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:597) [MinecraftServer.class:?]

**latest porus**

- SpongeForge version: 
- Forge version: 
- Java version: 
- Operating System:

- Plugins/Mods:

**Issue Description**

**Comment by ImMorpheus** [comment]
Please follow the issue template, it's actually rather important if you want to get dev attention to fix your issue.

Edit this issue with the required details / template, and I'll reopen and hide this comment.
