### ISSUE TITLE
[1.12.2] Sideness handling for nested classes in tile entity registration hook.

### ISSUE THREAD

**Issue by stfwi** [SpongePowered/SpongeForge#3122]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.1-RC4010
- Forge version: 1.12.2-2838
- Java version:  1.8.0_241
- Operating System: Windows 10

Mods please see https://github.com/stfwi/engineers-decor/files/4411781/latest.log.
Related issue: https://github.com/stfwi/engineers-decor/issues/91

Hey guys, can you add a sideness check (or a server side exception handling for `NoClassDefFoundError`) during the nested classes scan in tile entity registration hook?
(somewhere around `TileEntityTypeRegistryModule.doTileEntityRegistration` / `StaticMixinForgeHelper.getModIdFromClass()`).
Further details, logs, and logs are in the related issue report thread.

Cheers, wile -

**Comment by clienthax** [comment]
@stfwi Are you 100% sure you don't have any references to BlockDecorLabeledCrate$BGui from the server side?


It seems that it is the only class that fails to register.

```

[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorCraftingTable$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_crafting_table
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorLabeledCrate$LabeledCrateTileEntity
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: java.lang.NoClassDefFoundError: wile/engineersdecor/blocks/BlockDecorLabeledCrate$BGui
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at java.lang.Class.getDeclaringClass0(Native Method)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at java.lang.Class.getDeclaringClass(Class.java:1235)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at java.lang.Class.getEnclosingClass(Class.java:1277)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at java.lang.Class.getSimpleBinaryName(Class.java:1443)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at java.lang.Class.getSimpleName(Class.java:1309)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at org.spongepowered.mod.util.StaticMixinForgeHelper.getModIdFromClass(StaticMixinForgeHelper.java:323)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at org.spongepowered.common.SpongeImplHooks.getModIdFromClass(SpongeImplHooks.java:1994)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule.doTileEntityRegistration(TileEntityTypeRegistryModule.java:160)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraft.tileentity.TileEntity.handler$zkm000$impl$registerTileEntityClassWithSpongeRegistry(TileEntity.java:3755)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraft.tileentity.TileEntity.register(TileEntity.java:39)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:234)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:239)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at wile.engineersdecor.ModContent.registerBlocks(ModContent.java:715)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at wile.engineersdecor.ModEngineersDecor$RegistrationSubscriptions.registerBlocks(ModEngineersDecor.java:128)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5_RegistrationSubscriptions_registerBlocks_Register.invoke(.dynamic)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:847)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:128)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:552)
[21:06:39] [Server thread/INFO] [STDERR]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:172]: 	at java.lang.Thread.run(Thread.java:748)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: wile.engineersdecor.blocks.BlockDecorLabeledCrate$BGui
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 26 more
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@60743cdb from coremod FMLCorePlugin
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 28 more
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.RuntimeException: Attempted to load class wile/engineersdecor/blocks/BlockDecorLabeledCrate$BGui for invalid side SERVER
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[21:06:39] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	... 30 more
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorFurnace$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_lab_furnace
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorFurnaceElectrical$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_electrical_lab_furnace
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorHopper$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_factory_hopper
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorDropper$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_factory_dropper
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorPlacer$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_factory_placer
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorBreaker$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_block_breaker
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorTreeCutter$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_tree_cutter
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorWasteIncinerator$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_waste_incinerator
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorSolarPanel$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_solar_panel
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorMineralSmelter$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_mineral_smelter
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorPipeValve$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_pipe_valve
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorFluidFunnel$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_fluid_funnel
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorPassiveFluidAccumulator$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_passive_fluid_accumulator
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:157]: wile.engineersdecor.blocks.BlockDecorMilker$BTileEntity
[21:06:39] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule:doTileEntityRegistration:166]: registered engineersdecor:te_small_milking_machine
```

**Comment by stfwi** [comment]
Hey clienthax - good that you asked that question, I just saw indeed constants that can be indirectly referenced. Strangely enough I get no errors on dedicated servers - but that's definitely a thing to fix. So, gonna reopen my issue and keep you in the loop.

**Comment by stfwi** [comment]
Okay, unused but referenced constant did cause the issue in my Crate UI. Was undetected until now as dedicates servers do not actually access them. A fix on my side is committed an pushed, you can close the issue here. Cheers, thx again for catching a glimpse on the situation.
