### ISSUE TITLE
JourneyMap

### ISSUE THREAD

**Issue by Heriptik** [SpongePowered/SpongeForge#3127]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.2.0
- Forge version: 2838
- Java version: 242
- Operating System: Debian

**Issue Description**

In latest SpongeForge version, the JourneyMap does not display the map at the first connection :
https://image.noelshack.com/fichiers/2020/15/2/1586231093-2020-04-07-05-38-15.png

You must change dimensions for the map appear

This only does on sponge servers

**Comment by clienthax** [comment]
Client side log?

**Comment by GuusLieben** [comment]
I'm having the same issue on my server. Same versions for Sponge, Forge, and same server OS. Java version 1.8_231. JourneyMap version 1.12.2-5.5.5 (though also tested with newer versions)

Client side stacktrace :
```
[17:16:00] [Client thread/INFO] [FML]: Injecting existing registry data into this client instance
[17:16:01] [Client thread/INFO] [foamfix]: JEI search tree manager injection complete!
[17:16:01] [Client thread/INFO] [FML]: Applying holder lookups
[17:16:01] [Client thread/INFO] [FML]: Holder lookups applied
[17:16:01] [Client thread/ERROR] [journeymap]: Error in JourneyMap.performMainThreadTasks(): java.lang.NullPointerException
	at journeymap.client.JourneymapClient.stopMapping(JourneymapClient.java:584)
	at journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:43)
	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:84)
	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:654)
	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:91)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_113_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[17:16:01] [Netty Client IO #9/INFO] [FML]: [Netty Client IO #9] Client side modded connection established```
