### ISSUE TITLE
Advancement Crashing Server 

### ISSUE THREAD

**Issue by StrayCargo** [SpongePowered/SpongeForge#3146]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.1-RC4017
- Forge version: forge-1.12.2-14.23.5.2847-universal.jar
- Java version: 1.8.0_242
- Operating System: Ubuntu 18.04

- Plugins/Mods: No Plugins and all the mods 3 remix version 1.5.4

<!-- Please include as much information as possible. For the description, assume we have no idea Crashing on Startup due to advancements not parsing 
**Issue Description**
Advancement will not load and a not parsing causing a loop of the same series of processes then it crashes 

<!-- Please provide a *full* server log (and crash-report if applicable).
https://gist.github.com/StrayCargo/cd8c51520c130c5a27f9bcb534523b14

**Comment by StrayCargo** [comment]
https://gist.github.com/StrayCargo/cd8c51520c130c5a27f9bcb534523b14

**Comment by gabizou** [comment]
Gonna need the narrowed down list of mods needed to reproduce the issue. Also, need some logs to know what the error is.

**Comment by StrayCargo** [comment]
I can get the log but I cannot narrow down the mod list as it may not occur with the certain mods perhaps not sure.

**Comment by StrayCargo** [comment]
https://gist.github.com/StrayCargo/cd8c51520c130c5a27f9bcb534523b14

**Comment by StrayCargo** [comment]
https://gist.github.com/StrayCargo/b4c480bda55701a77cbe2faa2f44cbd2

**Comment by StrayCargo** [comment]
also tried a revision down and the same result on one version back

**Comment by GuusLieben** [comment]
The advancement errors are harmless. They're usually caused by a mod modifying the vanilla loot table or vanilla items that occur in it. 

It seems ComputerCraft is causing the issue, as it appears to cause a single tick to take 12.15 seconds (12.10 seconds longer than technically allowed)

```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 12.15 seconds (should be max 0.05)
	at dan200.computercraft.shared.proxy.ComputerCraftProxyCommon.initServer(ComputerCraftProxyCommon.java:75)
	at dan200.computercraft.ComputerCraft.onServerStarting(ComputerCraft.java:268)
```
One option would be to change `max-tick-time` in your server.properties to something higher (personally I use `60000` by default), as it might just take a bit long to register during server loading.

I'd be surprised if this was actually caused by Sponge, as both errors can be replicated with just Forge itself

**Comment by StrayCargo** [comment]
that did fix it when disabled Watchdog but now we need to fix the advancement issues

**Comment by StrayCargo** [comment]
Perhaps theirs a for Spongeforge to take care of advancements and disable them if they conflict

**Comment by clienthax** [comment]
Where is the log of the advancement crashing the server?

**Comment by StrayCargo** [comment]
This should help https://gist.github.com/StrayCargo/6f87b80f72e59f7fe042a545d2fd4e54

**Comment by StrayCargo** [comment]
so not only is that causing an issue but this too Stopping aura thread for dim 144
it could be having issues due to thaumcraft or it could just be thaumcraft
also, this was not occurring before we added sponge forge

**Comment by clienthax** [comment]
That's not a crash..?
