### ISSUE TITLE
Error while creating CraftingInventoryLensImpl or GridInventoryLensImpl with ClockworkPhase

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#3196]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.3
- Forge version: 14.23.5.2854
- Java version: 1.8.0_252/64-bit (Oracle Corporation)
- Operating System: Linux (4.19.62-mod-std-ipv6-64-rescue/amd64)

- Plugins/Mods:
Plugins (20): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, Buycraft, CatClearLag, GriefDefender, HuskyCrates, HuskyUI, LuckPerms, MagiBridge, Nucleus, Prism, Server Backup, Total Economy, WrapperPing, spark
Mods (174): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, AgriCraft, Always Eat Mod, AppleSkin, Applied Energistics 2, Arcane Archives, Arcane Essentials, Arcane World, Armourer's Workshop, Astral Sorcery, Automated Redstone, B.A.S.E, BD Lib, BNBGamingLib, Bad Wither No Cookie! Reloaded, Bauble Wings, Baubles, Bewitchment, BiblioCraft, Biomes O' Plenty, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bookshelf, Bookworm Library, Botania, Building Gadgets, CD4017BE_lib, Cathedral, Chameleon, Chisel, Chococraft 3, Clockwork Phase, CoFH Core, CoFH World, CodeChicken Lib, Comforts, Construct's Armory, Cooking for Blockheads, Coralreef, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Creeper Confetti, Cucumber Library, Cyclops Core, Diet Hopper, Doggy Talents, Dynamic Surroundings, Dynamic Trees, Dynamic Trees BOP, Dynamic Trees PHC, Electroblob's Wizardry, Enchanted Wolves, Enchanting Plus, End: Reborn, EverlastingAbilities, EvilCraft, EvilCraft-Compat, Extra Cells 2, Fairy Lights, Fast Leaf Decay, FastFurnace, FastWorkbench, Fence Jumper, FoamFix, FoamFixCore, Foamflower, Forbidden & Arcanus, Fossils and Archeology Revival, Garbage Bins, Garden Stuff, Guide-API, Guidebook, HelpFixer, Huggable Cactuses, Ice and Fire, Immersive Cables, Immersive Engineering, Immersive Posts, Infernal Mobs, InfinityLib, Inventory Pets, Inventory Tweaks, It's the little things, JJ Races, JourneyMap, Just Enough Items, LLibrary, LagGoggles, LemonLib, LittleTiles, LittleTilesCore, LunatriusCore, MTLib, Mantle, MetalChests, Metallurgy 4: Reforged, Minecraft Comes Alive, MmmMmmMmmMmm, Mod Tweaker, Morph, Morpheus, Mowzie's Mobs, Mowzie's Wings, Mystical Agradditions, Mystical Agriculture, Mystical Agriculture Tiered Crystals, Mystical Lib, Mystical World, Nature's Aura, NemesisSystem, Nether Chest, NetherPortalFix, OreExcavation, OreLib Support Mod, Pam's Cookables, Pam's HarvestCraft, Patchouli, Phosphor Lighting Engine, Placebo, PlusTiC, RandomPatches, Rats, Reborn Core, Redstone Flux, Redstone Paste, Reliquary, Runes of Wizardry, Runes of Wizardry - Classic Dusts Pack, Schematica, Shadowfacts' Forgelin, Snad, Soul Shards Respawn, SpongeForge, Steam Age Revolution, Steam Motion, Storage Drawers, SwingThroughGrass, TBone, TOP Addons, TeamLapen Library, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Thermal Logistics, TickCentral, Tinker's JEI, Tinkering With Blood Magic, Tinkers Tool Leveling, Tinkers' Construct, ToroTraits, Underground Biomes, Vampirism, VampirismIntegrations, Vending, Waystones, Whoops, Wings, WorldEdit, Zoo and Wild Animals Mod: Rebuilt, iChunUtil

Specifically using ClockworkPhase-1.12.2-1.0.8

**Issue Description**
When player opens the Tool page of a Clockwork Assembly Table, then pickup any item, a callstack is dumped in console about 
```
Error while creating CraftingInventoryLensImpl or GridInventoryLensImpl for lumaceon.mods.clockworkphase.client.gui.container.ContainerClockworkAssemblyTableAssemble
java.lang.IndexOutOfBoundsException: Index: 39
```
The mod seems to work fine otherwise.

Steps to reproduce:
- Place a Clockwork Assembly Table
- Click the sandglass button to see the tool assembly page:
![image](https://user-images.githubusercontent.com/4776032/89585611-6e666e00-d83e-11ea-84ee-5b0d0439f9bd.png)
- The page should look like that:
![image](https://user-images.githubusercontent.com/4776032/89585637-7b835d00-d83e-11ea-8752-3f8061d32328.png)
- while on that page, click any item from your normal inventory

https://gist.github.com/LemADEC/bb1ac808a234fe26f954971e82d635db

**Comment by Faithcaio** [comment]
https://github.com/Lumaceon/ClockworkPhase/blob/master/src/main/java/lumaceon/mods/clockworkphase/client/gui/container/ContainerClockworkAssemblyTableAssemble.java

4x9 + 3 Slots 

The "matrix" inventory has 9 slots of which only 2 are used.

```
java.lang.IndexOutOfBoundsException: Index: 39
	at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.checkIndex(DynamicLensCollectionImpl.java:156) ~[DynamicLensCollectionImpl.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.getLens(DynamicLensCollectionImpl.java:94) ~[DynamicLensCollectionImpl.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.get(DynamicLensCollectionImpl.java:89) ~[DynamicLensCollectionImpl.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.lens.impl.collections.SlotCollection.getSlot(SlotCollection.java:123) ~[SlotCollection.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.lens.impl.comp.CraftingInventoryLensImpl.init(CraftingInventoryLensImpl.java:64) ~[CraftingInventoryLensImpl.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.lens.impl.comp.OrderedInventoryLensImpl.<init>(OrderedInventoryLensImpl.java:58) ~[OrderedInventoryLensImpl.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.lens.impl.comp.CraftingInventoryLensImpl.<init>(CraftingInventoryLensImpl.java:52) ~[CraftingInventoryLensImpl.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.lens.impl.comp.CraftingInventoryLensImpl.<init>(CraftingInventoryLensImpl.java:48) ~[CraftingInventoryLensImpl.class:1.12.2-2838-7.2.4-RC4065]
	at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:265) [ContainerUtil.class:1.12.2-2838-7.2.4-RC4065]
	at net.minecraft.inventory.Container.bridge$generateLens(Container.java:2015) [afr.class:?]
	at net.minecraft.inventory.Container.bridge$getRootLens(Container.java:2654) [afr.class:?]
	at net.minecraft.inventory.Container.impl$getAdapters(Container.java:2027) [afr.class:?]
	at net.minecraft.inventory.Container.bridge$getContainerSlot(Container.java:2473) [afr.class:?]
	at net.minecraft.inventory.Container.bridge$detectAndSendChanges(Container.java:2121) [afr.class:?]
	at net.minecraft.inventory.Container.func_75142_b(Container.java:2094) [afr.class:?]
```
