### ISSUE TITLE
Error when loading plugin: "error in opening zip file"

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3201]
**I am currently running**

- SpongeForge version: `1.12.2-2838-7.2.3`
- Forge version: `14.23.5.2854`
- Java version: `1.8.0_252`
- Operating System: `Ubuntu 20.04 LTS`

I don't know if this is a problem with Forge or with SpongeForge itself. When FML tries to load a plugin, this error is raised:
```
[03:59:22] [main/ERROR] [FML]: Unable to read the jar file SkinsRestorer.jar - ignoring
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_252]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_252]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_252]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_252]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_252]
        at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:200) [forge.jar>
        at net.minecraftforge.fml.relauncher.libraries.LibraryManager.cleanDirectory(LibraryManager.java:169) [forge.ja>
        at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:97) [forge.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) [forge.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:87) [forge.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) [forge>
        at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) [for>
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge.jar:?]
```

**Comment by Zidane** [comment]
This is not a Sponge issue, Forge is having issues reading the library jar.
