### ISSUE TITLE
HOW TO FIX this ?

### ISSUE THREAD

**Issue by a6060741** [SpongePowered/SpongeForge#3206]
[00:33:15] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerDestroyItemEvent@1d4927fa:
java.lang.NullPointerException: null
	at com.bewitchment.common.handler.PoppetHandler.toolProtection(PoppetHandler.java:170) ~[PoppetHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1765_PoppetHandler_toolProtection_PlayerDestroyItemEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerDestroyItem(ForgeEventFactory.java:204) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.getContainerItem(ForgeHooks.java:1029) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.defaultRecipeGetRemainingItems(ForgeHooks.java:1007) [ForgeHooks.class:?]
	at net.minecraft.item.crafting.IRecipe.getRemainingItems(IRecipe.java:20) [akt.class:?]
	at com.rwtema.extrautils2.tile.TileCrafter.operate(TileCrafter.java:239) [TileCrafter.class:?]
	at com.rwtema.extrautils2.tile.TileAdvInteractor.update(TileAdvInteractor.java:94) [TileAdvInteractor.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237) [TrackingUtil.class:1.12.2-2838-7.3.1-RC4077]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:5249) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$zme000$onUpdateTileEntities(WorldServer.java:5233) [oo.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1838) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:4431) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_265]
[00:33:15] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[00:33:15] [Server thread/ERROR] [FML]: 0: NORMAL
[00:33:15] [Server thread/ERROR] [FML]: 1: ASM: class crazypants.enderio.base.handler.darksteel.UpgradeRegistry onItemDesctroyed(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[00:33:15] [Server thread/ERROR] [FML]: 2: ASM: crafttweaker.mc1120.events.CommonEventHandler@a4e76ff0 onPlayerDestroyItemEvent(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[00:33:15] [Server thread/ERROR] [FML]: 3: ASM: com.bewitchment.common.handler.PoppetHandler@9b4bd915 toolProtection(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[00:33:15] [Server thread/ERROR] [FML]: 4: ASM: ItemForestryTool{Name=null} onDestroyCurrentItem(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[00:33:15] [Server thread/ERROR] [FML]: 5: ASM: ItemForestryTool{Name=null} onDestroyCurrentItem(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[00:33:15] [Server thread/ERROR] [FML]: 6: ASM: svenhjol.charm.enchanting.feature.Salvage@c8b8973a onDestroy(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[00:33:15] [Server thread/ERROR] [FML]: 7: ASM: mob_grinding_utils.events.ChickenFuseEvent@dee9b8d4 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[00:33:15] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************************/
[00:33:15] [Server thread/ERROR] [Sponge]: /*                                                  Exception occurred during a PhaseState                                                  */
[00:33:15] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************************/
[00:33:15] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best                                                                                                    */
[00:33:15] [Server thread/ERROR] [Sponge]: /* effort to not throw exceptions randomly                                                                                                  */
[00:33:15] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most                                                                                                  */
[00:33:15] [Server thread/ERROR] [Sponge]: /* cases, something else triggered this                                                                                                     */
[00:33:15] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash                                                                                                   */
[00:33:15] [Server thread/ERROR] [Sponge]: /* by catching it. The following stacktrace                                                                                                 */
[00:33:15] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                                  */
[00:33:15] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************************/
[00:33:15] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: Tick{TileEntity}                                                                                     */
[00:33:15] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                                        */
[00:33:15] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@a610ba8f                                                                                        */
[00:33:15] [Server thread/ERROR] [Sponge]: /*                                                                                                                                          */
[00:33:15] [Server thread/ERROR] [Sponge]: /*  StackTrace :                                                                                                                            */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     java.lang.NullPointerException: null                                                                                                 */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     com.bewitchment.common.handler.PoppetHandler.toolProtection(PoppetHandler.java:170)                                                  */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1765_PoppetHandler_toolProtection_PlayerDestroyItemEvent.invoke(.dynamic) */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)                                           */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)                                              */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706)                                                          */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.event.ForgeEventFactory.onPlayerDestroyItem(ForgeEventFactory.java:204)                                           */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.common.ForgeHooks.getContainerItem(ForgeHooks.java:1029)                                                          */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.common.ForgeHooks.defaultRecipeGetRemainingItems(ForgeHooks.java:1007)                                            */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.item.crafting.IRecipe.getRemainingItems(IRecipe.java:20)                                                               */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     com.rwtema.extrautils2.tile.TileCrafter.operate(TileCrafter.java:239)                                                                */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     com.rwtema.extrautils2.tile.TileAdvInteractor.update(TileAdvInteractor.java:94)                                                      */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)                                           */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:5249)                                                              */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$zme000$onUpdateTileEntities(WorldServer.java:5233)                                          */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.updateEntities(World.java:1838)                                                                            */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.updateEntities(WorldServer.java:4431)                                                                */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)                                            */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)                                  */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)                                                                  */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                   */
[00:33:15] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Thread.java:823)                                                                                                */
[00:33:15] [Server thread/ERROR] [Sponge]: /*                                                                                                                                          */
[00:33:15] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                                       */
[00:33:15] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.3.0-299f484b6                                                                                                              */
[00:33:15] [Server thread/ERROR] [Sponge]: /* Sponge : 1.12.2-7.3.1-SNAPSHOT                                                                                                           */
[00:33:15] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2838-7.3.1-RC4077                                                                                                   */
[00:33:15] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.5.2847                                                                                                           */
[00:33:15] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************************/

I use spong in the Eternal (ServerPack 1.3.7)
Suddenly appeared today
this msg 
replay  report my cmd
log is big

how to fix tihs?

**Comment by a6060741** [comment]
I found the problem
And solved it smoothly
thx
