### ISSUE TITLE
IllegalStateException: Block Change Proxy corruption

### ISSUE THREAD

**Issue by forresthopkinsa** [SpongePowered/SpongeForge#3225]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.3.0
- Forge version: 14.23.5.2838
- Java version: 1.8.0_272
- Operating System: Ubuntu Server 20.04

- Plugins/Mods:

```
	Mods:

	| State  | ID                                           | Version                  | Source                                         | Signature                                |
	|:------ |:-------------------------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                                          | 9.42                     | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core                            | 1.12.2-1.0               | minecraft.jar                                  | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                  | None                                     |
	| LCHIJA | spongeapi                                    | 7.3-7127e0882            | spongeforge-1.12.2-2838-7.3.0.jar              | None                                     |
	| LCHIJA | sponge                                       | 1.12.2-7.3.0             | spongeforge-1.12.2-2838-7.3.0.jar              | None                                     |
	| LCHIJA | spongeforge                                  | 1.12.2-2838-7.3.0        | spongeforge-1.12.2-2838-7.3.0.jar              | None                                     |
	| LCHIJA | aether_legacy                                | 1.5.2                    | aether-1.12.2-v1.5.2.jar                       | None                                     |
	| LCHIJA | applecore                                    | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                   | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | astralsorcery                                | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar               | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | jei                                          | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJA | quark                                        | r1.6-179                 | Quark-r1.6-179.jar                             | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-32                   | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHIJA | bettercaves                                  | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                   | None                                     |
	| LCHIJA | bettermineshafts                             | 1.12.2-2.1.0             | BetterMineshaftsForge-1.12.2-2.1.0.jar         | None                                     |
	| LCHIJA | biomesoplenty                                | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar  | None                                     |
	| LCHIJA | blockcraftery                                | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                 | None                                     |
	| LCHIJA | cd4017be_lib                                 | 6.5.1                    | CD4017BE_lib-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| LCHIJA | codechickenlib                               | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                                 | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCHIJA | cofhcore                                     | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCHIJA | cofhworld                                    | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCHIJA | mantle                                       | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCHIJA | conarm                                       | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | cookingforblockheads                         | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar          | None                                     |
	| LCHIJA | darknesslib                                  | 1.1.0                    | DarknessLib-1.12.2-1.1.0.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | movingworld                                  | 1.12-6.353               | movingworld-1.12-6.353-full.jar                | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar            | None                                     |
	| LCHIJA | sereneseasons                                | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar      | None                                     |
	| LCHIJA | orelib                                       | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                                    | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dynamictrees                                 | 1.12.2-0.9.14            | DynamicTrees-1.12.2-0.9.14.jar                 | None                                     |
	| LCHIJA | dynamictreesbop                              | 1.12.2-1.4.2             | DynamicTreesBOP-1.12.2-1.4.2.jar               | None                                     |
	| LCHIJA | natura                                       | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                     | None                                     |
	| LCHIJA | dynamictreesnatura                           | 1.12.2-1.1.2             | dynamictreesNatura-1.12.2-1.1.2.jar            | None                                     |
	| LCHIJA | harvestcraft                                 | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                | None                                     |
	| LCHIJA | dynamictreesphc                              | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar               | None                                     |
	| LCHIJA | dynamictreesquark                            | 1.12.2-1.0.4             | dynamictreesQuark-1.12.2-1.0.4.jar             | None                                     |
	| LCHIJA | rustic                                       | 1.1.6                    | rustic-1.1.6.jar                               | None                                     |
	| LCHIJA | thaumcraft                                   | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| LCHIJA | dynamictreestc                               | 1.12.2-1.4.2             | DynamicTreesTC-1.12.2-1.4.2.jar                | None                                     |
	| LCHIJA | dynamictreestconstruct                       | 1.12.2-1.2.2             | dynamictreesTConstruct-1.12.2-1.2.2.jar        | None                                     |
	| LCHIJA | dynamictreestheaether                        | 1.12.2-1.0.9             | dynamictreesTheAether-1.12.2-1.0.9.jar         | None                                     |
	| LCHIJA | forgelin                                     | 1.8.4                    | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | grue                                         | 1.8.0                    | Grue-1.12.2-1.8.0.jar                          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | waila                                        | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | llibrary                                     | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                                   | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCHIJA | ichunutil                                    | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | refinedstorage                               | 1.6.16                   | refinedstorage-1.6.16.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | railcraft                                    | 12.0.0                   | railcraft-12.0.0.jar                           | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | thermalfoundation                            | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCHIJA | immersiveengineering                         | 0.12-98                  | ImmersiveEngineering-0.12-98.jar               | None                                     |
	| LCHIJA | immersivecables                              | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar               | None                                     |
	| LCHIJA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | libraryex                                    | 1.1.3                    | LibraryEx-1.12.2-1.1.3.jar                     | None                                     |
	| LCHIJA | mobends                                      | 1.0.0-beta-20.06.20      | MoBends_1.12.2-1.0.0-beta-20.06.20.jar         | None                                     |
	| LCHIJA | netherex                                     | 2.1.8                    | NetherEx-1.12.2-2.1.8.jar                      | None                                     |
	| LCHIJA | portalgun                                    | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | storagedrawers                               | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
	| LCHIJA | storagedrawersextra                          | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar            | None                                     |
	| LCHIJA | beneath                                      | 1.7.0                    | The+Beneath-1.12.2-1.7.0.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | thermalexpansion                             | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCHIJA | thermaldynamics                              | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None                                     |
	| LCHIJA | tinkersaether                                | 1.4.0                    | tinkersaether-1.4.0.jar                        | None                                     |
	| LCHIJA | tinkersjei                                   | 1.2                      | tinkersjei-1.2.jar                             | None                                     |
	| LCHIJA | tumbleweed                                   | 1.12-0.4.7               | tumbleweed-1.12-0.4.7.jar                      | None                                     |
	| LCHIJA | dimstack                                     | 0.1.9                    | VerticallyStackedDimensions-1.12.2-0.1.9.jar   | None                                     |
	| LCHIJA | wanionlib                                    | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                       | None                                     |
	| LCHIJA | xaerominimap                                 | 20.26.0                  | Xaeros_Minimap_20.26.0_Forge_1.12.jar          | None                                     |
	| LCHIJA | hungeroverhaul                               | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar     | None                                     |
	| LCHIJA | mysticallib                                  | 1.12.2-1.5.0             | mysticallib-1.12.2-1.5.0.jar                   | None                                     |
	| LCHIJA | unidict                                      | 1.12.2-2.9.6             | UniDict-1.12.2-2.9.6.jar                       | None                                     |


	Plugins:

	| State  | ID        | Version       | Source                                         | Signature |
	|:------ |:--------- |:------------- |:---------------------------------------------- |:--------- |
	| LCHIJA | luckperms | 5.2.15        | LuckPerms-Sponge-5.2.15.jar                    | None      |
	| LCHIJA | nucleus   | 2.2.3         | Nucleus-2.2.3-MC1.12.2-SpongeAPI7.3-plugin.jar | None      |
	| LCHIJA | plan      | 5.1 build 770 | Plan-5.1-build-770.jar                         | None      |
````

**Issue Description**

I can't reliably reproduce the error, but I'm hoping to get more info on what exactly I should be looking for.

Server crashes, seemingly spontaneously; the players online weren't doing anything new. One player had just gone through an Astral Sorcery portal, and another one had just placed down Starlight. They've done both of these things a number of times in the past.

I will continue tracking this error when it happens and I'll update this issue accordingly.

Log snip:

```
Time: 11/5/20 11:47 PM
Description: Exception ticking world

java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess.popProxy(SpongeProxyBlockAccess.java:189)
	at org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess.popProxy(SpongeProxyBlockAccess.java:150)
	at org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess.access$300(SpongeProxyBlockAccess.java:60)
	at org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess$Proxy.close(SpongeProxyBlockAccess.java:590)
	at org.spongepowered.common.event.tracking.context.MultiBlockCaptureSupplier.clearProxies(MultiBlockCaptureSupplier.java:802)
	at org.spongepowered.common.event.tracking.context.MultiBlockCaptureSupplier.processTransactions(MultiBlockCaptureSupplier.java:753)
...
	Suppressed: java.lang.IllegalStateException: Block Change Proxy corruption! Attempted to pop a proxy that was not on the stack.
		at org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess.popProxy(SpongeProxyBlockAccess.java:128)
		at org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess.access$300(SpongeProxyBlockAccess.java:60)
		at org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess$Proxy.close(SpongeProxyBlockAccess.java:590)
		at org.spongepowered.common.event.tracking.context.MultiBlockCaptureSupplier.processTransactions(MultiBlockCaptureSupplier.java:730)
		at org.spongepowered.common.event.tracking.TrackingUtil.performBlockAdditions(TrackingUtil.java:594)
		at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:463)
		at org.spongepowered.common.event.tracking.UnwindingState.performPostBlockNotificationsAndNeighborUpdates(UnwindingState.java:293)
		at org.spongepowered.common.event.tracking.UnwindingState.performPostBlockNotificationsAndNeighborUpdates(UnwindingState.java:53)
		at org.spongepowered.common.event.tracking.TrackingUtil.performNeighborAndClientNotifications(TrackingUtil.java:738)
		at org.spongepowered.common.event.tracking.context.BlockTransaction$ChangeBlock.process(BlockTransaction.java:477)
```

[Full log](https://gist.github.com/forresthopkinsa/f9a3136a92789151176b905d1a9f0143)

[Crash report](https://gist.github.com/forresthopkinsa/fba0c0991618b50947471dd57b44cc76)

**Comment by forresthopkinsa** [comment]
This has continued to happen a lot. It doesn't have to do with Astral Sorcery portals, it happens on chunk load in certain areas. I still can't reliably reproduce the problem, but it only seems to happen when players are walking in a certain part of the world. I get a few log messages about chunks being loaded right before the incredibly long stack trace.
