### ISSUE TITLE
1.12.2-2838-7.4.7 crash in pure forge-2838 server-end when start-up.

### ISSUE THREAD

**Issue by Kenhuey** [SpongePowered/SpongeForge#3308]
### Version

7.4.7

### Operating System

Windows 11

### Java Version

jdk_8u202_x64 or jre_8u202_x64

### Plugins/Mods

Only sponge in ./mods folder.

### Describe the bug

Seems like **java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContextFactory** cause that.
I am using forge installer for server, **org.apache.logging.log4j** looks like not including in original forge libiray.
Did I missed some step to install spongeforge for server?

Crash logs context:
```
[23:11:03] [Server thread/INFO] [Sponge]: Creating injector in stage 'PRODUCTION'
[23:11:03] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContextFactory.isClassLoaderDependent()Z
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:49) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46) ~[minecraft_server.1.12.2.jar:?]
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
        at org.spongepowered.common.inject.SpongeImplementationModule.configure(SpongeImplementationModule.java:96) ~[SpongeImplementationModule.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.inject.SpongeForgeModule.configure(SpongeForgeModule.java:45) ~[SpongeForgeModule.class:1.12.2-2838-7.4.7]
        at com.google.inject.PrivateModule.configure(PrivateModule.java:101) ~[PrivateModule.class:1.12.2-2838-7.4.7]
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347) ~[Elements$RecordingBinder.class:1.12.2-2838-7.4.7]
        at com.google.inject.spi.Elements.getElements(Elements.java:104) ~[Elements.class:1.12.2-2838-7.4.7]
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137) ~[InjectorShell$Builder.class:1.12.2-2838-7.4.7]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105) ~[InternalInjectorCreator.class:1.12.2-2838-7.4.7]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[Guice.class:1.12.2-2838-7.4.7]
        at com.google.inject.Guice.createInjector(Guice.java:78) ~[Guice.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:219) ~[SpongeMod.class:1.12.2-2838-7.4.7]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_202]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_202]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:377) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
[23:11:03] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: F:\dev\mas.mythsland\.dev\test\.\crash-reports\crash-2022-12-06_23.11.03-server.txt
[23:11:03] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.IllegalStateException: Sponge has not been initialized!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.api.Sponge.check(Sponge.java:77) ~[Sponge.class:1.12.2-2838-7.4.7]
        at org.spongepowered.api.Sponge.getGame(Sponge.java:91) ~[Sponge.class:1.12.2-2838-7.4.7]
        at org.spongepowered.api.Sponge.isServerAvailable(Sponge.java:229) ~[Sponge.class:1.12.2-2838-7.4.7]
        at net.minecraft.server.MinecraftServer.handler$zjh000$onStopServer(MinecraftServer.java:4634) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
```

**Comment by Kenhuey** [comment]
Fixed, use 2860 version forge.

**Comment by TheXeler** [comment]
Will Version 2860 not cause compatibility issues?
