### ISSUE TITLE
I could not download the "Sponge-librarys", it views "Failed to download library" when i run the bat. 

### ISSUE THREAD

**Issue by Alivec** [SpongePowered/SpongeForge#3313]
### Version

8.1.0

### Operating System

Win10

### Java Version

1.8.0_291

### Plugins/Mods

```shell
spongeforge-1.16.5-36.2.5-8.1.0-RC1264-universal
```

### Describe the bug

[21:18:10] [main/INFO] [or.sp.fo.ap.lo.mo.li.LibraryManager/]: Scanning and verifying libraries in '.\sponge-libraries'. Please wait, this may take a moment...
[21:18:10] [pool-2-thread-16/ERROR] [or.sp.fo.ap.lo.mo.li.LibraryManager/]: Failed to download library
java.util.concurrent.CompletionException: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture.biRelay(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$BiRelay.tryFire(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:1.8.0_291] {}
        at org.spongepowered.forge.applaunch.loading.moddiscovery.library.AsyncUtils.lambda$asyncFailableFuture$0(AsyncUtils.java:42) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_291] {}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
        at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_291] {}
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:1.8.0_291] {}
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_291] {}
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:1.8.0_291] {}
        at org.spongepowered.forge.applaunch.loading.moddiscovery.library.LibraryManager.getResponseFor(LibraryManager.java:209) ~[?:?] {}
        at org.spongepowered.forge.applaunch.loading.moddiscovery.library.LibraryManager.lambda$validate$0(LibraryManager.java:154) ~[?:?] {}
        at org.spongepowered.forge.applaunch.loading.moddiscovery.library.AsyncUtils.lambda$asyncFailableFuture$0(AsyncUtils.java:40) ~[?:?] {}
        ... 3 more
        Suppressed: java.net.SocketException: Connection reset by peer: socket write error
                at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_291] {}
                at java.net.SocketOutputStream.socketWrite(Unknown Source) ~[?:1.8.0_291] {}
                at java.net.SocketOutputStream.write(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_291] {}
                at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_291] {}
                at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:1.8.0_291] {}
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_291] {}
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:1.8.0_291] {}
                at org.spongepowered.forge.applaunch.loading.moddiscovery.library.LibraryManager.getResponseFor(LibraryManager.java:209) ~[?:?] {}
                at org.spongepowered.forge.applaunch.loading.moddiscovery.library.LibraryManager.lambda$validate$0(LibraryManager.java:154) ~[?:?] {}
                at org.spongepowered.forge.applaunch.loading.moddiscovery.library.AsyncUtils.lambda$asyncFailableFuture$0(AsyncUtils.java:40) ~[?:?] {}
                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_291] {}
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_291] {}
                at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_291] {}
        at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_291] {}
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_291] {}
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:1.8.0_291] {}
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_291] {}
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:1.8.0_291] {}
        at org.spongepowered.forge.applaunch.loading.moddiscovery.library.LibraryManager.getResponseFor(LibraryManager.java:209) ~[?:?] {}
        at org.spongepowered.forge.applaunch.loading.moddiscovery.library.LibraryManager.lambda$validate$0(LibraryManager.java:154) ~[?:?] {}
        at org.spongepowered.forge.applaunch.loading.moddiscovery.library.AsyncUtils.lambda$asyncFailableFuture$0(AsyncUtils.java:40) ~[?:?] {}
        ... 3 more
[21:18:10] [main/ERROR] [or.sp.fo.ap.lo.mo.li.LibraryManager/]: Failed to download some libraries:
[21:18:10] [main/ERROR] [or.sp.fo.ap.lo.mo.li.LibraryManager/]: javax.net.ssl.SSLException: java.net.SocketException: Connection reset

**Comment by Alivec** [comment]
I have used the spongeforge for a long time, and it's i try API-8.1.0 first, i get bad when the beginning. Help me please, and i will be very thankful of you~

**Comment by NickLouder** [comment]
Hi. Recently I decided to create my own server with mods, but ate as I got to the moment with the launch of forge.

The problem with version 1.16.5 is that it has not yet been fully disclosed, for example, as 1.12.2. When you create a server on 1.16.5, you must install the latest version of forge, at the moment it is 36.2.34. At the same time, your sponge must be the same version as forge, but the latest version of sponge that exists is 36.2.5.

If you try to find a common version, it is unlikely that you will succeed. If you install forge 36.2.5, the server will not start, and there is no other version of sponge.

If you try to install the latest version of forge (36.2.34) and the latest version of sponge (36.2.5), then some mods will work, and some will not. You can forget about plugins. I'm now faced with this problem and I think I'll try to do everything on 1.12.2, even if I don't really want to, but what can I do.

I don't know much about it yet, but I hope I helped you. If I wrote something wrong somewhere, then correct me. Thanks.
