### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by BinaryAura** [SpongePowered/SpongeForge#376]
clicking on the download links on https://repo.spongepowered.org causes a 404 message to appear.

**Comment by liach** [comment]
[Here] (https://repo.spongepowered.org/maven/) is the actual maven repo. https://repo.spongepowered.org just link to spongepowered.org

**Comment by Tzky** [comment]
Staff is aware of this issue and currently trying to fix it. :)

**Comment by HorusDev** [comment]
SpongeForge builds can be now found at http://files.minecraftforge.net/spongepowered

**Comment by BinaryAura** [comment]
Thanks. I used the version available there and it gave me and it failed to launch Minecraft. the "latest log" is as follows (I tried to attach this file, but Github yelled at me :frowning: ):

latest:

[22:16:46] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[22:16:46] [main/INFO]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[22:16:46] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:16:46] [main/INFO]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[22:16:46] [main/INFO]: Bootstrapping LiteLoader 1.8
[22:16:47] [main/INFO]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[22:16:47] [main/INFO]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[22:16:47] [main/INFO]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[22:16:47] [main/INFO]: Initialising API 'liteloader' ...
[22:16:47] [main/INFO]: LiteLoader begin PREINIT...
[22:16:47] [main/INFO]: Initialising Loader properties...
[22:16:47] [main/INFO]: Setting up logger...
[22:16:47] [main/INFO]: LiteLoader 1.8.0 starting up...
[22:16:47] [main/INFO]: Active Pack: 1.8-SNAPSHOT-r372-b53-2015-09-09_11-36-17
[22:16:47] [main/INFO]: Java reports OS="windows 10"
[22:16:47] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[22:16:47] [main/INFO]: Enumerating class path...
[22:16:47] [main/INFO]: Class path separator=";"
[22:16:47] [main/INFO]: Class path entries=(
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\mumfrey\liteloader\1.8\liteloader-1.8.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.8-11.14.3.1450\forge-1.8-11.14.3.1450.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.6.1\realms-1.6.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\versions\1.8\1.8.jar
)
[22:16:47] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[22:16:47] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Dunker\AppData\Roaming\.minecraft\mods]
[22:16:47] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Dunker\AppData\Roaming\.minecraft\mods\1.8]
[22:16:47] [main/INFO]: Registering enumerator plugin DefaultEnumeratorPlugin: [com.mumfrey.liteloader.core.api.DefaultEnumeratorPlugin@6d2a209c]
[22:16:47] [main/INFO]: Discovering tweaks on class path...
[22:16:47] [main/INFO]: Baking listener list for EnumerationObserver with 1 listeners
[22:16:47] [main/INFO]: Discovering valid mod files in folder C:\Users\Dunker\AppData\Roaming\.minecraft\mods
[22:16:47] [main/INFO]: Inspecting jar metadata in 'liteloader-1.7.10.jar'
[22:16:47] [main/INFO]: Ignoring C:\Users\Dunker\AppData\Roaming\.minecraft\mods\liteloader-1.7.10.jar
[22:16:47] [main/INFO]: Discovering valid mod files in folder C:\Users\Dunker\AppData\Roaming\.minecraft\mods\1.8
[22:16:47] [main/INFO]: Inspecting jar metadata in 'spongeforge-1.8-1521-2.1-DEV-735-dev.jar'
[22:16:47] [main/INFO]: Mod file 'spongeforge-1.8-1521-2.1-DEV-735-dev.jar' provides tweakClass 'org.spongepowered.asm.launch.MixinTweaker', adding to Launch queue with priority 0
[22:16:47] [main/INFO]: tweakClass 'org.spongepowered.asm.launch.MixinTweaker' was successfully added
[22:16:47] [main/INFO]: ClassPathUtilities: attempting to inject file:/C:/Users/Dunker/AppData/Roaming/.minecraft/mods/1.8/spongeforge-1.8-1521-2.1-DEV-735-dev.jar into LaunchClassLoader
[22:16:47] [main/INFO]: LiteLoader PREINIT complete
[22:16:47] [main/INFO]: Injecting cascaded tweakers...
[22:16:47] [main/INFO]: Injecting tweak class org.spongepowered.asm.launch.MixinTweaker with priority 0
[22:16:47] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[22:16:47] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[22:16:47] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[22:16:47] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[22:16:47] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[22:16:47] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[22:16:47] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.MinecraftTransformer'
[22:16:47] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[22:16:47] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[22:16:47] [main/INFO]: Forge Mod Loader version 8.99.124.1450 for Minecraft 1.8 loading
[22:16:47] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_60, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_60
[22:16:47] [main/INFO]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from liteloader-1.7.10.jar
[22:16:47] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.8-1521-2.1-DEV-735-dev.jar
[22:16:47] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[22:16:47] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by HorusDev** [comment]
Are you sure you downloaded the correct version?

**Comment by BinaryAura** [comment]
Which should I download?

**Comment by Tzky** [comment]
The ``Mod.jar``, **NOT** the ``DEV.jar``.

**Comment by BinaryAura** [comment]
The mod download is a zip file not a jar.

**Comment by Minecrell** [comment]
It was for a short time, but that has been fixed for the latest builds already.

**Comment by Tzky** [comment]
@Minecrell 
It was fixed for 737 but it's a zip again in 738.

**Comment by BinaryAura** [comment]
So, what do I download now. The wiki assumes that a have the correct download.

**Comment by Tzky** [comment]
I'd try with Build 737 for now. It's a ``.jar`` and should hopefully work. The Repo is a bit wonky atm. Sorry for the inconvenience.

**Comment by Minecrell** [comment]
Meh.

**Comment by BinaryAura** [comment]
Okay. Thanks

**Comment by Minecrell** [comment]
Fixed in latest build (1.8-1521-2.1-DEV-739).

**Comment by BinaryAura** [comment]
My game is crashing during load. 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8-1521-2.1-DEV-739.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/19/15 12:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Sponge was already initialized
  at org.spongepowered.common.Sponge.<init>(Sponge.java:65)
  at org.spongepowered.common.Sponge.class(Sponge.java:50)
  while locating org.spongepowered.common.Sponge

1 error
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:413)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Sponge was already initialized
  at org.spongepowered.common.Sponge.<init>(Sponge.java:65)
  at org.spongepowered.common.Sponge.class(Sponge.java:50)
  while locating org.spongepowered.common.Sponge

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:103)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:334)
	... 11 more
Caused by: java.lang.IllegalStateException: Sponge was already initialized
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.spongepowered.common.Sponge.<init>(Sponge.java:67)
	at org.spongepowered.common.Sponge$$FastClassByGuice$$818cdaf.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 406506456 bytes (387 MB) / 578813952 bytes (552 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1521 4 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		Sponge{1.8-1521-2.1-DEV-739} [SpongeForge] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1521.jar) 
		Forge{11.14.3.1521} [Minecraft Forge] (forge-1.8-11.14.3.1521.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8-1521-2.1-DEV-739.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 7700 Series'
```

**Comment by Minecrell** [comment]
@BinaryAura Let's don't extent this issue anymore, the issue is solved - post your problem in a new issue.
