### ISSUE TITLE
Crash with Liteloader and WorldEditCUI

### ISSUE THREAD

**Issue by BinaryAura** [SpongePowered/SpongeForge#378]
Lite loader works with Forge, but not with Sponge. Minecraft crashes with the follows when liteloader is enabled.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8-1521-2.1-DEV-739.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/19/15 12:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Sponge was already initialized
  at org.spongepowered.common.Sponge.<init>(Sponge.java:65)
  at org.spongepowered.common.Sponge.class(Sponge.java:50)
  while locating org.spongepowered.common.Sponge

1 error
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:413)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Sponge was already initialized
  at org.spongepowered.common.Sponge.<init>(Sponge.java:65)
  at org.spongepowered.common.Sponge.class(Sponge.java:50)
  while locating org.spongepowered.common.Sponge

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:103)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:334)
	... 11 more
Caused by: java.lang.IllegalStateException: Sponge was already initialized
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.spongepowered.common.Sponge.<init>(Sponge.java:67)
	at org.spongepowered.common.Sponge$$FastClassByGuice$$818cdaf.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 406506456 bytes (387 MB) / 578813952 bytes (552 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1521 4 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		Sponge{1.8-1521-2.1-DEV-739} [SpongeForge] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1521.jar) 
		Forge{11.14.3.1521} [Minecraft Forge] (forge-1.8-11.14.3.1521.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8-1521-2.1-DEV-739.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 7700 Series'
```

**Comment by Mumfrey** [comment]
Please can you post the full logs, the crash doesn't really tell us very much.

**Comment by BinaryAura** [comment]
I can't attach documents: "Unfortunately, we don't support that file type." (.zip, .txt)
The latter is really weird because TXT is in the list of supported file types. I've also seen it deny attachments because I need permission.

Do you have an email?

**Comment by gabizou** [comment]
You can open the full client log and copy that into a [gist](http://gist.github.com/). No need to wrap around texts or zips or anything.

**Comment by BinaryAura** [comment]
https://gist.github.com/BinaryAura/ba2cabde6a9e578cfde5

**Comment by Mumfrey** [comment]
Looking at the log, I'm pretty sure this is actually an issue with Mixin rather than with Sponge or LiteLoader. When loading alongside FML, Mixin has to determine whether or not its *container* (eg. in this case the sponge mod jar) needs to be re-injected or not. Under normal circumstances, FML suppresses the injection of a mod jar which contains a *Tweaker* which means that Mixin has to **manually** inject the container in order to allow the mod to be loaded.

Now in other circumstances this does **not** happen, and thus the "helpful" injection leads to there being *two copies* of the mod in the classpath, which is the error you're experiencing. However this error is only a symptom of the dual injection and can thus be ignored.

I'd need to see LiteLoader's log to be sure, but I think the most likely culprit is that because you've put the sponge jar in the **1.8** folder, this is actually allowing LiteLoader to load the mod jar (because liteloader respects the tweaker contract, and thus will load tweak jars placed in the `mods/<version>` folder) which subsequently confuses Mixin's (admittedly quite naïve) detection for whether it needs to do the re-injection, causing the duplicate.

A quick hacky fix might be to explicitly include the `ModType` manifest entry in our jar. This was a system cpw proposed which basically allows LiteLoader and FML to ignore each other's mod jars if supplied. It may not work, but since it's easy to try we should give it a spin to start with and see if the issue goes away.

**Comment by BinaryAura** [comment]
I found Lite Loader's Log:

```
[06:35:11] [main/INFO]: LiteLoader 1.8.0 starting up...
[06:35:11] [main/INFO]: Active Pack: 1.8-SNAPSHOT-r372-b53-2015-09-09_11-36-17
[06:35:11] [main/INFO]: Java reports OS="windows 10"
[06:35:11] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[06:35:11] [main/INFO]: Enumerating class path...
[06:35:11] [main/INFO]: Class path separator=";"
[06:35:11] [main/INFO]: Class path entries=(
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\mumfrey\liteloader\1.8\liteloader-1.8.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.8-11.14.3.1521\forge-1.8-11.14.3.1521.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.6.1\realms-1.6.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar
   classpathEntry=C:\Users\Dunker\AppData\Roaming\.minecraft\versions\1.8\1.8.jar
)
[06:35:11] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[06:35:11] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Dunker\AppData\Roaming\.minecraft\mods]
[06:35:11] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Dunker\AppData\Roaming\.minecraft\mods\1.8]
[06:35:11] [main/INFO]: Registering enumerator plugin DefaultEnumeratorPlugin: [com.mumfrey.liteloader.core.api.DefaultEnumeratorPlugin@6d2a209c]
[06:35:11] [main/INFO]: Discovering tweaks on class path...
[06:35:11] [main/INFO]: Baking listener list for EnumerationObserver with 1 listeners
[06:35:11] [main/INFO]: Discovering valid mod files in folder C:\Users\Dunker\AppData\Roaming\.minecraft\mods
[06:35:11] [main/INFO]: Discovering valid mod files in folder C:\Users\Dunker\AppData\Roaming\.minecraft\mods\1.8
[06:35:11] [main/INFO]: Inspecting jar metadata in 'spongeforge-1.8-1521-2.1-DEV-739.jar'
[06:35:11] [main/INFO]: Mod file 'spongeforge-1.8-1521-2.1-DEV-739.jar' provides tweakClass 'org.spongepowered.asm.launch.MixinTweaker', adding to Launch queue with priority 0
[06:35:11] [main/INFO]: tweakClass 'org.spongepowered.asm.launch.MixinTweaker' was successfully added
[06:35:11] [main/INFO]: LiteLoader PREINIT complete
[06:35:17] [main/INFO]: Injecting onstartupcomplete[x1] in func_71384_a in Minecraft
[06:35:17] [main/INFO]: Injecting prerenderfbo[x1] in func_71411_J in Minecraft
[06:35:17] [main/INFO]: Injecting postrenderfbo[x1] in func_71411_J in Minecraft
[06:35:17] [main/INFO]: Injecting ontimerupdate[x1] in func_71411_J in Minecraft
[06:35:17] [main/INFO]: Injecting onrender[x1] in func_71411_J in Minecraft
[06:35:17] [main/INFO]: Injecting ontick[x1] in func_71411_J in Minecraft
[06:35:17] [main/INFO]: Injecting updateframebuffersize[x1] in func_147119_ah in Minecraft
[06:35:17] [main/INFO]: Injecting newtick[x1] in func_71407_l in Minecraft
[06:35:17] [main/INFO]: MinecraftTransformer found INIT injection point, this is good.
[06:35:17] [main/INFO]: Injecting onoutboundchat[x1] in func_71165_d in EntityPlayerSP
[06:35:17] [main/INFO]: Injecting onrenderchat[x1] in func_175180_a in GuiIngame
[06:35:17] [main/INFO]: Injecting postrenderchat[x1] in func_175180_a in GuiIngame
[06:35:17] [main/INFO]: Injecting onsessionprofilebad[x1] in func_148256_e in Session
[06:35:18] [Client thread/INFO]: Injecting onservertick[x1] in func_71190_q in MinecraftServer
[06:35:18] [Client thread/INFO]: Injecting oncreateintegratedserver[x1] in <init> in IntegratedServer
[06:35:18] [Client thread/INFO]: Injecting onplayerlogin[x1] in func_72377_c in ServerConfigurationManager
[06:35:18] [Client thread/INFO]: Injecting onplayerlogout[x1] in func_72367_e in ServerConfigurationManager
[06:35:18] [Client thread/INFO]: Injecting onspawnplayer[x1] in func_148545_a in ServerConfigurationManager
[06:35:18] [Client thread/INFO]: Injecting oninitializeplayerconnection[x1] in func_72355_a in ServerConfigurationManager
[06:35:18] [Client thread/INFO]: Injecting onrespawnplayer[x1] in func_72368_a in ServerConfigurationManager
[06:35:18] [Client thread/INFO]: Injecting onblockclicked[x1] in func_180784_a in ItemInWorldManager
[06:35:18] [Client thread/INFO]: Injecting onactivateblockoruseitem[x1] in func_180236_a in ItemInWorldManager
[06:35:22] [Client thread/INFO]: Injecting renderfbo[x1] in func_178038_a in Framebuffer
[06:35:25] [Thread-7/INFO]: Generating new Event Handler Proxy Class com.mumfrey.liteloader.core.event.EventProxy
[06:35:25] [Thread-7/INFO]: Successfully generated event handler proxy class with 22 handlers(s) and 22 total invokations

```

**Comment by simon816** [comment]
@Mumfrey this is your domain, any ideas on a fix?

**Comment by Mumfrey** [comment]
Yep that's exactly what I was expecting:

    [06:35:11] [main/INFO]: Mod file 'spongeforge-1.8-1521-2.1-DEV-739.jar' provides tweakClass 'org.spongepowered.asm.launch.MixinTweaker', adding to Launch queue with priority 0

You can fix this temporarily by just putting sponge jar directly in `mods` instead of `mods/1.8` and we can investigate options for dealing with it.

**Comment by Zidane** [comment]
Closing this.

If still an issue, reopen later.
