### ISSUE TITLE
BiomesOplenty

### ISSUE THREAD

**Issue by gothdawid** [SpongePowered/SpongeForge#388]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  SpongeCoremod (spongeforge-1.8-1530-2.1-DEV-767.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1461-universal.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 28.10.15 19:38
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.enums.BOPFlowers, values=[clover, swampflower, deathbloom, glowflower, blue_hydrangea, orange_cosmos, pink_daffodil, wildflower, violet, white_anemone, enderlotus, bromeliad, dandelion, pink_hibiscus, lily_of_the_valley, burning_blossom]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
	at biomesoplenty.common.block.BlockBOPFlower.getLightValue(BlockBOPFlower.java:148)
	at org.spongepowered.common.SpongeImplFactory.getBlockLightValue(SpongeImplFactory.java:93)
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:350)
	at net.minecraft.world.World.func_180501_a(World.java:409)
	at biomesoplenty.common.world.feature.GeneratorFlora.func_180709_b(GeneratorFlora.java:133)
	at biomesoplenty.api.biome.generation.BOPGeneratorBase.scatter(BOPGeneratorBase.java:96)
	at biomesoplenty.api.biome.generation.GeneratorWeighted.scatter(GeneratorWeighted.java:112)
	at biomesoplenty.common.handler.decoration.DecorateBiomeEventHandler.runGeneratorStage(DecorateBiomeEventHandler.java:63)
	at biomesoplenty.common.handler.decoration.DecorateBiomeEventHandler.onBiomeDecorate(DecorateBiomeEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_DecorateBiomeEventHandler_onBiomeDecorate_Decorate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:79)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:56)
	at net.minecraftforge.event.terraingen.TerrainGen.decorate(TerrainGen.java:42)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:215)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:125)
	at net.minecraft.world.biome.BiomeGenBase.func_180624_a(BiomeGenBase.java:350)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_73153_a(ChunkProviderGenerateBOP.java:533)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:269)
	at net.minecraft.world.chunk.Chunk.onPopulateChunkPre(Chunk.java:304)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1126)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:180)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:122)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:413)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:389)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:381)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:259)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 185534528 bytes (176 MB) / 579338240 bytes (552 MB) up to 951058432 bytes (907 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 105
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1532 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1532-universal.jar) 
	UCHIJAA	Forge{11.14.3.1532} [Minecraft Forge] (forge-1.8-11.14.3.1532-universal.jar) 
	UCHIJAA	Aroma1997Core{1.0.3.4} [Aroma1997Core] (Aroma1997Core-1.8-1.0.3.4.jar) 
	UCHIJAA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHIJAA	Sponge{DEV} [Sponge] (minecraft.jar) 
	UCHIJAA	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHIJAA	Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper] (Aroma1997Core-1.8-1.0.3.4.jar) 
	UCHIJAA	BetterChests{1.2.0.0} [BetterChests] (BetterChests-1.8-1.2.0.0.jar) 
	UCHIJAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1461-universal.jar) 
	UCHIJAA	chiselsandbits{1.4.1} [Chisels & Bits] (chiselsandbits-1.4.1.jar) 
	UCHIJAA	hopperducts{1.4.5} [Hopper Ducts] (hopperducts-mc1.8-1.4.5.jar) 
	UCHIJAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJAA	IronChest{6.0.107.754} [Iron Chest] (ironchest-1.8-6.0.107.754-universal.jar) 
	UCHIJAA	morelight{1.4_release} [More Light] (MoreLight-1.8-1.4_release.jar) 
	UCHIJAA	ProjectE{1.8-PE1.1.0} [ProjectE] (ProjectE-1.8-PE1.1.0.jar) 
	UCHIJAA	vp{1.5.1} [VanillaPlus] (VanillaPlus-1.8-1.5.1.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
SpongeCoremod (spongeforge-1.8-1530-2.1-DEV-767.jar)
  
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)
  
CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  
NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1461-universal.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 0 / 4; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)

**Comment by simon816** [comment]
I'm pretty sure [this call to getBlockLightValue](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L350) should use the existing block, `block1` not the new block, `block`

**Comment by gothdawid** [comment]
So what do I do?
