### ISSUE TITLE
NoSuchMethodError on CommandSource.sendMessage(Text text)

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeForge#430]
Ever since build 839 CommandSource.sendMessage(Text text) has been throwing the following error
java.lang.NoSuchMethodError:org.spongepowered.api.util.command.CommandSource.sendMessage([Lorg/spongepowered/api/text/Text;)V

I've tried doing a Gradle refresh and re-compile on my plugins to no effect.  Any ideas?

**Comment by gabizou** [comment]
@Zerthick try the latest SpongeForge.

**Comment by Zerthick** [comment]
@gabizou I can confirm this issue is still present on build 847

**Comment by simon816** [comment]
If you're using more than one `Text` the method is called `sendMessages`
Notice the signature your plugin is trying to lookup `sendMessage([Lorg/spongepowered/api/text/Text;)V` the `[` means array, yet the method takes a single `Text` parameter

**Comment by Zerthick** [comment]
I'm currently using Texts.of() to concatenate multiple Strings into one texts object, sample code:

```Java
public CommandResult execute(CommandSource src, CommandContext args)
    throws CommandException {

    src.sendMessage(Texts.of(TextColors.DARK_GREEN, container.getName(),
        TextColors.GREEN, " version: ", TextColors.DARK_GREEN, 
        container.getVersion(), TextColors.GREEN, " by ", 
        TextColors.DARK_GREEN, "Zerthick"));

    return CommandResult.success();
}
```

And the full trace:
```
Error occurred while executing command 'gy' for source net.minecraft.server.dedicated.DedicatedServer@64bcdd0e: org.spongepowered.api.util.command.CommandSource.sendMessage([Lorg/spongepowered/api/text/Text;)V
java.lang.NoSuchMethodError: org.spongepowered.api.util.command.CommandSource.sendMessage([Lorg/spongepowered/api/text/Text;)V
        at io.github.zerthick.graveyards.cmdexecuters.GraveyardExecutor.execute(GraveyardExecutor.java:44) ~[GraveyardExecutor.class:?]
        at org.spongepowered.api.util.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:170) ~[ChildCommandElementExecutor.class:1.8-1577-2.1-DEV-847]
        at org.spongepowered.api.util.command.spec.CommandSpec.process(CommandSpec.java:334) ~[CommandSpec.class:1.8-1577-2.1-DEV-847]
        at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.8-1577-2.1-DEV-847]
        at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:250) [SimpleCommandService.class:1.8-1577-2.1-DEV-847]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [cl.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:400) [po.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:365) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

This code ran without any errors on Build 838, but has thrown this error on every build since.

**Comment by simon816** [comment]
You need to recompile from source. You say you've tried that but perhaps it used a cache file because that code works fine, I just tested it.

**Comment by Zerthick** [comment]
Hmm, clearing my cache again and recompiling from source again seems to have fixed the issue, odd that it didn't fix it the first time around.
