### ISSUE TITLE
Sign Interacting Bug

### ISSUE THREAD

**Issue by sweetcode** [SpongePowered/SpongeForge#448]
Reproduction:
1. Restart your Sponge Server
2. Join and just interact with a sign (right/left click)
2.1 Results in an error
3. Click again on a sign
3.1 Results in no error

```
[20:11:34 FATAL] [mixin]: Mixin failed applying mixins.common.core.json:command.MixinSignCommandSender -> net.minecraft.tileentity.TileEntitySign$2: org.spongepowered.asm.mixin.transformer.InvalidMixinException Shadow field field_174797_a was not located in the target class
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Shadow field field_174797_a was not located in the target class
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.attachFields(MixinPreProcessor.java:222) ~[spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.attach(MixinPreProcessor.java:151) ~[spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.createContextFor(MixinPreProcessor.java:133) ~[spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:623) ~[spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189) ~[spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:644) ~[spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:616) [spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:434) [spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:105) [spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_60]
    at net.minecraft.tileentity.TileEntitySign.func_174882_b(SourceFile:135) [bdj.class:?]
    at net.minecraft.block.BlockSign.func_180639_a(SourceFile:78) [bai.class:?]
    at net.minecraft.server.management.ItemInWorldManager.func_180236_a(SourceFile:292) [qx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.onActivateBlockOrUseItem(SourceFile:447) [rj.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(SourceFile:452) [rj.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_180769_a(SourceFile:59) [mx.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) [mx.class:?]
    at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:85) [ih.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:111) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:305) [po.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:531) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(SourceFile:447) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Comment by gabizou** [comment]
> spongevanilla-1.8-2.1DEV-19.jar:1.8-2.1-DEV-93

This isn't SpongeVanilla. If this is still an issue with SpongeForge, then please update the log, otherwise, open a new issue on SpongeVanilla.
