### ISSUE TITLE
WorldInfo crash with EvilCraft

### ISSUE THREAD

**Issue by rubensworks** [SpongePowered/SpongeForge#454]
I got a crash report from someone trying to load the EvilCraft mod with SpongeForge at CyclopsMC/EvilCraft#316 (crash log included in the issue).

My code basically creates a `FakeWorld` and turns of some `World` parts like for example its world generation.
It looks like this is somehow conflicting with Sponge.
If I'm correct, a `doesKeepSpawnLoaded` method is added by Sponge to `WorldInfo` which causes a nullpointer because of my `FakeWorldInfo` class which just calls the default constructor of `WorldInfo`.

Any idea how we can solve this issue?

**Comment by ST-DDT** [comment]
The error seems to occur in SpongeCommon:
[MixinWorldInfo (line 479)](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/storage/MixinWorldInfo.java#L479)

````java
@Override
public boolean doesKeepSpawnLoaded() {
    if (!this.worldConfig.isConfigEnabled()) {
        return SpongeHooks.getActiveConfig(this.dimensionType.getId(), this.getWorldName()).getConfig().getWorld().getKeepSpawnLoaded();
    }
    return this.worldConfig.getWorld().getKeepSpawnLoaded(); // <- line 479
}
````

If you use an uptodate build then `this.worldConfig.getWorld()` seems to return null, but I don't know why or whether this is wrong at all.

**Comment by simon816** [comment]
It's actually two lines above that's causing the NPE
```java
return SpongeHooks.getActiveConfig(this.dimensionType.getId(), this.getWorldName()).getConfig().getWorld().getKeepSpawnLoaded();
```
because the crash was on build 921 which is this tree: https://github.com/SpongePowered/SpongeCommon/tree/e97b579d4599ca0cd3d9dbbf8fd41f672dfc9072

**Comment by simon816** [comment]
The fix is simple, all we need to do is add `this.dimensionType = DimensionTypes.OVERWORLD;` to the default constructor so a new WorldInfo object has a default dimension type.
The problem now is that EvilCraft is calling this in PREINIT which means that DimensionTypes are not mapped because I delayed them to POSTINIT (https://github.com/SpongePowered/SpongeCommon/commit/b9d42ec3af6f1ad9d4b4c5702a52df4297e9c689#diff-e27090bc1fbcb71169d7c50af6de72ccR91) in case mods want to change things in the init phases.
So I think the best compromise is to do the mapping twice - once in PREINIT and again in POSTINIT

**Comment by simon816** [comment]
@rubensworks Having a `FakeWorld` `FakeWorldInfo` and `FakeWorldProvider` will definitely cause issues in some way or another.
I suggest you try to redesign the things that rely on the fake world to not need it. Perhaps use `MinecraftServer.getServer().getEntityWorld()` when a world is needed (only available once worlds are initialized though).
I can add a bit more defense to sponge but there still will be undesired side-effects like a config file generated for 'fakeworld' for example.

**Comment by rubensworks** [comment]
@simon816 The main reason I need a fake world is because I provide a machine in which mobs (in a box) can be inserted, an that machine will grind them and give the drops. I do this in a fake world, because there is no need to actually spawn them in the normal world, I want to keep its footprint as low as possible. (And yes, this is the only way to do this, I know it's a hack. Once 1.9 is out, loot tables can be used though)

Up until now, I never had any issues with it, and it's been released for over a year now.
If I'm not incorrect, there are other mods that do this as well, like for example Mystcraft, which does some world oregen profiling, which happens in some kind of fake world.

The ideal solution would be for Forge to add a shared fake world (like the fake player), but I can already imagine the response that would be given to such a suggestion...

**Comment by gabizou** [comment]
Try with the latest build of SpongeForge.

**Comment by rubensworks** [comment]
User seems to be having the same crash with the last build: https://github.com/CyclopsMC/EvilCraft/issues/316#issuecomment-166271828

**Comment by simon816** [comment]
I have pushed a partial fix for this crash. There's still a problem, and you need to disable the `entity-activation-range` module because it's crashing there. (open `config/sponge/global.conf` and under `modules` put `entity-activation-range=false`)

If several mods are creating fake worlds perhaps we need to redesign a few things to support that.
The main reason why things are breaking is because we inject into the constructor of `World` and load config immediately, perhaps we need to load only when the world is actually being loaded into the DimensionManager.

**Comment by rubensworks** [comment]
Awesome, thanks for the quick feedback!
@hxpx, Does this solve your problem?

**Comment by hxpx** [comment]
@rubensworks @simon816 
Im turn off this module but still have error. **lastest.log**
```16:09:19] [Server thread/INFO]: Starting minecraft server version 1.8
[16:09:30] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at net.minecraft.world.storage.WorldInfo.doesKeepSpawnLoaded(WorldInfo.java:477) ~[bqo.class:?]
	at net.minecraft.world.World.onConstructed(World.java:334) ~[aqu.class:?]
	at net.minecraft.world.World.<init>(World.java:141) ~[aqu.class:?]
	at org.cyclops.evilcraft.core.world.FakeWorld.<init>(FakeWorld.java:32) ~[FakeWorld.class:?]
	at org.cyclops.evilcraft.core.world.FakeWorld.getInstance(FakeWorld.java:23) ~[FakeWorld.class:?]
	at org.cyclops.evilcraft.block.BoxOfEternalClosure.setVengeanceSwarmContent(BoxOfEternalClosure.java:161) ~[BoxOfEternalClosure.class:?]
	at org.cyclops.evilcraft.block.BoxOfEternalClosureConfig.onRegistered(BoxOfEternalClosureConfig.java:62) ~[BoxOfEternalClosureConfig.class:?]
	at org.cyclops.cyclopscore.config.ConfigHandler.loadConfig(ConfigHandler.java:89) ~[ConfigHandler.class:?]
	at org.cyclops.cyclopscore.config.ConfigHandler.handle(ConfigHandler.java:63) ~[ConfigHandler.class:?]
	at org.cyclops.cyclopscore.init.ModBase.preInit(ModBase.java:250) ~[ModBase.class:?]
	at org.cyclops.evilcraft.EvilCraft.preInit(EvilCraft.java:124) ~[EvilCraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553) ~[forge-1.8-11.14.4.1563-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.onPost(LoadController.java:54) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[po.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[16:09:30] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Grishin\Desktop\spongeforge minecraft\.\crash-reports\crash-2015-12-21_16.09.30-server.txt
```

**Comment by simon816** [comment]
You have build 950, latest is 951

**Comment by hxpx** [comment]
@simon816  Oh yea done,it's working now i'll going to test it right now. Thanks
