### ISSUE TITLE
Fresh linux server install of SpongeForge 1.8-1577-2.1-DEV-987. InvalidMixinException

### ISSUE THREAD

**Issue by AriaFallah** [SpongePowered/SpongeForge#472]
*Edit:* Using 1.8-1563-2.1-DEV-814 instead fixed the problem

Following along with these instructions:

https://docs.spongepowered.org/en/server/getting-started/installation.html

Forge server runs fine without sponge in the mods folder. When I put sponge in it crashes. Server is Ubuntu 14.04 and is running Java 8.

Here's the entire log from the server start.

```bash
[09:58:25] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[09:58:25] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[09:58:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[09:58:26] [main/INFO] [FML]: Forge Mod Loader version 11.14.4.1577 for Minecraft 1.8 loading
[09:58:26] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Linux:amd64:3.13.0-24-generic, installed at /usr/lib/jvm/java-8-oracle/jre
[09:58:26] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.8-1577-2.1-DEV-986.jar
[09:58:26] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:58:26] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[09:58:26] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.4.7 Source=file:/opt/msm/servers/sponge/mods/spongeforge-1.8-1577-2.1-DEV-986.jar Env=SERVER
[09:58:26] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[09:58:26] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[09:58:26] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[09:58:26] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[09:58:26] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:58:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:58:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:58:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:58:28] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[09:58:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:58:28] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[09:58:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:58:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:58:28] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[09:58:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:58:28] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[09:58:31] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassNotFoundException: The specified class 'net.minecraft.entity.boss.IBossDisplayData' was not found
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.TreeInfo.loadClass(TreeInfo.java:92)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.TreeInfo.getClassNode(TreeInfo.java:59)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1432)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.findInHierarchy(ClassInfo.java:1239)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.findMethodInHierarchy(ClassInfo.java:1101)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.findMethodInHierarchy(ClassInfo.java:1086)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.updateBinding(MixinTargetContext.java:494)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.updateStaticBinding(MixinTargetContext.java:475)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethodRef(MixinTargetContext.java:294)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:249)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMethods(MixinApplicator.java:294)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:206)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:645)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:617)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:435)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:105)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.block.Block.func_149671_p(Block.java:2176)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1417)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[09:58:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[09:58:35] [main/INFO] [mixin]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[09:58:35] [main/INFO] [Sponge]: /********************************************************************************************************/
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /* Oh dear. Something went wrong and the server had to shut down!                                       */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*------------------------------------------------------------------------------------------------------*/
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /* A critical error was encountered while blending Sponge with Forge!                                   */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*   Possible causes are:                                                                               */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*    * An incompatible Forge "core mod" is present. Try removing other mods to                         */
[09:58:35] [main/INFO] [Sponge]: /*      see if the problem goes away.                                                                   */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*    * You are using the wrong version of Minecraft Forge. You must use the                            */
[09:58:35] [main/INFO] [Sponge]: /*      correct version of Forge when running Sponge, this version is for                               */
[09:58:35] [main/INFO] [Sponge]: /*      11.14.4.1577 (you are running 11.14.4.1577)                                                     */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*    * An error exists in Sponge itself. Ensure you are running the latest version                     */
[09:58:35] [main/INFO] [Sponge]: /*      of Sponge.                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*    * Gremlins are invading your computer. Did you feed a Mogwai after midnight?                      */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*------------------------------------------------------------------------------------------------------*/
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /* Technical details:                                                                                   */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /*      Failed on class : net.minecraft.entity.boss.EntityWither                                        */
[09:58:35] [main/INFO] [Sponge]: /*         During phase : DEFAULT                                                                       */
[09:58:35] [main/INFO] [Sponge]: /*                Mixin : entity.boss.MixinEntityWither                                                 */
[09:58:35] [main/INFO] [Sponge]: /*               Config : mixins.common.core.json                                                       */
[09:58:35] [main/INFO] [Sponge]: /*           Error Type : org.spongepowered.asm.mixin.transformer.InvalidMixinException                 */
[09:58:35] [main/INFO] [Sponge]: /*            Caused by : java.lang.RuntimeException                                                    */
[09:58:35] [main/INFO] [Sponge]: /*              Message : Unexpecteded error whilst applying the mixin class                            */
[09:58:35] [main/INFO] [Sponge]: /*                                                                                                      */
[09:58:35] [main/INFO] [Sponge]: /********************************************************************************************************/
[09:58:35] [main/INFO] [FML]: Java has been asked to exit (code 1) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:682).
[09:58:35] [main/INFO] [FML]: This is an abortive exit and could cause world corruption or other things
[09:58:35] [main/INFO] [FML]: If this was an unexpected exit, use -Dfml.debugExit=true as a JVM argument to find out where it was called
```

Don't know if this is related, but forge is getting a lot of 403s when trying to access libraries.minecraft.net

```bash
Installing server to current directory
MESSAGE: Data kindly mirrored by Minecraft Forge at http://files.minecraftforge.net/
MESSAGE: Considering minecraft server jar
MESSAGE: Downloading minecraft server version 1.8
  ETag: 5b19d1a562a8a7c5f9a787ad96c8148b
  MD5:  5b19d1a562a8a7c5f9a787ad96c8148b
MESSAGE: Considering library net.minecraftforge:forge:1.8-11.14.4.1563: Not Downloading
MESSAGE: Considering library io.netty:netty-all:4.0.15.Final
MESSAGE: Downloading library io.netty:netty-all:4.0.15.Final
java.io.IOException: Server returned HTTP response code: 403 for URL: https://libraries.minecraft.net/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar.pack.xz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:428)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:416)
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.Files.copy(Files.java:382)
	at net.minecraftforge.installer.DownloadUtils.downloadFile(DownloadUtils.java:374)
	at net.minecraftforge.installer.DownloadUtils.downloadInstalledLibraries(DownloadUtils.java:84)
	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:72)
	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:42)
	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:61)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:36)
MESSAGE: Considering library net.minecraft:launchwrapper:1.12
MESSAGE: Downloading library net.minecraft:launchwrapper:1.12
java.io.IOException: Server returned HTTP response code: 403 for URL: https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar.pack.xz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:428)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:416)
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.Files.copy(Files.java:382)
	at net.minecraftforge.installer.DownloadUtils.downloadFile(DownloadUtils.java:374)
	at net.minecraftforge.installer.DownloadUtils.downloadInstalledLibraries(DownloadUtils.java:84)
	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:72)
	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:42)
	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:61)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:36)
MESSAGE: Considering library org.ow2.asm:asm-all:5.0.3
MESSAGE: Downloading library org.ow2.asm:asm-all:5.0.3
java.io.IOException: Server returned HTTP response code: 403 for URL: https://libraries.minecraft.net/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar.pack.xz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:428)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:416)
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.Files.copy(Files.java:382)
	at net.minecraftforge.installer.DownloadUtils.downloadFile(DownloadUtils.java:374)
	at net.minecraftforge.installer.DownloadUtils.downloadInstalledLibraries(DownloadUtils.java:84)
	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:72)
	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:42)
	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:61)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:36)
MESSAGE: Considering library com.typesafe.akka:akka-actor_2.11:2.3.3
MESSAGE: Downloading library com.typesafe.akka:akka-actor_2.11:2.3.3
MESSAGE: Unpacking packed file akka-actor_2.11-2.3.3.jar.pack.xz
  Signed
  Checksum Length: 140942
  Total Length:    2606968
  Temp File:       /tmp/art5350993691883926639.pack
MESSAGE: Successfully unpacked packed file akka-actor_2.11-2.3.3.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library com.typesafe:config:1.2.1
MESSAGE: Downloading library com.typesafe:config:1.2.1
MESSAGE: Unpacking packed file config-1.2.1.jar.pack.xz
  Signed
  Checksum Length: 12246
  Total Length:    111476
  Temp File:       /tmp/art1887511758199571890.pack
MESSAGE: Successfully unpacked packed file config-1.2.1.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/com/typesafe/config/1.2.1/config-1.2.1.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-actors-migration_2.11:1.1.0
MESSAGE: Downloading library org.scala-lang:scala-actors-migration_2.11:1.1.0
MESSAGE: Unpacking packed file scala-actors-migration_2.11-1.1.0.jar.pack.xz
  Signed
  Checksum Length: 3311
  Total Length:    52481
  Temp File:       /tmp/art284366901771633698.pack
MESSAGE: Successfully unpacked packed file scala-actors-migration_2.11-1.1.0.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-compiler:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-compiler:2.11.1
MESSAGE: Unpacking packed file scala-compiler-2.11.1.jar.pack.xz
  Signed
  Checksum Length: 942120
  Total Length:    9183051
  Temp File:       /tmp/art632724448410416811.pack
MESSAGE: Successfully unpacked packed file scala-compiler-2.11.1.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2
MESSAGE: Downloading library org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2
MESSAGE: Unpacking packed file scala-continuations-library_2.11-1.0.2.jar.pack.xz
  Signed
  Checksum Length: 2416
  Total Length:    18871
  Temp File:       /tmp/art3825975747008471676.pack
MESSAGE: Successfully unpacked packed file scala-continuations-library_2.11-1.0.2.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2
MESSAGE: Downloading library org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2
MESSAGE: Unpacking packed file scala-continuations-plugin_2.11.1-1.0.2.jar.pack.xz
  Signed
  Checksum Length: 16815
  Total Length:    139418
  Temp File:       /tmp/art5966308086284370557.pack
MESSAGE: Successfully unpacked packed file scala-continuations-plugin_2.11.1-1.0.2.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-library:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-library:2.11.1
MESSAGE: Unpacking packed file scala-library-2.11.1.jar.pack.xz
  Signed
  Checksum Length: 341368
  Total Length:    5984083
  Temp File:       /tmp/art1052336589623839723.pack
MESSAGE: Successfully unpacked packed file scala-library-2.11.1.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-parser-combinators_2.11:1.0.1
MESSAGE: Downloading library org.scala-lang:scala-parser-combinators_2.11:1.0.1
MESSAGE: Unpacking packed file scala-parser-combinators_2.11-1.0.1.jar.pack.xz
  Signed
  Checksum Length: 37614
  Total Length:    273457
  Temp File:       /tmp/art1888496073891213080.pack
MESSAGE: Successfully unpacked packed file scala-parser-combinators_2.11-1.0.1.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-reflect:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-reflect:2.11.1
MESSAGE: Unpacking packed file scala-reflect-2.11.1.jar.pack.xz
  Signed
  Checksum Length: 291610
  Total Length:    3217021
  Temp File:       /tmp/art7057263973818707750.pack
MESSAGE: Successfully unpacked packed file scala-reflect-2.11.1.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-swing_2.11:1.0.1
MESSAGE: Downloading library org.scala-lang:scala-swing_2.11:1.0.1
MESSAGE: Unpacking packed file scala-swing_2.11-1.0.1.jar.pack.xz
  Signed
  Checksum Length: 39019
  Total Length:    888907
  Temp File:       /tmp/art126666576841383772.pack
MESSAGE: Successfully unpacked packed file scala-swing_2.11-1.0.1.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-xml_2.11:1.0.2
MESSAGE: Downloading library org.scala-lang:scala-xml_2.11:1.0.2
MESSAGE: Unpacking packed file scala-xml_2.11-1.0.2.jar.pack.xz
  Signed
  Checksum Length: 35380
  Total Length:    739509
  Temp File:       /tmp/art1994902671764917640.pack
MESSAGE: Successfully unpacked packed file scala-xml_2.11-1.0.2.jar.pack.xz
Checking "/opt/msm/servers/sponge/./libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar" internal checksums
    checksums.sha1 validated successfully
    Jar contents validated successfully
MESSAGE: Considering library lzma:lzma:0.0.1
MESSAGE: Downloading library lzma:lzma:0.0.1
java.io.IOException: Server returned HTTP response code: 403 for URL: https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.jar.pack.xz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:428)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:416)
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.Files.copy(Files.java:382)
	at net.minecraftforge.installer.DownloadUtils.downloadFile(DownloadUtils.java:374)
	at net.minecraftforge.installer.DownloadUtils.downloadInstalledLibraries(DownloadUtils.java:84)
	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:72)
	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:42)
	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:61)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:36)
MESSAGE: Considering library net.sf.jopt-simple:jopt-simple:4.5
MESSAGE: Downloading library net.sf.jopt-simple:jopt-simple:4.5
java.io.IOException: Server returned HTTP response code: 403 for URL: https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar.pack.xz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:428)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:416)
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.Files.copy(Files.java:382)
	at net.minecraftforge.installer.DownloadUtils.downloadFile(DownloadUtils.java:374)
	at net.minecraftforge.installer.DownloadUtils.downloadInstalledLibraries(DownloadUtils.java:84)
	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:72)
	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:42)
	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:61)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:36)
The server installed successfully, you should now be able to run the file forge-1.8-11.14.4.1563-universal.jar
You can delete this installer file now if you wish
```

**Comment by Deamon5550** [comment]
Related: spongepowered/Mixin#87

**Comment by AriaFallah** [comment]
@Deamon5550 this was on build 987

**Comment by Mahagon** [comment]
Same happens to me with build 989
