### ISSUE TITLE
Client can't launch

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeForge#482]
````java
[01:29:37] [main/FATAL]: Mixin failed applying mixins.forge.preinit.json:fml.common.MixinMinecraftDummyContainerClient -> net.minecraftforge.fml.common.MinecraftDummyContainer: org.spongepowered.asm.mixin.transformer.InvalidMixinException Unexpecteded error whilst applying the mixin class
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unexpecteded error whilst applying the mixin class
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:214) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:645) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:617) [Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:435) [Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:105) [Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_65]
	at java.lang.Class.getDeclaredMethods0(Native Method) [?:1.8.0_65]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_65]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_65]
	at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_65]
	at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_65]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:39) [forge-1.8-11.14.4.1577.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NullPointerException
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:592) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:572) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:564) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformConstant(MixinTargetContext.java:390) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformConstantNode(MixinTargetContext.java:360) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spException in thread "main" ongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:255) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMethods(MixinApplicator.java:294) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:206) ~[Sponge.jar:1.8-1577-3.0.0-BETA-1014]
	... 17 more
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/MinecraftDummyContainer
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getMethod0(Class.java:3018)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getMethod(Class.java:1784)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:39)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.MinecraftDummyContainer
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 8 more
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: org.spongepowered.asm.mixin.MixinApplyError: Mixin [mixins.forge.preinit.json:fml.common.MixinMinecraftDummyContainerClient] from phase [PREINIT] in config [mixins.forge.preinit.json] FAILED
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinErrorState(MixinTransformer.java:685)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:441)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:105)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 10 more
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unexpecteded error whilst applying the mixin class
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:214)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:645)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:617)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:435)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 13 more
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:592)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:572)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:564)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformConstant(MixinTargetContext.java:390)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformConstantNode(MixinTargetContext.java:360)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:255)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMethods(MixinApplicator.java:294)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:206)
[01:29:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 17 more
````
Build: 3.0.0-BETA-1014

**Comment by DarkArc** [comment]
On my side somewhere
