### ISSUE TITLE
IronChest incompatibility

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#493]
progwml6/ironchest#53

still an issue on 1.8.9 BETA-1049

crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8.9-1691-3.1.0-BETA-1047.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.5.21.1.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.2.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
  LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/13/16 11:51 AM
Description: Exception in server tick loop

java.lang.NullPointerException: clazz
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at org.spongepowered.common.data.type.SpongeTileEntityType.<init>(SpongeTileEntityType.java:42)
	at net.minecraft.tileentity.TileEntity.onRegister(TileEntity.java:99)
	at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.java:42)
	at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntityWithAlternatives(GameRegistry.java:340)
	at cpw.mods.ironchest.IronChest.load(IronChest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.onPost(LoadController.java:53)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:205)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_72-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 342188528 bytes (326 MB) / 1151336448 bytes (1098 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xmx2048M -Xms512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.0.1695 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UCHI	Forge{11.15.0.1695} [Minecraft Forge] (forge.jar) 
	UCHI	OpenComputers|Core{1.5.21.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHI	sponge{DEV} [Sponge] (spongeforge-1.8.9-1691-3.1.0-BETA-1047.jar) 
	UCHI	BuildCraft|Core{7.2.0-pre6} [BuildCraft] (buildcraft-7.2.0-pre6.jar) 
	UCHI	BuildCraft|Energy{7.2.0-pre6} [BC Energy] (buildcraft-7.2.0-pre6.jar) 
	UCHI	ActuallyAdditions{1.8.9-r23} [Actually Additions] (ActuallyAdditions-1.8.9-r23.jar) 
	UCHI	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHI	aura{unspecified} [Aura Cascade] (AuraCascade-1.8.8-v0.2.2a.jar) 
	UCHI	betterbuilderswands{0.4.2} [Better Builder's Wands] (BetterBuildersWands-0.4.2-1.8.9r73+04b6c51.jar) 
	UCHI	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1631-universal.jar) 
	UCHI	BloodMagic{1.8.9-2.0.0-4} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-4.jar) 
	UCHI	Thaumcraft{5.1.2} [Thaumcraft] (Thaumcraft-1.8.9-5.1.2.jar) 
	UCHI	Botania{r1.8-249} [Botania] (Botania.r1.8-248-MC1.8-64e3a96.jar) 
	UCHI	BuildCraft|Transport{7.2.0-pre6} [BC Transport] (buildcraft-7.2.0-pre6.jar) 
	UCHI	BuildCraft|Factory{7.2.0-pre6} [BC Factory] (buildcraft-7.2.0-pre6.jar) 
	UCHI	BuildCraft|Silicon{7.2.0-pre6} [BC Silicon] (buildcraft-7.2.0-pre6.jar) 
	UCHI	BuildCraft|Robotics{7.2.0-pre6} [BC Robotics] (buildcraft-7.2.0-pre6.jar) 
	UCHI	BuildCraft|Builders{7.2.0-pre6} [BC Builders] (buildcraft-7.2.0-pre6.jar) 
	UCHI	Chameleon{1.8.8-0.2.0} [Chameleon] (Chameleon-1.8.8-0.2.0.jar) 
	UCHI	mcmultipart{1.0.4} [MCMultiPart] (MCMultiPart-1.0.4-universal.jar) 
	UCHI	CharsetLib{0.1.3} [‽] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHI	CharsetTweaks{0.1.3} [*] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHI	CharsetWires{0.1.3} [+] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHI	CharsetAudio{0.1.3} [♫] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHI	CharsetPipes{0.1.3} [|] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHI	CharsetGates{0.1.3} [&] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHI	chiselsandbits{@version@} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8-beta8.jar) 
	UCHI	ComputerCraft{1.77pr0} [ComputerCraft] (ComputerCraft1.77pr0.jar) 
	UCHI	cosmeticarmorreworked{1.8.9-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v1.jar) 
	UCHI	EssentialCmds{6.8-bbb9c46} [EssentialCmds] (EssentialCmds-6.8d.jar) 
	UCHI	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHI	flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.5.jar) 
	UCHI	HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar) 
	UCHI	inventorytweaks{1.60-dev-28-3253249} [Inventory Tweaks] (InventoryTweaks-1.60-dev-28.jar) 
	UCHE	IronChest{6.0.115.759} [Iron Chest] (ironchest-1.8.9-6.0.115.759.jar) 
	UCHI	JEI{2.16.2.78} [Just Enough Items] (jei_1.8.9-2.16.2.78.jar) 
	UCHI	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHI	mantle{1.8.9-0.6.jenkins70} [Mantle] (Mantle-1.8.9-0.6.jenkins70.jar) 
	UCHI	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHI	Morpheus{1.8.9-2.0.57} [Morpheus] (Morpheus-1.8.9-2.0.57.jar) 
	UCHI	OpenComputers{1.5.21.1} [OpenComputers] (OpenComputers-MC1.8.9-1.5.21.1.jar) 
	UCHI	PermissionsEx{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHI	Ping{1.1.1} [Ping] (Ping-1.8.9-1.1.1.B10-universal.jar) 
	UCHI	PneumaticCraft{1.13.0 - err} [PneumaticCraft] (PneumaticCraft-1.8.8-1.13.1-universal.jar) 
	UCHI	RandomThings{3.5.7} [Random Things] (RandomThings-MC1.8.8-3.5.7.jar) 
	UCHI	rftools{4.20beta8} [RFTools] (rftools-1.8.9-4.20beta8.jar) 
	UCHI	StorageDrawers{1.8.8-2.2.0} [Storage Drawers] (StorageDrawers-1.8.8-2.2.0.jar) 
	UCHI	tconstruct{1.8.9-2.0.1.jenkins41} [Tinkers' Construct] (TConstruct-1.8.9-2.0.1.jenkins41.jar) 
	UCHI	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHI	wawla{1.4.1} [What Are We Looking At] (Wawla-1.4.1-1.8+.jar) 
	UCHI	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1-SNAPSHOT-dist (1).jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8.9-1691-3.1.0-BETA-1047.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.5.21.1.jar)
  li.cil.oc.common.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.2.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
  lumien.randomthings.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by gabizou** [comment]
It seems like IronChest is attempting to register a `null` `TileEntity` class which isn't supported.

**Comment by gabizou** [comment]
This has been fixed for a while now.
