### ISSUE TITLE
SpongeForge 1.8.9-1694-3.1.0-BETA-1053 and JRE 1.8.0_66

### ISSUE THREAD

**Issue by dpisarenko** [SpongePowered/SpongeForge#500]
When I try to launch Minecraft with

  * spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar,
  * forge-1.8.9-11.50.0.1694, and
  * jre1.8.0_66,

under Windows 7 I get the error below (see [profile config](http://i.imgur.com/ApBtU1M.png)).

```
2016-01-16 13:23:12,197 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-01-16 13:23:12,199 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[13:23:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:23:12] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:23:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[13:23:13] [main/INFO] [FML]: Forge Mod Loader version 11.15.0.1694 for Minecraft 1.8.9 loading
[13:23:13] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_66, running on Windows 7:x86:6.1, installed at C:\Program Files\Java\jre1.8.0_66
[13:23:13] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar
[13:23:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:23:13] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[13:23:13] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.4.11 Source=file:/C:/Users/DP118M/AppData/Roaming/.minecraft/mods/spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar Env=CLIENT
[13:23:13] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[13:23:13] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[13:23:15] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[13:23:15] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[13:23:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:23:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:23:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:23:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:23:20] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[13:23:20] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[13:23:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:23:20] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
2016-01-16 13:23:20,339 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-01-16 13:23:20,391 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-01-16 13:23:20,394 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[13:23:20] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@9d2b1b
[13:23:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:23:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:23:22] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[13:23:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:23:22] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[13:23:27] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[13:23:27] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.injection.InjectionError: Critical injection failure: Callback method onlaunchIntegratedServerBeforeStart(Ljava/lang/String;Ljava/lang/String;Lnet/minecraft/world/WorldSettings;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/storage/ISaveHandler;Lnet/minecraft/world/storage/WorldInfo;)V in mixins.forge.core.json:client.MixinMinecraft failed injection check, (0/1) succeeded
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:240) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyInjections(MixinApplicator.java:713) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:208) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:655) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:619) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:437) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:107) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1053.jar:1.8.9-1694-3.1.0-BETA-1053]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Exception in thread "main" [13:23:27] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:23:27] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[13:23:27] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[13:23:27] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[13:23:27] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[13:23:27] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[13:23:27] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by dpisarenko** [comment]
Tried it with JRE 1.8.0_65 - same result.

**Comment by Minecrell** [comment]
Can you try the latest SpongeForge (1055)?

**Comment by dpisarenko** [comment]
Many thanks, now it works. Awesome :)
