### ISSUE TITLE
Server Watchdog/FATAL

### ISSUE THREAD

**Issue by ThornsOfire** [SpongePowered/SpongeForge#510]
Caused during map exploration, slight chunk loading lag visible. Watchdog does not shutdown server.

[19:21:48] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4716ms behind, skipping 94 tick(s)
[19:23:20] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[19:23:20] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
[19:23:20] [Server Watchdog/ERROR]: This crash report has been saved to: C:\Users\Peav\Desktop\Minecraft Stuff\Minecraft Server\.\crash-reports\crash-2016-01-21_19.23.20-server.txt

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8-1577-3.0.0-BETA-1000.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 21/01/16 7:23 PM
Description: Watching Server

java.lang.Error
	at net.minecraft.util.LongHashMap.func_76164_a(SourceFile:49)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:188)
	at net.minecraft.world.World.func_72964_e(World.java:304)
	at net.minecraft.world.World.func_175726_f(World.java:299)
	at net.minecraft.world.World.func_175642_b(World.java:724)
	at net.minecraft.world.World.func_175638_a(World.java:2792)
	at net.minecraft.world.World.func_180500_c(World.java:2902)
	at net.minecraft.world.chunk.Chunk.func_76609_d(Chunk.java:351)
	at net.minecraft.world.chunk.Chunk.func_76615_h(Chunk.java:463)
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:485)
	at net.minecraft.world.World.func_180501_a(World.java:378)
	at net.minecraft.world.gen.feature.WorldGenerator.func_175903_a(SourceFile:41)
	at net.minecraft.world.gen.feature.WorldGenerator.func_175905_a(SourceFile:34)
	at net.minecraft.world.gen.feature.WorldGenTaiga1.func_180709_b(WorldGenTaiga1.java:97)
	at net.minecraft.world.gen.feature.WorldGenTaiga1.placeObject(WorldGenTaiga1.java:95)
	at org.spongepowered.common.world.gen.populators.ForestPopulator.populate(ForestPopulator.java:88)
	at org.spongepowered.mod.world.gen.SpongeChunkProviderForge.func_73153_a(SpongeChunkProviderForge.java:162)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:269)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1098)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:180)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:122)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:189)
	at net.minecraft.world.World.func_72964_e(World.java:304)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:380)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.util.LongHashMap.func_76164_a(SourceFile:49)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:188)
	at net.minecraft.world.World.func_72964_e(World.java:304)
	at net.minecraft.world.World.func_175726_f(World.java:299)
	at net.minecraft.world.World.func_175642_b(World.java:724)
	at net.minecraft.world.World.func_175638_a(World.java:2792)
	at net.minecraft.world.World.func_180500_c(World.java:2902)
	at net.minecraft.world.chunk.Chunk.func_76609_d(Chunk.java:351)
	at net.minecraft.world.chunk.Chunk.func_76615_h(Chunk.java:463)
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:485)
	at net.minecraft.world.World.func_180501_a(World.java:378)
	at net.minecraft.world.gen.feature.WorldGenerator.func_175903_a(SourceFile:41)
	at net.minecraft.world.gen.feature.WorldGenerator.func_175905_a(SourceFile:34)
	at net.minecraft.world.gen.feature.WorldGenTaiga1.func_180709_b(WorldGenTaiga1.java:97)
	at net.minecraft.world.gen.feature.WorldGenTaiga1.placeObject(WorldGenTaiga1.java:95)
	at org.spongepowered.common.world.gen.populators.ForestPopulator.populate(ForestPopulator.java:88)
	at org.spongepowered.mod.world.gen.SpongeChunkProviderForge.func_73153_a(SpongeChunkProviderForge.java:162)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:269)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1098)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:180)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:122)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:189)
	at net.minecraft.world.World.func_72964_e(World.java:304)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:380)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)

-- Thread Dump --
Details:
	Threads: "Netty Server IO #2" Id=29 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@7a4d67ce
	-  locked java.util.Collections$UnmodifiableSet@748a96f7
	-  locked sun.nio.ch.WindowsSelectorImpl@c013b2a
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:596)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306)
	...

"Chunk I/O Executor Thread-1" Id=51 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@70b50cbe
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@70b50cbe
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Netty Server IO #1" Id=28 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@35b79ccc
	-  locked java.util.Collections$UnmodifiableSet@24d5eea3
	-  locked sun.nio.ch.WindowsSelectorImpl@7dc0f1da
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:596)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306)
	...

"File IO Thread" Id=47 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51)
	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
	at java.lang.Thread.run(Unknown Source)

"LAN Discovery" Id=46 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at ninja.leaping.landiscovery.LanThread.run(LanThread.java:98)

"Server Watchdog" Id=45 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

"Timer-0" Id=44 TIMED_WAITING on java.util.TaskQueue@448e9e0
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@448e9e0
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"Netty Server IO #0" Id=27 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@5cc0c52b
	-  locked java.util.Collections$UnmodifiableSet@55986383
	-  locked sun.nio.ch.WindowsSelectorImpl@15e4ca3b
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:596)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306)
	...

"Server console handler" Id=21 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	-  locked java.io.BufferedInputStream@5e333f65
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	-  locked java.io.InputStreamReader@1d77daaa
	at java.io.InputStreamReader.read(Unknown Source)
	...

"DestroyJavaVM" Id=20 RUNNABLE

"Server thread" Id=18 RUNNABLE
	at net.minecraft.util.LongHashMap.func_76164_a(SourceFile:49)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:188)
	at net.minecraft.world.World.func_72964_e(World.java:304)
	at net.minecraft.world.World.func_175726_f(World.java:299)
	at net.minecraft.world.World.func_175642_b(World.java:724)
	at net.minecraft.world.World.func_175638_a(World.java:2792)
	at net.minecraft.world.World.func_180500_c(World.java:2902)
	at net.minecraft.world.chunk.Chunk.func_76609_d(Chunk.java:351)
	...

"Server Infinisleeper" Id=17 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:73)

"Snooper Timer" Id=16 TIMED_WAITING on java.util.TaskQueue@47c4adb2
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@47c4adb2
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"Sponge Async Scheduler Thread" Id=15 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@51d65ab2
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@51d65ab2
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at org.spongepowered.common.scheduler.AsyncScheduler.preTick(AsyncScheduler.java:112)
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:102)
	at org.spongepowered.common.scheduler.AsyncScheduler.mainLoop(AsyncScheduler.java:66)
	at org.spongepowered.common.scheduler.AsyncScheduler$$Lambda$9/854056805.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Attach Listener" Id=6 RUNNABLE

"Signal Dispatcher" Id=5 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@16d99ffa
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@16d99ffa
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@35d8b501
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@35d8b501
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(SourceFile:59)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1210914624 bytes (1154 MB) / 2077753344 bytes (1981 MB) up to 10667687936 bytes (10173 MB)
	JVM Flags: 3 total; -Xms2G -Xmx10G -XX:+UseConcMarkSweepGC
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577-universal.jar) 
	UCHIJAAAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577-universal.jar) 
	UCHIJAAAA	sponge{1.8-1577-3.0.0-BETA-1000} [SpongeForge] (spongeforge-1.8-1577-3.0.0-BETA-1000.jar) 
	UCHIJAAAA	AdminShop{1.3} [AdminShop] (AdminShop-1.3b.jar) 
	UCHIJAAAA	AntiSwear{1.1.3} [AntiSwear] (AntiSwear.jar) 
	UCHIJAAAA	Blood Money{0.2.8} [Blood Money] (BloodMoney.jar) 
	UCHIJAAAA	EssentialCmds{6.9-36b5986} [EssentialCmds] (EssentialCmds-6.9f.jar) 
	UCHIJAAAA	foxcore{0.6.2} [FoxCore] (FoxCore-v0.6.2-70-SNAPSHOT.jar) 
	UCHIJAAAA	Kits{1.3} [Kits] (Kits-1.3.jar) 
	UCHIJAAAA	landiscovery{1.0.1} [LanDiscovery] (landiscovery-1.0.1.jar) 
	UCHIJAAAA	TotalEconomy{1.3.1} [Total Economy] (TotalEconomy-v1.3.1.jar) 
	UCHIJAAAA	looty{0.9.0} [RPG Looty] (looty-0-9.jar) 
	UCHIJAAAA	PermissionsEx{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	PJP{0.7.24} [Project Portals] (ProjectPortals-3.1.0-v0.7.25.jar) 
	UCHIJAAAA	PJW{0.6.40} [Project Worlds] (ProjectWorlds-3.1.0-v0.6.40.jar) 
	UCHIJAAAA	PvPLogger{1.1} [PvPLogger] (PvPLogger-1.1.jar) 
	UCHIJAAAA	Vanish{4.0.0} [Vanish] (vanish.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8-1577-3.0.0-BETA-1000.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [EntityPlayerMP['Peav420'/370, l='world', x=1182.52, y=123.72, z=-0.18], EntityPlayerMP['Thorns_Ofire'/602, l='world', x=196.00, y=76.00, z=248.00]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)

**Comment by kashike** [comment]
Update to 1.8.9.
https://github.com/MinecraftForge/MinecraftForge/pull/2367

**Comment by Minecrell** [comment]
Closing because of inactivity. Also this should be fixed in 1.8.9 as @kashike mentioned.
