### ISSUE TITLE
Sponge Generating BC Oil Wells/Springs crashing a server

### ISSUE THREAD

**Issue by AuricPolaris** [SpongePowered/SpongeForge#556]
Hello and Good Day,

Title says it all. I am not sure if this has already be posted or resolved, and if so, my apologies!

Crashlog: [http://pastebin.com/d2GrnKRq](http://pastebin.com/d2GrnKRq)
Spongeversion: spongeforge-1.8.9-1732-3.1.0-BETA-1164
ForgeVersion: forge-1.8.9-11.15.1.1755-universal

**Comment by Aaron1011** [comment]
You're running an out-of-date SpongeForge - can you try again with the latest build?

**Comment by hunter688** [comment]
It looks like TConstruct problem, no BC. See:

`
java.lang.IllegalArgumentException: Empty string not allowed
    at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22)
    at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:104)
    at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:83)
    at slimeknights.tconstruct.library.smeltery.SmelteryTank.writeToNBT(SmelteryTank.java:121)
    at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.func_145841_b(TileSmeltery.java:566)
    at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.func_145844_m(TileSmeltery.java:608)
`
