### ISSUE TITLE
4.0/bleeding: Error calling secondary interact event

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeForge#567]
```
[13:25:31] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.spongepowered.api.event.impl.InteractBlockEvent$Secondary$Impl cannot be cast to org.spongepowered.mod.interfaces.IMixinEvent
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_60]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ClassCastException: org.spongepowered.api.event.impl.InteractBlockEvent$Secondary$Impl cannot be cast to org.spongepowered.mod.interfaces.IMixinEvent
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:193) ~[SpongeModEventManager.class:1.8.9-1763-4.0.0-BETA-0]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:60) ~[ForgeEventFactory.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:575) ~[lm.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106) ~[PacketUtil.class:1.8.9-1763-4.0.0-BETA-0]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51) ~[fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
```
Looks like IMixinEvent is mixed into AbstractEvent -- does the event impl class not inherit from that or something?

**Comment by gabizou** [comment]
Can you reproduce this with `-Dmixin.debug=true` and hand a log out etc?

**Comment by zml2008** [comment]
Ok, I've reproduced this -- however the stacktrace only appeared in the latest.log, not the fml-latest-server.log, so both are in this gist: https://gist.github.com/anonymous/82595c69f4ef13445838

**Comment by gabizou** [comment]
Fixed in the latest commit to bleeding.
