### ISSUE TITLE
[LaunchWrapper/]: Unable to launch

### ISSUE THREAD

**Issue by Xiaminou** [SpongePowered/SpongeForge#578]
Server will not launch: http://pastebin.com/0vJEh010

**Comment by Aaron1011** [comment]
@Xiaminou: What version of SpongeForge and Forage are you using?

**Comment by kashike** [comment]
@Aaron1011 The log states the versions.
Forge: 11.15.1.1763
SpongeForge: 1.8.9-1763-3.1.0-BETA-1181

**Comment by Zidane** [comment]
@Xiaminou 

You've got a coremod that is classloading MinecraftDummyContainer too early. Remove coremods one by one and see which is causing it.

Relevant lines:

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.8.9-11.15.1.1763-universal.jar:?]
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.8.9-11.15.1.1763-universal.jar:?]
Caused by: java.lang.AbstractMethodError: Method net/minecraftforge/fml/common/MinecraftDummyContainer.getId()Ljava/lang/String; is abstract
    at net.minecraftforge.fml.common.MinecraftDummyContainer.getId(MinecraftDummyContainer.java) ~[MinecraftDummyContainer.class:?]
    at net.minecraft.command.ServerCommandManager.func_71560_a(SourceFile:103) ~[bd.class:?]
    at net.minecraft.command.ServerCommandManager.<init>(SourceFile:15) ~[bd.class:?]
    at net.minecraft.server.MinecraftServer.func_175582_h(MinecraftServer.java:175) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:166) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:56) ~[ko.class:?]
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1475) ~[MinecraftServer.class:?]
    ... 12 more
[19:18:39] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]: 
```

**Comment by Xiaminou** [comment]
Looks like it's Extra Utilities 2, should I open an issue on their github? You guys will have to explain what's happening because I don't understand any of it.

**Comment by NEXUS2345** [comment]
I am also having this issue. Tried multiple forge and sponge versions.

**Comment by Xiaminou** [comment]
Looks like RWTema fixed it in the latest version of ExU2
