### ISSUE TITLE
Crash on custom pack with 150 mods

### ISSUE THREAD

**Issue by killerjerick** [SpongePowered/SpongeForge#585]
Hey guys, it's probably just an incompatibility but the crashlog seems to reference nothing of the sort so I thought I'd post the crash log and see if there is a fix for it.

1.8.9 
Forge 1808
Sponge 1808

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (LoadingProfiler-MC1.8.8-1.3.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  OpenModsCorePlugin (OpenModsLib-1.8.9-0.9.1.21.jar)
  OpenBlocksCorePlugin (OpenBlocks-1.8.9-1.5.1.10.jar)
  MDECore-Core (mdecore-1.8.9-1.1.1.jar)
  LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.1.2.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.5.jar)
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.12-beta.jar)
  SpongeCoremod (spongeforge-1.8.9-1808-4.1.0-BETA-1227.jar)
  ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.85.jar)
  MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  BookshelfLoadingPlugin (Bookshelf-1.8.9-1.1.2.207.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.3.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 3/28/16 6:10 AM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at org.spongepowered.common.registry.CommonModuleRegistry.registerCommonModules(CommonModuleRegistry.java:267)
	at org.spongepowered.common.registry.CommonModuleRegistry.registerDefaultModules(CommonModuleRegistry.java:124)
	at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:127)
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:136)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: net.minecraft.item.Item cannot be cast to org.spongepowered.api.item.ItemType
	at net.minecraft.item.ItemStack.getItem(ItemStack.java:133)
	at org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.<init>(SpongeItemStackSnapshot.java:80)
	at net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:210)
	at org.spongepowered.common.registry.type.ItemTypeRegistryModule.<clinit>(ItemTypeRegistryModule.java:49)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 3.5.0-51-generic
	Java Version: 1.8.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4140036520 bytes (3948 MB) / 5239734272 bytes (4997 MB) up to 5239734272 bytes (4997 MB)
	JVM Flags: 2 total; -Xmx5120M -Xms5120M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1808 6 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1808-universal.jar) 
		Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808-universal.jar) 
		Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
		mdecore-core{1.0} [MDE Core - ASM Tweaks] (minecraft.jar) 
		OpenComputers|Core{1.6.0.2-beta.1} [OpenComputers (Core)] (minecraft.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (LoadingProfiler-MC1.8.8-1.3.jar)
  lumien.loadingprofiler.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  li.cil.oc.common.asm.ClassTransformer
CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  
OpenModsCorePlugin (OpenModsLib-1.8.9-0.9.1.21.jar)
  openmods.core.OpenModsClassTransformer
OpenBlocksCorePlugin (OpenBlocks-1.8.9-1.5.1.10.jar)
  openblocks.asm.OpenBlocksClassTransformer
MDECore-Core (mdecore-1.8.9-1.1.1.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  lumien.bloodmoon.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
MalisisCorePlugin (malisiscore-1.8.9-2.1.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.5.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
EnderCorePlugin (EnderCore-1.8.9-0.3.0.12-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
SpongeCoremod (spongeforge-1.8.9-1808-4.1.0-BETA-1227.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar)
  net.shadowfacts.shadowmc.core.ShadowMCTransformer
DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  DummyCore.ASM.DCASMManager
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
thaumicinfusion (ThaumicInfusion-1.8.9-4.85.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
BookshelfLoadingPlugin (Bookshelf-1.8.9-1.1.2.207.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.3.jar)
  
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by kashike** [comment]
Could you provide a list of the mods?

**Comment by modwizcode** [comment]
@kashike I think this is probably an issue with one of the listed coremods preventing the mixin for `ItemType` from being applied properly

**Comment by modwizcode** [comment]
Sorry, jumped a beat, missed the title, yeah definitely going to need a complete listing of mods.

**Comment by killerjerick** [comment]
The list is pretty long, like I said I don't want to waste your time but if any of these mods are known to cause issues please let me know :) Thanks guys!
 http://i.imgur.com/zNF6k0L.png

**Comment by kinggoesgaming** [comment]
holy... I would be not surprised if more than one mod in there is causing the crash :tongue:

**Comment by liach** [comment]
@killerjerick You should post the full log, as mixin has debug outputs.

**Comment by gabizou** [comment]
One of the core mods seems to be loading the `net.minecraft.item.Item` class earlier than SpongeForge can start mixins:

> Caused by: java.lang.ClassCastException: net.minecraft.item.Item cannot be cast to org.spongepowered.api.item.ItemType

**Comment by JonathanxD** [comment]
I tried to start a server with DummyCore-2.2.189.0.jar, may be DummyCore.
```
java.lang.ClassCastException: net.minecraftforge.fml.common.event.FMLConstructionEvent cannot be cast to org.spongepowered.api.event.Event
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:55) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) ~[ko.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[21:54:44] [Server thread/ERROR]: This crash report has been saved to: /home/jonathan/Sponge_WCommands/./crash-reports/crash-2016-03-28_21.54.44-server.txt
[21:54:44] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
> mar 28, 2016 9:54:44 PM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
GRAVE: Could not dispatch event: sponge to public void org.spongepowered.mod.SpongeMod.onStateEvent(net.minecraftforge.fml.common.event.FMLStateEvent)
[21:54:44] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[21:54:44] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
```

I've added only DummyCore

forge-1.8.9-11.15.1.1808
spongeforge-1.8.9-1763-4.1.0-BETA-1220

**Comment by modwizcode** [comment]
Different error

**Comment by JonathanxD** [comment]
mdcore is the causer.

Full log:
```
$ java -jar forge-1.8.9-11.15.1.1808-universal.jar 
[15:04:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[15:04:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[15:04:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[15:04:41] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.1808 for Minecraft 1.8.9 loading
[15:04:41] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_74, running on Linux:amd64:4.4.5-1-ARCH, installed at /usr/lib/jvm/java-8-openjdk/jre
[15:04:41] [main/WARN] [FML]: The coremod com.mattdahepic.mdecore.asm.MDECoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:04:41] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.8.9-1763-4.1.0-BETA-1220.jar
[15:04:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:04:41] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:04:41] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.5.3 Source=file:/home/jonathan/SpongeServer/mods/spongeforge-1.8.9-1763-4.1.0-BETA-1220.jar Env=SERVER
[15:04:41] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[15:04:41] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[15:04:41] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[15:04:41] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[15:04:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:04:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:04:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:04:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:04:44] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:04:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:04:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:04:44] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[15:04:48] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@4fce136b
[15:04:48] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:04:50] [main/INFO] [mdecore]: Patching MinecraftServer class for tickrate changing...
[15:04:50] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.mattdahepic.mdecore.asm.TickrateTransformer' was detected and will no longer process meta class data
[15:04:50] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:04:50] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[15:04:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:04:50] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[15:04:50] [main/INFO] [mdecore]: Patching MinecraftServer class for tickrate changing...
[15:05:01] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[15:05:13] [Server thread/INFO]: Starting minecraft server version 1.8.9
[15:05:13] [Server thread/INFO] [FML]: MinecraftForge v11.15.1.1808 Initialized
[15:05:13] [Server thread/INFO] [FML]: Replaced 204 ore recipies
[15:05:18] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError
	at org.spongepowered.common.registry.CommonModuleRegistry.registerCommonModules(CommonModuleRegistry.java:267) ~[CommonModuleRegistry.class:1.8.9-1763-4.1.0-BETA-1220]
	at org.spongepowered.common.registry.CommonModuleRegistry.registerDefaultModules(CommonModuleRegistry.java:124) ~[CommonModuleRegistry.class:1.8.9-1763-4.1.0-BETA-1220]
	at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:127) ~[SpongeGameRegistry.class:1.8.9-1763-4.1.0-BETA-1220]
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:136) ~[SpongeMod.class:1.8.9-1763-4.1.0-BETA-1220]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) ~[ko.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassCastException: net.minecraft.item.Item cannot be cast to org.spongepowered.api.item.ItemType
	at net.minecraft.item.ItemStack.getItem(ItemStack.java:133) ~[zx.class:?]
	at org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.<init>(SpongeItemStackSnapshot.java:80) ~[SpongeItemStackSnapshot.class:1.8.9-1763-4.1.0-BETA-1220]
	at net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:210) ~[zx.class:?]
	at org.spongepowered.common.registry.type.ItemTypeRegistryModule.<clinit>(ItemTypeRegistryModule.java:49) ~[ItemTypeRegistryModule.class:1.8.9-1763-4.1.0-BETA-1220]
	... 16 more
[15:05:18] [Server thread/ERROR]: This crash report has been saved to: /home/jonathan/SpongeServer/./crash-reports/crash-2016-03-29_15.05.18-server.txt
[15:05:18] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[15:05:18] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: Sponge has not been initialized!
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.api.Sponge.getGame(Sponge.java:43)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:256)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:184)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:188)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.dedicated.DedicatedServer.handler$postGameStoppingEvent$0(DedicatedServer.java:72)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71240_o(DedicatedServer.java)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:545)
[15:05:18] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Deamon5550** [comment]
Well theres the problem... [this transformer](https://github.com/MattDahEpic/MDECore/blob/1.9.X/src/main/java/com/mattdahepic/mdecore/asm/TickrateTransformer.java) class loads his mods main class [in order to use the logger](https://github.com/MattDahEpic/MDECore/blob/1.9.X/src/main/java/com/mattdahepic/mdecore/asm/TickrateTransformer.java#L19) which causes [Item and Material to be classloaded as well](https://github.com/MattDahEpic/MDECore/blob/1.9.X/src/main/java/com/mattdahepic/mdecore/MDECore.java#L47)

**Comment by gabizou** [comment]
Any ideas on where to report to the developer of mdcore?

**Comment by gabizou** [comment]
@killerjerick You'll have to re-create the process again to find out what core mod is loading the Forge event classes before SpongeForge can get to them.

**Comment by MattDahEpic** [comment]
I've fixed my end of the problem.

**Comment by simon816** [comment]
You could try using SpongeBootstrap - https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275
I'm hoping it will be a short-term fix for these class loading edge-cases

**Comment by bloodmc** [comment]
Closing due to no response in over 20 days.
