### ISSUE TITLE
ConstructEntityEvent.POST event caught, but nothing there

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeForge#589]
Abstract errors all around for getTargetType, getTargetEntity, etc
Spongeforge1808

I need an event that contains both the cause of the spawning (ie, mobcube) and the ability to get the spawnedentity UUID both, and the .POST seems like where it will be at.

**Comment by gabizou** [comment]
You're not really making sense, there is no SpongeForge 1808 build, we've only reached so far build 1231 today.

Could you clarify what the actual issue is (I don't care for reasons why you want to use the event) and what your event listener looks like?

**Comment by theboomer** [comment]
Hmm, my version info got all truncated out -- At the time of posting, it was Spongeforge-1808-1228 with forge-1808


LISTENER CODE:
```
92    @Listener         
93    public void conspost(ConstructEntityEvent.Post event) {
94        System.out.println(event.toString());
95         if (event.getTargetType() == EntityTypes.BLAZE) {
96            System.out.println("Blazepost");
97        }
98    }
```
Event fires, but the methods in the event throw abstract errors when called:

Log:
```
[Server thread/INFO] [STDOUT/]: [com.prennet.boomod.testplatforma.TestPlatformA:conspost:94]: net.minecraftforge.event.entity.EntityEvent$EntityConstructing@64561963
Server thread/ERROR] [Sponge/]: Could not pass EntityConstructing to org.spongepowered.mod.plugin.SpongeModPluginContainer@e27f8c3
java.lang.AbstractMethodError: net.minecraftforge.event.entity.EntityEvent$EntityConstructing.getTargetType()Lorg/spongepowered/api/entity/EntityType;
	at com.prennet.boomod.testplatforma.TestPlatformA.conspost(TestPlatformA.java:95) ~[TestPlatformA.class:?]
	at org.spongepowered.common.event.listener.PostListener_TestPlatformA_conspost14.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1808-4.1.0-BETA-1229]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:239) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1229]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:199) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1229]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:70) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:58) [EventBus.class:?]
	at net.minecraft.entity.Entity.redirect$onEntityConstruct$0(Entity.java:64) [pk.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:184) [pk.class:?]
	at net.minecraft.entity.item.EntityEnderCrystal.<init>(SourceFile:22) [uf.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_74]
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:162) [pm.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:469) [anj.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109) [ld.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84) [ld.class:?]
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:610) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:586) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:452) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:254) [ko.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]

**Comment by theboomer** [comment]
Also to clarify, its not like its just that one error message aka "oh, something to do with endercrystals" - the event throws a few hundred times when the server starts up with no login, throwing on all types of entities in the stacktrace, cows, pigs, sheep, skeletons...

**Comment by gabizou** [comment]
I believe I know the root of the issue then, I'll have a fix in a moment.

**Comment by theboomer** [comment]
Excellent, that brought the getTargetEntity, getTargetType, and getTransform out of abstract errorville..
But the CAUSE is a constant unchanged for all entity spawns alike -- is this also due to missing a bridge from a placeholder cause and a fast fix, or is it a huge undertaking because no cause code is in place for it|?

```
[23:52:47] [Server thread/INFO] [STDOUT]: com.prennet.boomod.testplatforma.TestPlatformA:conspost:99]: Cause[{Name=Source, Object=SpongeModGame{platform=SpongeModPlatform{type=SERVER,executionType=SERVER,api=Plugin{id=spongeapi, name=SpongeAPI, version=4.1.0-SNAPSHOT-8b23bcf}, impl=sponge, minecraftVersion=SpongeMinecraftVersion{name=1.8.9, protocol=47}}}}}]
[23:52:47] [Server thread/INFO] [STDOUT]: com.prennet.boomod.testplatforma.TestPlatformA:conspost:100]: Transform{location=Location{(0.0, 0.0, 0.0) in net.minecraft.world.WorldServer@3763d7c3}, rotation=(0.0, 0.0, 0.0), scale=(1.0, 1.0, 1.0)}
