### ISSUE TITLE
minetweaker reload does not work with SpongeForge

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#601]
when do /mt reload

http://pastebin.com/6fjPtwvS

**Comment by Aaron1011** [comment]
@hunter688: I've opened an issue with MineTweaker to fix this problem.

**Comment by bloodmc** [comment]
@Aaron1011 couldn't we just avoid this from happening on our end?

**Comment by Aaron1011** [comment]
@bloodmc: Technically, yes, but mods shouldn't really be re-registering a command.

**Comment by bloodmc** [comment]
@Aaron1011 how about we avoid the error and log a warning with the mod info?

**Comment by Aaron1011** [comment]
@zml2008 would be the one to talk to - I'm not sure if we want to add in an exception for duplicate-command registering when a mod is involved.

**Comment by jaredlll08** [comment]
I fixed this in the official continuation of Minetweaker3 https://github.com/jaredlll08/CraftTweaker/issues/15

**Comment by bloodmc** [comment]
@jaredlll08 thanks.

**Comment by jaredlll08** [comment]
No problem :) sorry I took so long to fix it

**Comment by hunter688** [comment]
This fix is useless because 17 days ago support 1.8.x was canceled in this commit:

https://github.com/jaredlll08/CraftTweaker/commit/a426d8da799a58c34984b2b6854b1b9e471b0841

**Comment by jaredlll08** [comment]
I thought the general consensus was to skip 1.8, especially considering that 1.9 has a RB now.

**Comment by hunter688** [comment]
Sponge Forge is 1.8.9. Could you please add back 1.8.9 support please?

**Comment by jaredlll08** [comment]
Expect it next release, the 1.8.9 support that was added was extremely broken anyway, i had to port 1.7 -> 1.9 to get it to work correctly, so I'll do 1.9 -> 1.8 now

**Comment by hunter688** [comment]
Thanks a lot.

**Comment by hunter688** [comment]
FYI see how many downloads are 1.8.9 version, its most wanted :) http://mods.curse.com/mc-mods/minecraft/239197-crafttweaker-customized-minetweaker3#t1:other-downloads

**Comment by jaredlll08** [comment]
Yea I gotta say, I never looked at that when I decided to remove the support...

**Comment by jaredlll08** [comment]
http://minecraft.curseforge.com/projects/crafttweaker-customized-minetweaker3/files/2298190
There you go

**Comment by hunter688** [comment]
it crashes on the server:
`
java.lang.IllegalArgumentException: Multiple entries with same key: MineTweaker3=FMLMod:MineTweaker3{3.0.4} and MineTweaker3=FMLMod:MineTweaker3{3.0.5}
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:365)
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
        at java.lang.Thread.run(Thread.java:745)
`

something wrong inside mod

**Comment by jaredlll08** [comment]
Send the full log please

**Comment by hunter688** [comment]
http://pastebin.com/PP6FgHqK

Looks like two mods with two versions inside jar

**Comment by hunter688** [comment]
client crashes with same error

**Comment by hunter688** [comment]
when delete directory mc19 inside jar, mod working, but looks like wrong modid, modtweaker need depedency to "crafttweaker"
 `Missing Mods:
        crafttweaker : any

net.minecraftforge.fml.common.MissingModsException: Mod modtweaker2 (Mod Tweaker 2) requires [crafttweaker]
        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:238)
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:492)
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by jaredlll08** [comment]
Ok so, I know and have fixed the mod duplicate error, the modtweaker error
however... Well modtweaker 1.8 is terribly broken, like super broken, and I
don't know of enough mods in 1.8 to support it, so gimme a list of mods
that you want support for, and I'll get a fixed version with those mods up
today or tomorrow

**Comment by hunter688** [comment]
Modtweaker is not necessary now, it is just notice about error. Many thanks for fixing bugs.
