### ISSUE TITLE
Throw TConstruct item cause connection timeout

### ISSUE THREAD

**Issue by bunSakurAing** [SpongePowered/SpongeForge#620]
http://pastebin.com/12Y78Htg
Thrown out  TConstruct item after display connection timeout, then unable to enter the server

**Comment by Aaron1011** [comment]
@bunSakurAing: Could you paste the whole stacktrace? It appears to be cut off at the top.

**Comment by simon816** [comment]
I was able to reproduce this by throwing out a Tinker's Construct Pickaxe. 
A `StackOverflowError` is thrown repeatedly
```
[23:03:51] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@56647183:
java.lang.StackOverflowError
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:114) ~[minecraft_server.1.8.9.jar:?]
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:90) ~[minecraft_server.1.8.9.jar:?]
	at org.apache.logging.log4j.core.impl.DefaultLogEventFactory.createEvent(DefaultLogEventFactory.java:49) ~[minecraft_server.1.8.9.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:365) ~[minecraft_server.1.8.9.jar:?]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:110) ~[minecraft_server.1.8.9.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1448) ~[minecraft_server.1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:83) ~[forge-1.8.9-11.15.1.1855-universal.jar:?]
	at net.minecraftforge.fml.common.FMLLog.log(FMLLog.java:40) ~[FMLLog.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.handleException(EventBus.java:154) ~[EventBus.class:?]
[REPEAT]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:87) ~[EventBus.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callEntityJoinWorldEvent(SpongeForgeEventFactory.java:892) ~[SpongeForgeEventFactory.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:338) ~[SpongeForgeEventFactory.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:197) ~[SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:244) ~[SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) ~[SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:131) ~[SpongeImpl.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.common.event.CauseTracker.processSpawnEntity(CauseTracker.java:1080) ~[CauseTracker.class:1.8.9-1855-4.1.0-BETA-1307]
	at net.minecraft.world.World.func_72838_d(World.java:321) ~[adm.class:?]
	at net.minecraftforge.common.ForgeInternalHandler.onEntityJoinWorld(ForgeInternalHandler.java:55) ~[ForgeInternalHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5_ForgeInternalHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
[END REPEAT]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:84) ~[EventBus.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callEntityJoinWorldEvent(SpongeForgeEventFactory.java:892) ~[SpongeForgeEventFactory.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:338) ~[SpongeForgeEventFactory.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:197) ~[SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:244) ~[SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) ~[SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1307]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:131) ~[SpongeImpl.class:1.8.9-1855-4.1.0-BETA-1307]
[23:04:21] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[23:04:21] [Server thread/ERROR] [FML/]: 0: HIGHEST
[23:04:21] [Server thread/ERROR] [FML/]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@6a08a65a onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
```

It looks like Forge's [`ForgeInternalHandler#onEntityJoinWorld`](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/ForgeInternalHandler.java#L18) is causing an infinite loop with the cause tracker, see line 55, `event.world.spawnEntityInWorld(newEntity);`
