### ISSUE TITLE
Maps/ItemFrames with maps in them crash clients

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeForge#621]
Clients which have SpongeForge installed crash while attempting to render item frames. This looks like it's specific to item frames with maps in them.
```
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:447) ~[biu.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:356) ~[biu.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:323) ~[biu.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:821) ~[bfr.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1714) ~[bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1543) ~[bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1328) ~[bfk.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051) ~[ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_03-Ubuntu]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_03-Ubuntu]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_03-Ubuntu]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_03-Ubuntu]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemMap.redirect$loadOverworldMapData$0(ItemMap.java:42) ~[aab.class:?]
	at net.minecraft.item.ItemMap.func_77873_a(ItemMap.java:51) ~[aab.class:?]
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_82402_b(RenderItemFrame.java:137) ~[bjg.class:?]
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_76986_a(RenderItemFrame.java:89) ~[bjg.class:?]
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_76986_a(RenderItemFrame.java:280) ~[bjg.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:399) ~[biu.class:?]
	... 15 more
[15:13:24] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (Sponge.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 5/1/16 3:13 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.item.ItemMap.redirect$loadOverworldMapData$0(ItemMap.java:42)
	at net.minecraft.item.ItemMap.func_77873_a(ItemMap.java:51)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_82402_b(RenderItemFrame.java:137)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_76986_a(RenderItemFrame.java:89)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_76986_a(RenderItemFrame.java:280)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:399)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:356)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:323)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:821)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1714)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1543)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1328)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemMap.redirect$loadOverworldMapData$0(ItemMap.java:42)
	at net.minecraft.item.ItemMap.func_77873_a(ItemMap.java:51)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_82402_b(RenderItemFrame.java:137)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_76986_a(RenderItemFrame.java:89)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_76986_a(RenderItemFrame.java:280)

-- Entity being rendered --
Details:
	Entity Type: ItemFrame (net.minecraft.entity.item.EntityItemFrame)
	Entity ID: 45450
	Entity Name: entity.ItemFrame.name
	Entity's Exact location: 450.03, 82.50, -422.50
	Entity's Block location: 450.00,82.00,-423.00 - World: (450,82,-423), Chunk: (at 2,5,9 in 28,-27; contains blocks 448,0,-432 to 463,255,-417), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.tileentity.RenderItemFrame@31d6a931
	Location: -16.50,-11.74,-117.41 - World: (-17,-12,-118), Chunk: (at 15,-1,10 in -2,-8; contains blocks -32,0,-128 to -17,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -90.0
	Delta: 0.21347146
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:399)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:356)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:323)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:821)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1714)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1543)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Dark_Arc'/30156, l='MpServer', x=467.04, y=94.24, z=-305.67]]
	Chunk stats: MultiplayerChunkCache: 430, 430
	Level seed: 0
	Level generator: ID 09 - overworld, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 8.00,82.00,8.00 - World: (8,82,8), Chunk: (at 8,5,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1336763229 game time, 1482239 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 46 total; [EntityPlayerSP['Dark_Arc'/30156, l='MpServer', x=467.04, y=94.24, z=-305.67], EntitySheep['Sheep'/30401, l='MpServer', x=474.50, y=24.00, z=-324.50], EntityBat['Bat'/46465, l='MpServer', x=470.63, y=28.03, z=-312.04], EntityBat['Bat'/48193, l='MpServer', x=478.44, y=27.00, z=-303.13], EntitySheep['Sheep'/30402, l='MpServer', x=476.50, y=24.00, z=-328.50], EntitySheep['Sheep'/30403, l='MpServer', x=478.19, y=24.00, z=-328.50], EntitySheep['Sheep'/30404, l='MpServer', x=479.81, y=24.00, z=-328.50], EntityChicken['Chicken'/30405, l='MpServer', x=475.50, y=24.00, z=-324.50], EntityChicken['Chicken'/30406, l='MpServer', x=474.50, y=24.00, z=-325.50], EntityChicken['Chicken'/30407, l='MpServer', x=472.50, y=24.00, z=-323.50], EntityChicken['Chicken'/30408, l='MpServer', x=471.50, y=24.00, z=-321.50], EntityRabbit['Rabbit'/30409, l='MpServer', x=476.50, y=24.00, z=-325.50], EntityXPOrb['Experience Orb'/45449, l='MpServer', x=350.75, y=31.50, z=-430.25], EntityRabbit['Rabbit'/30410, l='MpServer', x=477.34, y=24.00, z=-322.66], EntityItemFrame['entity.ItemFrame.name'/45450, l='MpServer', x=450.03, y=82.50, z=-422.50], EntityRabbit['Rabbit'/30411, l='MpServer', x=476.34, y=24.00, z=-321.66], EntitySheep['Sheep'/30284, l='MpServer', x=462.72, y=74.00, z=-262.81], EntityChicken['Chicken'/30285, l='MpServer', x=456.41, y=74.00, z=-329.44], EntityHorse['Donkey'/35347, l='MpServer', x=539.94, y=81.00, z=-259.69], EntityXPOrb['Experience Orb'/35348, l='MpServer', x=539.53, y=81.00, z=-175.88], EntityXPOrb['Experience Orb'/43738, l='MpServer', x=355.06, y=6.00, z=-428.19], EntityBat['Bat'/47643, l='MpServer', x=478.22, y=27.50, z=-304.59], EntityXPOrb['Experience Orb'/43739, l='MpServer', x=357.66, y=6.00, z=-429.19], EntityXPOrb['Experience Orb'/43741, l='MpServer', x=360.19, y=6.00, z=-429.75], EntityXPOrb['Experience Orb'/43742, l='MpServer', x=356.88, y=3.00, z=-426.78], EntityPig['Pig'/30250, l='MpServer', x=463.03, y=78.00, z=-343.56], EntityBat['Bat'/51374, l='MpServer', x=476.28, y=24.59, z=-285.97], EntitySheep['Sheep'/33712, l='MpServer', x=470.09, y=78.00, z=-252.50], EntityBat['Bat'/45552, l='MpServer', x=476.77, y=26.55, z=-321.80], EntitySheep['Sheep'/34609, l='MpServer', x=488.50, y=24.00, z=-297.50], EntitySheep['Sheep'/34610, l='MpServer', x=483.44, y=24.00, z=-297.09], EntityChicken['Chicken'/30259, l='MpServer', x=462.19, y=70.00, z=-272.31], EntitySheep['Sheep'/34611, l='MpServer', x=483.44, y=24.00, z=-299.03], EntityBat['Bat'/45555, l='MpServer', x=478.66, y=28.38, z=-300.30], EntitySheep['Sheep'/34612, l='MpServer', x=484.69, y=24.00, z=-298.84], EntityChicken['Chicken'/34932, l='MpServer', x=497.66, y=74.00, z=-309.75], EntityRabbit['Rabbit'/34613, l='MpServer', x=488.50, y=24.00, z=-301.50], EntityChicken['Chicken'/34933, l='MpServer', x=497.38, y=70.00, z=-285.63], EntityBat['Bat'/51381, l='MpServer', x=483.31, y=25.09, z=-288.56], EntityRabbit['Rabbit'/34614, l='MpServer', x=488.34, y=24.00, z=-299.66], EntityPig['Pig'/34615, l='MpServer', x=487.50, y=24.00, z=-300.50], EntityPig['Pig'/34616, l='MpServer', x=486.09, y=24.00, z=-298.63], EntityBat['Bat'/51384, l='MpServer', x=480.81, y=22.91, z=-285.75], EntityPig['Pig'/34617, l='MpServer', x=484.94, y=24.00, z=-296.94], EntityPig['Pig'/34618, l='MpServer', x=485.50, y=24.00, z=-295.50], EntitySheep['Sheep'/34619, l='MpServer', x=486.94, y=75.00, z=-260.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by DarkArc** [comment]
It's definitely just maps.
