### ISSUE TITLE
spongeforge-1.8.9-1890-4.1.0-BETA-1380 crash-reports

### ISSUE THREAD

**Issue by bbtiger** [SpongePowered/SpongeForge#657]
input spawn *  ERR

java.lang.NoSuchMethodError: org.spongepowered.api.entity.living.player.Player.setLocation(Lorg/spongepowered/api/world/Location;)V
        at main.java.me.cuebyte.nexus.commands.CommandSpawnTeleport.<init>(CommandSpawnTeleport.java:35) ~[CommandSpawnTeleport.class:?]
        at main.java.me.cuebyte.nexus.commands.CommandSpawn.process(CommandSpawn.java:30) ~[CommandSpawn.class:?]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.1.0-BETA-1380]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:269) [SpongeCommandManager.class:1.8.9-1890-4.1.0-BETA-1380]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:115) [PacketUtil.class:1.8.9-1890-4.1.0-BETA-1380]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onPr

forge-1.8.9-11.15.1.1902-1.8.9-universal + spongeforge-1.8.9-1890-4.1.0-BETA-1380 + PermissionsEx-Sponge#128 + Nexus v1.8.1a

**Comment by ryantheleach** [comment]
https://github.com/CuebyteGit/Nexus/blob/ae0eb8dcf98ebe04987bae232ad889c6aa9c211b/src/main/java/me/cuebyte/nexus/commands/CommandSpawnTeleport.java#L35

https://github.com/SpongePowered/SpongeAPI/commit/29eeb92d962fc5c09439f296ed1d5533094d0686

Would changing the return type from void to boolean break binary compatibility?

**Comment by bbtiger** [comment]
spongeforge-1.8.9-1890-4.1.0-BETA-1368 Without this problem

**Comment by Deamon5550** [comment]
@ryantheleach yes it does, plugins will have to update. (just a recompile in this case of void -> bool)

**Comment by CuebyteGit** [comment]
Thanks for reporting this issue! This has been fixed in [Nexus v1.8.2c](https://github.com/CuebyteGit/Nexus/releases).
