### ISSUE TITLE
Teleport/World Issue

### ISSUE THREAD

**Issue by seanamor** [SpongePowered/SpongeForge#660]
Minecraft: 1.8.9
SpongeAPI: 4.1.0-SNAPSHOT-6aa22d5
SpongeForge: 1.8.9-1890-4.1.0-BETA-1385
Minecraft Forge: 11.15.1.1902

I try teleporting to a player, and this occurs:

```
03.06 20:25:00 [Server] Server thread/INFO [io.github.hsyyid.essentialcmds]: [Sean_Amor] executed command world spawn
03.06 20:25:00 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'world spawn' for source EntityPlayerMP['Sean_Amor'/3897, l='world', x=-3206.50, y=96.00, z=-4347.50]: org.spongepowered.api.entity.living.player.Player.setLocation(Lorg/spongepowered/api/world/Location;)V
03.06 20:25:00 [Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.entity.living.player.Player.setLocation(Lorg/spongepowered/api/world/Location;)V
03.06 20:25:00 [Server] INFO at io.github.hsyyid.essentialcmds.cmdexecutors.world.WorldsBase$Spawn.execute(WorldsBase.java:629) ~[WorldsBase$Spawn.class:8.1.2]
03.06 20:25:00 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:177) ~[ChildCommandElementExecutor.class:1.8.9-1890-4.1.0-BETA-1385]
03.06 20:25:00 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331) ~[CommandSpec.class:1.8.9-1890-4.1.0-BETA-1385]
03.06 20:25:00 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.1.0-BETA-1385]
03.06 20:25:00 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:269) [SpongeCommandManager.class:1.8.9-1890-4.1.0-BETA-1385]
03.06 20:25:00 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
03.06 20:25:00 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:115) [PacketUtil.class:1.8.9-1890-4.1.0-BETA-1385]
03.06 20:25:00 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
03.06 20:25:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
03.06 20:25:00 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
03.06 20:25:00 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
03.06 20:25:00 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
03.06 20:25:00 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by JBYoshi** [comment]
@gabizou Probably a mistake in https://github.com/SpongePowered/SpongeCommon/commit/f39be58f704466dd8ca7e66ecb88777c29475f3b? Specifically, I think the JVM was looking for a method in `org.spongepowered.api.mixin.Entity`, but the actual method is in `MixinEntity`. Probably could be fixed by mixing into `org.spongepowered.api.mixin.Entity` and adding the methods from `IMixinEntityBackwardsCompatible`.

**Comment by Aaron1011** [comment]
@seanamor: Can you link to the version of EssentialCmds that you're using?
