### ISSUE TITLE
Blood Magic - Demonic Will 

### ISSUE THREAD

**Issue by seanamor** [SpongePowered/SpongeForge#672]
https://github.com/WayofTime/BloodMagic/issues/784

Can anyone do further testing, The dev closed out the issue if you read the above issue. It does not look like they will/can fix this issue, but its pretty game breaking for the mod itself, it worked on past version of sponge, I just cannot verify which one.

**#### What you expected to happen:**

Receive demonic will

**#### Steps to reproduce:**

1. Snared the mob, waited for the particle effects, attacked with sentient sword/bow while activated
2. no demonic will was produced

...

____
**#### Affected Versions (Do *not* use "latest"):**

BloodMagic: 20
Minecraft: 1.8.9
SpongeAPI: 4.1.0-SNAPSHOT-6aa22d5
1.8.9-1890-4.1.0-BETA-1385
Minecraft Forge: 11.15.1.1902

**Plugins/Mods Used**
06.06 16:38:57 [Server] Server thread/INFO Plugins (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeForge, Baubles Stuff, Better Foliage, BiomeTweaker, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Bloodmoon, Bookshelf, DjxyCore, Calendar, Conquest Mod, CustomNPCs, Custom Spawners, Baubles, Thaumcraft, Dark Utilities, EnjinMinecraftPlugin, EssentialCmds, FastAsyncWorldEdit, Floocraft, FoxCore, FoxGuard, Grimoire of Gaia 3, guide, keys, Mantle, MorePlayerModels, NameAPI, Nations, PermissionManager, Project Worlds, RadixCore, Redstone Paste, Reptile Mod, Rope Bridge, Realistic Terrain Generation, StatusProtocol, ServerListPlus, Tinkers' Construct, The Little Things, Total Economy, Wings, Horns, and Hooves, the Ultimate Unicorn Mod!, WorldEdit

the only error I see (might not be related)
```
06.06 16:33:44 [Server] Server thread/ERROR [Sponge]: Could not pass InteractBlockEvent$Secondary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@71d10808
06.06 16:33:44 [Server] INFO java.util.NoSuchElementException: No value present
06.06 16:33:44 [Server] INFO at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_45]
06.06 16:33:44 [Server] INFO at com.helion3.keys.listeners.InteractBlockListener.onUse(InteractBlockListener.java:49) ~[InteractBlockListener.class:1.2+unknown-b0.git-unknown]
06.06 16:33:44 [Server] INFO at org.spongepowered.common.event.listener.SecondaryListener_InteractBlockListener_onUse102.handle(Unknown Source) ~[?:?]
06.06 16:33:44 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:193) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:223) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:608) [SpongeCommonEventFactory.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:603) [SpongeCommonEventFactory.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:551) [lm.class:?]
06.06 16:33:44 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) [ja.class:?]
06.06 16:33:44 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) [ja.class:?]
06.06 16:33:44 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:115) [PacketUtil.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:44 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
06.06 16:33:44 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
06.06 16:33:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
06.06 16:33:44 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
06.06 16:33:44 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
06.06 16:33:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
06.06 16:33:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
06.06 16:33:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
06.06 16:33:44 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
06.06 16:33:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
06.06 16:33:46 [Server] Server thread/ERROR [Sponge]: Could not pass InteractBlockEvent$Secondary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@71d10808
06.06 16:33:46 [Server] INFO java.util.NoSuchElementException: No value present
06.06 16:33:46 [Server] INFO at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_45]
06.06 16:33:46 [Server] INFO at com.helion3.keys.listeners.InteractBlockListener.onUse(InteractBlockListener.java:49) ~[InteractBlockListener.class:1.2+unknown-b0.git-unknown]
06.06 16:33:46 [Server] INFO at org.spongepowered.common.event.listener.SecondaryListener_InteractBlockListener_onUse102.handle(Unknown Source) ~[?:?]
06.06 16:33:46 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:193) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:223) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:608) [SpongeCommonEventFactory.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:603) [SpongeCommonEventFactory.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:551) [lm.class:?]
06.06 16:33:46 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) [ja.class:?]
06.06 16:33:46 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) [ja.class:?]
06.06 16:33:46 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:115) [PacketUtil.class:1.8.9-1890-4.1.0-BETA-1385]
06.06 16:33:46 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
06.06 16:33:46 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
06.06 16:33:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
06.06 16:33:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
06.06 16:33:46 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
06.06 16:33:46 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
06.06 16:33:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
06.06 16:33:46 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
06.06 16:33:46 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
06.06 16:33:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
06.06 16:33:46 [Server] Server thread/ERROR [Sponge]: Could not pass InteractBlockEvent$Secondary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@71d10808
06.06 16:33:46 [Server] INFO java.util.NoSuchElementException: No value present
06.06 16:33:47 [Multicraft] Skipped 25 lines due to rate limit (29/s)
```

**Comment by bloodmc** [comment]
@seanamor Test build SF 1421.

**Comment by bloodmc** [comment]
Closing as this is a prism bug.
