### ISSUE TITLE
Villager ID crash with Immersive Engineering and SpongeForge 4.2.0-BETA-1414

### ISSUE THREAD

**Issue by iPencil** [SpongePowered/SpongeForge#676]
When the Immersive Engineering Villager is loaded it immediately crashes the server. I'm not sure who is at fault here but I thought reporting it here might be better.

As I said we're using SpongeForge 4.2.0-BETA-1414 and Immersive Engineering 0.8-27 for 1.8.9

Please note that while the ID currently says -1, it started crashing with 80, crashes with 5, 7, or anything else we have tried.

Please let me know if you need any additional information.

```
java.lang.IllegalStateException: Invalid Villager profession id is present! Found: -1 when the expected contain: [SpongeProfession{id=farmer, name=farmer, type=0}, SpongeProfession{id=librarian, name=librarian, type=1}, SpongeProfession{id=priest, name=priest, type=2}, SpongeProfession{id=blacksmith, name=blacksmith, type=3}, SpongeProfession{id=butcher, name=butcher, type=4}]
	at org.spongepowered.common.entity.EntityUtil.validateProfession(EntityUtil.java:135)
	at net.minecraft.entity.passive.EntityVillager.handler$onSetProfession$0(EntityVillager.java:88)
	at net.minecraft.entity.passive.EntityVillager.func_70938_b(EntityVillager.java:320)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1617)
	at blusunrize.immersiveengineering.common.world.VillageEngineersHouse.func_74875_a(VillageEngineersHouse.java:205)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:46)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:86)
	at rtg.world.gen.ChunkProviderRTG.func_73153_a(ChunkProviderRTG.java:669)
	at org.spongepowered.mod.world.gen.SpongeChunkProviderForge.func_73153_a(SpongeChunkProviderForge.java:222)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:88)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1082)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
	at net.minecraft.world.World.func_72964_e(World.java:287)
	at net.minecraft.world.World.func_175726_f(World.java:282)
	at net.minecraft.world.World.func_180495_p(World.java:822)
	at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:72)
	at net.minecraft.block.Block.func_180645_a(Block.java:431)
	at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1106)
	at net.minecraft.world.WorldServer.redirect$onUpdateBlocks$0(WorldServer.java:171)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:431)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


 A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.spongepowered.common.entity.EntityUtil.validateProfession(EntityUtil.java:135)
	at net.minecraft.entity.passive.EntityVillager.handler$onSetProfession$0(EntityVillager.java:88)
	at net.minecraft.entity.passive.EntityVillager.func_70938_b(EntityVillager.java:320)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1617)
	at blusunrize.immersiveengineering.common.world.VillageEngineersHouse.func_74875_a(VillageEngineersHouse.java:205)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:46)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:86)
	at rtg.world.gen.ChunkProviderRTG.func_73153_a(ChunkProviderRTG.java:669)
	at org.spongepowered.mod.world.gen.SpongeChunkProviderForge.func_73153_a(SpongeChunkProviderForge.java:222)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:88)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1082)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
	at net.minecraft.world.World.func_72964_e(World.java:287)
	at net.minecraft.world.World.func_175726_f(World.java:282)
	at net.minecraft.world.World.func_180495_p(World.java:822)
	at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:72)
	at net.minecraft.block.Block.func_180645_a(Block.java:431)
	at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1106)
	at net.minecraft.world.WorldServer.redirect$onUpdateBlocks$0(WorldServer.java:171)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:431)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
```

**Comment by gabizou** [comment]
So, there's no clear way to fix this sadly. The unfortunate part is that Forge's `VillagerRegistry` was rewritten for 1.9, but the changes were never back ported to 1.8.9, which basically prevents mods from properly registering their custom villagers and what's called `ITradeList`s. While it *is* possible to add support for custom `VillagerProfession`s, it's not very well possible for us (sponge) to remain compatible with mod added `ITradeList`s due to the inability to retrieve them anywhere.

**Comment by iPencil** [comment]
Well it seems like Immersive Engineering hasn't even implemented their villager and are spawning it by accident so that conflict should be resolved. Just seems like SpongeForge is more sensitive with that stuff than Forge itself, because it doesn't crash on a vanilla/forge server.

**Comment by gabizou** [comment]
Closing this as SpongeForge is doing it's job appropriately to where villager careers that were not registered correctly are being reported as such. Granted, the registration process could be improved, 1.8.9's `VillagerRegistry` was far from usable. 1.9+ saw a registry rewrite, so the `VillagerRegistry` works perfectly for that version moving forward.
