### ISSUE TITLE
Server start Crash with latest spongeforge-1.9.4-1965-5.0.0-BETA-1464

### ISSUE THREAD

**Issue by flash4203** [SpongePowered/SpongeForge#695]
The new spongeforge-1.9.4-1965-5.0.0-BETA-1464 and  forge-1.9.4-12.17.0.1965-universal wont work. clean install. 

wont even start server. Report below

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.9.4-1965-5.0.0-BETA-1464.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 6/18/16 3:30 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/Int2BooleanArrayMap
	at org.spongepowered.common.world.WorldManager.<clinit>(WorldManager.java:112)
	at org.spongepowered.common.registry.type.world.DimensionTypeRegistryModule.registerDefaults(DimensionTypeRegistryModule.java:54)
	at org.spongepowered.common.registry.util.RegistryModuleLoader.tryModulePhaseRegistration(RegistryModuleLoader.java:61)
	at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:425)
	at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:144)
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:132)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:349)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:499)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:91)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:321)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.Int2BooleanArrayMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Linux (amd64) version 2.6.32-042stab104.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 290674944 bytes (277 MB) / 559939584 bytes (534 MB) up to 1335885824 bytes (1274 MB)
	JVM Flags: 11 total; -XX:+OptimizeStringConcat -XX:OnOutOfMemoryError=curl https://api.creeper.host/callbacks/minecraft/outofmemory.php?instance=mc-575ff8ce8d704 -k -XX:OnError=curl https://api.creeper.host/callbacks/minecraft/crash.php?instance=mc-575ff8ce8d704 -k -XX:-UseCompressedOops -Xmx1453M -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:ParallelGCThreads=2 -XX:+AggressiveHeap -XX:+AggressiveOpts -XX:MaxMetaspaceSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1965 3 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1965-universal.jar) 
		Forge{12.17.0.1965} [Minecraft Forge] (forge-1.9.4-12.17.0.1965-universal.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.9.4-1965-5.0.0-BETA-1464.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)`

**Comment by flash4203** [comment]
btw I tested forge before the mod and it worked. it is a sponge issue.

**Comment by Zidane** [comment]
@flash4203 

Update your bleeding build that I just pushed.

**Comment by flash4203** [comment]
Ok I done that. no need to swear :o

**Comment by Zidane** [comment]
@flash4203 

Where in the reply to you did I...swear :S?

**Comment by flash4203** [comment]
its a joke I think in the UK bleeding means  like

Just bleeding doing it already, stems from Bloody. Like Bloody hell. etc.  ( I guess its lost in translation somewhere)

**Comment by Zidane** [comment]
@flash4203 

We had quite a laugh over here. For reference, SpongeForge for 1.9.4 originates from the codebase branch called "bleeding" meaning bleeding edge.

**Comment by flash4203** [comment]
ah I get you. but thank you anyway. No I got to hunt down the dynmap guy as his mod is bugged out as well. but he does not seem to answer his requests as quick as you guys. Kudos for you.
