### ISSUE TITLE
[1.8.9] Netty AssertionError on player join

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeForge#720]
This exception was generated on the latest build of SpongeForge 4.2.0. Stack trace follows:

```
[11:49:43] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError
    at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:203) ~[EmbeddedChannel.class:?]
    at org.spongepowered.common.world.DimensionManager.sendDimensionRegistration(DimensionManager.java:159) ~[DimensionManager.class:1.8.9-1890-4.2.0-BETA-1511]
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:276) ~[lx.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239) ~[NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54) ~[NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190) ~[NetworkDispatcher$1.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289) ~[ek.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189) ~[ll.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
```

Obviously the JVM needs the `-ea` flag passed to replicate this.

**Comment by gabizou** [comment]
And how do you replicate this?

**Comment by caseif** [comment]
Simply by joining the server. Also, for the record, this occurs on Forge build #1902.

**Comment by simon816** [comment]
I'm not sure why this is calling `writeOutbound` directly. I've seen most the time the `writeAndFlush` method is used
https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/common/world/MixinDimensionManager.java#L159

**Comment by caseif** [comment]
It appears this also occurs on SpongeForge 5.0.0 w/ Forge #2073. Stack trace follows:

```
java.lang.AssertionError
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:203)
	at org.spongepowered.common.world.WorldManager.sendDimensionRegistration(WorldManager.java:89)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:288)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Zidane** [comment]
@simon816 

Change this to how you want it to be then.
