### ISSUE TITLE
1.8.9 FakePlayer problems

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeForge#776]
Not entirely sure what is causing this or the direct impact that this is having on protection and such, but whenever a mod's FakePlayer attempts to do something (Specifically ComputerCrafts) it starts spamming the console with this message:

```
[05:56:40] [pool-2-thread-9/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@73695fe7[id=0d0c4ca0-4ff1-11e4-916c-0800200c9a66,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
        at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
        at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1586]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1586]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1586]
        at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1586]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[05:56:42] [pool-2-thread-9/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@637a4201[id=0d0c4ca0-4ff1-11e4-916c-0800200c9a66,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
        at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
        at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1586]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1586]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1586]
        at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1586]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

0d0c4ca0-4ff1-11e4-916c-0800200c9a66 is the UUID for ComputerCraft's FakePlayer.
I'm running SpongeForge 1586

**Comment by inklit** [comment]
Also I accidentally opened it in SpongeCommon first and then moved it to SpongeForge, if it turns out to be an issue with SpongeCommon feel free to close this and re-open the issue at https://github.com/SpongePowered/SpongeCommon/issues/854

**Comment by inklit** [comment]
This bug is not present in B1575 and below.
It was introduced in B1576 and is present onward.
