### ISSUE TITLE
Tab autocomplete throws an exception

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeForge#778]
```
[06:52:44] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "d016dfe11dcb.ocnm"
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NumberFormatException: For input string: "d016dfe11dcb.ocnm"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_91]
        at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_91]
        at java.lang.Long.valueOf(Long.java:776) ~[?:1.8.0_91]
        at java.lang.Long.decode(Long.java:928) ~[?:1.8.0_91]
        at java.util.UUID.fromString(UUID.java:206) ~[?:1.8.0_91]
        at org.spongepowered.common.service.user.UserDiscoverer.getAllProfiles(UserDiscoverer.java:130) ~[UserDiscoverer.class:1.8.9-1890-4.2.0-BETA-1575]
        at org.spongepowered.common.service.user.SpongeUserStorageService.getAll(SpongeUserStorageService.java:85) ~[SpongeUserStorageService.class:1.8.9-1890-4.2.0-
BETA-1575]
        at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.getChoices(GenericArguments.java:1010) ~[GenericArguments$UserCommandElement.class:
1.8.9-1890-4.2.0-BETA-1575]
        at org.spongepowered.api.command.args.PatternMatchingCommandElement.complete(PatternMatchingCommandElement.java:73) ~[PatternMatchingCommandElement.class:1.8
.9-1890-4.2.0-BETA-1575]
        at org.spongepowered.api.command.spec.CommandSpec.complete(CommandSpec.java:302) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1575]
        at org.spongepowered.api.command.spec.CommandSpec.getSuggestions(CommandSpec.java:337) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1575]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:346) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1575]
        at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:329) ~[SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-157
5]
        at net.minecraft.command.ServerCommandManager.func_180524_a(SourceFile:168) ~[bd.class:?]
        at net.minecraft.server.MinecraftServer.func_180506_a(MinecraftServer.java:832) ~[MinecraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1156) ~[lm.class:?]
        at net.minecraft.network.play.client.C14PacketTabComplete.func_148833_a(SourceFile:46) ~[id.class:?]
        at net.minecraft.network.play.client.C14PacketTabComplete.func_148833_a(SourceFile:10) ~[id.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:119) ~[PacketUtil.class:1.8.9-1890-4.2.0-BETA-1575]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
```

"d016dfe11dcb" seems to be the last part of my player's UUID (BTC) although that same value shows up even when you use tab autocomplete on players that don't have that UUID.

**Comment by simon816** [comment]
Is there a rogue file called `d016dfe11dcb.ocnm` in the `world/playerdata` folder. There should only be files with the player UUID as their filename.

**Comment by inklit** [comment]
There's a file called ac440b00-f677-4852-bb32-d016dfe11dcb.ocnm which is my entire UUID. 
I don't know how this file got there or it's purpose so I've copied it out of the directory and it seems to fix the issue.
Maybe a check for invalid files in the directory should be created.

Thanks.

**Comment by ryantheleach** [comment]
What mods did you have installed? I wonder if this is some strange storage for one of your mods?

**Comment by inklit** [comment]
OpenComputers, ChunkLoaderZ, ComputerCraft, CCTweaks, MoreFurnaces, and Iron Chest.

**Comment by inklit** [comment]
Ah I see.
They are for OpenComputer's Nanomachine data storage.

**Comment by inklit** [comment]
https://github.com/MightyPirates/OpenComputers/blob/399e0f44e6e6088a8b95f011011d817cbec45177/src/main/scala/li/cil/oc/common/event/NanomachinesHandler.scala#L111

**Comment by Zidane** [comment]
I think this has been resolved a bit ago.
