### ISSUE TITLE
[1.8.9] invalid-lookup-uuids option is broken

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeForge#804]
**Summary**
According to Sponge, you are supposed to add mod FakePlayers to this list to prevent GameProfile lookups from contacting Mojang and causing spam.
However, the `invalid-lookup-uuids` option does not work.
I am using SpongeForge 1625.

**Expected Result**
The expected result is that GameProfile lookups for a UUID added to the `invalid-lookup-uuids` option will no longer contact Mojang and cause spam related to throttling.

**Actual Result**
The actual result is that regardless of the `invalid-lookup-uuids` list, Sponge seems to not mark it as invalid and continues to contact Mojang.
As a result of it contacting Mojang, it gets the server ratelimited and then causes spam in the console like so:

```
[10:45:46] [pool-2-thread-3/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@35f36dba[id=ebcda071-3ef5-4f4a-849d-c078264010c4,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
        at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
        at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1625]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[10:45:48] [pool-2-thread-3/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@532bbae9[id=ebcda071-3ef5-4f4a-849d-c078264010c4,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
        at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
        at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1625]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[10:45:50] [pool-2-thread-3/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@5e7bad08[id=ebcda071-3ef5-4f4a-849d-c078264010c4,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
        at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
        at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1625]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Suspected Reason**
My suspected reason for this bug is that Sponge seems to be overwriting the `invalid-lookup-uuids` option on start and then removing quotations from UUIDs that were added to the list.

**Example**
I am trying to add the UUID `ebcda071-3ef5-4f4a-849d-c078264010c4` to the `invalid-lookup-uuids` list.
Here is what I wrote to the configuration file:

```
        invalid-lookup-uuids=[
            "00000000-0000-0000-0000-000000000000",
            "0d0c4ca0-4ff1-11e4-916c-0800200c9a66",
            "41c82c87-7afb-4024-ba57-13d2c99cae77",
            "ebcda071-3ef5-4f4a-849d-c078264010c4"
        ]
```

After I started the server, it became very apparent that my file had been changed.
This is what Sponge had changed it to:

```
        invalid-lookup-uuids=[
            "00000000-0000-0000-0000-000000000000",
            "0d0c4ca0-4ff1-11e4-916c-0800200c9a66",
            "41c82c87-7afb-4024-ba57-13d2c99cae77",
            ebcda071-3ef5-4f4a-849d-c078264010c4
        ]
```

As for why it is overwriting the configuration file and modifying it to not have quotes I do not know, but I suspect that if there is a lack of quotations it does not actually get marked as invalid with this configuration option.

If I am simply doing something wrong, please let me know.

**Comment by cartman-2000** [comment]
This also affects the Prism plugin when rolling back of an entity, it still spams the console with this error after adding the fake UUID to the list in the config.

**Comment by ryantheleach** [comment]
For why it's stripping quotes, I believe it's likely because of the hocon lib deciding that since the string starts with a number it needs to be wrapped in quotes.

**Comment by inklit** [comment]
That's interesting ryantheleach, do you know if the quotes are needed for the UUID to be ignored?
It could be quite an odd coincidence that all of the required UUIDs to be ignored by default have numbers as the first character, which could be why nobody has noticed this til now.

**Comment by ryantheleach** [comment]
Assuming that it's parsing correctly the quotes shouldn't matter one way or another, and is just a distraction from whatever issue is the real issue.

**Comment by inklit** [comment]
I'm going to do more testing for this issue on 1.10.2 to see if this is still relevant.

**Comment by Zidane** [comment]
Re-test with stable-5 and report back if still an issue and we will re-open.
