### ISSUE TITLE
[1.10] Sponge crashes custom dimensions

### ISSUE THREAD

**Issue by sky0-1** [SpongePowered/SpongeForge#812]
When using SpongeForge and my dimension-adding mod, a user got this error:
```
Caused by: java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[minecraft_server.1.10.2.jar:?]
at org.spongepowered.common.world.WorldManager.getWorldProperties(WorldManager.java:330) ~[WorldManager.class:1.10.2-2026-5.0.0-BETA-1599]
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:184) ~[DimensionManager.class:?]
at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:71) ~[MinecraftServer.class:?]
```
This possibly occurred because of calling `MinecraftServer#worldServerForDimension(int dimID)` or `MinecraftServer#getPlayerList()#transferPlayerToDimension(PlayerMP player, Teleporter tel)`

**Comment by sky0-1** [comment]
Using my dimension-adding mod without SpongeForge causes no crash

**Comment by gabizou** [comment]
Could you include the full error? and use ` ``` ` to make a code block so there's no space issues.

**Comment by JonDaHackingWiz** [comment]
@sky0-1 You're not the only one to have this problem. Apparently the dimension handler on SpongeForge is a little bit screwed and needs fixing.

**Comment by sky0-1** [comment]
@gabizou I did not get the crash, but [here is the log](http://pastebin.com/6ZGzzxzX) I was provided.
Line 35-36 of that log is where my mod's block is activated and the TileEntity transfers the player to the dimension. My code for that is [here](https://github.com/sky0-1/Nomadic-Tents-1.9.4/blob/master/com/yurtmod/block/TileEntityTentDoor.java#L155-L173)
