### ISSUE TITLE
[1.10.2] Joining world that doesn't exist

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeForge#825]
```
java.lang.RuntimeException: Attempt made to initialize dimension who isn't registered!
        at net.minecraftforge.common.DimensionManager.lambda$initDimension$2(DimensionManager.java:179) ~[DimensionManager.class:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_101]
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:179) ~[DimensionManager.class:?]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:69) ~[MinecraftServer.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:201) ~[mp.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

blood fixed something similar on Cauldron, perhaps reset player's position to the spawn point if the world doesn't exist?

**Comment by Aaron1011** [comment]
Can you please list the versions of any mods you're using (as well as the versions of Sponge and Forge)?

**Comment by Nentify** [comment]
```
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-d41be56
    SpongeForge: 1.10.2-2052-5.0.0-BETA-1668
    Minecraft Forge: 12.18.1.2057
```

```
luke@play:/home/minecraft/tekkify-5/beta-1$ ls -l mods
total 74200
-rw-rw-r-- 1 minecraft minecraft  6127125 Aug 13 11:11 BiomesOPlenty-1.9.4-4.1.0.2066-universal.jar
-rw-rw-r-- 1 minecraft minecraft    19173 Jul 12 18:54 BlockRenderer-1.0.0.jar
-rw-rw-r-- 1 minecraft minecraft    70393 Jul 12 09:25 Chameleon-1.9.4-2.1.6.jar
-rw-rw-r-- 1 minecraft minecraft  6835568 Jul 12 14:56 Chisel-MC1.9.4-0.0.6.33.jar
-rw-rw-r-- 1 minecraft minecraft   630460 Aug 13 11:07 chiselsandbits-11.10.jar
-rw-rw-r-- 1 minecraft minecraft   339521 Aug 13  2016 CookingForBlockheads_1.10.2-4.1.12.jar
-rw-rw-r-- 1 minecraft minecraft   775098 Jul 12 09:28 CraftTweaker-1.10.2-3.0.10.jar
-rw-rw-r-- 1 minecraft minecraft   357775 Aug  5 16:22 cyberware-1.9.4-1.10.2-beta-0.1.12.jar
-rw-rw-r-- 1 luke      minecraft  7578180 Aug 13 16:34 DiscordIntegration-mc1.10.2-2.0.0.jar
-rw-rw-r-- 1 minecraft minecraft   452419 Aug 13 11:08 EnderCore-1.10.2-0.4.1.47-beta.jar
-rw-rw-r-- 1 minecraft minecraft  4495218 Aug 13 11:09 EnderIO-1.10.2-3.0.1.92_beta.jar
-rw-rw-r-- 1 minecraft minecraft     7241 Jun 27 13:56 FastLeaveDecay-MC1.9.4-1.2.1.jar
-rw-rw-r-- 1 minecraft minecraft  3930540 Aug 13 11:10 forestry_1.10.2-5.2.8.231.jar
drwxrwsr-x 2 minecraft minecraft     4096 Aug 13 16:32 h3ntlibs
-rw-rw-r-- 1 minecraft minecraft   230808 Jul 12 09:24 InventoryTweaks-1.61-58.jar
-rw-rw-r-- 1 minecraft minecraft   148229 Jul 18 19:00 ironchest-1.10.2-7.0.7.795.jar
-rw-rw-r-- 1 minecraft minecraft   332152 Aug 13 11:11 jei_1.10.2-3.8.1.242.jar
-rw-rw-r-- 1 minecraft minecraft   825732 Aug  4 13:45 malisiscore-1.9.4-4.1.1.jar
-rw-rw-r-- 1 minecraft minecraft  1547067 Aug  4 00:04 malisisdoors-1.9.4-5.0.2.jar
-rw-rw-r-- 1 minecraft minecraft  3202531 Jul 28 19:17 Mantle-1.10.2-0.10.4.jar
-rw-rw-r-- 1 minecraft minecraft   172952 Aug 13 11:12 MCMultiPart-1.2.1-universal.jar
-rw-rw-r-- 1 minecraft minecraft   111946 Jul 12 09:26 ModTweaker2-2.0.0.jar
-rw-rw-r-- 1 minecraft minecraft    16254 Aug  2 21:10 Neat 1.3-11.jar
-rw-rw-r-- 1 minecraft minecraft   152903 Jul 31 12:39 notenoughwands-1.9.4-1.3.5.jar
-rw-rw-r-- 1 minecraft minecraft 11961792 Aug  1 15:14 OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
-rw-rw-r-- 1 minecraft minecraft   131031 Aug  4 13:45 OpenGlasses-1.4.jar
-rw-rw-r-- 1 minecraft minecraft    22993 Jun 27 20:04 PackingTape-1.9.4-0.5.2.jar
-rw-rw-r-- 1 minecraft minecraft  2797258 Aug 13  2016 Pam's HarvestCraft 1.9.4-1.10.2c.jar
-rw-rw-r-- 1 minecraft minecraft    56971 Jun 28 12:44 Ping-1.10.X-1.2.2.B7-universal.jar
drwxrwsr-x 2 luke      minecraft     4096 Aug 13 16:58 plugins
-rw-rw-r-- 1 minecraft minecraft  1168869 Aug 13 11:15 Quark-beta-50.jar
-rw-rw-r-- 1 minecraft minecraft   609145 Aug 13 11:17 refinedstorage-0.8.18.jar
-rw-rw-r-- 1 minecraft minecraft   103698 Aug  2 21:12 Souls-1.10.2-1.1.0.jar
-rw-rw-r-- 1 luke      minecraft 17476841 Aug 13 15:50 spongeforge-1.10.2-2052-5.0.0-BETA-1668.jar
-rw-rw-r-- 1 minecraft minecraft   530380 Aug 13 11:18 StorageDrawers-1.10.2-3.2.3.jar
-rw-rw-r-- 1 minecraft minecraft  2419116 Jul 28 19:17 TConstruct-1.10.2-2.4.0.jenkins312.jar
-rw-rw-r-- 1 minecraft minecraft   153570 Aug  3 13:00 theoneprobe-1.10-1.0.15.jar
-rw-rw-r-- 1 minecraft minecraft   101174 Aug 13 11:19 topaddons-1.10.2-0.5.0.jar
-rw-rw-r-- 1 minecraft minecraft    14711 Aug  5 16:28 Zoom-MC1.10.2-1.1.0.jar
luke@play:/home/minecraft/tekkify-5/beta-1$ ls -l mods/plugins/
total 3112
-rw-rw-r-- 1 luke minecraft  799331 Aug 13 16:33 holograms-v1.1.1.jar
-rw-rw-r-- 1 luke minecraft  936429 Aug  9 13:53 Nucleus-0.7.0-S5-1.10.2-plugin.jar
-rw-rw-r-- 1 luke minecraft   37319 Aug 13 16:33 Titles-0.4.0.jar
-rw-rw-r-- 1 luke minecraft 1403689 Aug 13 16:33 worldedit-sponge-mc1.10.2-6.1.4-SNAPSHOT-dist.jar
```

I'm pretty sure it's just a simple Sponge issue though. I deleted the world the users were last in and they now can't connect because the world doesn't exist. In Cauldron, blood just made it so the player gets set to the server default spawn.

**Comment by cartman-2000** [comment]
I've noticed this in my own testing, if you remove a world that a player was in the last time they were on the server, they can no longer connect to the server without getting DC'd on connect from an error like this. It should be made so that a player will be sent to the main world spawn when this happens.

**Comment by Zidane** [comment]
I have code to resolve this in an old branch and have cleaned it up locally. If it works, I'll push it up.

**Comment by jk-5** [comment]
Before you could prevent this by changing the World the player spawns in in an ClientConnectionEvent.Login, but now the server throws this error before calling that event.
