### ISSUE TITLE
[1.10.2] Server error when teleporting to an unloaded world.

### ISSUE THREAD

**Issue by cartman-2000** [SpongePowered/SpongeForge#826]
I got this error when teleporting to an unloaded nether world using a nether portal.

```
[22:19:57] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (Nether)
[22:19:57] [Server thread/INFO] [FML]: Loading dimension -1 (DIM-1) (DedicatedServer)
[22:19:57] [Server thread/INFO]: Preparing start region for level -1 (DIM-1)
[22:19:58] [Server thread/WARN]: Failed to handle packet for /192.168.1.96:56868
java.util.NoSuchElementException
        at java.util.ArrayDeque.removeFirst(Unknown Source) ~[?:1.8.0_91]
        at java.util.ArrayDeque.pop(Unknown Source) ~[?:1.8.0_91]
        at org.spongepowered.common.event.tracking.CauseStack.pop(CauseStack.java:74) ~[CauseStack.class:1.10.2-2052-5.0.0-BETA-1670]
        at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:150) ~[CauseTracker.class:1.10.2-2052-5.0.0-BETA-1670]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$0(NetHandlerPlayServer.java:237) ~[me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[22:19:58] [Server thread/INFO]: cartman2000 lost connection: Internal server error
[22:19:58] [Server thread/INFO]: cartman2000 has logged off.
[22:20:12] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (DIM-1)
```

Server version:
[22:29:12] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-d11a7b4
    SpongeForge: 1.10.2-2052-5.0.0-BETA-1670
    Minecraft Forge: 12.18.1.2052

**Comment by jk-5** [comment]
Same issue happens for me when creating (hotloading) a new dimension.
SpongeForge 8e803f3960bc56501c1a40c8b2604fb62af73485

**Comment by cartman-2000** [comment]
Technically speaking there is a "workaround" for this, you could throw an item in the portal before going through it, that will cause the world to load, and you won't get DC'd when you go through, if you go through before the time it unloads again.

**Comment by gabizou** [comment]
This was already fixed. Forgot to link the issue in the commit.

**Comment by jk-5** [comment]
Is the fix already in SpongeForge bleeding?

**Comment by gabizou** [comment]
Yes.

**Comment by jk-5** [comment]
Ok. Thanks
