### ISSUE TITLE
[1.10.2] Could not pass CollideBlockEvent$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@4121b14c

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#828]
I updated to latest SpongeForge and Forge builds and now i get this error spamming a lot in the console:

```
`[03:27:05] [Server thread/ERROR] [Sponge/]: Could not pass CollideBlockEvent$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@4121b14c
java.lang.NullPointerException
	at me.ryanhamshire.griefprevention.event.BlockEventHandler.onBlockCollide(BlockEventHandler.java:240) ~[BlockEventHandler.class:?]
	at org.spongepowered.common.event.listener.CollideBlockEventListener_BlockEventHandler_onBlockCollide80.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2052-5.0.0-BETA-1670]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1670]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:390) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1670]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1670]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10.2-2052-5.0.0-BETA-1670]
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleCollideBlockEvent(SpongeCommonEventFactory.java:394) [SpongeCommonEventFactory.class:1.10.2-2052-5.0.0-BETA-1670]
	at net.minecraft.entity.Entity.onEntityCollideWithBlockState(Entity.java:1012) [rw.class:?]
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:934) [rw.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:855) [rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1802) [sf.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2224) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:47) [yx.class:?]
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:279) [zi.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52) [yx.class:?]
	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:356) [zi.class:?]
	at net.minecraft.entity.monster.EntityPigZombie.func_70071_h_(SourceFile:70) [yy.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:95) [TrackingUtil.class:1.10.2-2052-5.0.0-BETA-1670]
	at net.minecraft.world.WorldServer.onCallEntityUpdate(WorldServer.java:1141) [ls.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1260) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`
```

**Comment by Eufranio** [comment]
Sorry, updated to the latest GriefPrevention build and seems it's fixed!
