### ISSUE TITLE
Error feedback about death event.

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#831]
After death, inventory is keeped, although keepinventory is setted false.
spongeforge-1.8.9-1890-4.2.0-BETA-1666
This error happened after I installed gravestone mod.
https://mods.curse.com/mc-mods/minecraft/238551-gravestone-mod
```
[20:48:36] [Server thread/ERROR] [Sponge/]: Could not pass ClientConnectionEvent$Disconnect$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@7038fda0
java.lang.NullPointerException
    at net.minecrell.serverlistplus.sponge.SpongePlugin$LoginListener.onPlayerQuit(SpongePlugin.java:207) ~[SpongePlugin$LoginListener.class:?]
    at org.spongepowered.common.event.listener.DisconnectListener_LoginListener_onPlayerQuit26.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1666]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:184) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1666]
    at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$0(NetHandlerPlayServer.java:439) [lm.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:704) [lm.class:?]
    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:449) [ek.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:183) [ll.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by Deamon5550** [comment]
Duplicate #798
