### ISSUE TITLE
[1.10.2] Incompatability with RFTools Dimensions

### ISSUE THREAD

**Issue by tenten8401** [SpongePowered/SpongeForge#832]
Hey there, using sponge, when I restart the world w/ an RFTools dimension enabled, it crashes, giving this stack trace.
```
[02:40:22] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.getDimensionManager(RfToolsDimensionManager.java:303) ~[RfToolsDimensionManager.class:?]
at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:74) ~[GenericWorldProvider.class:?]
at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.createBiomeProviderInternal(GenericWorldProvider.java:200) ~[GenericWorldProvider.class:?]
at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_76572_b(GenericWorldProvider.java:190) ~[GenericWorldProvider.class:?]
at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39) ~[atl.class:?]
at net.minecraft.world.WorldServer.<init>(WorldServer.java:113) ~[ls.class:?]
at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) ~[lo.class:?]
at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:768) ~[WorldManager.class:1.10.2-2052-5.0.0-BETA-1670]
at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:735) ~[WorldManager.class:1.10.2-2052-5.0.0-BETA-1670]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:323) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) ~[ld.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

I reported this to RFToolsDimensions and he seems to think it's a problem with sponge. See the issue [here](https://github.com/McJty/RFToolsDimensions/issues/26).

**Comment by mbax** [comment]
https://github.com/McJty/RFToolsDimensions/issues/26

**Comment by gabizou** [comment]
Please include steps to reproduce. A stack trace and an issue doesn't really help much.

**Comment by tenten8401** [comment]
Create a dimension, Any kind, teleport to it, and restart the server.
