### ISSUE TITLE
[1.8.9]Error feedback about chat system.

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#833]
```
[23:57:29] [Server thread/ERROR] [Sponge/]: Could not pass ServerChatEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@7ff14943
java.lang.NullPointerException
	at com.gmail.trentech.simpletags.EventListener.onMessageChannelEventChat(EventListener.java:56) ~[EventListener.class:?]
	at org.spongepowered.common.event.listener.ChatListener_EventListener_onMessageChannelEventChat112.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:148) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:92) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:81) [EventBus.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$0(NetHandlerPlayServer.java:78) [lm.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:799) [lm.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by 5igm** [comment]
spongeforge-1.8.9-1890-4.2.0-BETA-1666

**Comment by gabizou** [comment]
This is a plugin's event listener NPE  not sponge.
