### ISSUE TITLE
Error feedback about movement event

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#835]
spongeforge-1.8.9-1890-4.2.0-BETA-1666
```
[01:07:34] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLServerStartingEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@76c2ac40
java.lang.NoClassDefFoundError: org/spongepowered/api/event/entity/MoveEntityEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_101]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_101]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_101]
	at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_101]
	at org.spongepowered.common.event.SpongeEventManager.registerListener(SpongeEventManager.java:156) ~[SpongeEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.event.SpongeEventManager.registerListeners(SpongeEventManager.java:200) ~[SpongeEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at main.java.me.cuebyte.nexus.Nexus.onEnable(Nexus.java:148) ~[Nexus.class:?]
	at org.spongepowered.common.event.listener.GameStartingServerEventListener_Nexus_onEnable16.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:185) [SpongeMod.class:1.8.9-1890-4.2.0-BETA-1666]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:787) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:284) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:281) [ko.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.entity.MoveEntityEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	... 39 more
Caused by: java.lang.NullPointerException
```

**Comment by Minecrell** [comment]
The plugin you downloaded was built for SpongeAPI 5.0 (1.10.2 builds of SF) and is not compatible with SpongeForge 1.8.9. You may need to download a different version or an older build.
