### ISSUE TITLE
[1.10.2]Sponge is not compatible with Nomadic Tents

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#836]
MC: 1.10.2

Forge: forge-1.10.2-12.18.1.2026-universal
spongeforge-1.10.2-2044-5.0.0-BETA-1649
Nomadic Tents: NomadicTents[1.10.2]-7.01
```
[23:01:06] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[minecraft_server.1.10.2.jar:?]
at org.spongepowered.common.world.WorldManager.getWorldProperties(WorldManager.java:330) ~[WorldManager.class:1.10.2-2026-5.0.0-BETA-1599]
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:184) ~[DimensionManager.class:?]
at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:71) ~[MinecraftServer.class:?]
at com.yurtmod.block.TileEntityTentDoor.onPlayerActivate(TileEntityTentDoor.java:156) ~[TileEntityTentDoor.class:?]
at com.yurtmod.block.BlockTentDoor.func_180639_a(BlockTentDoor.java:78) ~[BlockTentDoor.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:178) ~[lv.class:?]
at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$0(NetHandlerPlayServer.java:636) ~[me.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) ~[PacketUtil.class:1.10.2-2026-5.0.0-BETA-1599]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fl$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more
[23:01:06] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[minecraft_server.1.10.2.jar:?]
at org.spongepowered.common.world.WorldManager.getWorldProperties(WorldManager.java:330) ~[WorldManager.class:1.10.2-2026-5.0.0-BETA-1599]
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:184) ~[DimensionManager.class:?]
at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:71) ~[MinecraftServer.class:?]
at com.yurtmod.block.TileEntityTentDoor.onPlayerActivate(TileEntityTentDoor.java:156) ~[TileEntityTentDoor.class:?]
at com.yurtmod.block.BlockTentDoor.func_180639_a(BlockTentDoor.java:78) ~[BlockTentDoor.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:178) ~[lv.class:?]
at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$0(NetHandlerPlayServer.java:636) ~[me.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) ~[PacketUtil.class:1.10.2-2026-5.0.0-BETA-1599]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fl$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more
```

**Comment by FiveEYZ** [comment]
update forge to 2044, the spongeforge u are using require forge 2044

**Comment by bloodmc** [comment]
This was already fixed. Update to latest SF build.
