### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#838]
spongeforge-1.8.9-1890-4.2.0-BETA-1666
```
[21:05:06] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Ticking player
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:379) ~[lf.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(SourceFile:88) ~[ip$c.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) ~[PacketUtil.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at squeek.spiceoflife.foodtracker.FoodHistory.get(FoodHistory.java:225) ~[FoodHistory.class:?]
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodModifier(FoodModifier.java:116) ~[FoodModifier.class:?]
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodValues(FoodModifier.java:36) ~[FoodModifier.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_108_FoodModifier_getFoodValues_GetPlayerFoodValues.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:110) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:81) ~[EventBus.class:?]
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getFoodValuesForPlayer(AppleCoreAccessorMutatorImpl.java:96) ~[AppleCoreAccessorMutatorImpl.class:?]
	at squeek.applecore.asm.Hooks.onFoodStatsAdded(Hooks.java:35) ~[AppleCore-mc1.8.9-1.3.2.jar:?]
	at net.minecraft.util.FoodStats.func_151686_a(SourceFile:34) ~[xg.class:?]
	at net.minecraft.item.ItemFood.func_77654_b(SourceFile:37) ~[zs.class:?]
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:157) ~[zx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.java:430) ~[wn.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:911) ~[lf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:237) ~[wn.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:328) ~[lf.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(SourceFile:88) ~[ip$c.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) ~[PacketUtil.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
```

**Comment by ST-DDT** [comment]
This looks like a plugin issue:
[`FoodHistory#get(EntityPlayer)`](https://github.com/squeek502/SpiceOfLife/blob/1.8.9/java/squeek/spiceoflife/foodtracker/FoodHistory.java#L223)
The passed player seems to be `null`.
