### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#839]
spongeforge-1.8.9-1890-4.2.0-BETA-1666
```
[22:59:14] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at com.tlf.HN.commands.CommandName.func_71519_b(CommandName.java:194) ~[CommandName.class:?]
	at org.spongepowered.common.command.MinecraftCommandWrapper.testPermission(MinecraftCommandWrapper.java:168) ~[MinecraftCommandWrapper.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.lambda$filterCommands$1(SimpleDispatcher.java:391) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1666]
	at com.google.common.base.Predicates$CompositionPredicate.apply(Predicates.java:552) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.FilteredEntryMultimap.satisfies(FilteredEntryMultimap.java:71) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.FilteredEntryMultimap.access$000(FilteredEntryMultimap.java:46) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.FilteredEntryMultimap$ValuePredicate.apply(FilteredEntryMultimap.java:84) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.Iterators.indexOf(Iterators.java:773) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.Iterators.any(Iterators.java:679) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.Iterables.any(Iterables.java:623) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.Collections2$FilteredCollection.isEmpty(Collections2.java:186) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.FilteredEntryMultimap$AsMap$2$1.computeNext(FilteredEntryMultimap.java:258) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.FilteredEntryMultimap$AsMap$2$1.computeNext(FilteredEntryMultimap.java:247) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.Iterators.size(Iterators.java:186) ~[minecraft_server.1.8.9.jar:?]
	at com.google.common.collect.FilteredEntryMultimap$AsMap$2.size(FilteredEntryMultimap.java:279) ~[minecraft_server.1.8.9.jar:?]
	at java.util.AbstractMap.size(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.collect.Maps$KeySet.size(Maps.java:3492) ~[minecraft_server.1.8.9.jar:?]
	at java.util.Spliterators$IteratorSpliterator.estimateSize(Unknown Source) ~[?:1.8.0_101]
	at java.util.Spliterator.getExactSizeIfKnown(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_101]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:329) ~[SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.command.ServerCommandManager.func_180524_a(SourceFile:168) ~[bd.class:?]
	at net.minecraft.server.MinecraftServer.func_180506_a(MinecraftServer.java:832) ~[MinecraftServer.class:?]
	at net.minecraftforge.server.console.ConsoleCommandCompleter$1.call(ConsoleCommandCompleter.java:50) ~[ConsoleCommandCompleter$1.class:?]
	at net.minecraftforge.server.console.ConsoleCommandCompleter$1.call(ConsoleCommandCompleter.java:45) ~[ConsoleCommandCompleter$1.class:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
```

**Comment by 5igm** [comment]
```
[23:50:35] [Server thread/ERROR] [Sponge/]: Could not pass InteractBlockEvent$Secondary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@6d614690
java.lang.NullPointerException
	at io.github.nucleuspowered.nucleus.dataservices.GeneralService.getBlacklistedTypes(GeneralService.java:59) ~[GeneralService.class:0.7.1-SNAPSHOT]
	at io.github.nucleuspowered.nucleus.modules.blacklist.listeners.BlacklistListener.onTransaction(BlacklistListener.java:129) ~[BlacklistListener.class:0.7.1-SNAPSHOT]
	at io.github.nucleuspowered.nucleus.modules.blacklist.listeners.BlacklistListener.onTransaction(BlacklistListener.java:106) ~[BlacklistListener.class:0.7.1-SNAPSHOT]
	at io.github.nucleuspowered.nucleus.modules.blacklist.listeners.BlacklistListener.onPlayerInteractBlock(BlacklistListener.java:86) ~[BlacklistListener.class:0.7.1-SNAPSHOT]
	at org.spongepowered.common.event.listener.InteractBlockEventListener_BlacklistListener_onPlayerInteractBlock90.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:184) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:633) [SpongeCommonEventFactory.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:628) [SpongeCommonEventFactory.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:571) [lm.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) [ja.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) [ja.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by 5igm** [comment]
```
[23:50:15] [Server thread/ERROR] [Sponge/]: Could not pass ChangeInventoryEvent$Held$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@6d614690
java.lang.NullPointerException
	at io.github.nucleuspowered.nucleus.dataservices.GeneralService.getBlacklistedTypes(GeneralService.java:59) ~[GeneralService.class:0.7.1-SNAPSHOT]
	at io.github.nucleuspowered.nucleus.modules.blacklist.listeners.BlacklistListener.onPlayerChangeItem(BlacklistListener.java:58) ~[BlacklistListener.class:0.7.1-SNAPSHOT]
	at org.spongepowered.common.event.listener.ChangeInventoryEventListener_BlacklistListener_onPlayerChangeItem91.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeInventoryHeldEvent(SpongeCommonEventFactory.java:206) [SpongeCommonEventFactory.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.NetHandlerPlayServer.handler$onGetSlotId$0(NetHandlerPlayServer.java:764) [lm.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147355_a(NetHandlerPlayServer.java:758) [lm.class:?]
	at net.minecraft.network.play.client.C09PacketHeldItemChange.func_148833_a(SourceFile:30) [iv.class:?]
	at net.minecraft.network.play.client.C09PacketHeldItemChange.func_148833_a(SourceFile:8) [iv.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by 5igm** [comment]
[23:51:40] [Server thread/ERROR] [Sponge/]: Could not pass ClickInventoryEvent$Shift$Primary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@6d614690
java.lang.NullPointerException
	at io.github.nucleuspowered.nucleus.dataservices.GeneralService.getBlacklistedTypes(GeneralService.java:59) ~[GeneralService.class:0.7.1-SNAPSHOT]
	at io.github.nucleuspowered.nucleus.modules.blacklist.listeners.BlacklistListener.onPlayerChangeItem(BlacklistListener.java:58) ~[BlacklistListener.class:0.7.1-SNAPSHOT]
	at org.spongepowered.common.event.listener.ChangeInventoryEventListener_BlacklistListener_onPlayerChangeItem91.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:468) [SpongeCommonEventFactory.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:430) [CauseTracker.class:1.8.9-1890-4.2.0-BETA-1666]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:122) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1666]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by ST-DDT** [comment]
@5igm The first looks like its a plugin issue, but i cannot verify that since I cannot find the corresponding source code of that plugin. Might be caused by this plugin: https://minecraft.curseforge.com/projects/hide-names

@5igm The second one looks like a different error. But I cannot investigate it without more context. But from the stacktrace I would say, its either a bad plugin  config or a plugin bug.

[`GeneralService#getBlacklistedTypes()`](https://github.com/NucleusPowered/Nucleus/blob/master/src/main/java/io/github/nucleuspowered/nucleus/dataservices/GeneralService.java#L59)
[`BlacklistListener#onPlayerChangeItem(...)`](https://github.com/NucleusPowered/Nucleus/blob/master/src/main/java/io/github/nucleuspowered/nucleus/modules/blacklist/listeners/BlacklistListener.java#L58)

Please provide a full list of your plugins and their versions when reporting an issue.

**Comment by gabizou** [comment]
These seem to be all plugin issues.

**Comment by 5igm** [comment]
@ST-DDT Thank you very much. May kind people be blessed with life-long peace .
