### ISSUE TITLE
[1.10.2] Exception in server tick loop

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#853]
Sponge version - 1.10.2-2052-5.0.0-BETA-1680
Forge version - 1.10.2-12.18.1.2052

Crash Report - http://pastebin.com/fX1ZnJhb
Full Log - http://pastebin.com/42QDCf7z

I have confirmed that this issue does not happen without sponge, and it crashes before fully loading

> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341)
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:390)
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:194)
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:198)
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.dedicated.DedicatedServer.handler$postGameStoppingEvent$0(DedicatedServer.java:82)
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.dedicated.DedicatedServer.func_71240_o(DedicatedServer.java)
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:535)
> [22:55:49] [Server thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:    at java.lang.Thread.run(Unknown Source)

**Comment by Tencao** [comment]
I would also like to add that this bug did not exist a few builds ago (1678)
