### ISSUE TITLE
Server connection

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#876]
Sometimes it is very hard to connect to the server. Is it caused by sponge?
spongeforge-1.10.2-2073-5.0.0-BETA-1689

```
[03:33:53] [Netty Server IO #14/WARN] [io.netty.util.concurrent.DefaultPromise/]: An exception was thrown by net.minecraft.network.NetHandlerPlayServer$1.operationComplete()
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@515b5ded(uncancellable)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390) ~[DefaultPromise.class:?]
    at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157) ~[DefaultChannelPromise.class:?]
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283) ~[DefaultPromise.class:?]
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135) ~[DefaultChannelPromise.class:?]
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28) ~[DefaultChannelPromise.class:?]
    at net.minecraft.network.NetworkManager.func_150718_a(NetworkManager.java:302) ~[eo.class:?]
    at net.minecraft.network.NetHandlerPlayServer$1.operationComplete(NetHandlerPlayServer.java:265) ~[me$1.class:?]
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680) [DefaultPromise.class:?]
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603) [DefaultPromise.class:?]
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563) [DefaultPromise.class:?]
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406) [DefaultPromise.class:?]
    at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) [DefaultChannelPromise.class:?]
    at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:523) [ChannelOutboundBuffer.class:?]
    at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:247) [ChannelOutboundBuffer.class:?]
    at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:322) [ChannelOutboundBuffer.class:?]
    at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:301) [NioSocketChannel.class:?]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [AbstractChannel$AbstractUnsafe.class:?]
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:321) [AbstractNioChannel$AbstractNioUnsafe.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:519) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by bloodmc** [comment]
Update to latest SF.
