### ISSUE TITLE
[1.8.9] Ticking World Crash

### ISSUE THREAD

**Issue by GershonR** [SpongePowered/SpongeForge#893]
http://pastebin.com/DDDdEMny

```
07.09 11:25:17 [Server] Server thread/ERROR Encountered an unexpected exception
07.09 11:25:17 [Server] INFO net.minecraft.util.ReportedException: Exception ticking world
07.09 11:25:17 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696) ~[MinecraftServer.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
07.09 11:25:17 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
07.09 11:25:17 [Server] INFO Caused by: java.lang.StackOverflowError
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3797) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Curly.match0(Pattern.java:4279) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Curly.match(Pattern.java:4234) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Branch.match(Pattern.java:4602) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Curly.match0(Pattern.java:4279) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Curly.match(Pattern.java:4234) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Branch.match(Pattern.java:4602) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Pattern$Start.match(Pattern.java:3461) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Matcher.search(Matcher.java:1248) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.regex.Matcher.find(Matcher.java:664) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.Formatter.parse(Formatter.java:2549) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.lang.String.format(String.java:2940) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at net.minecraft.entity.Entity.toString(Entity.java:2081) ~[pk.class:?]
07.09 11:25:17 [Server] INFO at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at com.google.common.base.Objects$ToStringHelper.toString(Objects.java:401) ~[minecraft_server.1.8.9.jar:?]
07.09 11:25:17 [Server] INFO at net.minecraft.entity.ai.EntityAITasks.toString(SourceFile:241) ~[re.class:?]
07.09 11:25:17 [Server] INFO at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at java.lang.String.format(String.java:2940) ~[?:1.8.0_92]
07.09 11:25:17 [Server] INFO at org.spongepowered.api.event.SpongeEventFactory.createAITaskEventAdd(SpongeEventFactory.java:2331) ~[SpongeEventFactory.class:1.8.9-1890-4.2.0-BETA-1693]
07.09 11:25:17 [Server] INFO at net.minecraft.entity.EntityLiving.handleDelayedTaskEventFiring(EntityLiving.java:114) ~[ps.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.entity.EntityLiving.firePostConstructEvents(EntityLiving.java:105) ~[ps.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.entity.Entity.handler$onReadFromNBT$0(Entity.java:982) ~[pk.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.entity.Entity.func_70020_e(Entity.java:1508) ~[pk.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:174) ~[pm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:469) ~[anj.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:153) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_72964_e(World.java:287) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_175726_f(World.java:282) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_180495_p(World.java:822) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_174912_b(TileEntityChest.java:276) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_174911_a(TileEntityChest.java:253) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_145979_i(TileEntityChest.java:242) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_145843_s(TileEntityChest.java:423) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:879) ~[amy.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862) ~[amy.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:504) ~[anj.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:153) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_72964_e(World.java:287) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_175726_f(World.java:282) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_180495_p(World.java:822) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_174912_b(TileEntityChest.java:276) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_174911_a(TileEntityChest.java:253) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_145979_i(TileEntityChest.java:242) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_145843_s(TileEntityChest.java:423) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:879) ~[amy.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862) ~[amy.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:504) ~[anj.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:153) ~[ld.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_72964_e(World.java:287) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_175726_f(World.java:282) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.world.World.func_180495_p(World.java:822) ~[adm.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_174912_b(TileEntityChest.java:276) ~[aky.class:?]
07.09 11:25:17 [Server] INFO at net.minecraft.tileentity.TileEntityChest.func_174911_a(TileEntityChest.java:253) ~[aky.class:?]
```

**Comment by Aaron1011** [comment]
@GershonR: That's one monster of a stacktrace :)

Are you able to reproduce this consistently? If so, what steps did you take?

**Comment by GershonR** [comment]
This happened every time on server startup but after looking into it it seems to be a Pixelmon issue according to their dev team
