### ISSUE TITLE
Exception on Login

### ISSUE THREAD

**Issue by iKaneki-Ken** [SpongePowered/SpongeForge#904]
I get this error whenever I try to login a Sponge based server.

```
16.09 15:02:46 [Server] INFO Exception in thread "User Authenticator #1" [15:02:46] [User Authenticator #1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.mojang.authlib.properties.PropertyMap$Serializer.deserialize(PropertyMap.java:38)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.mojang.authlib.properties.PropertyMap$Serializer.deserialize(PropertyMap.java:19)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.gson.Gson.fromJson(Gson.java:803)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.gson.Gson.fromJson(Gson.java:768)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.gson.Gson.fromJson(Gson.java:717)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.gson.Gson.fromJson(Gson.java:689)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:55)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.hasJoinedServer(YggdrasilMinecraftSessionService.java:95)
16.09 15:02:46 [Server] User Authenticator #1/INFO [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.network.NetHandlerLoginServer$2.run(NetHandlerLoginServer.java:187)
```

**Comment by kashike** [comment]
It's a temporary issue with the Mojang session servers. Should be fixed soon. See https://help.mojang.com/  for status updates.
