### ISSUE TITLE
[1.10.2] Lost EntityPlayer in EventBus (after player respawn)

### ISSUE THREAD

**Issue by lujiren** [SpongePowered/SpongeForge#916]
**It's fine in forge server but  in spongeforge broken**

Using AppleCoreAPI with spongeforge-1.10.2-2092-5.0.0-BETA-1746
If the player is not dead before, everything is work and fine.
When player after die and try to firing "FoodEvent.FoodEaten" event,  Client will be kicked out server and throw an exception (On server).
**by checked code , its seems event.player is null**

Here is the exception

```
[02:03:55] [Server thread/ERROR] [FML/]: Exception caught during firing event squeek.applecore.api.food.FoodEvent$FoodEaten@15922a4c:
java.lang.NullPointerException
    at mymod.EventHandler.onFoodEaten(EventHandler.java:174) ~[EventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_103_BlockHarvestEventHandler_onFoodEaten_FoodEaten.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130) [EventBus.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99) [EventBus.class:?]
    at squeek.applecore.asm.Hooks.onPostFoodStatsAdded(Hooks.java:128) [AppleCore-mc1.10.2-2.0.1.jar:?]
    at net.minecraft.util.FoodStats.func_151686_a(SourceFile:33) [abb.class:?]
    at net.minecraft.item.ItemFood.func_77654_b(SourceFile:46) [adt.class:?]
    at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:168) [adz.class:?]
    at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2612) [sf.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1002) [lu.class:?]
    at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2512) [sf.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1939) [sf.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) [zs.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [lu.class:?]
    at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$0(NetHandlerPlayServer.java:225) [me.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) [me.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) [NetworkDispatcher$1.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by gabizou** [comment]
Yeah, I don't know what event this is getting thrown from, but it's not a Sponge event that is causing it. Does it still break with forge only?

**Comment by lujiren** [comment]
no, just use forge server its always fine @gabizou

**Comment by lujiren** [comment]
The problem is **lost PlayerObject in event (after player respawn)**. 

 I found bug#827 - Sponge has duplicate PlayerInteractEvent to mods. (Declared has been fixed)
May be they have relevance?

**Comment by kashike** [comment]
https://github.com/squeek502/SpiceOfLife/issues/99
https://github.com/squeek502/AppleCore/issues/78

**Comment by ProsperCraft** [comment]
We are also having this issue on our Allthemods server using the same versions, and spongeforge 1834

**Comment by Eufranio** [comment]
Progress?

**Comment by Zidane** [comment]
@Eufranio 

We will get to it when we get to it. It isn't a very easy issue to solve.
