### ISSUE TITLE
Server crash on worldgen

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#930]
http://pastebin.com/qXfnz0kZ

at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:90)
    at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:487)
    at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:248)

**Comment by mister-man** [comment]
Hallo,

didn't find the post before posting. These error seems equal to mine.

#940

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/952ca27921a25d5a1829e05070816f0d88c4afbb
