### ISSUE TITLE
[1.10.2 / Sponge 5.0.0-BETA-1784] Crash While world generation

### ISSUE THREAD

**Issue by mister-man** [SpongePowered/SpongeForge#940]
Hallo together,

I found a crash while world generation with sponge version 

```
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:45)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:90)
	at net.minecraft.world.gen.structure.MapGenStructure.populate(MapGenStructure.java:64)
	at org.spongepowered.api.world.gen.Populator.populate(Populator.java:101)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:224)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$0(PlayerChunkMapEntry.java:79)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:45)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:90)
	at net.minecraft.world.gen.structure.MapGenStructure.populate(MapGenStructure.java:64)
	at org.spongepowered.api.world.gen.Populator.populate(Populator.java:101)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:224)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$0(PlayerChunkMapEntry.java:79)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
```

Thanks :)

**Comment by Aaron1011** [comment]
@mister-man: Sorry for the delay in getting this. Can you please tell us the mods that you're running (as well as their versions). Also, does this issue always occur when generating a fresh world, or is it an issue with an existing one?

**Comment by bloodmc** [comment]
Fixed in commit
https://github.com/SpongePowered/SpongeCommon/commit/952ca27921a25d5a1829e05070816f0d88c4afbb
