### ISSUE TITLE
Fakeplayer Crash with Extra Utilities quarry.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#970]
When you create the Extra Utilities 2 Quantum Quarry multiblock and turn it on the server instantly crashes, this is repeatable, and does not happen when sponge is not on the server.

Complete Crash log -
http://pastebin.com/qcppLYPv

Relevant portion-
Description: Ticking block entity

[10:23:05] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: bleeding-SNAPSHOT-b550bfa
    SpongeForge: 1.10.2-2098-bleeding-BETA-0
    Minecraft Forge: 12.18.2.2106

java.lang.NullPointerException: Ticking block entity
    at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:161)
    at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:142)
    at net.minecraftforge.common.util.FakePlayer.<init>(FakePlayer.java:42)
    at com.rwtema.extrautils2.fakeplayer.XUFakePlayer.<init>(XUFakePlayer.java:30)
    at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:246)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:195)
    at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjk000(WorldServer.java:1294)
    at net.minecraft.world.World.func_72939_s(World.java:1256)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by TheMrCaveman** [comment]
your server forge is not matching, sponge needs forge 2098

**Comment by Aaron1011** [comment]
@ProsperCraft: I can't reproduce this with the latest Spongeforge. Are you able to reproduce it with only Sponge and Extrautils (running the matching Forge version for Sponge).

**Comment by ProsperCraft** [comment]
http://pastebin.com/DKL6emym

Different pack(hermitcraft) same crash

[09:09:59] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: bleeding-SNAPSHOT-b550bfa
    SpongeForge: 1.10.2-2098-bleeding-BETA-0
    Minecraft Forge: 12.18.1.2095

I will try with the latest spongeforge, will the change to API 6 break all of my plugins?

**Comment by ProsperCraft** [comment]
[10:40:27] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-73050f3
    SpongeForge: 1.10.2-2098-6.0.0-BETA-1819
    Minecraft Forge: 12.18.2.2099

Tested with recommended forge and latest spongeforge, still crashing.
http://pastebin.com/QVHvbCXQ

**Comment by Aaron1011** [comment]
@ProsperCraft: Can you list the exact steps you took to set up the quantum quarry? Mine was mining blocks without any problems (they appeared in the attached chest).

**Comment by bloodmc** [comment]
No response in over a month.

**Comment by phit** [comment]
this is still an issue, just updated sponge and was greeted by this http://vpaste.net/KZUHB
no idea why it popped up now, I also noticed this line on startup
`No entity type is registered for class com.rwtema.extrautils2.fakeplayer.XUFakePlayer`

**Comment by Magi1053** [comment]
+1

**Comment by ktole1999** [comment]
is ftb utilities in the pack and is this within an ftbu claim or other claimed area?

**Comment by Magi1053** [comment]
FTB Utilities was in the pack, but I removed the mod when I installed SpongeForge
